"""Dullness, turning, hare, rope and smear: related-looking roots kept distinct."""

def populate(add,tokens):
    add('d4750','be blunt, dull, dim, perish','*maẓ-u-k(k); *maẓ-u-ŋk; low-a nominal grade',
        'm','a','ẓ','u/a','CVC-u-KK / CVC-u-NK','verb/noun',
        'Tamil maẓuku/maẓukku/maẓuŋku and Kannada maẓgu independently establish a short a root, approximant and high-u/velar formation. Kannada maẓa and Tamil maẓa separately attest a low-a nominal grade.',
        'Southern full forms and Tulu marg support m-a-apical before Telugu mrakku/mraggu. Tamil makku and Kannada maggu also show that medial apical loss can produce plain velar forms independently.',
        '*maẓ-ukk > *maẓ-kk > *mẓa-kk > mrakku; voiced mraggu may involve voicing or a different consonantal history. Telugu mrakku > makku and mraggu > maggu are possible locally supported r-loss chains, but inherited/borrowed already assimilated forms can converge on the same outputs. Nasal forms maŋku need only medial assimilation.',
        'A high-u geminate formation supports the short displaced outcome. The paired plain forms cannot all be assigned exclusively to r loss because independently plain cognates exist. Source hypothesis of old Kannada borrowing for some voiced geminate Telugu formations is relevant but unproved for this individual root. Do not merge with alveolar turn d4761 or forget d4760 simply because Telugu collapses the apicals to r and meanings overlap.',
        {'Tamil':('O','maṛ̆u|maṛ̆uku|maṛ̆ukku|maṛ̆uŋku|maṛ̆uŋkal|maṛ̆ukkam|maṛ̆a|makku|maŋku|maŋkul|maŋkulam','Full approximant versus independently medially assimilated forms.'),'Malayalam':('O','maṛ̆unnanē āka|maŋŋuka|maŋŋul|maŋŋiram|maŋku','Retained approximant phrase and medial nasal assimilation.'),'Kannada':('O','maṛ̆a|maṛ̆gu|maṛ̆gisu|maṛ̆al|maggu|maggisu|maŋku|maŋkutana|mañju|maka','Full apical and internal assimilation.'),'Tulu':('O','margɯ|margɯ āpini|maŋku|maŋka','Full apical dead formation and nasal dullness.'),'Kota':('O','mak|makl|mak- (maky-)|mag- (magy-)|maŋg- (maŋgy-)|mang-|mangy-','Medial loss/assimilation, no initial mr witnessed.'),'Toda':('O','mak Qoṯ- (Qoṯy-)|makθoṯ-','Internally reduced noun in complex predicate.'),'Telugu':('D','mrakku|mraggu|makku|maggu','Initial clusters directly attested; plain outcomes may converge from more than one history.'),'Kui':('O','manguri','Nasal/velar assimilation; no initial mr evidence.'),'Kurux':('R','maṛxnā','Retained apical order.'),'Malto':('R','maṛɣe|maṛɣro|maṛɣru|maṛɣtre','Retained apical/velar formations.'),'Badaga':('O','maggi|maggu','Internal assimilation or contact, no initial mr evidence.')},
        input_confidence='high',references='DEDR 4750; K61 pp.65–66 §1.153 voiced-geminate loan hypothesis (general, not proof for this root)',boundary='Velar and nasal derivatives independently supported; adjacent semantically similar roots with different apicals remain separate.')
    tokens('d4750','Tamil',R='maṛ̆u|maṛ̆uku|maṛ̆ukku|maṛ̆uŋku|maṛ̆uŋkal|maṛ̆ukkam|maṛ̆a',O='makku|maŋku|maŋkul|maŋkulam')
    tokens('d4750','Malayalam',R='maṛ̆unnanē āka',O='maŋŋuka|maŋŋul|maŋŋiram|maŋku')
    tokens('d4750','Kannada',R='maṛ̆a|maṛ̆gu|maṛ̆gisu|maṛ̆al',O='maggu|maggisu|maŋku|maŋkutana|mañju|maka')
    tokens('d4750','Tulu',R='margɯ|margɯ āpini',O='maŋku|maŋka')

    add('d4761','turn over, return, be distressed, fall','*maṯ-i/u; *maṯ-aŋk; *maṯ-al',
        'm','a','ṟ','i/u/a','CVC-i / CVC-u-K / CVC-a-NK / CVC-a-l','verb/noun',
        'Tamil maṟi, maṟuku, maṟaŋku and Malayalam maṟiyuka/maṟukuka independently establish several formative vowels. Kannada maral/maraḷ and Telugu maralu support a second-lateral formation.',
        'Full southern and eastern root forms establish m-a-apical before Telugu mraŋgu/mrandu. The meanings perish/decrease overlap other m-r roots, so exact linkage must be tested rather than inferred from spelling.',
        'A short high-u/zero nasal or stop formation *maṯ-NK/ND > mraŋgu/mrandu is possible. If the exact input is instead Tamil low-a *maṟaŋku, short Telugu a requires later shortening after contraction. Telugu maralu > maḷḷu can result from medial r-l assimilation, with no initial mr stage. Kui mag-b > mabg reverses suffix consonants after a separate medial apical loss.',
        'The short Telugu nasal-cluster outcome is not a deterministic confirmation until its V2 is fixed independently. Mraŋgu/mraggu may reflect convergence with d4750; preserve separate lexical affiliations and flag double-count risk. Kannada malar beside maral reverses the two liquids internally, a different process from initial vowel/apical displacement. Tulu marakaṇɛ/maraŋkaṇɛ is explicitly alternatively linked to d4740 and remains uncertain.',
        {'Tamil':('O','maṟi|maṟuku|maṟaŋku|maṟukkam|maṟukali|maṟukkaḷi|maṟivi|maṟam|makkaḷi','Full apical forms and medial reduction in relapse.'),'Malayalam':('R','maṟi|maṟiyuka|maṟikka|maṟivu|maṟiccal|maṟippu|maṟukuka','Multiple retained formations.'),'Kannada':('R','maral|maraḷ|malar|maralcu|maraḷcu|maraḷisu','Initial vowel retained; malar separately has internal liquid exchange.'),'Kota':('R','marṇ- (marḍ-)|marṇ-|marḍ-|marṭ- (marṭy-)|mayr- (marc-)','Initial vowel retained despite medial changes.'),'Toda':('R','maṟy- (maṟs-)|maṟy-|maṟs-|maṟc-','Retained initial order across voice/tense.'),'Kodagu':('R','mari- (mariv-, mariñj-)','Retained high-i formation.'),'Tulu':('A','maraḷikke|marapuni|marakaṇɛ|maraŋkaṇɛ','Retained secure forms and alternative-cognacy supine terms.'),'Telugu':('M','mara|maralu|maṟalu|marala|maṟala|maṟalan|maralincu|maṟalincu|maralucu|maralã-baḍu|maralã-bāṭu|maḷḷu|mraŋgu|mrandu|mraggu','Retained turn, internally assimilated return and displaced-looking distress/death formations.'),'Konda':('R','maṟ- (maRt-)|maR- (-t-)','Retained order.'),'Kui':('O','mabga (&lt; mag-b-; magd-)','Medial loss/assimilation and separate g-b exchange.'),'Kuwi':('R','mar- (-h-)|marhī marhī hal','Retained apical.'),'Pengo':('R','maz- (mast-)|mah- (mast-)','Medial apical changes across voice; vowel remains initial after m.'),'Badaga':('O','maraḷisu|mālu','Retained two-liquid verb and reduced long swing noun.')},
        input_confidence='high for root family; medium for exact Telugu formation',references='DEDR 4761; DEN1 1972 p.413 entry3898; compare DEDR 4750 and 4740',boundary='High-i/u, low-a nasal and second-lateral formations separately reconstructed.')
    tokens('d4761','Tamil',R='maṟi|maṟuku|maṟaŋku|maṟukkam|maṟukali|maṟukkaḷi|maṟivi|maṟam',O='makkaḷi')
    tokens('d4761','Tulu',R='maraḷikke|marapuni',A='marakaṇɛ|maraŋkaṇɛ')
    tokens('d4761','Telugu',R='mara|maralu|maṟalu|marala|maṟala|maṟalan|maralincu|maṟalincu|maralucu|maralã-baḍu|maralã-bāṭu',O='maḷḷu',D='mraŋgu|mrandu',A='mraggu')
    tokens('d4761','Badaga',R='maraḷisu',O='mālu')

    add('d4968','hare','*muc/y-al; regional *mol/mor-Vl, K80 *moẓ-al',
        'm','u/o','secondary l/r, earlier c/y','a/o','CVC-a-l','noun',
        'Tamil mucal/muyal and Malayalam muyal independently support a low-a final-l formation with medial c/y. Gondi molol/malol and Konda morol establish a regional two-liquid stage before initial clusters. K80 *moẓ-al is a scholarly intermediate, not a directly attested Proto-Dravidian root.',
        'Full southern and Gondi/Konda forms favor m-V-C-V-l before Kui mṛāḍu and Kuvi mrālu. Regional apical identity is clearer than its exact relation to the southern palatal/glide.',
        'Regional *mor-al/ol > *mrōl > mrālu gives Kui/Kuvi with lowering and Kui final l>ḍ; Pengo mrōl retains the mid vowel. The deeper *mucal > moyal > regional molol/morol requires palatal weakening plus assimilation/rhotacism, whose order relative to metathesis is not directly dated. Central/northern nasal forms reflect other c/nc developments.',
        'No Telugu attestation in this group. The independently low-a southern ending supports a historical formation, but reconstructing first-syllable o rather than u needs the umlaut/relative chronology argument. Do not classify this as ordinary inherited PDr apical metathesis without the secondary-apical stages. K80 p.498 additionally quotes Indi mnāl/mnōl, absent from this group; later nasal clusters need separate source annotation.',
        {'Tamil':('R','mucal|muyal','Full palatal/glide and final lateral.'),'Malayalam':('R','muyal','Same.'),'Kannada':('R','mola|mala','Medial c/y loss leaves final l, no promotion.'),'Kota':('R','molm','Contraction plus noun ending, no initial cluster.'),'Toda':('R','mȳs|my·s̱','Rounded vowel and final lateral fricative; y here is vowel notation.'),'Kodagu':('O','mona','Medial/final nasal assimilation.'),'Tulu':('R','mola|mugerɯ|muggerɯ|muyerɯ|mērɯ','Medial alternatives/contraction, final apical remains postvocalic.'),'Gondi':('R','molol ( D.molohk, Ma.molosku)|malol ( D.molohk, Ma.molosku)|mulol ( D.molohk, Ma.molosku)|molor|maloṛ ( -i ( D.molohk, Ma.molosku)|malōl ( malōhk ( D.molohk, Ma.molosku)','Full two-liquid formations, number and lect variants preserved.'),'Konda':('R','morol','Full two-liquid regional form.'),'Kui':('D','mṛāḍu','Initial apical cluster, lowered long vowel, final lateral-to-stop.'),'Kuwi':('D','mṛālū|mrālu|mṛalu','Initial cluster, quantity/lect variation.'),'Pengo':('D','mrōl','Cluster retains long mid vowel.'),'Kolami':('O','mi·te','Different medial palatal/nasal development, no metathesis established.'),'Naikri':('O','mīte','Same.'),'Parji':('O','mū̃da','Nasal/dental development and quantity.'),'Gadaba':('O','munde|mūnde','Nasal/dental development.'),'Kurux':('O','muńyā̃','Nasal/palatal formation.'),'Malto':('O','muṉye','Same broad pattern.'),'Brahui':('R','murū','Medial apical remains postvocalic; deeper final lateral history uncertain.'),'Badaga':('R','mola','Contracted full-order form.'),'Irula':('O','monna|munna','Nasal assimilation, no initial displacement.')},
        input_confidence='high for broad order; medium for secondary-apical intermediate',references='K80 p.498 item15; DEDR 4968; K03 *muc-Vl/*moy-al',eligibility='secondary-apical-regional',boundary='Two-liquid regional formation descends from a palatal/glide root; stages must precede a narrow-apical classification.')

    add('d4976','rope, cord, bark fibre','*mur-a-ṟc / regional *mor-a-(n)c',
        'm','u/o','r','a','CVC-a-(N)C','noun',
        'Tamil muraṟci and Tulu murajɛ independently supply a low-a formative; Gondi moros/moras/maronj gives matching regional rhotic and final s/nj formations. First-vowel u/o/a variation remains important.',
        'Tamil/Tulu/Gondi establish m-V-r before Kui mrāsu. Kuvi database marcu preserves m-a-r, while K80 prints a long-vowel form in the same comparison.',
        'Regional *mor-a-s > *mrōs > mrās gives Kui under K80 lowering. K80’s deeper *mut-a/*mot-a > *mor-a requires a separate t/r correspondence argument. Kuvi marcu may retain order; the long form cited by K80 may reflect a different quantity grade or metathesis followed by vowel reinsertion, neither demonstrated.',
        'Kui direction is plausible with strong suffix support, but not all branches share the same material or rope construction. The Kui leather rope versus Gondi tree fibre could reflect semantic specialization or contact. Telugu is unattested here. Preserve discrepancy between short database Kuvi marcu and long K80 spelling instead of silently normalizing it or counting two independent roots.',
        {'Tamil':('R','muraṟci','Full low-a cord formation.'),'Tulu':('R','murajɛ','Full low-a rope formation.'),'Gondi':('R','moros|moras|maṛos|maṛōnj|maronj|marõj|mōrūm|moroli','Full root with material/number/quantity and suffix variants.'),'Kui':('D','mrāsu','Displaced lowered rope noun.'),'Kuwi':('R','marcu','Database short retained-order form; K80 quantity differs.')},
        input_confidence='high for order and low-a formation; medium for root mid-vowel stage',references='K80 p.498 item16; DEDR 4976',boundary='Low-a formative independently attested; suffix s/nj and material-specific noun variants not separate roots.')

    add('d5082','smear, plaster, wax','*meẓ-u-k; other *meẓ-V-nḍ/ŋk/w formations',
        'm','e/i','ẓ','u / unknown','CVC-u-K / CVC-V-NK / CVC-V-w','verb/noun',
        'Tamil meẓuku, Malayalam meẓukuka and Konda miṛis independently establish an apical root and high-vowel formations. No compared form independently supplies the exact low-a formative required by K80 *meẓ-a for the Telugu/Kui long outputs.',
        'Southern and Konda/Brahui full forms favor m-V-apical before Telugu mrē- and Kui mrānḍa. Thus order is firmer than exact quantity/formative conditioning.',
        'Conditional *meẓ-a-ŋk > *mẓēŋk > mrē̃gu > mē̃gu gives Telugu if low a is justified; *meẓ-a-nḍ > *mẓēnḍ > mrānḍa adds Kui lowering. High-u/zero inputs could instead involve other contraction/lengthening routes. Telugu mrēvu has a different final labial development, not a free substitute for ŋg. Kuvi mrispi matches the high-i Konda form more closely.',
        'A real quantity/formative residual: do not use long ē/ā to manufacture the a whose prediction is being tested. Telugu mēdu could be another formation or internal assimilation and is uncertain. Kolami mēg/Naikri mēgh may be old Telugu loans or independently medially reduced forms. Kuvi mṇek introduces a nasal not directly expected from ẓ, so its cognacy/assimilation needs separate evidence.',
        {'Tamil':('R','meṛ̆uku|meṛ̆ukku|meṛ̆ukkam','Independent high-u/velar formations.'),'Malayalam':('R','meṛ̆ukuka|meṛ̆uku|meṛ̆ukku|meṛ̆u','Same.'),'Kota':('O','mek|mek- (meky-)|mek-|meky','Medial apical loss, no initial mr required.'),'Toda':('R','møṣk|møšk- (møšky-)|møśk-|møśky-','Apical/fricative remains after first vowel.'),'Kodagu':('O','mukk','Medial assimilation and vowel change.'),'Telugu':('A','mrē̃gu|mē̃gu|mrēvu|mēdu','Order-displaced forms have uncertain exact formative/quantity; mēdu additionally uncertain.'),'Gondi':('O','maṛhuttānā|māc|mācānā|miṭānā|miṭṭūs|mitus','Retained apical/dental forms versus internally reduced plaster.'),'Konda':('R','miṛis- (-t-)','Full high-i formation.'),'Kui':('D','mrānḍa (mrānḍi-)','Displaced nasal-dental formation; a input remains hypothesis.'),'Kuwi':('A','mrispi kīnai|mṇek- (-h-)','Displaced rhotic polish versus uncertain nasal clean.'),'Kolami':('A','me·g- (me·kt-)','Long internally reduced form, contact possible.'),'Naikri':('A','mēgʰ- (mēkt-)','Same.'),'Brahui':('R','miring','Retained medial apical, high-vowel form.'),'Badaga':('O','mekku','Medial loss/assimilation or contact.'),'Irula':('O','məkku','Same.')},
        input_confidence='high for apical order; low for proposed exact low-a input',references='K80 p.498 item17; DEDR 5082; PSS83 parenthesized a reconstruction discussed in prior source audit',eligibility='vowel-input-uncertain',boundary='High-u velar, high-i palatal and uncertain low-a nasal/labial formations separate.')
    tokens('d5082','Telugu',D='mrē̃gu|mē̃gu|mrēvu',A='mēdu')
    tokens('d5082','Gondi',R='maṛhuttānā|miṭānā|miṭṭūs|mitus',O='māc|mācānā')
    tokens('d5082','Kuwi',D='mrispi kīnai',A='mṇek- (-h-)')
