"""Regional bone/sell, long prattle residual and name contraction."""

def populate(add,tokens):
    add('d4418','bone, hard stone of fruit','*peẓ/ṛ-V-n; plural -k',
        'p','e','ẓ/ṛ','e/a/unknown','CVC-V-n','noun',
        'Gondi peṛeŋka/peṛeka and Konda peṛen independently establish p-e-apical-V-n/k. No southern cognate in this group uniquely establishes underlying ẓ rather than another source of regional ṛ, or low a rather than e in V2.',
        'Full Gondi/Konda forms support earlier p-V-ṛ before Kui/Kuvi/Pengo/Manda pṛēn. Kuvi pēṛnu retains postvocalic ṛ but has long quantity, whose age is not independently established.',
        '*peṛ-V-n > pṛēn by vowel loss/reassociation and contraction gives the eastern series. Kui/Kuvi plurals pṛēka replace/omit the singular nasal before number morphology; they are not additional metathesis etyma. Gondi peṛeŋka > penˀka/pɛnka permits medial apical loss; long Kuvi pēṛnu could reflect independent contraction, undoing of a cluster or an older grade.',
        'A good regional order comparison, weaker exact input class. Kui ē without lowering cannot falsify the low-a rule unless V2 a is independently established; K03 *peẓ-an is a scholarly reconstruction to test, not independently observed a. Do not call Kuvi pēṛnu a certain reversal of metathesis or certain long-root exception. Nihali bone loans are not independent Dravidian languages or ancestral witnesses.',
        {'Gondi':('O','peṛeŋka|peṛka|peṛekā|peṛeka|penˀ ka|pɛnka|paneka|panēkā','Retained full rhotic forms and medial reduction/quantity variants.'),'Konda':('R','peṛen ( peṛek','Retained singular/plural alternation.'),'Kui':('D','pṛēnu ( pṛēka)','Displaced singular and plural, one family.'),'Kuwi':('M','pēṛnu|prēnū|pṛēnu|plēnu|pṛēnu ( pṛēka)','Postvocalic apical variant and initial-cluster variants; quantity/lect preserved.'),'Pengo':('D','pṛēn ( pṛēku)','Displaced number paradigm.'),'Manda':('D','pṛēn ( pṛēke)','Same with plural vowel difference.')},
        input_confidence='high for regional order; medium for segment, low for exact V2',references='DEDR 4418; K03 *peẓ-an reconstruction; comparison DEDR 4153 not adjudicated',eligibility='regional-vowel-input-uncertain',boundary='Singular n versus plural k is morphological, not independent roots.')
    tokens('d4418','Gondi',R='peṛeŋka|peṛka|peṛekā|peṛeka',O='penˀ ka|pɛnka|paneka|panēkā')
    tokens('d4418','Kuwi',R='pēṛnu',D='prēnū|pṛēnu|plēnu|pṛēnu ( pṛēka)')

    add('d4536','sell','*por-V; proposed *por-a, *prō',
        'p','o','r','unknown','CVC-V','verb/noun',
        'Konda por independently supports p-o-r and corresponds semantically to eastern prā/pro/pre. It does not itself attest a following low-a vowel; the K80 *por-a input remains a reconstruction requiring support beyond the outcome.',
        'Konda favors p-V-r before the eastern clusters, but a single retained language plus restricted regional distribution gives less robust direction than a broad cross-branch set.',
        'Conditional *por-a > *prō > prā gives Kui/Kuvi under K80 lowering. Pengo pro preserves o, Manda pre has another vowel outcome. Kuvi pār retains r after a long vowel and may reflect cluster anaptyxis, an independent grade or contact; no unique history follows from the modern pair.',
        'K80 separated sell from spread d3949 (old DED3255); preserve that editorial distinction and record a family-merge sensitivity rather than counting the separation as proof of independent roots. No Telugu reflex in the linked group. Imported PSD1 reconstructions misassign a source explicitly labeled PSDII; these are not South Dravidian I attestations. Exact low-a conditioning remains unverified here.',
        {'Konda':('R','por- (-t-)','Only full retained root in this group.'),'Kui':('D','prāpa (prāt-)','Displaced formation with long low vowel.'),'Kuwi':('M',"pṛācali|pra'- (prat-)|prahnai|prā- (-t-)|pār- (-h-)",'Cluster variants and postvocalic-r long variant; distinct stems/source labels preserved.'),'Pengo':('D','pro- (-t-)','Cluster with mid back vowel.'),'Manda':('D','pre','Cluster with mid front vowel.')},
        input_confidence='medium for order; low for independently established V2',references='K80 pp.497–499 sell comparison; DEDR 4536 explicitly separated from DED3255',eligibility='regional-vowel-input-uncertain',boundary='Konda bare root does not prove a formative; compare spread only in sensitivity analysis.')
    tokens('d4536','Kuwi',D="pṛācali|pra'- (prat-)|prahnai|prā- (-t-)",R='pār- (-h-)')

    add('d4430','talk, prattle, command','*pēc / *pēẓ; short expressive variants distinct',
        'p','ē','ẓ/c','u/zero','CVVC / CVVC-V','verb/noun',
        'Tamil pēcu/pēccu, Malayalam pēcuka, Kannada pēẓ and Kuvi pēl independently establish a long first vowel. The exact relationship between c and ẓ series is itself reconstructed, while Telugu prēlu retains l in addition to its initial r.',
        'Long p-V-apical order is broadly supported. An ancestral short **per-al cannot be inferred from Telugu prēlu alone, and metathesis of a single ẓ does not by itself explain both r and l in prēlu.',
        'Possible *pēẓ > pēlu with lateral development, then secondary r > prēlu on literary Cr models; alternatively a distinct short derivative or analogical influence from homophonous burst prēlu d4194. These are hypotheses. Kota peṛc versus pe·c suggests internal cluster/quantity complexity but does not supply the exact two-liquid Telugu input.',
        'A long-input and segment-count residual, not a secure case of long-vowel metathesis. The burst and prattle homophones cannot be merged or used to repair each other without historical semantic evidence. Toda is explicitly alternatively compared with d4003 and remains uncertain. Kurux short reduplicative prattle verbs may be expressive formations distinct from long command pēsnā.',
        {'Tamil':('R','pēcu|pēccu|pēccal|pēcal','Long first vowel retained.'),'Malayalam':('R','pēcuka|pēccu','Same.'),'Kannada':('R','pēṛ̆ (pēṛ̆d-)|pēṛ̆uvike|pēṛ̆ike|pēṛ̆ige','Long approximant root retained.'),'Kota':('R','pe·c- (pe·c-)|peṛc|peṛc- (peṛc-)','Long or internal-cluster variants, no initial reversal.'),'Toda':('A','øšt- (øšty-)|øśt-','Alternative cognacy d4003, initial loss and cluster history uncertain.'),'Tulu':('R','pērmɛ','Long apical root with noun suffix.'),'Telugu':('A','pēlu|prēlu|prēlari','Long root plus unexplained/secondary r; no independently supported short two-liquid input.'),'Kuwi':('R','pēl- (-it-)|pēlki ā','Long root retains order.'),'Kurux':('R','pēsnā|pēskā|parparernā|perperᵉrnā|perxperxnā','Long command and short expressive formations distinguished.'),'Malto':('R','peṛqe','Internal cluster, initial vowel retained.'),'Badaga':('R','hēgu|ēgu|hēgidama|badilu ēgu|badilu hēgu','Initial/medial consonant change and loss without apical promotion.')},
        input_confidence='high for long input; low for Telugu added-r history',references='DEDR 4430; K03 *pēc/*pēẓ; comparison DEDR 4194; K61 secondary-r model n.80',eligibility='long-input-secondary-r-uncertain',quantity='long independently established',boundary='Do not invent a short *peral prattle derivative; expressive formations separate.',mechanism='Possible secondary r or analogical contamination, not established metathesis.')

    add('d4410','name, name someone','*pin-cc-Vr > *pic-ar / *pec-ar; regional pidir/peder',
        'p','i/e/ē','c/d with final r','a/i','CVC-a-r / CVVC','noun/verb',
        'Kannada pesar, Tamil peyar, Tulu pudar, central pidir and northern pinj/pin independently support a medial palatal/dental plus a later final rhotic formation. K03 reconstructs *pic-ar and deeper *pin-cc-Vr; long pēr results from loss/contraction, not an originally short p-e-r root.',
        'Southern pes-ar > pey-ar > pēr preserves final r while losing the medial consonant. Telugu pēru fits this contraction without moving r. Konda/Kuvi dōr and Pengo tōr promote or retain a dental-looking segment but differ in both onset and vowel; they are not straightforward r-metathesis.',
        '*pec-ar > *pey-ar > pēr gives Telugu and southern long forms. For eastern dōr/tōr, possible *peder > *pdēr > dēr with initial p loss would require secondary dental-cluster formation plus unexplained o; alternative medial assimilation or regional lexical replacement remains open. Do not present that schematic route as an attested intermediate.',
        'A useful contraction control and possible different secondary-apical process. K03 p.104 explicitly treats Kolami/Naikri pēr as Telugu loans. Their forms therefore cannot independently reconstruct early long quantity. Badaga pēru may similarly involve southern contact, while hesaru provides its fuller comparison. The northern naming verb lacks the final rhotic extension and is not a retained instance of the same CVr input.',
        {'Tamil':('R','peyar|piyar|pēr|peyaraṉ|peyartti|pērtti|peyarkku|peyariya','Full and contracted forms, no r promotion.'),'Malayalam':('R','peyar|piyar|pēr','Same.'),'Kannada':('R','pesar|pesaru|pesarisu','Full palatal-r formation.'),'Kota':('R','pēr|pe·r','Contracted noun.'),'Toda':('R','pø·r|pø̄r|pø̄śf-|pø̄śt-|pø·šf- (pø·št-)','Contracted noun and derivative.'),'Kodagu':('O','peda','Final r loss; medial dental retained.'),'Tulu':('R','pudarɯ|hudari','Full medial dental and final r.'),'Telugu':('R','pēru','Contracted long root, no apical displacement.'),'Gondi':('R','peder|pediri|padur|paddur|poral|porol|poroy|paroi|parōl|paṛōl|parroi','Full forms with medial/final apical assimilation or variation, initial vowel retained.'),'Konda':('A','pēr|pēru|dōr','Contracted long form versus unexplained dental-initial regional variant.'),'Kui':('O','paḍa|pāru','Internal changes/contraction, no initial pr cluster.'),'Kuwi':('A','dāru|dōru|dōrū|dōru ki','Dental-initial regional formation, exact pathway uncertain.'),'Pengo':('A','tōr','Same issue with voiceless initial.'),'Manda':('A','dar','Short low-vowel regional variant.'),'Kolami':('B','pe·r ( pe·ḍl)','K03 explicitly Telugu loan.'),'Naikri':('B','pēr ( pēḍḷ)','Same explicit attribution.'),'Naiki':('A','pēr','Possible loan by regional comparison, not explicitly proven here.'),'Parji':('R','pidir','Full medial dental and final r.'),'Gadaba':('R','pidir','Same.'),'Kurux':('R','pińjnā','Unextended naming verb, no comparable medial r.'),'Malto':('R','pinje','Same.'),'Brahui':('R','pin','Unextended nasal root.'),'Badaga':('A','hesaru|esaru|pēru','Full name forms versus possible borrowed contracted variant.'),'Koraga':('R','podari|hudari','Full dental and final rhotic.'),'markodi':('R','perə|pera|putrᵘ','Contracted and consonant-cluster regional variants; no initial apical promotion.')},
        input_confidence='high for contraction family; low for eastern dental-initial history',references='K03 p.104 example31 and discussion; DEDR 4410',eligibility='contraction-and-secondary-apical-control',quantity='long produced by contraction in relevant southern forms',boundary='Final r is an extension after earlier c/d; do not misread pēr as primitive short CVr.',mechanism='Medial consonant loss and contraction; eastern dental-initial variants unresolved.')
    tokens('d4410','Konda',R='pēr|pēru',A='dōr')
    tokens('d4410','Badaga',R='hesaru|esaru',A='pēru')
