"""Additional eastern displacement and competing reductions in the e-section."""

def populate(add,tokens):
    add('d800','fan, blow, wave','*e/iṟ-i-ñc; regional *er-sk',
        'Ø','e/i','ṟ','i/unknown','VC-i-NC / VC-sk','verb/noun',
        'Gondi ersk preserves vowel-r order alongside rēsk. DEDR explicitly reconstructs *eṟiñc for corrected Konda ṟīnz, while Tulu edde and Malto eswe/espro supply reduced/changed coronal cognates, not the exact same full suffix.',
        'The retained Gondi order and independent morphological comparanda favor an earlier V-apical sequence over the displayed *ǯīnǯ head as a family-wide proto-form. Konda source explicitly corrects r to ṟ, significant for the subsequent j correspondence.',
        '*e/iṟ-iñc > *ṟī/ĭnj > Konda ṟīnz, Kui jīnja and short Kuvi/Pengo/Manda jinj is a proposed displacement family. Gondi *er-sk > rēsk has a separate suffix and quantity history. Initial ṟ>j and later palatal/affricate developments are not interchangeable with inherited initial j.',
        'Exact V1/V2 and length are not independently uniform; short versus long eastern forms cannot all be predicted by a single reconstructed *eṟiñc without additional vowel history. Tulu geminate dd might result from earlier apical/suffix assimilation, and Malto has suffix consonant variation. Telugu is genuinely unattested in this group, not retained. Source Konda correction is duplicated into long/short parser variants; do not count both as independent historical stages.',
        {'Tulu':('O','edde|eddeṇe|eddyana|eddyuni','Geminate coronal; earlier cluster reduction plausible.'),'Gondi':('M','ersk|rēsk','Same meaning, both initial orders, dialect difference.'),'Konda':('D','ṟīnz- (-it-)|ṟīnzpis- (K.\'s correction forrīnz-, etc.;*eṟiñc-&gt;*ṟīnj-)|ṟīnzpis- (K.\'s correction forrīnz-, etc.;*eṟiñc-&gt;*ṟinj-)','Corrected alveolar and causative; duplicated notation not independent.'),'Kui':('D','jīnja (jīnji-)|jīnjeṛi','Long displaced verbal/noun formation.'),'Kuwi':('D','jinj- (-it-)|jinjali|jinjinai|jinjiki|jinjiri|jīnj|jīnjiki','Quantity and nominal suffix variants.'),'Pengo':('D','jinj- (jinc-)|jicoṇa','Displaced root and derived fan noun.'),'Manda':('D','jinj','Short form.'),'Malto':('O','esve|esvre|espro','Changed coronal plus different suffixes, initial vowel retained.')},
        input_confidence='medium for exact input; high regional order contrast',references='DEDR800 p.79 directly read; DEN1 1972 pp.401,407 entries686,2127',boundary='Gondi sk versus eastern ñc formations distinguished; no unsupported low-a suffix.')
    tokens('d800','Gondi',R='ersk',D='rēsk')

    add('d809','arrive, reach','*ey-t; regional *e/ik-pa',
        'Ø','e/i','y','zero','VC-T / V-K#P','verb',
        'Tamil eytu, Malayalam eytuka, Kannada aydu and historical eydu independently establish a glide root with dental extension. Pengo ika plus ipka < ik-pa identifies a separate velar-plus-labial intensive boundary.',
        'Vowel-first order is preserved across branches; this root has no independently original medial nonnasal apical in the relevant first position. Pengo k-p direction is independently given by the simplex ika and intensive formation.',
        '*ey-t > eydu/ēdu or ett through glide/dental changes, not apical metathesis. Gondi ev/av, Kui epa and Konda ī have their own lenition/contraction histories. Pengo ik-pa > ipka is genuine local stop-cluster exchange after intensive suffixation; initial-vowel order remains unchanged.',
        'This extends the local k-p process beyond Kui without pretending it establishes one family-wide innovation. The labial construction is intensive in Pengo rather than automatically the identical causative function of every Kui example. Kui epa/eppa contains no velar to exchange and is an appropriate distinct input control. Kuvi ne and Manda neyka require initial nasal/morphological history; they do not prove nasal metathesis. Brahui hining is an infinitive citation of in-, not an original h-i-n-root unanalysed whole. Tulu labels restored from source; Kuvi motion-base/personal-object tags are shifted in the parser.',
        {'Tamil':('R','eytu','Glide-dental form.'),'Malayalam':('R','eytuka|ettuka|ettikka|ettu|ettal|ettam','Glide retention and assimilation.'),'Kannada':('R','aydu|ay-tar','Root and compound.'),'Kodagu':('R','ett- (etti-)','Geminate dental reflex.'),'Tulu':('R','ettāḍuni|ettɯ|ekkɯ','Source-corrected language; local strong stops.'),'Telugu':('R','eydu|eyidu|ēdu|ētencu|egudu','Different extensions, no apical transfer.'),'Gondi':('R','ev|av|avvānā|avh|avih|āvsahtānā','Labial reflex and causative variations.'),'Konda':('R','ī- (-t-)','Contraction, no moved apical.'),'Kui':('R','epa (et-)|eppa (ept-)','Labial formations without velar.'),'Kuwi':('A','ega|eda|egovā|ep- (-it-)|e- (-t-)|ejali|ne- (-t-)','Vowel-first forms plus unexplained nasal onset.'),'Pengo':('R','ika|ika vā|ipka|ipka vā','Initial order retained; separate kp exchange.'),'Manda':('A','neyka vā','Nasal onset/compound history unresolved.'),'Kolami':('R','end- (ent-)','Nasal dental stem.'),'Parji':('R','ēd|ēy|eypip- (eypit-)|epip- (epit-)','Glide/dental/labial paradigms.'),'Gadaba':('R','ed','Vowel-first dental.'),'Brahui':('R','hining','Source identifies stem in-, infinitive morphology.'),'pampa':('R','eydu|ey- tar','Historical Kannada glide forms.'),'Toda':('R','ɨc- (ɨč-)|ɨc-|ic- (ič-)|ic-','Inherited and explicitly borrowed variants.')},
        c2_structure='glide plus dental',input_confidence='high for nonapical root and local Pengo boundary',references='DEDR809 p.79 directly read; MBE1962 pp.63–64 cited there',eligibility='nonapical-control',boundary='Pengo velar stem plus intensive p suffix independently identified.',mechanism='Initial retention; independent Pengo stop-cluster exchange.')
    tokens('d809','Kuwi',R='ega|eda|egovā|ep- (-it-)|e- (-t-)|ejali',A='ne- (-t-)')
    tokens('d809','Toda',R='ɨc- (ɨč-)|ɨc-',B='ic- (ič-)|ic-')

    add('d837','white ant, termite','regional *el-u-m/b; exact older vowel grades uncertain',
        'Ø','e/a','l','u','VC-u-M/B','noun',
        'Parji elub, Gadaba elub/elb and Gondi elum/allum independently establish vowel-l-u-labial order, while eastern līm/līmbu is reduced. The displayed *līm head does not establish the earlier family-wide input.',
        'Several central and Gondi full forms support vowel-first order before the lateral; eastern initial l/ḍ is secondary under the parsimonious comparison. Geminate Gondi/Gadaba variants cannot be imposed on singleton elub/elum.',
        '*el-u-m/b > līm/līmbu is a displacement-family development, but the exact change e-u > ī is unresolved. Kuvi lēmpu beside līmpu/līmbu and short limbu reveals real vowel/quantity variation. Kui initial ḍ follows the lateral-to-stop correspondence; it does not imply original *ṭ.',
        'This challenges a mechanical output rule based on the directly attested full e-u sequence. An earlier *il-im could explain ī but is not independently attested here and is not adopted to save the rule. Alternative vowel assimilation, extension reshaping or borrowing among eastern languages needs source/dialect evidence. Compound ant terms piṛku/dār/pete are not additional roots. Telugu is missing, not retained.',
        {'Parji':('R','elub ( elbul)','Full form and plural syncope.'),'Gadaba':('R','elub ( elbul)|ellūb ( elbūl)|elb (elub)','Full, strengthened/long and syncopated forms.'),'Gondi':('R','elum|allum|elu pete|ellum patteŋ','Full and compound forms.'),'Konda':('D','līm piṛku','Displaced member within compound.'),'Kui':('D','ḍīmbu','Lateral displaced and stopped.'),'Kuwi':('D','līmbu|līmpu|lēmpu|limbu','Vowel/quantity variants preserved.'),'Pengo':('D','līm dār','Displaced compound member.'),'Manda':('D','līm','Displaced root.')},
        input_confidence='high for order; medium for exact shared vowels',references='DEDR837 p.81 directly read',boundary='Full labial-ending noun independently reconstructed, exact prehistoric formative grade unresolved.')

    add('d851','rise, lift; awake, caution','*eẓ-u; *eẓ-c/ar, nasal/velar/labial extensions',
        'Ø','e','ẓ','u/a/unknown','VC-u / VC-C / VC-ar','verb/noun',
        'Tamil eṛ̆u, Malayalam eṛ̆uka, Kannada eṛ̆ and Kota eṛv establish vowel-approximant order. Kannada eṛ̆caṟ independently supports the medial approximant before the caution suffix, even though many caution forms assimilate it.',
        'Southern full forms precede eastern initial ḍ in lifting/standing variants. The caution r after cc belongs to an extension, not a moved first apical. The database *enǯ alternative and imported *eẓ-c head refer to particular formations and must not replace the whole complex root.',
        'Conditional *eẓ-Vk/ñj > *ẓēk/ñj > Kui ḍēk/ḍēnja and Manda/Kuvi ḍēk gives initial displacement and apical stopping, but exact V2 and length are not independently fixed. Gondi ḍiŋ has a different vowel. *eẓ-car > eccar through medial assimilation yields Telugu eccarika etc.; no earlier initial displacement is required. Tulu eḷañci > leñci/eñci permits aphaeresis and medial loss in a ladder noun.',
        'Separate lifting, waking/caution and ladder formations. Telugu is represented only by caution derivatives in this entry; ordinary lēcu is assigned to d916 in DEDR and cannot be silently imported here. Brahui harfing/hēfing involves a morphologically complex infinitive and medial consonant loss/grade, not initial r transfer. Long southern ēẓ variants are independently attested and prevent a single uniform short quantity for all formations. Tulu short leñci may be aphaeresis, not the eastern long-vowel process.',
        {'Tamil':('O','eṛ̆u|eṛ̆al|eṛ̆uvu|eṛ̆uppu|eṛ̆uppam|eṛ̆ucci|eṛ̆umai|eṛ̆umpu (eṛ̆umpi-) = eṛ̆u|eṭu|eṭuppu|eṭai|iṭai|eṭci|ēṭci|empu|evvu|eccarikkai|eccarippu','Retained approximant and distinct strong/assimilated derivatives.'),'Malayalam':('O','eṛ̆uka|eṛ̆u|eṛ̆uma|ēṛ̆uka|eṛ̆umpuka = eṛ̆uka|eṭukka|eṭuppu|eṭuppikka','Full and strong formations.'),'Kota':('R','eṛv- (eṛd-)|eṛv-|eṛd-|eṛ|etor- (etoṯ-)|etorc- (etorc-)','Root and queried wake derivatives; English fly fragment excluded.'),'Toda':('R','øḍ- (øḍQ-)|øḍ-|øḍθ-|øṛf- (øṛt-)|øṛf-|øṛt-|øṛt- (øṛty-)|øṛty-','Vowel-first apicals and paradigms.'),'Kannada':('O','eṛ̆|ēṛ̆ (eṛ̆d-)|ēṛ̆u (edd-)|eṛ̆bu|eṛ̆bisu|eṛ̆visu|erbu|ebbu|ebbisu|eṛ̆caṟ|eccaṟ (eṛ̆catt-, eccatt-)|eccaṟ|eccaṟa|eccaṟike|eccaṟisu','Full apical versus assimilated labial/caution.'),'Kodagu':('O','ə·ḷ- (ə·v, ədd-)|əḍɨ- (əḍɨp-, əḍɨt-)|əpp- (əppi-)|eccara','Retained apical versus assimilation.'),'Tulu':('A','erkuni|erkɯ|erka|erke|erkelɯ|ertɛ|erkāvuni|erpuni|eḷañci|leñci|eñci|ēñc̣ɯ|eccarike|eccaripuni|eccarisuni','Retained rise root, possible ladder aphaeresis, caution assimilation.'),'Telugu':('O','eccarika|eccaramu|eccarinta|eccarincu|ecarincu|eccarikincu|heccarika|heccarincu|heccarikincu = eccarincu','Medially assimilated caution formation; initial h prothesis.'),'Gondi':('D','ḍiŋ|ḍingānā','Initial displaced apical, i vowel needs separate formation.'),'Kui':('D','ḍēnja (ḍēnji-)|ḍēska (ḍēski-)|ḍēspa (ḍēst-)|ḍehka (ḍehki-)|ḍēka','Displaced carry/raise formations, different action morphology.'),'Kuwi':('D',"ḍēk- (-it-)|dēki'nai|dekali",'Carry forms with quantity/retroflex notation variation.'),'Manda':('D','ḍēk','Carry root.'),'Parji':('O','eñ|ecip- (ecit-)','Wake paradigm with palatal/nasal reduction.'),'Kurux':('O','ejnā (ejjas)|ejrnā','Wake palatal forms.'),'Malto':('O','eje|ejre','Wake palatal forms.'),'Brahui':('O','harfing|hēfing','Complex infinitives with medial r loss/grade, no initial r.'),'Badaga':('O','ellu|ēḷa|ebbu|eccarike','Lateral, assimilated labial and caution forms.'),'Koraga':('O','eṇṇi|eṇṇali','Medial nasal assimilation.')},
        quantity='short/long by formation',input_confidence='high root order; low exact eastern V2',references='DEDR851 p.82 directly read; compare separately DEDR916',boundary='Caution -car, rise/lift and ladder derivatives separately reconstructed.',mechanism='Eastern displacement; southern medial assimilation and local ladder aphaeresis alternatives.')
    tokens('d851','Tamil',R='eṛ̆u|eṛ̆al|eṛ̆uvu|eṛ̆uppu|eṛ̆uppam|eṛ̆ucci|eṛ̆umai|eṛ̆umpu (eṛ̆umpi-) = eṛ̆u|eṭu|eṭuppu|eṭai|iṭai|eṭci|ēṭci',O='empu|evvu|eccarikkai|eccarippu')
    tokens('d851','Malayalam',R='eṛ̆uka|eṛ̆u|eṛ̆uma|ēṛ̆uka|eṛ̆umpuka = eṛ̆uka|eṭukka|eṭuppu|eṭuppikka')
    tokens('d851','Kannada',R='eṛ̆|ēṛ̆ (eṛ̆d-)|ēṛ̆u (edd-)|eṛ̆bu|eṛ̆bisu|eṛ̆visu|erbu|eṛ̆caṟ',O='ebbu|ebbisu|eccaṟ (eṛ̆catt-, eccatt-)|eccaṟ|eccaṟa|eccaṟike|eccaṟisu')
    tokens('d851','Kodagu',R='ə·ḷ- (ə·v, ədd-)|əḍɨ- (əḍɨp-, əḍɨt-)',O='əpp- (əppi-)|eccara')
    tokens('d851','Tulu',R='erkuni|erkɯ|erka|erke|erkelɯ|ertɛ|erkāvuni|erpuni|eḷañci',A='leñci',O='eñci|ēñc̣ɯ|eccarike|eccaripuni|eccarisuni')
    tokens('d851','Badaga',R='ellu|ēḷa',O='ebbu|eccarike')

    add('d859','throw, strike, shoot','*e/iṟ-i/u; long *ēṟ; labial extensions',
        'Ø','e/i','ṟ','i/u/a','VC-i / VC-C / VVC','verb/noun',
        'Tamil eṟi/iṟu, Malayalam eṟiyuka, Kannada iṟi and Konda iṟ independently establish vowel-first alveolar order. Long ēṟu/ēṭu blow is independently attested and not shortened to fit the short branch.',
        'Broad southern and Konda/Kuvi vowel-first reflexes precede Telugu ṟimmu and Gondi rē/rēh under a displacement account. Exact labial formative of ṟimmu is less certain than root order.',
        '*iṟ-(V)mm > *ṟimm gives Telugu ṟimmu if that strong labial derivative is established; a high-vowel root is independent, but mm must not be invented from the outcome. Gondi rē/rēh likely displaces a vowel-first stem while other dialects retain ērīstānā/ertānā. Kannada ṟeppu is an initial-loss/displaced-looking labial form with unexplained e. Kui ig-b > ibg is separately supported local cluster exchange.',
        'Quantity and suffix predictions remain conditional: independent iṟi does not establish the exact mm derivative. Kannada initial ṟeppu may be local development or contact, not a family-wide exceptionless process. Kui ig root versus ṟ needs an allomorphic/correspondence explanation, while Kuvi ir remains unchanged. Toda mediative-causative eṯ is morphologically distinct from the throwing root and not an independent ordinary verb vote.',
        {'Tamil':('R','eṟi|iṟu|eṟṟu|ēṟu|eṟiva','Short, strong and long formations.'),'Malayalam':('R','eṟiyuka|eṟi|eṟikka|ēṟu|eṟṟu|eṟṟuka','Same.'),'Kota':('R','eyr- (erc-)|eyr-|erc-|eyrl|e·rp|e·r pa·ṛ|e·rp pa·ṛ|et- (ety-)','Apical/dental paradigm and long nouns.'),'Toda':('R','eṟy (eṟs-)|iṟ- (iṟQ-)|iṟ-|iṟθ-|ɨṟ|īṟk|i·ṟk','Full root and long cutting nouns; separate causative suffix omitted.'),'Kannada':('A','iṟi (iṟid-)|iṟi|iṟu|iṟa|iṟipu|iṟita|iṟata|iṟaku|iṟike|ēṟu|ēṭu|eṭṭu|ettu|ṟeppu','Retained roots and uncertain initial-loss labial form.'),'Tulu':('R','eṭṭuni|eṭṭakuṭṭa','Strong dental formations.'),'Telugu':('M','ēṭu|ṟimmu','Long retained blow versus short displaced labial verb.'),'Gondi':('M','ērīstānā|ertānā|rē|rēh','Retained and displaced formations.'),'Konda':('R','iṟ- (iRt-)|eR- (-t-)|iṟga','Short root and sling derivative.'),'Kui':('A','ibga','Velar allomorph relation unresolved; local g-b exchange separate.'),'Kuwi':('R',"ir- (-h-)|irh'nai|iskali",'Retained rhotic and plural-action palatal/cluster formation.'),'Pengo':('R','ec- (ecc-)','Apical-to-palatal root remains vowel-first.'),'Gadaba':('R','ey- (eṭṭ-)','Strong paradigm retains order.'),'Badaga':('R','iri|ēru|mandēru','Short verb and long ache noun.')},
        quantity='short/long by formation',input_confidence='high root order; low exact Telugu mm suffix',references='DEDR859',boundary='Short labial verb and independent long noun differentiated; no suffix recovered solely from output.')
    tokens('d859','Kannada',R='iṟi (iṟid-)|iṟi|iṟu|iṟa|iṟipu|iṟita|iṟata|iṟaku|iṟike|ēṟu|ēṭu|eṭṭu|ettu',A='ṟeppu')
    tokens('d859','Telugu',R='ēṭu',D='ṟimmu')
    tokens('d859','Gondi',R='ērīstānā|ertānā',D='rē|rēh')

    add('d860','pull, drag, pluck','regional *ṟel / *er-i / *ar-i; deeper order uncertain',
        'Ø/r','e/a','r/ṟ/l','i/unknown','VC-i versus CVC','verb',
        'Gondi ari/eri full forms coexist with Konda ṟel, Kui jel and Pengo jel. Telugu remmu has a labial formation, not the same medial/final consonants as all the eastern stems.',
        'Gondi may preserve an earlier vowel-first root, but the broad regional ṟel/jel series and its final l cannot be derived by a bare reversal of ari. The displayed *Rel is a regional reconstruction, not independently settled deeper order.',
        'A conditional *eṟ-Vl > *ṟel could account for the Konda/Kui/Pengo series, with later ṟ>j, but no full identical -Vl formation is attested here. Telugu *eṟ-(V)mm > remmu requires a different derivative. Alternatively the Gondi ari material and eastern ṟel stems are distinct or only distantly related.',
        'Keep the entire displacement claim uncertain rather than inventing *erel/*erimm to explain each result. Needed: older Gondi/Konda paradigms, independent final-l derivative, and regular correspondences linking Telugu mm to the same root. The several Gondi bringing/taking compounds do not add independent lexical votes.',
        {'Telugu':('A','remmu','Unmatched labial formation.'),'Gondi':('R','ari sota|arri|arrī|arri vara|arri tatānā|arītānā|arrītānā|erī|aṛ vay','Vowel-first local forms, deeper cognacy uncertain.'),'Konda':('A','ṟel- (ṟen-, ṟeR-)','Initial alveolar, final lateral with paradigm.'),'Kui':('A','jelba (jes-)','Initial j/final l derivation not fully established.'),'Kuwi':('A',"re'- (recc-)|rennai|rejali (rec-)|rejja-koḍḍinai",'Diverse strengthened/compound forms.'),'Pengo':('A','jel- (-t-)','Regional initial-j lateral root.')},
        input_confidence='low for common full input',references='DEDR860; DEN1 1972 p.415 entry4243',eligibility='lookalike-unresolved',boundary='Final-l and labial derivatives require independent reconstruction.',mechanism='Competing cognacy and displacement hypotheses.')
