"""Strong-root controls and a North Dravidian cluster-loss comparison."""

def populate(add,tokens):
    add('d958','adhere, join, heap; smear','*oṭṭ- / *oṇṭ-; Central *oṭ-p-',
        'Ø','o','ṭ','u/i/zero','VCC-V / VC-p','verb/noun',
        'Tamil oṭṭu/oṇṭu, Malayalam oṭṭuka and Kannada oṭṭu/oḍḍu independently establish strong/geminate or nasal-cluster formations; a singleton dictionary head does not override them.',
        'Vowel-first forms in SD I, Telugu and CD establish order; the independently strong SD I consonants explain why this is not a plain singleton-apical control.',
        '*oṭṭ > oṭṭu/oḍḍu with strength/voicing variation; Central oṭ-p/ or-p keeps vowel before apical plus labial. Kota oṭ/oc paradigms reflect local consonant developments, not initial displacement.',
        'Smear and adhere meanings could connect separate strong formations; exact common reconstruction needs caution. Telugu fire-placing and total senses are not two roots for frequency counts. Relation to oath959 and place962 is semantically possible through bind/place but not automatic.',
        {'Tamil':('R','oṭṭu|oṇṭu|oṭṭal|oṭṭi','Independent strong/nasal variants.'),'Malayalam':('R','oṭṭu|oṭṭuka|oṭṭikka|oṭṭam','Strong root.'),'Kota':('R','oṭ- (oṭy-)|oṭ- (oc-)|oṭ- (oṭy)|oc-','Local paradigms.'),'Kannada':('R','oṭṭu|oḍḍu|oḍḍa|oṭṭisu|oṭṭalu','Strong retained root.'),'Tulu':('R','oṭṭu|oṭṭuni','Strong root.'),'Telugu':('R','oṭṭu','Total and putting senses.'),'Parji':('R','oṭp- (oṭt-)','Consonantal formative.'),'Gadaba':('R','orp- (ort-)','Consonantal formative.'),'Badaga':('R','oṭtu|ottu|oṭṭu|oddu','Source/dialect variants, one family.')},c2_structure='geminate/nasal cluster independently attested; Central formation uncertain',references='DEDR958',eligibility='strong-cluster-control',input_confidence='high for strong SD I formation')
    add('d959','oath, wager','regional *oṭṭ/oḍḍ; Indo-Aryan *hōḍḍa comparison',
        'Ø','o','ṭ','u/a','VCC-V','noun/verb',
        'Tamil oṭṭu, Malayalam oṭṭam and Kannada oṭṭu/oḍḍu establish a strong medial stop independently of Telugu. Eastern singletons may reflect simplification or borrowing.',
        'All selected forms keep vowel before the stop; the source does not require initial-stop metathesis.',
        '*oṭṭ > Telugu oṭṭu oath and oḍḍu wager; Kui oḍa and Kuvi oṭu/ottinai show regional strength variation. Kuvi ōtali has lengthening with vowel first, not a metathesis long-vowel product.',
        'Indo-Aryan hōḍḍa/hoḍḍa and modern hoṛ forms require contact analysis; their initial h is not evidence for a Dravidian word-initial apical. CDIAL explicitly labels Sinhala oṭṭu as Tamil loan, which is not an independent Dravidian vote. Shared origin with adhere958/place962 remains a family sensitivity question.',
        {'Tamil':('R','oṭṭu|oṭṭam','Strong root.'),'Malayalam':('R','oṭṭam','Strong wager noun.'),'Kannada':('R','oṭṭu|oḍḍu|oḍḍa','Voice/meaning contrast.'),'Telugu':('R','oṭṭu|oḍḍu|oḍḍanamu|oḍḍimi','Several derivatives of one family.'),'Kui':('R','oḍa (oḍi-)','Singleton outcome of uncertain strength/contact history.'),'Kuwi':('R','otali|ōtali|oṭu|ottinai','Short/long variants retain order.'),'Kolami':('R','oḍ','Vowel first.')},c2_structure='geminate independently supported',references='DEDR959; CDIAL14175',eligibility='strong-cluster-contact-control',input_confidence='high for strong regional form; inherited distribution uncertain')
    add('d962','place, offer, extend; set net or snare','regional *oḍḍ-; Old Telugu oḍ-uk variant',
        'Ø','o','ṭ','u','VCC-V / VC-u-C','verb',
        'Kannada oḍḍu and Tulu oḍḍuni independently support a strong medial retroflex matching Telugu oḍḍu. Old Telugu oḍuku is a distinct weaker extended form, not evidence that modern strength was original in every formation.',
        'SD I and Telugu retain initial vowel; Gondi urrānā and Malto aḍye have the same order despite different consonant strength and vowel.',
        '*oḍḍ > oḍḍu and regional simplified oḍ; Old Telugu oḍuku requires derivational or strength-alternation history. No initial displacement is necessary.',
        'Pali oḍḍeti set a net is explicitly compared; contact direction is not established here. Old Telugu inscription label has no date in this record, so it cannot anchor chronology. Do not merge place962 with bank965 or stake959 solely for phonetic identity; retain a documented sensitivity option.',
        {'Kota':('R','oḍ- (oḍy-)','Set-net verb.'),'Kannada':('R','oḍḍu|oḍḍisu|oḍḍuvike|oḍḍike','Strong root and derivatives.'),'Tulu':('R','oḍḍuni|oḍḍāvuni','Strong root.'),'Telugu':('R','oḍḍu','Strong root.'),'OTelugu':('R','oḍuku','Undated inscriptional weak extension.'),'Gondi':('R','urrānā','Retained vowel-first noose verb.'),'Malto':('R','aḍye','Vowel correspondence needs explanation, order retained.')},c2_structure='geminate with separate singleton extension',references='DEDR962; source Pali comparison',eligibility='strong-formation-contact-control',input_confidence='high for strong regional form; medium for full cognacy')
    add('d965','bank, shore, slope','*oṭṭ / *oṇṭ-',
        'Ø','o','ṭ','u/i','VCC-V','noun',
        'Kannada oḍḍu/oṇḍi and Kurux oṭṭā independently support strong or nasal-cluster input, while Konda/Gondi/Kuvi singletons are daughter outcomes.',
        'Cross-branch vowel-first forms and independent consonant strength support retained order, not reconstruction from Telugu alone.',
        '*oṭṭ-V > Telugu/Kannada oḍḍu, with simplification in Gondi/Konda/Kuvi oḍu. Nasal Kannada oṇḍi supplies a formation variant but does not uniquely prove common *oṇṭ.',
        'Regional river terminology could diffuse, and the comparison does not prove every singleton is independently inherited. Badaga slope and numerous place names derive from one base; never count each name. Meaning could connect to a bank built by heaping958, but that semantic history is unproven.',
        {'Kota':('R','oḍ','Slope.'),'Kannada':('R','oḍḍu|oṇḍi','Strong and nasal variants.'),'Telugu':('R','oḍḍu','Strong bank noun.'),'Gondi':('R','oḍu','Seoni/Koya records, one language-family cell.'),'Konda':('R','oḍu','Simplified stop.'),'Kuwi':('R','oḍu','Dialect duplicates preserved.'),'Kurux':('R','oṭṭā','Independent strong stop.'),'Badaga':('R','oddu|odde','Slope base; place names not extra roots.')},c2_structure='geminate/nasal cluster',references='DEDR965',eligibility='strong-cluster-control',input_confidence='high for non-singleton regional input')
    add('d967','clear, pure, beautiful; filter','regional *oṭ-V',
        'Ø','o','ṭ','i/a/unknown','VC-V / VC-p','verb/adjective/noun',
        'Kui oḍa and Kuvi odi/oditi/oḍ independently support short vowel-before-retroflex matching Telugu oḍikamu, but not its exact -ikam suffix.',
        'The eastern full forms establish order independently of Telugu; all remain vowel first.',
        '*oṭ-i/V > odi/oḍa/oḍikamu; Kuvi oṭpi and oṭ show transitive/strong development while retaining vowel first. Light verbs in oṭpi ki are not pieces of a reconstructed root.',
        'Beauty versus purity/recovery is a plausible semantic connection, with contact still possible in this regional set. Kui oṭka is stranded in the gloss and has not been newly normalized as an attestation. The high second vowel of Telugu matches Kuvi odi but the complete nominal derivation remains unestablished.',
        {'Telugu':('R','oḍikamu','Retained short formation.'),'Kui':('R','oḍa (oḍi-)','Full paradigm.'),'Kuwi':('R','odi|oditi|oḍ- (-it-)|oṭ- (-h-)|oṭpi ki|otpinai|otʰpinai|otʰ\'nai|oḍḍamne','Distinct formations, no displacement.'),'Kolami':('R','oḍav','Retained regional adjective.')},references='DEDR967; DEDS(N)112',eligibility='regional-formation-control',input_confidence='medium')
    add('d985','slowly, gently; constantly','expressive *oll-/oyy- with adverbial material',
        'Ø','o','ll/yy','a/e','VCC-V(n)','adverb',
        'Kannada ollane/oyyane and Tamil oyy-eṉa establish a strong consonant and adverbial formation independently of Telugu ollana/oyyana.',
        'All witnesses have vowel before lateral/glide; ll versus yy is a segmental alternation, not an order change.',
        '*oll/oyy-an > ollane/ollana/oyyana, with Tamil eṉa quotative/adverbial material potentially separately grammaticalized. Kuvi olle olle is reduplicated.',
        'Expressive origin, quotative material and ll/yy alternation prevent a unique singleton reconstruction. Kuvi constantly versus gently/slowly needs semantic caution and may reflect borrowing; Naikri regional diffusion also remains possible. Repeated olle is one adverbial formation.',
        {'Tamil':('R','oyy-eṉa','Geminate glide with adverbial material.'),'Kannada':('R','ollane|oyyane','Lateral/glide alternatives.'),'Telugu':('R','ollana|oyya|oyyana','Retained strong expressive forms.'),'Kuwi':('A','olle olle','Semantic/contact qualification.'),'Naikri':('R','ollaki','Strong lateral regional adverb.')},c2_structure='geminate lateral/glide',references='DEDR985',eligibility='expressive-geminate-control',input_confidence='medium')
    add('d996','sound, cry, weep','*ol-i/u; *ol-k; *ul-amp; long *ōl formations',
        'Ø','o/u','l','i/u/zero/a','VC-V / VC-k / VC-a-mp; long nouns','verb/noun',
        'Tamil oli/ulampu, Malayalam oli and Kannada uli independently support vowel-before-lateral. Kurux olx and Malto olg give an independently matching northern velar extension for comparison with Brahui hōɣ.',
        'The northern full lateral-plus-velar forms are particularly strong evidence for order and for loss of lateral in Brahui; a Telugu metathesis model is unnecessary.',
        '*ol-k > Kurux olx, Malto olg and, with lateral loss plus initial h/vowel history, Brahui hōɣ. Emeneau1997 pp.441–442 proposes this cluster-loss analysis and compares other lost preconsonantal laterals. Telugu uliyu/ulivu retains order; Tamil ōl/ōlam involves separate quantity formation. No root-lateral promotion is established.',
        'Bray instead proposed imitative hō plus hiatus-bridging ɣ; Emeneau argues the comparative velar extension favors inheritance but leaves imperative/prohibitive ɣ absence unresolved. The source does not supply every intermediate explaining Brahui length and h. Keep that uncertainty visible; neither competing account is initial liquid metathesis. Tamil/Malayalam ulapp versus ulamp is nasal/strength variation. Potential relationship to strong oll expressives985 is not assumed.',
        {'Tamil':('R','oli|olippu|ulampu|ulampal|ulappal|ōl|ōlam|ōlu|ōl āṭṭu','Short, long and labial formations.'),'Malayalam':('R','oli|olikka|ulampuka|ulappam|ōli|ōlam','Retained order.'),'Kota':('R','oj|o·l a·ṭ- (a·c-)','Lateral/glide development and compound.'),'Kannada':('R','ole|uli (ulid-)|ulivu|uluvu|ulipu|ulipa','High-vowel root retained.'),'Kodagu':('R','oli','Retained order.'),'Telugu':('R','uliyu|ulivu','Retained high-vowel formation.'),'Kurux':('R','olᵒxnā (ulxyas)|cīxnā olᵒxnā','Northern full lateral-velar input.'),'Malto':('R','olge','Northern full lateral-velar input.'),'Brahui':('O','hōɣẖing|hōɣ-','Lateral cluster loss versus imitative analysis; no secure displacement.')},quantity='short root and separately long formations',references='DEDR996; Emeneau1997 pp.441–442 §§2.2–3 directly read; https://www.jstor.org/stable/619537',eligibility='mixed-formation-cluster-loss-control',input_confidence='high for northern ol-k comparison',mechanism='Brahui cluster-member loss; competing imitative origin, not initial apical metathesis.')
