"""Kuvi nasal/long domains; distinguish inherited nasal from secondary nasal."""

def populate(add,tokens):
    add('d4438','god, spirit, demon','*pēy / regional *pēn; Kuvi plural pēn-ka',
        'p','ē','n/y','zero/u','CVVC + plural-k(a)','noun',
        'Gondi pēn, Pengo pen and Kui pēnu independently establish a regional nasal stem; Kuvi itself has pēnu and retained plural pēṇka/pēnka. Tamil pēy and other southern y forms make the deeper nasal-versus-glide reconstruction uncertain, without undermining the immediate Kuvi nasal input.',
        'The singular stem and retained plural supply vowel-before-nasal order inside the same paradigm. pṇēka has no inherited initial cluster in that paradigm.',
        'Kuvi pēn-u + -ka > pēn-ka > pṇē-ka, with the vowel and nasal changing order in the consonantal plural formation and n/ṇ place variation. The explicit pēṇka/pṇēka alternatives are especially useful. Kui pēnu:pēnga and Gondi pēn:-k keep the vowel before the nasal. Tamil pēcci involves a separate strong derivative.',
        'This long-vowel nasal plural process falls outside the older narrow Telugu lexical domain. The data establish a morphological distribution, not a dated innovation or contemporary productivity. The surface plural can alternatively be modeled as stem allomorphy learned after a historical reordering; it is not eight independent etyma. DEDR parser truncates S. pēnka closing punctuation. No Telugu attestation in this entry is not a retained Telugu outcome. Possible pēy/pēn versus Parji vē̃d5530 connections and cult-term diffusion need separate reconstruction.',
        {'Tamil':('R','pēy|pēyaṉ|pēytti|pēycci|pēcci','Long root and strong derivatives.'),'Malayalam':('R','pē|pēyi|pēna|pē-nāyi','Glide/nasal and compound variants.'),'Kota':('R','pe·y|pe·n|pe·nm','Independent nasal/glide regional alternatives.'),'Toda':('R','ø·n|ø̄n','Initial labial loss; vowel still before nasal.'),'Kannada':('R','pē|hē|pētu|hēde|pēŋkuṇi|pēŋkuḷi|hēkuḷi','Several formations, no initial sonorant cluster.'),'Tulu':('R','pēyi','Long vowel before glide.'),'Gondi':('R','pēn|pen|ven|pēnu|pēn ( -k)|peṇ ( peṇḍku)|pēnvor','Nasal stem and retained plurals.'),'Kui':('R','pēnu ( pēnga)|vēnu ( vēnga)','Long nasal retained through plural.'),'Kuwi':('M','pēnu|pēṇka|pṇēka|pēnka|pēnū','Research-split paradigms preserve both plural orders.'),'Pengo':('R','pen ( -ku)','Short retained regional paradigm.'),'Malto':('R','peypeyre','Expressive reduplication with vowel before glide.'),'Badaga':('R','pēi|pēiki|pēi pisāsu','Long vowel before glide, derivatives one family.')},
        quantity='long regional root; Pengo short',c2_structure='nasal in immediate Kuvi input; deeper n/y uncertain',references='DEDR4438; PSS83 p.232 n.5; Hume2004 p.225',eligibility='late-kuvi-long-nasal-plural',boundary='Independently attested singular nasal stem plus consonantal plural suffix; source retained and displaced plurals.',input_confidence='high for immediate Kuvi nasal and length',mechanism='Direct paradigm supports long vowel–nasal reordering; stem allomorphy and phonetic implementation not independently dated.')
    tokens('d4438','Kuwi',R='pēnu|pēṇka|pēnka|pēnū',D='pṇēka')
    add('d4885','fish','*mīn; Kuvi mīn-ka',
        'm','ī','n','zero/u','CVVC + plural-k(a)','noun',
        'Tamil mīṉ, Malayalam/Kannada mīn, Telugu mīnu and the Gondi/Konda/Kui forms independently establish long vowel before nasal. Kuvi singular mīnu and retained S. plural mīnka establish the immediate morphological input without relying on a reconstruction.',
        'The full singular and alternative plural mīnka make m-n-ī in mnīka innovative. F. mrīka has secondary rhotic in the displaced cluster, not an independently primary r root.',
        'mīn-u + -ka > mīn-ka > mnī-ka, with dialectal mṇīka and mrīka requiring place/rhotic developments. Isr. singular mṇīnu retains the old postvocalic n as well as cluster ṇ: it is plausibly remodeled from the plural, or has nasal excrescence, rather than a literal one-for-one exchange. Kui mīnu:mīnga and Konda mīn:mīnga retain order.',
        'The singular cluster variant must not count as independent confirmation of a swap because it contains two nasals. Distinguishing analogical backformation from phonetic excrescence needs chronology and paradigms across speakers. Fish4885 and shine/star4876 may be historically related through bright/scaly semantics, but this is not established; merge only in a sensitivity partition. DEDR main parser omits Gadaba/Gondi/Konda and strands Isr. forms in glosses; source-restored observations preserve the complete printed paradigms. Sanskrit mīna is a contact comparison, not a Dravidian language denominator.',
        {'Tamil':('R','mīṉ','Independent long nasal.'),'Malayalam':('R','mīn','Long nasal.'),'Kota':('R','mi·n','Long nasal.'),'Toda':('R','mi·n|mīn','Long nasal; star homophony preserved.'),'Kannada':('R','mīn','Long nasal.'),'Kodagu':('R','mi·nɨ','Long nasal.'),'Tulu':('R','mīnɯ','Long nasal.'),'Telugu':('R','mīnu','Long nasal retained.'),'Gadaba':('R','mīn (mīnil)','Source-restored Ollari plural.'),'Gondi':('R','mīn','Source-restored broad dialect attestation.'),'Konda':('R','mīn (mīnga)','Source-restored BB paradigm.'),'Kui':('R','mīnu ( mīnga)','Long nasal retained through plural.'),'Kuwi':('M','mīnu|mīnka|mrīka|mnīka|mṇīka|mṇīnu','Plural reordering, retained plural and uncertain analogical singular.'),'Pengo':('R','min ( -ku)','Short regional paradigm, order retained.'),'Manda':('R','min ( -ke)','Short regional paradigm.'),'Parji':('R','mīni ( mīnul)','Long nasal retained.'),'Malto':('R','mínu','Accent versus quantity preserved.'),'Badaga':('R','mīnu','Fish base; star compounds not extra roots.'),'markodi':('R','mīn','Vannarkadav long root.')},
        quantity='long independently attested; Pengo/Manda short',c2_structure='nasal',references='DEDR4885 p.436 directly read; PSS83 p.232 n.5; Hume2004 p.225',eligibility='late-kuvi-long-nasal-plural',boundary='Attested singular stem plus plural -ka; source/dialect plural alternatives.',input_confidence='high',mechanism='Direct long vowel–nasal plural reordering; secondary cluster place change and possible singular analogy.')
    tokens('d4885','Kuwi',R='mīnu|mīnka',D='mrīka|mnīka|mṇīka',A='mṇīnu')
    add('d4855','Anogeissus tree','regional *miṇ-iya',
        'm','i','ṇ','i','CVC-i-yV','noun',
        'Pengo and Manda miṇiya independently give short i before nasal and i after it; Kuvi mṇīya is the displaced comparison. The database *mṇīj head follows the outcome and is not accepted as the earlier order.',
        'Two full regional forms support miṇ-i over an inherited initial mṇ followed by two separate identical epentheses; tree-name borrowing remains an alternative source of the geographical pattern.',
        'Possible *miṇ-iya > *mṇiiya > mṇīya, consistent with same-vowel contraction after nasal reordering. Literal exchange versus first-vowel loss and compensatory length is not uniquely proven by this set.',
        'This is a nasal-input case, unlike eel4737 where independent full forms have l. The sparse regional botanical comparison needs better species/dialect records, and the Kuvi database gloss loses an independent F. full form if any existed: only the printed Pengo/Manda evidence is asserted here. No Telugu attestation is a missing cell, not retention.',
        {'Pengo':('R','miṇiya','Full high-same-vowel input.'),'Manda':('R','miṇiya','Full input.'),'Kuwi':('D','mṇīya','Long displaced nasal cluster.')},c2_structure='nasal',references='DEDR4855; PSS83 p.232 n.5, DEDS785',eligibility='late-kuvi-short-nasal',boundary='Full miṇiya independently attested, but lexical suffix segmentation unproven.',input_confidence='high for immediate segment order, medium for common inheritance')
    add('d4876','shine, flash, lightning; star','*min / *min-uŋ/ukk; long star *mīn; regional *min-s',
        'm','i/ī','n','u/zero/unknown','CVC-C / CVC-u-CC; long noun','verb/noun',
        'Tamil miṉ/miṉuŋku, Malayalam minnuka and Kannada minugu establish a nasal root and short/long formation contrast independently. Kuvi miṇs, miṇig and mirsi coexist with mṇih/mṇīh and supply especially close regional input evidence.',
        'The full nasal root across southern languages and retained Kuvi miṇs favor pre-vowel nasal promotion for mṇih. Gondi/Konda r/ḍ variants show that the apical may change identity before or after reordering; their existence does not prove all Kuvi nasals are secondary.',
        'Regional miṇ-s > mṇi-s with h~st stem alternation can yield mṇih (mṇist-). The Isr. long mṇīh requires separate length or earlier vowel-coalescence history, not automatically the long star root. Telugu minuku:minku shows medial syncope retaining m-i-n order; miḍũgu versus miṇũgu involves nasal/stop change without metathesis. North bīnko/bínḍke has initial m>b and suffixal/cluster developments, not nasal promotion.',
        'Keep short shine and long star formations separate. The fish reconstruction linked in this entry should not replace shine-root quantity; possible common origin with4885 is sensitivity only. Kuvi mrih has rhotic rather than nasal, and full mirsi could precede it by the ordinary nonnasal process; the exact order of n>r and reordering is not independently dated. mṇispu spelling lightening is the source gloss, not a different weather concept. Tulu broken HTML fragments miṇ&lt/kuni/&gt are not independent lexical forms.',
        {'Tamil':('R','miṉ|miṉṉu|miṉṉal|miṉuŋku|miṉukku|miṉmiṉi|mīṉ','Short nasal root and long star.'),'Malayalam':('R','minnuka|minnu|minnal|minuŋŋuka|minukkuka|mīn','Separate short/long formations.'),'Kota':('R','minc- (minc-)|mi·n','Short verb versus long star.'),'Toda':('R','mic- (mič-)|mic|mi·n|mīn','Cluster loss in verb; long star retained.'),'Kannada':('R','minu|mini|minugu|minuku|miṇa|miṇaku|miṇuku|miñcu|mīn','Nasal place and short/long variants.'),'Kodagu':('R','minn- (minni-)','Strong retained root.'),'Tulu':('R','miṇuku|meṇuku|meṇakɯ|minukuni|miñcuni|meñcuni|miṇimiṇi','Retained nasal, vowel variants.'),'Telugu':('R','minuku|minku|miṇuku|mincu|miṇũgu|miṇũguṟu|miḍũgu|miḍũguṟu|minna|minamina|minukkuranu|minuku-minukum-anu','Medial syncope and nasal/stop variations, no initial displacement.'),'Gondi':('R','minko|mīnkō|minŋūṛ|miṛko|miṛkom|miḍkos|miṛc|miṛs|miḍcānā|miḍstānā|mirsālnā|mirsīlnā|mirsīltānā|mīḍsā|mīrcā','Nasal/rhotic/stop developments retain C-V-apical order.'),'Konda':('R','mirs','Retained secondary rhotic.'),'Kuwi':('M','miṇs|miṇig|mirsi mannai|mṇih- (mṇist-)|mṇīh- (mṇīst-)|mṇispu|mrih\'nai','Retained nasal/rhotic and displaced short/long variants.'),'Parji':('R','minnal','Strong nasal.'),'Gadaba':('R','munake','Vowel shift with nasal retained.'),'Kurux':('R','bincō|bīnkō','Initial m>b and quantity formation.'),'Malto':('R','bínḍke','Initial m>b, retained vowel-before-nasal cluster.'),'Badaga':('R','minigu|miniki|miccu|miccalu|mīnu','Short verbs versus long star.'),'markodi':('R','idiminnal','Compound lightning term.')},
        quantity='short verbal root and independent long star formation',c2_structure='nasal; regional r/ḍ secondary',references='DEDR4876 p.435 directly read; PSS83 p.232 n.5',eligibility='late-kuvi-nasal-mixed-formation',boundary='Independent short/long lexical formations and Kuvi retained miṇs; exact long verbal grade unresolved.',input_confidence='high for nasal root; medium for immediate long verb',mechanism='Short nasal reordering supported; long variant and n/r chronology unresolved.')
    tokens('d4876','Kuwi',R='miṇs|miṇig|mirsi mannai',D='mṇih- (mṇist-)|mṇīh- (mṇīst-)|mṇispu|mrih\'nai')
