"""Retained Telugu formations with positive eastern comparisons and opaque relatives."""

def populate(add,tokens):
    add('d4411','grow, increase, big; elder kin','*per-u-k(k); *per-V / *pēr; kinship derivatives',
        'p','e','r','u/i/unknown','CVC-u-K / CVC-V / CVVC','verb/adjective/noun',
        'Tamil peruku/perukku, Malayalam perukuka and Telugu perugu independently share e-r-u-k. Konda pergi and Kolami perg corroborate consonantal derivatives. Long *pēr is independently distinct from the short grow verb.',
        'Multiple branches support p-V-r, and Telugu perugu/pergu retains it even after medial syncope. Old Telugu perddaḷ supplies medial r before dd in a different elder formation, supporting an internal-assimilation history for pedda.',
        '*per-uk > perug(u) > pergu retains order; it does not become **preggu. *per-tt > perdd > pedd gives the elder series schematically, supported by inscriptional perddaḷ. Other penu/penn/pemme/peccu derivatives may involve nasal/labial/palatal assimilation. Kui prēnḍa elder male is displaced-looking but its exact input vowel and quantity are not independently identical to grow *peruku.',
        'This is a genuine short-root high-u retained Telugu control, explicitly cited as nonapplication by PSS83 p.229. Loss of V2 alone is therefore insufficient to force metathesis. Elder kinship and person compounds add no independent roots. Telugu heccu/eccu, central pedda and Gondi peddal may involve borrowing or medial reduction; do not assert a hidden pr stage. Kui prēnḍa versus Kolami perendā supports a formation comparison, but ancient a versus e still requires independent reconstruction. The imported perl/peru HTML fragments are not extra Telugu forms.',
        {'Tamil':('R','peru|peruku|perukku|periya|perumai|perumāṉ','Full short-root formations retain order.'),'Malayalam':('R','peru|perukuka|perukkuka|periya|pēr|pirān','Short/long and kinship formations distinguished.'),'Kannada':('O','per|pēr|piri|percu|percisu|perme|peccu|pempu|pedda|peddi|heccu|eccu','Retained root versus internal assimilation and p/h/loss history.'),
         'Kodagu':('R','perɨ|perɨm|perɨ- (perɨp-, perɨt-)|periə|perta','Retained short formations.'),'Tulu':('O','periya|percuni|pērcuni|perguḍɛ|heccuni|hemme|hemma','Retained apical versus medial assimilation and initial change.'),'Kota':('O','pe|pe-|ec- (ec-)|ec|peda·ry','Medial and initial consonant losses; individual derivative histories unresolved.'),'Toda':('O','pe|pex- (pexy-)|ec- (eč-)|ic- (ič-)','Medial/initial reduction in different formations.'),
         'Telugu':('O','perugu|pergu|perũgu|perũguḍu|perime|pērimi|pērima|pēru|pērucu|pērcu|pedda|peddi|penn|penu (before consonant)|pemme|peccu|pencu|pekku|heccu|eccu|pellu','Secure retained grow and long formations; numerous other derivatives separately coded.'),
         'OTelugu':('R','perddaḷ','Medial r retained before dd in elder plural.'),'Gondi':('O','pers|persānā|bers|bars|beriya|biriyā|paṛōl|perma|pēri|pēṛī|pēpi|pēpī|peddal','Retained rhotic and medially reduced kinship/office formations; contact possible.'),'Konda':('R','per|peri|pir|pergi|pirp','Root and velar/labial growth formations retain order.'),
         'Kui':('A','beri beri inba|pēreṛi|pēro|prēnḍa|pihereju','Retained swell/big forms; initial-cluster elder derivative has less secure exact input.'),'Kuwi':('R','bir- (-it-)','Retained grow root.'),'Manda':('O','pēmba','Medial rhotic/labial formation, no directly attested initial cluster.'),
         'Kolami':('A','per|pera|peret|perg- (perekt-)|perp- (perept-)|perendā|perāmā|pedda','Retained inherited-looking forms plus possible Telugu pedda loan.'),'Naikri':('A','perg|perp|pedda','Growth retained; elder form may be borrowed.'),'Naiki':('R','peruk|perk|pʰar','Retained order with aspiration and vowel differences.'),'Parji':('O','peru|berto|peŋgoṭ|peñot','Retained root and medially altered quantity formations.'),'Gadaba':('O','pernonḍ|berit|berbullū|beŋgiḍ|beŋgurtul','Retained apical versus medial nasal formations.'),'Brahui':('R','piring','Retained short-vowel swell root.'),'Badaga':('O','eccu|heggade|heggirisu','Internal/initial changes with contact possibilities; selected relevant lexemes only.'),'markodi':('R','periyə','Retained adjective.')},
        input_confidence='high',references='PSS83 p.229 §16.1.2; DEDR 4411; K03 *per-V/*pēr',quantity='mixed by formation',boundary='Short high-u grow formation independently matched; free/long big and elder compounds receive separate formation classes.',mechanism='Genuine retained grow formation; internal assimilation and uncertain kinship displacement elsewhere.')
    tokens('d4411','Telugu',R='perugu|pergu|perũgu|perũguḍu|perime|pērimi|pērima|pēru|pērucu|pērcu',O='pedda|peddi|penn|penu (before consonant)|pemme|peccu|pencu|pekku',A='heccu|eccu|pellu')
    tokens('d4411','Kannada',R='per|pēr|piri|percu|percisu|perme',O='peccu|pempu|pedda|peddi|heccu|eccu')
    tokens('d4411','Tulu',R='periya|percuni|pērcuni|perguḍɛ',O='heccuni|hemme|hemma')
    tokens('d4411','Gondi',R='pers|persānā|bers|bars|beriya|biriyā|paṛōl|perma|pēri|pēṛī',O='pēpi|pēpī',A='peddal')
    tokens('d4411','Kui',R='beri beri inba|pēreṛi|pēro|pihereju',A='prēnḍa')
    tokens('d4411','Kolami',R='per|pera|peret|perg- (perekt-)|perp- (perept-)|perendā|perāmā',A='pedda')
    tokens('d4411','Naikri',R='perg|perp',A='pedda')
    tokens('d4411','Parji',R='peru|berto',O='peŋgoṭ|peñot')
    tokens('d4411','Gadaba',R='pernonḍ|berit|berbullū',O='beŋgiḍ|beŋgurtul')

    add('d3259','open','*ti/eṯ-a; velar, labial and palatal extensions',
        't','i/e','ṟ','a','CVC-a / CVC-a-C','verb/noun',
        'Tamil tiṟa, Kannada teṟa/teṟe and Malayalam tuṟakka independently establish a low-a formative and t-V-apical order. Telugu teṟacu/teṟa retains that independently supported environment.',
        'Full southern forms and Konda Gūṛi teṟe support t-V-apical before Konda ṟe. Initial loss alone from teṟa would give ṟa, so the mid vowel in ṟē/jē requires prior vowel interaction or a different independently established formation.',
        'Conditional *teṯ-a > *tṟē > ṟē gives Konda; later apical change gives Pengo/Manda jē and Kuvi de. Kui dāpa adds low outcome (contraction then lowering or lowering then contraction). Telugu teṟacu retains initial order, and suffix cu requires its own historical morphology.',
        'A clear low-a retained Telugu family versus broader eastern displacement. Gondi rehānā may show first-member loss, but its own suffix/vowel and donor history remain uncertain. Tulu jappuni/depp could involve medial assimilation plus initial t>j/d, not necessarily the same metathesis; Kurux/Malto tisg likewise preserves the first vowel despite loss/change of apical. Toda key tɨrp is explicitly alternatively compared with turn d3246 or Tamil borrowing and cannot be treated as an independent ordinary open reflex.',
        {'Tamil':('R','tiṟa|tiṟappu|tiṟavu|tuṟappu','Full low-formative root, i/u variant.'),'Malayalam':('R','tuṟakka|tuṟakku|tuṟappu|tuṟavu','Low-formative root with initial u.'),'Kannada':('R','teṟa|teṟe|teṟapu|teṟahu|teṟavu|teṟave','Full low-formative retained series.'),'Kota':('R','terv- (terd-)','Syncope retains initial order.'),'Toda':('A','teṟ- (teṟQ-)|teṟ ɨr|tɨrp','Retained root and uncertain key comparison.'),'Kodagu':('R','tora- (torap-, torand-)','Retained low-a paradigm.'),'Tulu':('A','terapu|jappuni|depp|jattoṇuni','Retained space noun versus opaque consonant developments.'),
         'Telugu':('R','teṟa|teṟacu|teṟapa|teṟapi','Retained initial order throughout selected formations.'),'Gondi':('A','tarī|tarītānā|tarritānā|taṛi|terr|teṛ|tarih|tarh|rehānā|tugaituna','Full retained forms with uncertain r-initial and old-transcription outliers.'),'Konda':('M','teṟe|ṟe|ṟē','Gūṛi retains first consonant/V order; other variants show displaced apical and first-member loss.'),'Kui':('A','dāpa (dāt-)|dari inba','Displaced/lowered door-opening formation; dari expressive/light-verb formation uncertain.'),'Kuwi':('D',"de'- (det-)|de'nai",'Displaced family with initial-member loss and apical reflex d.'),'Pengo':('D','jē- (-t-)','Displaced family with first-member loss and apical j.'),'Manda':('D','jē- (-t-)','Same.'),'Kurux':('O','tisⁱgnā (tisɣas)|tisgrnā','Medial apical/cluster change, first vowel retained.'),'Malto':('O','tisge','Same broad internal pattern.'),'Badaga':('R','tare|tera','Retained low-formative verb and noun.')},
        input_confidence='high',references='K03 p.160 example 94; K80 pp.497–499 item 10; DEDR 3259',boundary='Low-a root independently attested; local labial/palatal extensions and input grades separate.')
    tokens('d3259','Toda',R='teṟ- (teṟQ-)|teṟ ɨr',A='tɨrp')
    tokens('d3259','Tulu',R='terapu',A='jappuni|depp|jattoṇuni')
    tokens('d3259','Gondi',R='tarī|tarītānā|tarritānā|taṛi|terr|teṛ|tarih|tarh',A='rehānā|tugaituna')
    tokens('d3259','Konda',R='teṟe',D='ṟe|ṟē')
    tokens('d3259','Kui',D='dāpa (dāt-)',A='dari inba')

    add('d4760','forget, hide, be lost','*maṯ-a/ay; *maṯ-a-nk and *maṯ-u-k formations',
        'm','a','ṟ','a/u','CVC-a / CVC-a-NK / CVC-u-K','verb/noun',
        'Tamil maṟa/maṟai, Malayalam maṟakka/maṟayuka and Kannada maṟe/maṟagu establish m-a-apical-a independently. Gondi māraŋg/mareŋg and Konda marg support a nasal/velar lost/hide formation.',
        'Full southern and Gondi/Konda forms support original m-V-apical. Telugu maṟacu/maṟũgu retains that order, while Kui mrāŋga promotes the apical into a cluster.',
        '*maṯ-aŋk > *mṟāŋg > Kui mrānga. Kuvi/Pengo jāŋg and Manda dāŋg are derived by DEDR through *mṟāŋg > *mjāŋg > jāŋg (with Manda apical d); these intermediate clusters are reconstructed, unlike attested Kui mr-. Separate causative mrāk-p > mrāp-k produces Kui mrāpka. Gondi ractāl is explicitly derived by the source from *mṟac with initial m loss.',
        'Low-a does not compel Telugu displacement. Different maṟa-cu, maṟu-k and maṟa-ŋ formations must remain distinct before interpreting exact exceptions. Eastern j/d stems support shared development more strongly when nasal/velar morphology agrees, but do not by themselves prove every language inherited an identical completed sound change. Southern and central mak/maŋ/meŋ reductions may be medial assimilation; do not force hidden mr stages. Tamil source ṛ in maṛa is a transcription inconsistency beside its clear ṟ derivatives.',
        {'Tamil':('R','maṛa|maṟai|maṟappu|maṟaivu|maṟaippu|maṟati','Full low-a formations.'),'Malayalam':('R','maṟakka|maṟayuka|maṟekka|maṟa|maṟavu|maṟappu','Retained low formations.'),'Kannada':('R','maṟe|maṟagu|maṟasu|maṟapu|maṟavu|moṟe','Order retained with separate vowel variants.'),'Kodagu':('R','mara- (marap-, marand-)|marandɨ|mare','Full low-a paradigm.'),'Kota':('R','marv- (mard-)|marc- (marc-)|mar','Syncope retains initial order.'),'Toda':('R','maṟ|maṟf|maṟf xɨy|maṟp','Root and compound forms retain initial order.'),'Tulu':('R','marepuni|marapuni|marapu|madapuni|madapu|madeyuni|madepuni|madɛ|marɛ','Medial r/d correspondences do not reverse order.'),
         'Telugu':('R','maṟacu|maṟũgu|maṟuvu|maṟukuva|maṟakuva|maṟapu|maṟapincu|maṟu-paḍu|moṟãgu|kanu-moṟãgu','Low/high and compound formations retain order.'),'Gondi':('M','mareŋg|māraŋg|marēngānā|maruŋg-sīānā|marūm|mak|makk|maksahtānā|ractāl','Retained full roots, internally assimilated hide, and displaced-source astray derivative.'),'Konda':('R','marg','Medial cluster retains initial vowel.'),'Kui':('D','mrānga (mrāngi-)|mrāpka (&lt; mrāk-p-; mrākt-)','Displaced nasal verb and independently analyzable causative cluster exchange.'),'Kuwi':('D','jāŋg- (-it-)|jānginai|jangali|jāk- (-h-)','Source reconstructs initial-member loss after displacement; quantity variants preserved.'),'Pengo':('D','jaŋg|jaŋ|jak','Source reconstructs displaced family with first-member loss; nasal versus transitive velar distinct.'),'Manda':('D','dāŋg|dāk','Same formation correspondence with local apical d.'),
         'Kolami':('R','mad- (matt-)','Medial apical paradigm retains V after m.'),'Naiki':('O','mak|makup|makp','Internal assimilation possible.'),'Parji':('O','meŋg','Internal apical reduction and vowel change.'),'Gadaba':('O','meyk|meyikp- (meyikt-)|mēy|meyonḍi','Medial glide/reduction and voice morphology.'),'Malto':('O','masɣe|masekáre','Medial apical/fricative development; no initial displacement required.'),'Badaga':('R','mare|maru|marisu|maradi|mariti|maruma','Retained full formations.')},
        input_confidence='high',references='DEDR 4760 and explicit *mṟāŋg>*mjāŋg note; PSS83 p.229 lexical nonapplication principle',boundary='Low-a and high-u formations independently distinguishable; matched lost/transitive nasal/velar comparison across eastern languages.')
    tokens('d4760','Gondi',R='mareŋg|māraŋg|marēngānā|maruŋg-sīānā|marūm',O='mak|makk|maksahtānā',D='ractāl')
