"""Input-defined i/e plus retroflex-stop families, individually compared."""

def populate(add,tokens):
    add('d432','split, crumble, crack','*iṭ-i- / *iṭ-a- and labial nominal extensions',
        'Ø','i','ṭ','i/a','VCV / VCVC','verb/noun',
        'Tamil iṭi/iṭa, Malayalam iṭika/iṭakka, Kannada iḍi/iḍupu and Telugu iḍiyu/iḍupu support vowel-first order and more than one formative vowel independently.',
        'Agreement on initial i before the apical across several branches favors earlier iṭ-, without assuming the Tamil forms alone are conservative.',
        '*iṭ-i > Telugu iḍiyu, Kannada iḍi; *iṭ-u-p > iḍupu in both. Kota/Toda lose final/medial vowels but retain the initial vowel. Irula ḍepisu may involve local aphaeresis after vowel lowering, but the source does not supply its immediate earlier form.',
        'Irula is an uncertain local initial-loss candidate, not evidence that the Telugu innovation was shared with Irula. The nasal in iṇḍe needs a separate formation history. Pengo d2955 and Kolami d2974 are explicitly tentative comparisons and are not silently added to this root. Badaga idi is source-marked uncertain; do not treat hamlet Idukore as another root.',
        {'Telugu':('R','iḍiyu|iḍupu|iṇḍe','All retain an initial vowel; nasal formation distinguished.'),
         'Tamil':('R','iṭi|iṭa|iṭappu|iṭivu','Different formative vowels independently visible.'),
         'Malayalam':('R','iṭika|iṭakka|iṭikka','Order retained across intransitive/transitive forms.'),
         'Kannada':('R','iḍi|iḍupu|iṇḍe','Matches Telugu retention and derivative variation.'),
         'Kota':('R','iṛy- (iṛc-)|iṛyv','Syncope and apical correspondence preserve order.'),
         'Toda':('R','ɨṛy- (ɨṛs-)|ɨṛy-|ɨṛc-','Quality change and syncope, no relocation.'),
         'Kodagu':('R','ɨḍi- (ɨḍiv-, ɨḍiñj-)','Initial vowel retained.'),'Tulu':('R','iḍɛ','Vowel-first crack noun.'),
         'Irula':('A','ḍepisu','Likely aphaeresis; vowel and causative ancestry incompletely recovered.'),
         'Badaga':('A','idi','Plausible retained cognate, source marks uncertainty.')},
        references='DEDR 432; cross-references 2955,2974 remain tentative',input_confidence='high',
        boundary='i/a verbal formations and u-p nominal formation independently attested; no single V2 assigned to all derivatives.')

    add('d434','place, room, opportunity','*iṭ-a-m / *iṭ-ay',
        'Ø','i','ṭ','a','VC-a-C / VC-ay','noun',
        'Tamil iṭam/iṭai, Malayalam iṭam/eṭam and Kannada iḍe/eḍe agree on vowel-first i/e plus apical; Kota eṛm preserves the nominal m.',
        'The shared vowel-first forms establish the pre-displacement order. Southern i/e alternation supports lowering before a, not a proto-initial d.',
        '*iṭ-am > *eḍam > Telugu eḍamu; *iṭ-ay > *eḍay > eḍa/eḍe. Kota and Toda shorten the word by final loss while keeping the first vowel. Tulu source contains dekki alongside iḍɛ, a likely local initial-loss formation with gemination.',
        'Merge d434 with interval d448 for primary root counts: Tamil iṭai and Telugu eḍa/eḍamu recur with intersecting place/space senses. This avoids counting one spatial noun twice. The exact relationship of Tulu dekki to the other nominal formations remains unresolved and it is not automatically a SCDr-type contraction.',
        {'Telugu':('R','eḍa|eḍamu','Retained spatial noun, shared with d448.'),'Tamil':('R','iṭam|iṭai|iṭaṉ','Related spatial formations.'),
         'Malayalam':('R','iṭa|iṭam|eṭa|eṭam|ēṭam','Initial order retained despite quantity variants.'),
         'Kota':('R','eṛm','Nominal m retained after medial/final contraction.'),'Toda':('R','ɨṛṇ','Final m/n correspondence separate.'),
         'Kannada':('R','iḍe|eḍe|eḍa','Lowering variants, no initial relocation.'),'Kodagu':('R','əḍe','Vowel-first proximity noun.'),
         'Tulu':('R','iḍɛ','Parsed root retains order; embedded dekki requires separate source observation.'),
         'Badaga':('R','ede','Place noun; one root irrespective of compounds.')},
        family='d434+d448',references='DEDR 434,448',input_confidence='high',
        boundary='m and ay nominal formations independently supported; proto-root unity with other iṭ- meanings is only a sensitivity hypothesis.')

    add('d435','affliction, obstacle','*iṭ-ar / *iṭ-um(p)-',
        'Ø','i','ṭ','a/u','VCVC / VC-V-NC','noun/verb',
        'Tamil/Malayalam iṭar, Kannada iḍaru/iḍuru and Old Telugu eḍaṟu support initial vowel plus apical. Tamil iṭumpai and Telugu iḍuma independently support a distinct labial/nasal derivative.',
        'The historical Telugu retained form and southern comparison establish vowel-first ancestry. Telugu ḍepparamu is related semantically but its exact pp-bearing formation is not independently matched.',
        '*iṭ-ar > *eḍar > eḍaru; *iṭ-um(p) > iḍuma with independent labial changes. A conditional *iṭ-a-ppar > *ḍēppar > ḍeppar with pre-geminate shortening could yield ḍepparamu/depparamu, but the reconstructed extension is not established by iṭar alone.',
        'Treat ḍepparamu as probable displacement with unresolved formation rather than inventing *-appar to guarantee the rule. eḍḍamu/eḍḍami have strengthening or cluster assimilation, not initial metathesis. The older obstruction verb may belong with stumble d437; that family collapse is a sensitivity, not an asserted etymology.',
        {'Telugu':('A','iḍuma|eḍaru|eḍḍamu|eḍḍami|ḍepparamu|depparamu','Secure retained forms and uncertain displaced nominal formation.'),
         'OTelugu':('R','eḍaṟu','Historical retained verb, source inscriptional label.'),
         'Tamil':('R','iṭar|iṭumpu|iṭumpai|iṭai','Different suffix/root formations retain order.'),
         'Malayalam':('R','iṭar|iṭampuka','Order retained.'),
         'Kannada':('R','iḍaru|iḍuru|iḍru|eḍru|eḍaru|eḍaṟu','Medial syncope and r/ṟ variation preserve initial vowel.')},
        references='DEDR 435; tentative comparison 788',input_confidence='medium',
        boundary='ar and um(p) independently attested; Telugu ppar morphology is not reconstructed from outcome alone.')
    tokens('d435','Telugu',R='iḍuma|eḍaru',O='eḍḍamu|eḍḍami',A='ḍepparamu|depparamu')

    add('d437','stumble, hinder','*iṭ-aṟ / *iṭ-aŋk / *iṭ-Vp',
        'Ø','i','ṭ','a','VC-a-C','verb',
        'Tamil/Malayalam iṭaṟ-, Kannada iḍaṟu/eḍaṟu/eḍagu, Tulu eḍaŋkɯ and Malto iṛpe support initial vowel plus retroflex. The velar and rhotic extensions must be distinguished.',
        'The comparative vowel-first order and Tulu dialect doublets establish earlier V–ṭ; Telugu ḍekku has shifted/lost the initial vowel under this cognacy.',
        'Conditional *iṭ-a-k(k) > *eḍakk > *ḍēkk > ḍekku with shortening before kk. Tulu eḍaŋkɯ > ḍaŋkɯ/daŋkɯ is independently described as dialectal aphaeresis (K03 p.116), not a required same event. Kannada Havyaka ḍaŋku and Koraga ḍakki could be local losses or contact forms.',
        'The Telugu vowel e fits lowered *i before a, but its exact kk formation remains uncertain. Tulu dompu/dumpiyuni and doŋkɯ have labial/velar alternatives and rounded vowels that initial loss alone does not explain. Neither matching initial ḍ nor geographic proximity proves shared ancestry. Badaga erandu is source-uncertain and has an unexplained nasal sequence.',
        {'Telugu':('D','ḍekku','Probable displacement; pre-kk shortening and formative reconstruction conditional.'),
         'Tamil':('R','iṭaṟu|iṭaṟal','Retained rhotic formation.'),'Malayalam':('R','iṭaṟuka|iṭampuka|iṭantuka','Several retained extensions.'),
         'Kannada':('A','iḍaṟu|eḍaṟu|eḍagu|eḍgu|ḍaŋku','Native retained stems; Havyaka initial-loss/contact candidate.'),
         'Toda':('R','ɨḍ- (ɨḍy-)','Initial vowel retained in limp.'),
         'Tulu':('O','eḍaŋkɯ|ḍaŋkɯ|daŋkɯ|doŋkɯ|dompu|dumpiyuni|eṭṭuni','Dialectal aphaeresis, vowel variation and different extensions.'),
         'Malto':('R','iṛpe|iṛmbe','Retained order, different labial extensions.'),
         'Koraga':('A','ḍakki','Tappu form; local loss/contact versus inherited displacement unresolved.'),
         'Badaga':('A','erandu','Source uncertainty and nasal correspondence unresolved.')},
        references='DEDR 437; DEN1 1972 p.400 entry 371; K03 p.116 citing Kekunnaya 1994 pp.42–44',input_confidence='medium',
        boundary='Rhotic, nasal-velar and labial formations attested separately; exact Telugu strong velar suffix not assumed to be identical to all.')
    tokens('d437','Kannada',R='iḍaṟu|eḍaṟu|eḍagu|eḍgu',A='ḍaŋku')
    tokens('d437','Tulu',R='eḍaŋkɯ',O='ḍaŋkɯ|daŋkɯ|eṭṭuni',A='doŋkɯ|dompu|dumpiyuni')

    add('d439','flour-based cake','*iṭ-i (food noun)',
        'Ø','i','ṭ','i','VCV, also compound-initial','noun',
        'Tamil iṭi flour/confection and iṭiyappam, Malayalam iṭiyappam and Telugu iḍi/iḍikuḍumu agree on the vowel-first food base.',
        'Independent southern food compounds corroborate vowel-first iṭi; there is no evidence here for a proto-initial ḍi.',
        '*iṭi > Telugu iḍi; appam/kuḍumu are separate compound components. The high-i match makes this a formal comparison to beat d443, but food-name diffusion may be later than the native change.',
        'Possible relation to pounding/beat and to iṭṭali d455 must be considered in family sensitivity. Do not count each kind of cake as an independent negative. Culinary borrowing chronology is unresolved, so retain it as a lexical control rather than use it alone to falsify an inherited law.',
        {'Telugu':('R','iḍi|iḍikuḍumu|iḍikuḍaka','Food base retains order.'),
         'Tamil':('R','iṭi|iṭiyappam|iṭiyal','Independent i+i input.'),'Malayalam':('R','iṭiyappam|iṭiyuṇṇi','Compound-initial food base.')},
        references='DEDR 439, cross-reference 455',eligibility='core-formation-uncertain',input_confidence='high',
        boundary='Food compounds are transparent at their first component; their historical entry into Telugu remains undated.')

    add('d442','put, place, give','*iṭ-u- (past *iṭ-ṭ-); nominal *īṭ-u',
        'Ø','i','ṭ','u','VC-u / VC-C tense alternation','verb/noun',
        'Tamil iṭu : iṭṭ-, Kannada iḍu : iṭṭ-, Telugu iḍu, and matching Central Dravidian paradigms independently support high u and vowel-first root. Long īḍu nouns are a separate quantity formation.',
        'Broad family distribution, including Kui/Kuvi/Pengo/Manda retention, supports original iṭ- order and rules out using Tulu dīpini as the reconstructive starting point.',
        '*iṭ-u > iḍu/ɨḍ-; past *iṭ-ṭ remains geminate in many languages. Gondi intervocalic ṭ corresponds to rhotic in ir/irr, Konda iṟ-, without initial relocation. Tulu dīpini beside iḍpini may show displacement, analogical remodeling or interaction with long īḍɯ; a literal *i+u contraction to ī is not established.',
        'The initial apical is singleton in the nonpast, despite past gemination; do not exclude the whole root as a geminate. Tulu dīḍɯ/jīḍɯ/ījɯ/īḍɯ require a linked paradigm/causative history, potentially d addition or expressive reinforcement; their shared ī is not evidence for a universal metathesis rule. Long nouns and aspectual auxiliary uses are not additional etyma.',
        {'Telugu':('R','iḍu|īḍu','High-u verb and long derived noun retain order.'),'Tamil':('R','iṭu|īṭu','Verb versus long noun.'),
         'Malayalam':('R','iṭuka|īṭu|iṭuvikka','Retained base and causative.'),'Kannada':('R','iḍu (iṭṭ-)|īḍu|iḍisu','Tense/quantity variation retained.'),
         'Kota':('R','iḍ- (iṭ-)|i·ṛ','Verb and long noun retain order.'),'Toda':('R','ɨḍ- (ɨṭ-)|iḍc-','Base and derived fire verb retain order.'),
         'Kodagu':('R','ɨḍ- (ɨḍuv-, ɨṭṭ-)','Paradigm retained.'),
         'Tulu':('A','iḍpini|dīpini|dīpāvuni|dīḍɯ|jīḍɯ|ījɯ|īḍɯ','Retained and innovated variants; historical segmentation and long vowel unresolved.'),
         'Gondi':('R','ir|irr|irrānā|aṛ|eṛ','Rhotic and vowel variants retain order.'),
         'Konda':('R','iḍ|iṟ- (iRt-)|iṭki- (-t-)','Multiple formations retain initial vowel.'),
         'Kui':('R','iṭa (iṭi-)','Whole recorded paradigm vowel-first.'),'Kuwi':('R','ittali|ittinai','Geminated forms retain vowel first.'),
         'Pengo':('R','iṭ- (-t-)|iz- (ist-)','Separate source paradigms preserved.'),'Manda':('R','iṭ','Order retained.'),
         'Kolami':('R','i·ḍ- (iṭṭ-)','Length alternation independently recorded.'),'Naikri':('R','iṛ- (iṭṭ-)','Order retained.'),
         'Naiki':('R','iṛ- (iṭṭ-)','Order retained.'),'Parji':('R','iḍ- (iṭṭ-)','Order retained.'),
         'Gadaba':('R','ir- (iṭṭ-)|ir','Ollari/Salur retained order.'),'Badaga':('R','idu','Base retains order; divorce compound not another root.')},
        references='DEDR 442; K03 Rule20 pp.157–158',input_confidence='high',
        boundary='Nonpast u and geminate past are independently supported; nominal length and causatives require formation-level classification.')
    tokens('d442','Tulu',R='iḍpini|īḍɯ|ījɯ',A='dīpini|dīpāvuni|dīḍɯ|jīḍɯ')

    add('d443','beat, strike, butt','*iṭ-i- / *iṭ-u- / *iṭ-a- formations',
        'Ø','i','ṭ','i','VC-i (beside u/a formations)','verb/noun',
        'Tamil iṭi, Malayalam iṭi/iṭikka and Kannada iḍi independently support i+i, while Tamil iṭu and Kannada iḍaku support other formations. Kota/Toda, Kolami, Pengo and Kurux have vowel-first root cognates.',
        'The independent high-i formation supports earlier iṭi > Telugu ḍī. Konda ṛey/ṛī were incorrectly assigned Kolami in the database: source p.43 makes Kolami iṛ- retained and Konda innovated.',
        '*iṭ-i > *ḍii > ḍī is a possible implementation of Rule20a; same-quality high vowels meet its contraction condition. Konda *iṭV > ṛī/ṛey involves its own apical correspondence and vowel variants. Kannada ḍī/ḍīku/ḍikki beside iḍi may be a Telugu loan, expressive reinforcement, or local displacement; no donor date yet decides.',
        'Do not count Kannada and Telugu identical impact nouns automatically as independent changes. Telugu ḍīkonu is a light-verb/compound extension of ḍī, not another etymon. Imported Badaga sickle/iron-saw records have possible cut/iron segmentation rather than the beat root; their linkage is questionable and not used as a decisive control. The Konda correction reverses which comparison language appears to innovate.',
        {'Telugu':('D','ḍī|ḍīkonu','High-i displacement and contraction candidate; one impact base.'),
         'Tamil':('R','iṭi|iṭu|iṭācu','Independent i/u/a formations.'),'Malayalam':('R','iṭi|iṭikka|iṭayuka','Retained beat and conflict formations.'),
         'Kota':('R','iḍ- (iṭ-)|i·ṛ|iṛyl|ēṭ','Quantity and lect variants; all vowel-first.'),'Toda':('R','ɨḍ- (ɨṭ-)','Retained hit verb.'),
         'Kannada':('A','iḍi|iḍaku|ḍī|ḍīku|ḍikki|ḍikkā','Retained base plus initial-stop nouns of unresolved contact/expressive history.'),
         'pampa':('R','iḍu (iṭṭ-)','Old Kannada hit paradigm retains order.'),
         'Tulu':('R','eḍapuni|eḍupuni|eḍpuni|eḍaŋkuni','Vowel/syncope/extension differences retain order.'),
         'Kolami':('R','iṛ','Kinwat retained order; remove mislabeled Konda forms.'),
         'Konda':('D','ṛey|ṛī','Source-corrected displacement; ey/ī correspondence merits dialectal history.'),
         'Pengo':('R','iṛ- (iṛt-)','Retained root, despite metathesis elsewhere in Pengo.'),
         'Kurux':('R',"iṛya'ānā",'Derived kicking verb retains order.'),
         'Badaga':('A','irubāḷu|iruvāḷu|irōḷu','Tool-name linkage to beat is questionable; component origins unresolved.')},
        references='DEDR 443 p.43 directly inspected; K03 Rule6 p.107 and Rule20 p.157',input_confidence='high',
        boundary='i-vocalism in the impact noun/verb is independently attested; do not replace all a/u extensions with i.')
    tokens('d443','Kannada',R='iḍi|iḍaku',A='ḍī|ḍīku|ḍikki|ḍikkā')

    add('d445','narrow, crowded, abundant','*iṭ-u-k / *iṭ-ṭ-aḷ formation',
        'Ø','i','ṭ','a','VCC-a-C (Telugu-matching strong formation)','adjective/noun/verb',
        'Tamil iṭṭaḷam, Kannada iṭṭaḷa/iṭṭaṇa and Telugu iṭṭalamu independently support a geminate target in this formation, alongside a singleton high-u narrowness family iṭukku/iḍuku.',
        'Both formations preserve initial i/e across southern languages; singleton and geminate stems must be classified separately before comparing Telugu.',
        '*iṭṭ-aḷ-am > Telugu iṭṭalamu with lateral simplification; crowded mass > abundant is independently bridged by Kannada meanings. The iṭ-uk narrowness words retain a singleton ṭ before a velar formative and cannot be treated as the identical input to iṭṭalamu.',
        'Telugu is a geminate-formation control, not proof that its singleton *iṭuk input resisted metathesis: that input is not attested in Telugu here. Gadaba iḍigeda a few has different morphology and possible contact, while Badaga glade/nook and place names have queried etymologies. Broad connection with spatial d434/d448 or distress d435 is plausible but unproven.',
        {'Telugu':('R','iṭṭalamu','Independently motivated geminate formation.'),
         'Tamil':('R','iṭṭaḷam|iṭṭu|iṭukku|iṭuku|iṭuŋku','Strong adjective/noun distinguished from singleton verb/velar formations.'),
         'Malayalam':('R','iṭukkuka|iṭukku|iṭṭil|iṭuŋŋuka','Singleton plus velar and geminate derivatives all vowel-first.'),
         'Kannada':('R','iṭṭaḷa|iṭṭaṇa|iṭṭu|iḍuku|iḍugu|iḍaku','Independent source for both structural classes.'),
         'Tulu':('R','iṭṭiḍe|eḍeŋkilɯ','Different forms retain order.'),
         'Gadaba':('A','iḍigeda','A few, different extension/contact not established.'),
         'Badaga':('A','ittu|idu','Source-uncertain glade/nook terms; no primary root inference from toponyms.')},
        references='DEDR 445 p.43; omitted nineteenth Tamil item source iṭakkar also checked',c2_structure='geminate',
        eligibility='geminate-control',input_confidence='high',
        boundary='Gemination belongs to the independently matched ṭṭaḷ formation, not every derivative of the etymological root.')

    add('d446','separate, distant','*iṭ-ay / *iṭ-av; regional *eṭ-',
        'Ø','i','ṭ','a','VC-a-y / VC-a-v','verb/adjective',
        'Tamil iṭai, Malayalam iṭayikka and Telugu eḍayu/eḍavu independently support vowel-first ordering with low second vowel; Malto eṛare provides a northern order comparison.',
        'Retained southern and northern orders favor an earlier vowel-first root. Telugu davvu is likely related to eḍavu, but its a and geminate vv require more than simply exchanging the initial e and ḍ.',
        '*iṭ-ay > *eḍay > eḍayu regularly retains the initial vowel. A displacement analysis of davvu would require an earlier vowel or analogical variant, plus vv strengthening/shortening; *eḍ-av > *ḍēv does not directly yield davvu. Kolami davva/dautān and Naikri dʰāv may be Telugu-area loans, not independent support for the missing steps.',
        'K03 p.57 explicitly doubts the derivation of davvu/dhāv from *iṭ-a; his alternative discussion concerns voiced aspiration and a possible older laryngeal, not a demonstrated solution. Brahui is explicitly questioned in DEDR p.43. Nahali dhava is a contact-zone comparison, not a Dravidian cognate vote. The spatial-root relation to d434/d448 is a sensitivity hypothesis; do not silently explain the vowel by assuming different proto-roots.',
        {'Telugu':('A','eḍayu|eḍavu|eḍalu|eḍapu|eḍalcu|eḍalucu|davvu','Secure retained formations, probable but incompletely explained displaced adjective.'),
         'Tamil':('R','iṭai|iṭampu','Retained low-vowel formations.'),'Malayalam':('R','iṭayikka|iṭekka|iṭaccal','Retained separation paradigm.'),
         'Malto':('R','eṛare|eṛatre','Retained order.'),'Gadaba':('R','īḍ-ēr','Long-vowel extended verb retains order.'),
         'Kolami':('A','davva|dautān','Possible Telugu borrowing, exact donor/recipient history unresolved.'),
         'Naikri':('A','dʰāv','Aspirated regional distance noun, contact likely but source not explicit.'),
         'Brahui':('A','aṛsing|haṛsēnging|haṛsēfing','Source explicitly queries cognacy; h is not itself metathesis.')},
        references='DEDR 446 p.43 directly checked, including question mark before Brahui; K03 p.57 explicitly questions the etymology of davvu/dhāv',input_confidence='high',
        boundary='ay and av formations independently visible; no unattested vowel distinction invented for davvu.')
    tokens('d446','Telugu',R='eḍayu|eḍavu|eḍalu|eḍapu|eḍalcu|eḍalucu',A='davvu')

    add('d447','grow weary, become thin','*iṭ-ay?; vowel reconstruction and lexical direction not final',
        'Ø','i','ṭ','a','VC-ay','verb',
        'Tamil iṭai weary is the sole independent unshifted witness in this entry. Telugu ḍayyu and Kuvi ḍah/daha/ḍāh agree semantically, but the imported initial *ḍaj reconstruction simply repeats the innovated-looking order.',
        'Tamil vowel-first order, general apical correspondences, and Kuvi y/h comparison favor earlier *iṭay, provisionally; with only one unshifted branch, prothesis or imperfect cognacy cannot be ruled out on majority arithmetic.',
        'Conditional *iṭay > an initial ḍay stem gives Telugu ḍayyu and Kuvi ḍah; the expected lowered/contracted ē and actual a are not reconciled. Kuvi length varies by source/lect. Kolami ḍay is explicitly a Telugu loan. Sastri 1969 p.111 derives Telugu dappi thirst from dayyu weary, offering an alternative to d109 aṭ-/aṇṭ- ancestry.',
        'Do not invent an unattested *aṭay just to match a. The fatigue-to-thirst derivative is semantically and morphologically plausible (compare noccu/noppi in Sastri), but it needs historical attestation and comparison with southern thirst cognates before merging d109. It also must remain separate from homophonous destruction ḍappi d277.',
        {'Telugu':('A','ḍayyu','Likely displacement-family outcome, but input vowel and direction less secure than in iṭi beat.'),
         'Tamil':('R','iṭai','Only unshifted witness here; not automatically proto by virtue of being Tamil.'),
         'Kuwi':('A','ḍah|ḍahinai|ḍāh- (-it-)|daha|dahi kīnai','Consistent initial stop, variable quantity; cognacy/donor and vowel history unresolved.'),
         'Kolami':('B','ḍay- (ḍayt-)','DEDR explicitly < Telugu.')},
        references='DEDR 447 p.44; Sastri 1969 p.111, image verified (PDF136)',
        eligibility='cognacy-or-input-uncertain',input_confidence='medium',confidence='low',
        boundary='ay verbal base probable from Tamil; pp thirst noun is a separate morphological hypothesis, not a new positive.')

    add('d448','interval, middle, waist','*iṭ-ay / *iṭ-a-m',
        'Ø','i','ṭ','a','VC-ay / VC-a-C','noun',
        'Tamil iṭai, Malayalam iṭa/eṭa, Kannada eḍa/eḍe and Telugu eḍa/eḍamu independently agree on vowel-first spatial input; Kota eṛ supports the shortened noun.',
        'The same independently supported order appears in place d434, whose forms and meanings overlap. Tulu dekkārɯ is a distinct compound/extension and does not reverse the reconstruction.',
        '*iṭay > *eḍay > eḍa; extended *iṭam > eḍamu. Tulu iḍɛ versus dekkārɯ may combine initial vowel loss with gemination and a leg-related compound component; exact segmentation requires a fuller dialect dictionary.',
        'Merge with d434 in primary root counts. Toda dairy-vessel and Badaga ritual/toponym compounds do not add etyma. The Tulu initial-loss derivative remains ambiguous because its immediate full input is not attested here; no outcome-defined suffix class is proposed.',
        {'Telugu':('R','eḍa|eḍamu','Same retained spatial root as d434.'),'Tamil':('R','iṭai|iṭuppu','Bare spatial and labial waist formations.'),
         'Malayalam':('R','iṭa|eṭa|iṭuppu','Order retained.'),'Kota':('R','eṛ|eṛgaṭ','Base and middle-route compound.'),
         'Toda':('R','ɨṛ kvāy','Root first in ritual vessel compound.'),'Kannada':('R','eḍa|eḍe|eḍati','Spatial and age derivative retain order.'),
         'Tulu':('A','iḍɛ|iḍetara|eḍavaṭṭɯ|eḍevaṭṭɯ|dekkārɯ','Retained core and incompletely analyzed initial-loss derivative.'),
         'Badaga':('R','ede|eda|edattara','Base and adverb retained; numerous compounds collapsed.')},
        family='d434+d448',references='DEDR 448 p.44; primary family merged with 434',input_confidence='high',
        boundary='ay/m spatial noun variants independently attested; do not assume Tulu dekkārɯ has precisely the same suffix.')
    tokens('d448','Tulu',R='iḍɛ|iḍetara|eḍavaṭṭɯ|eḍevaṭṭɯ',A='dekkārɯ')

    add('d449','left side','*iṭ-a(y)/m; *eṭ- regional outcome',
        'Ø','i','ṭ','a','VC-a-C / VC-ay','noun/adjective',
        'Tamil iṭai/iṭam, Malayalam iṭam/eṭam, Kannada eḍa and Telugu eḍama support earlier vowel-first i/e plus retroflex. Kota/Toda and Kodagu agree in order, though vowel quality differs.',
        'Telugu ḍā/dā is innovated relative to the comparative vowel-first left-side noun, but cannot be assigned the expected ē contraction without an additional vowel history. Tulu damma/datta has strengthening and local initial loss.',
        '*iṭam > *eḍam > eḍama is retained. Aphaeresis/clipping of an already a-bearing derivative, analogy with regional left-side words, or displacement followed by vowel change may underlie ḍā/dā; the current source does not select one. Kolami edamakei is explicitly a Telugu loan and was mislabeled Telugu in the parsed corpus.',
        'DEDR separately assigns many other SCDr left words to Indo-Aryan *ḍavva/*ḍevva: Kui deba/debe/debo, Kuvi tebri, Gondi ḍema/demar/ḍāvā, etc. Those are a loan comparison, not absent cognates or shared metathesis. Source-only loan observations are inventoried separately. Naiki ḍākiyan kī may reflect regional borrowing; its full donor is unresolved.',
        {'Telugu':('A','eḍama|ḍā|dā','Retained full adjective and shortened initial-stop variants of uncertain precise mechanism.'),
         'Tamil':('R','iṭai|iṭam|iṭaṉ|iṭattai|iṭavaṉ','Left-side and ox compounds retain order.'),'Malayalam':('R','iṭam|eṭam','Quality variants, retained order.'),
         'Kota':('R','eṛ','Retained shortened noun.'),'Toda':('R','øṛ','Vowel quality requires its own correspondence, order retained.'),
         'Kannada':('R','eḍa|eḍacu','Base and handedness derivative.'),'Kodagu':('R','əḍate','Retained order.'),
         'Tulu':('O','eḍa|yaḍa|eḍaŋkɯ|yaḍambu|damma|datta','Initial-glide/vowel variants and local loss plus strengthening.'),
         'Kolami':('B','edamakei','Source-corrected Hislop form, explicitly < Telugu.'),
         'Kui':('B','deba|debe|debo','Source identifies separate Indo-Aryan loan comparison.'),
         'Kuwi':('B','tebri|tēbri|ṭebri','Source identifies separate Indo-Aryan loan comparison.'),
         'Gondi':('B','ḍema|demar|ḍāvā','Source identifies separate Indo-Aryan loan comparison.'),
         'Naikri':('B','ḍāva','Source identifies separate Indo-Aryan loan comparison.'),
         'Parji':('B','ḍebri','Source identifies separate Indo-Aryan loan comparison.'),
         'Gadaba':('B','ḍebri','Source identifies separate Indo-Aryan loan comparison.'),
         'Naiki':('A','ḍākiyan kī','Left-hand compound, contact versus historical displacement unresolved.'),
         'Badaga':('R','eda','Retained base.'),'markodi':('R','eḍattᵘ|edat|edatŭ','Three source lects preserve initial vowel.')},
        references='DEDR 449 p.44; CDIAL 5539 loan comparison; source headings directly checked',input_confidence='high',
        boundary='a/m/ay left-side formations supported independently; short commands or clipping not assumed without source labels.')
    tokens('d449','Telugu',R='eḍama',A='ḍā|dā')
    tokens('d449','Tulu',R='eḍa|yaḍa|eḍaŋkɯ|yaḍambu',O='damma|datta')

    add('d455','steamed cake','regional *iṭṭali / *iḍḍali',
        'Ø','i','ṭ','a','VCCVCV','noun',
        'Tamil/Malayalam iṭṭali, Kannada iḍḍali/iḍḍalige and Telugu iḍḍena independently support gemination and vowel-first ordering of the regional food name.',
        'No language in this entry supplies initial ḍ as the original order; the shared food name begins i. Its date and ultimate origin remain open, including comparison with Sanskrit lexicographic iṇḍarī/iṇḍalī.',
        'Regional iṭṭali > iḍḍali-type variants; Telugu iḍḍena additionally changes the later lateral and vowel, requiring a loan/dialect history. Initial order is retained throughout.',
        'A structural geminate control, but not a decisive ancient inherited-law control without chronology. Link with flour/cake d439 and pounding verbs is plausible enough for sensitivity, not established from homophony. Modern dish variants do not add independent roots.',
        {'Telugu':('R','iḍḍena','Geminate regional food name; later n correspondence unresolved.'),
         'Tamil':('R','iṭṭali','Geminate input.'),'Malayalam':('R','iṭṭali|iḍḍali','Voicing variation, same order.'),
         'Kannada':('R','iḍḍali|iḍḍalige|iḍḍaḷige','Nominal extensions preserve initial order.')},
        references='DEDR 455 p.44; comparisons 439 and Skt iṇḍarī/iṇḍalī',c2_structure='geminate',
        eligibility='geminate-contact-control',input_confidence='high',
        boundary='Regional lexical gemination is independently supported; deep morphology and direction of culinary diffusion unresolved.')
