"""First independently inspected Kui–Kuvi lowering comparisons."""

def populate(add,tokens):
    add('d1959','scoop up','regional *ker-V; K80 proposes *ker-a',
        'k','e','r','unknown','CVC-V + labial/palatal formation','verb',
        'Konda ker independently supplies k-e-r order, but its stem notation ker- does not independently establish a following a. K80 reconstructs *ker-a from this comparison.',
        'The full Konda root and initial gr in all other reflexes support displacement, with separate k>g. Direction of e/a quality change is an additional issue, not settled by consonant order.',
        'Conditional *ker-a > *krē > grē, with Kui lowering to grā in one dialect; alternatively pre-contraction e>a before a yields grā. Kuvi grec, Pengo gre and Manda grepa preserve e. Exact labial/palatal formative and vowel quantities differ.',
        'Kui grāpa/grēpa is a valuable dialect contrast, but cannot independently validate the reconstructed low V2 which helps explain it. No Telugu cognate is supplied. Do not count each language’s suffix as an independent root. The regional proto-level is more defensible than a pan-Dravidian *grä already containing the outcome.',
        {'Konda':('R','ker- (-t-)','Independent uncontracted order, unknown suffix vowel.'),'Kui':('D','grāpa (grāt-)|grēpa (grēt-)','Both low and mid long vowels; Phulbani grēpa preserved.'),'Kuwi':('D','grecali (gret-)','Displaced order, distinct palatal formation.'),'Pengo':('D','gre- (-t-)','Displaced order.'),'Manda':('D','grepa','Displaced order, labial extension.')},
        references='K80 pp.496–499 item 1; DEDR 1959',eligibility='core-formation-uncertain',boundary='Konda establishes the root, not the exact low formative proposed in K80.')

    add('d1818','pit, hollow, tube, dig','*ku/oẓ-i pit; *ku/oẓ-al/av tube; consonantal digging formations',
        'k','u/o','ẓ','i/a/u','CVC-i / CVC-a-L / CVC-a-v / CVC-C','noun/verb',
        'Tamil kuẓi pit contrasts with kuẓal/kuẓai tube; Malayalam kuẓa/kuẓal and Kannada koẓal/koẓavi independently establish low-a tube formations. Gondi koṛi and Konda kuṛk corroborate initial k-V-apical order.',
        'Independent full southern/central forms support k-V-ẓ before Telugu kr and old kẓ. Different high/low and consonantal formations must not be collapsed to a single convenient *koẓ-a input.',
        'Low-a *koẓ-al/av > *kẓōl/ōv > krōlu/krōvi, then kōlu. A consonantal *koẓ-cc > *kẓocc > kroccu explains short digging forms; old kẓōce has a distinct long variant. Kui kṛāu/Kuvi gṛāyu are displaced pit names with low outcome, but independently known pit *kuẓ-i is not the same low-a tube derivative. Exact pit-name -ay formation needs reconstruction.',
        'K80 explicitly contrasts Kui pit kṛāu and tube krōḍu; that semantic distinction describes distribution without itself explaining a sound condition. Kui krūpa has another vowel/formation. Telugu kukki/goppu could be direct medial assimilation; do not infer concealed metathesis merely from lost ẓ. Kannada kōvi is explicitly Telugu borrowing. The porridge *kūẓ reconstruction attached to this group is not evidence for a long pit input.',
        {'Tamil':('R','kuṛ̆i|kuṛ̆al|kuṛ̆ai|kuṛ̆āy|kuṛ̆ici|kuṛ̆umpu','Independently different nominal/verb formations.'),'Malayalam':('R','kuṛ̆i|kuṛ̆ikka|kuṛ̆iyuka|kuṛ̆a|kuṛ̆al','High-i pit versus low-a hollow/tube.'),'Kannada':('A','kuṛ̆i|guṛ̆i|koṛ̆al|koṛ̆avi|koṛ̆ivi|kuṇi|guṇi|kuṇike|kuḷumpe|kōvi','Native full/nasal variants and explicit Telugu tube loan.'),'Kodagu':('R','koḷa','Low-vowel flute word.'),'Kota':('O','korl|koḷa·y|goṛḷ|kuy|kup|go·b','Full/syncopated apical versus internal loss/assimilation.'),'Toda':('O','kve·ḷ|kvēɫ̣|kuṣ|ku·ṭ|kūṭ','Medial apical reflexes and cluster changes; initial kv is a glide development.'),
         'Tulu':('R','kolāyi|kolavɛ|guri|korepini|gurike|gurkɛ|gurumbɛ|gurmpɛ','Vowel before apical in distinct formations.'),
         'Telugu':('D','krōvi|krōlu|kōlu|kroccu|groccu|groyyi|goyyi|groyyu|kukki|goppu','Displaced tube/dig series and reduced forms; kukki/goppu history uncertain.'),'OTelugu':('D','kṛ̆ocu|kṛ̆occe|kṛ̆ōce','Promoted approximant identity directly preserved; short/long variants.'),
         'Gondi':('O','koṛi|koṛpanj ( koṛpahk)|gumiya|gumiyā','Retained apical versus medial nasal assimilation.'),'Konda':('O','kuṛk- (-t-)|kuṛŋi- (-t-)|gumi','Retained apical verbs and reduced noun.'),'Kui':('D','kṛāu ( kṛānga)|krōḍu ( krōṭka)|krūpa','Three vowel/formative outcomes, all initial clusters.'),'Kuwi':('D','gṛāyu|glāyu|graiyū ( grānga)','Displaced low-vowel pit names with r/l and orthographic variation.'),'Pengo':('D','kṛoy','Displaced pit.'),'Manda':('D','kṛay','Displaced pit with different quality.'),
         'Parji':('R','kuṛub ( kuṛbul)','Independent high-u labial pit derivative.'),'Gadaba':('O','kuṛup|kuṛub|gummi','Retained Ollari/Pottangi versus nasal Salur.'),'Brahui':('R','xurrum','Vowel before rhotic; specific grainpit derivative.'),'Badaga':('O','guḷi|gui|kōvilu','Full/reduced pit forms; gun word likely separate contact history.')},
        references='K80 pp.497–499 item 7; DEDR 1818; K61 pp.67–68 old kẓ clusters',input_confidence='high',boundary='Pit -i, tube -al/-av and digging consonantal formations independently distinguished; no uniform low-a assignment.')
    tokens('d1818','Kannada',R='kuṛ̆i|guṛ̆i|koṛ̆al|koṛ̆avi|koṛ̆ivi|kuḷumpe',O='kuṇi|guṇi|kuṇike',B='kōvi')
    tokens('d1818','Kota',R='korl|koḷa·y|goṛḷ',O='kuy|kup|go·b')
    tokens('d1818','Telugu',D='krōvi|krōlu|kōlu|kroccu|groccu|groyyi|goyyi|groyyu',A='kukki|goppu')
    tokens('d1818','Gondi',R='koṛi|koṛpanj ( koṛpahk)',O='gumiya|gumiyā')
    tokens('d1818','Konda',R='kuṛk- (-t-)|kuṛŋi- (-t-)',O='gumi')
    tokens('d1818','Gadaba',R='kuṛup|kuṛub',O='gummi')
    tokens('d1818','Badaga',R='guḷi',O='gui',A='kōvilu')

    add('d1859','cut, reap, saw','*ku/oṯ-ay; high-vowel and consonantal cut derivatives',
        'k','u/o','ṟ','a/u/zero','CVC-ay / CVC-u / CVC-C','verb/noun',
        'Tamil kuṟai and Malayalam kuṟekka independently support low-ay cutting formation; Kannada koṟe and the shorter Tamil kuṟu support additional vowel histories. Central Dravidian kud/kut forms support medial apical but not identical suffixes.',
        'Southern/Central k-V-apical order supports earlier unshifted root. Kui krāpa has moved r before V; Old Telugu kōṟa remains V-before-r and is a long nominal formation.',
        'Conditional *koṯ-a-p > *krōp > krāp gives Kui krāpa under contraction then lowering; pre-contraction o>a is the competing order. Kannada korcu > koccu and Tulu koccu can arise by medial assimilation. Telugu kōṟa has a long vowel but no initial cluster and is not a displaced reflex.',
        'K80’s low-a comparison has independent southern support, but exact causative p formation and its vowel remain reconstructed. Do not apply the expected short-root change to the Old Telugu long noun without establishing its grade. Cutting, boring and fire-kindling meanings may converge with d2168; the source explicitly questions some Kannada comparisons.',
        {'Tamil':('R','kuṟai|kuṟu','Low/high formations independently distinguishable.'),'Malayalam':('R','kuṟekka','Low-formative comparison.'),'Kannada':('O','koṟe|koṟi|koṟata|koṟeta|korcu|koccu|koccike','Retained alveolar versus medial assimilation.'),'Kota':('R','korv- (kort-)','Retained order in labial/past paradigm.'),'Toda':('O','kvaṟf- (kvaṟt-)|kvɨc- (kvɨč-)','Retained apical versus medial palatal developments.'),'Tulu':('O','kudupuni|kudɛ|kojeluni|kojaluni|kojiluni|kojepuni|koccu','Various medial apical/cluster outcomes; no promoted initial apical.'),'OTelugu':('R','kōṟa','Long-root nominal retains order.'),'Kui':('D','krāpa (krāt-)','Displaced low-vowel result.'),'Naiki':('O','kutuk|kutup|kutk','Medial stop cluster history; V remains first syllable.'),'Parji':('R','kud- (kutt-)|kuḍ- (kuṭṭ-)','Medial apical retained, dialectal place variation.'),'Gadaba':('O','kuy','Medial apical lenition to glide.'),'Koraga':('R','kudi','Medial stop retained.'),'Badaga':('R','kore','Retained cutting root.')},
        references='K80 pp.497–499 item 8; DEDR 1859',input_confidence='high',boundary='Low-ay base independent; exact Kui labial formation reconstructed, historical Telugu noun is long.')
    tokens('d1859','Kannada',R='koṟe|koṟi|koṟata|koṟeta|korcu',O='koccu|koccike')
    tokens('d1859','Toda',R='kvaṟf- (kvaṟt-)',O='kvɨc- (kvɨč-)')

    add('d2018','kindred, family, friend','short *ki/eḷ-ay and long *kēḷ; Kui nominal -mbu formation',
        'k','i/e','ḷ','a','CVC-ay / CVVC / CVC-a-mb','noun/verb',
        'Tamil kiḷai ramify/kindred and Kannada keḷe/geḷe independently establish a short low-formative series alongside Tamil kēḷ friend. Short vowel cannot be rejected merely because the dictionary headword selects long kēḷ.',
        'Southern short and long forms have V before lateral; Kui klāmbu has initial cluster and additional nominal morphology. Direction of displacement is plausible independently of the long ā outcome.',
        '*keḷ-a-mbu > *klēmbu > klāmbu is K80-type contraction then lowering; pre-contraction e>a is also possible. Plural klāpka has stem/number alternation with mb/pk, not a second independent metathesis root. Kannada geṇe/geṇiya and Tulu geṇe have medial lateral-to-nasal developments.',
        'The exact -mbu formative should be checked against Kui nominal morphology; Tamil kiḷai alone does not supply it. K80 prints old DED 1628, but the correct old number is 1678 (modern2018); 1628 is do1957. Badaga kliūgidu is a plant name with a different Kannada comparison and is not evidence for lateral displacement in friend; its inclusion would manufacture an exception to southern distribution.',
        {'Tamil':('R','kiḷai|kēḷ|kēḷaṉ|kēḷvaṉ|kēḷir','Short/long formations retain order.'),'Kannada':('O','keḷe|keḷadi|keḷetana|geḷe|geḷiya|geḷate|geṇe|geṇiya|geṇati','Lateral versus nasal formations.'),'Tulu':('O','geṇe|geṇegāre','Medial nasal development, no displacement.'),'Kota':('R','keḷ','Short retained economic-partner term.'),'Toda':('R','keḷ|keɫ̣','Short retained partner term.'),'Kui':('D','klāmbu ( klāpka)','Displaced singular/plural family noun; one counting root.'),'Badaga':('O','kē','Long friend word with medial lateral loss.')},
        references='K80 pp.497–499 item 9, old-DED misnumbering; DEDR 2018',quantity='mixed by formation',input_confidence='high',boundary='Short kiḷai and long kēḷ independently distinct; Kui nominal ending not inferred as part of a bare root.')
    tokens('d2018','Kannada',R='keḷe|keḷadi|keḷetana|geḷe|geḷiya|geḷate',O='geṇe|geṇiya|geṇati')
