"""Formation contrasts: crow, fat and turn; no outcome-defined root classes."""

def populate(add,tokens):
    add('d1574','cry, crow, make noise','*kil-a/ay; *kil-i and expressive extensions',
        'k','i/e','l','a/i','CVC-a / CVC-i / CVC-C','verb/noun',
        'Tamil cilai, Malayalam cila/cilekka, Kannada kele and Tulu kele-puni independently support a low-a formation with initial k/c-V-l. Tamil cil and Gondi kil also supply a bare root; reduplicative shrieking stems have different morphology.',
        'Southern and Gondi full forms support k-V-l before Kui kl-. Palatalization in Tamil and some Kannada/Telugu forms is a separate initial k development; none requires reconstructing initial c in the common input.',
        '*kil-a-p > *klēp > klāpa is the K80 lowering analysis; an alternative lowers/assimilates before cluster creation. Kui klīri and Kuvi klīrinai show a different high-vowel expressive formation, not an exception to low-a-specific lowering. Telugu kilārucu/kelayu/celãgu retains initial vowel/l order.',
        'Postconsonantal l lies outside the narrow Telugu r/ṟ/ẓ metathesis set, while Kui admits it. This supports a structural language contrast, not simply a difference in frequency. Exact ancient morphology of the long ā Telugu expressive stem and klīri is not recoverable from the bare *kil head alone. Toda kīl ik is explicitly a Badaga loan; initial-loss Kota iḍ and alternative-cognacy jelk remain uncertain. Toda kv-style processes elsewhere must not be generalized to this root.',
        {'Tamil':('R','cil|cilai|cilampu|cilumpu|cilucilu|cill-eṉal','Full initial order with separate palatalization and expressive suffixes.'),'Malayalam':('R','cila|cilekka|cileppu|cilappu|cilampuka|cilampu|kāl-cilaŋku','Retained initial order, including compound second member.'),'Kannada':('R','kele|keleta|sele|cili','Retained lateral order with initial/vowel variation.'),'Tulu':('R','kelepuni|kilepuni|kilevuni|kilēvuni','Retained low/high formations.'),'Telugu':('R','kilārucu|kilārincu|kelayu|celãgu','Retained post-C lateral in multiple formations.'),'Gondi':('R','kil|kili|kilih|kilh|kilānā|kilītānā|kill|killītānā|kīlitānā|kiliyānā','Retained apical order; quantity and gemination variants preserved.'),'Kui':('D','klāpa (klāt-)|klīri klīri ṛīva|klīri inba|klīsi klīsi ṛīva','Displaced low-a formation and distinct high-vowel expressive formations.'),'Kuwi':('M','kileḍi kīnai|kileri-kīali|klīrinai|klīri innai','Retained and displaced expressive formations; exact same-formation alternation not established.'),'Kota':('A','kilc- (kilc-)|iḍ- (iṭ-)|jelk','Retained cry versus uncertain first-consonant/apical development and alternative anklet cognacy.'),'Toda':('O','kilk-|kilk- (kilky-)|kilky-|kis̱-|kis̱- (kis̱Q-)|kis̱θ-|ki·l ik- (iky-)|kīl ik-|iky-','Retained neigh, medial fricative crow and explicit Badaga loan trumpet.'),'Badaga':('R','kele','Retained low-formative verb.'),'Koraga':('R','kelappu','Retained low-formative verb.')},
        input_confidence='high',references='K80 pp.497–499 item 6; PSS83 p.230 post-C sonorant restriction; DEDR 1574',boundary='Low-a crow and high/expressive shriek formations differentiated by independent southern morphology.')
    tokens('d1574','Kuwi',R='kileḍi kīnai|kileri-kīali',D='klīrinai|klīri innai')
    tokens('d1574','Kota',R='kilc- (kilc-)',A='iḍ- (iṭ-)|jelk')
    tokens('d1574','Toda',R='kilk-|kilk- (kilky-)|kilky-',O='kis̱-|kis̱- (kis̱Q-)|kis̱θ-',B='ki·l ik- (iky-)|kīl ik-|iky-')

    add('d2146','fat, become fat, proud','*koẓ-u; *koẓ-(u)-w / *koẓ-(u)-kk; long *kōẓ',
        'k','o','ẓ','u/zero','CVC-u / CVC-w / CVC-K / CVVC','adjective/verb/noun',
        'Tamil koẓu/koẓuppu, Malayalam koẓu/koẓukka and Kannada korvu/korbu independently support o-ẓ and high-u/labial formations. Gondi koṛvinj and Konda koṛvu strengthen the short labial comparison; Tamil kōẓ is a separately attested long grade.',
        'Southern, Gondi, Konda and central forms agree on k-o-apical. Telugu krovvu and Kui krōga instead place the apical next to k. The input labial versus velar extensions cannot be collapsed into one identical stem.',
        '*koẓ-w > *kẓow > krovvu > kovvu gives Telugu schematically, with labial gemination a separate issue. Kui *koẓ-(u)-k > krōg gives a long mid vowel without the low ā found after independently low-a formations. Pengo kṛō and Manda kṛuva preserve different quantity/suffix histories. Kannada korbu > kobbu permits medial assimilation without an initial kr stage.',
        'This is a useful high-u comparison for eastern lowering, but exact u/zero in each immediate velar input is not supplied by the bare root alone. Toda kvāv/kvaḷp has initial k-v after loss/change of ẓ and a different vowel history; it is not evidence of the same k-r metathesis. Kuvi candle klōva is semantically plausible from fat/tallow yet requires source/contact scrutiny; kept uncertain. Related derivatives count as one family.',
        {'Tamil':('R','koṛ̆u|koṛ̆uppu|koṛ̆umai|kōṛ̆','Short high-u and long root retained.'),'Malayalam':('R','koṛ̆u|koṛ̆uppu|koṛ̆ukka','Short high-u formations retained.'),'Kannada':('O','korvu|korbu|kobbu|kobbisu|kobbiga','Retained apical versus medial assimilation.'),'Kota':('R','koḷ-|koḍ-|koḷ- (koḍ-)|koḷāyko|koḷād','Initial vowel/apical order remains; negative formations distinguished.'),'Toda':('A','køv|kog-|kog ɨr|kog-ɨr|kvāv|kva·v|kvaḷp','Medial loss/change in køv/kog and possible distinct k-v restructuring in kv forms.'),'Tulu':('O','kommɛ','Internal nasal/labial assimilation; no kr stage required.'),'Telugu':('D','krovvu|krovvina|kovvu','Attested kr and later r-loss variants, one labial formation family.'),'Gondi':('O','koṛvinj|koṛvonj|koṛvenj|kurvinj|koṛvos|korū|koselā|koduvasaka','Retained rhotic majority and old-transcription outliers.'),'Konda':('O','koṛvu|koṇes','Labial noun retains order; adjective internally altered.'),'Kui':('D','krōga|kṛōga','Displaced velar noun with mid long vowel.'),'Kuwi':('A','koṛva|korova|klōva','Retained fat nouns; candle comparison may be displaced/borrowed.'),'Pengo':('M','koṛva|kṛō- (-t-)','Labial noun retains order, verb displaced.'),'Manda':('D','kṛuva','Displacement with two vowels; no compulsory long contraction.'),'Kolami':('R','koru','Retained short root.'),'Naikri':('R','koru','Same.'),'Parji':('R','koṛ|koṛv|koṛukuḍ','Retained initial order.'),'Gadaba':('R','koḍukuḍ|koḍukuṭ|koṛkuṭ','Apical reflex differs, initial vowel remains.'),'Badaga':('O','koḷuppu|kobbu','Retained apical and medially assimilated forms; possible Kannada sharing.')},
        input_confidence='high',references='DEDR 2146; K80 low-a lowering hypothesis; K03 Rule 21',quantity='short and independently long grade',boundary='Labial fat noun and velar verb/noun separated; no low-a input independently established for these forms.')
    tokens('d2146','Kannada',R='korvu|korbu',O='kobbu|kobbisu|kobbiga')
    tokens('d2146','Gondi',R='koṛvinj|koṛvonj|koṛvenj|kurvinj|koṛvos|korū',A='koselā|koduvasaka')
    tokens('d2146','Konda',R='koṛvu',O='koṇes')
    tokens('d2146','Kuwi',R='koṛva|korova',A='klōva')
    tokens('d2146','Pengo',R='koṛva',D='kṛō- (-t-)')
    tokens('d2146','Badaga',R='koḷuppu',O='kobbu')

    add('d3246','turn, return, twist, wander','*tir-i/u; *tir-u-pp; *tir-u-kk; nasal and low-a derivatives',
        't','i','r','i/u/a','CVC-u-K / CVC-u-PP / CVC-u-KK / CVC-V-NK','verb/noun',
        'Tamil tiri/tiruku/tiruppu/tirukku and Kannada tiri/tirugu independently establish high-vowel root and distinct singleton velar, geminate labial and geminate velar formations. Kannada tiragu/tirapa and Kodagu teraŋg additionally attest low-a formations; no one V2 fits all derivatives.',
        'Tamil, Malayalam, Kannada, Gondi, Konda and central retained forms agree on t-i-r before Telugu tr-. Telugu itself contrasts retained tirugu and displaced trippu/trikku. The grammatical contrast is independently supported by Tamil intransitive and causative formations.',
        '*tir-upp > *tir-pp > *tri-pp > trippu; *tir-ukk > *tir-kk > *tri-kk > trikku, with equal-vowel syncope/reassociation not requiring a literal audible vowel swap. *tir-uk > tirugu retains order. Kui trēba and Kuvi rēnai involve a different formative and initial t loss in the latter; its exact low-a/ high-i input must not be inferred solely from ē. Manda trīmba matches a nasal formation with long quantity.',
        'A strong independently formed Telugu contrast: singleton-velar turn is retained while geminate causative/twist forms displace. This is evidence for morphological/cluster conditioning within a family, not a universal rule until other geminate and singleton inputs are tested. Trimmaṭa/trimmaru wandering need exact derivational reconstruction and are flagged less certain than trippu. Central tipp may result directly from medial r-p assimilation; Telugu tipiri may be analogical or metathetically restructured but does not prove initial tr loss. Badaga Tirikōṇa is a proper name and should not be an extra inherited turn witness.',
        {'Tamil':('R','tiri|tiruku|tirukku|tiruppu|tiruppam|tirumpu|tirumu|tiripu|tirivu|tirikai|tilupp|tilump','Initial order retained across independent formations; dialectal r/l differs.'),'Malayalam':('R','tirukuka|tirukkuka|tirippuka','Retained singleton/geminate formations.'),'Kannada':('R','tiri|tirugu|tirigu|tiragu|tirupu|tiripu|tiruvu|tirivu|tirapa|tirumpu|tiricu','Retained root and formations.'),'Kota':('R','tirg- (tirgy-)|tirk- (tirky-)|tiry- (tirc-)|tirc- (tirc-)|tirndk-|tirynd-|tirgan','Syncope retains initial vowel/r order.'),'Toda':('R','tɨrx- (tɨrxy-)|tɨrk- (tɨrky-)|tɨrb- (tɨrby-)|tɨrp- (tɨrpy-)|tɨry|tɨrk','Initial order retained.'),'Kodagu':('R','tir- (tiri-)|tirɨk- (tirɨki-)|tirɨg- (tirɨgi-)|teraŋg- (teraŋgi-)|terak- (teraki-)|tera- (-p-, -t-)|tere- (terev-, terand-)|tiri','High/low formative contrasts retain order.'),'Tulu':('O','tirpuni|tirpu|tirpuḷi|tippili|tirŋgāvuni|tirŋgaṇɛ|tirŋgāṭa|tereḍuni|tirduni|tiri|siri','Retained forms and possible medial r-p assimilation in tippili.'),
         'Telugu':('M','tirugu|tiriyu|tirugali|tirugalli|tirigi|tiruga|tiripamu|tiripemu|tiripari|tiri|tiṟi|tirika|tiruguḍu|tirugudala|tirugã-baḍu|trippu|trikku|trippaṭa|trippari|trimmaṭa|trimmaṭakā̃ḍu|trimmaru|tipiri','Retained singleton/nominal forms versus displaced geminate formations and less secure nasal derivatives.'),'Gondi':('R','tiri|tiṛitānā|tiritānā|tirītānā|tirh|tirhānā|tiruhtānā|tirah|tirahtānā|tirisahtānā|tirīstānā','Root and causative order retained.'),'Konda':('R','tiri- (-t-)|tiris- (-t-)|tirvi- (-t-)|tirp- (-t-)','Including labial clusters: syncope alone does not force initial displacement.'),'Kui':('M','trēba (trēt-)|trehpa (treht-)|trespa (trest-)|terpa (tert-)|tija (tiji-)|tihpa (tiht-)','Displaced wander versus retained twist and medial-loss/change turn formations.'),'Kuwi':('M',"triv- (-it-)|tṛīcali|trepʰ'nai|rēnai|rēh- (-t-)|re'- (recc-)|rejali|rēvu|tiṛvali|tirvikīnai|termpinai|tēṛmbali|tipali",'Displaced spin/wander with t loss versus retained turn/wallow and medial-loss turn.'),'Manda':('D','trīmba','Displaced nasal formation.'),'Kolami':('O','tirg- (tirikt-)|tirgip- (tirgipt-)|tirgal|tip- (tipt-)','Retained velar formations; labial derivative medially assimilated or potentially concealed displacement.'),'Naikri':('O','tirg|tipp','Same contrast, chronology not independently fixed.'),'Parji':('R','tirk','Retained initial order.'),'Kurux':('R','terᵉmnā (tirmyas)|termᵉrnā|tīrnā','Retained initial order, quantity and voice separate.'),'Brahui':('R','cirrēnging','Initial consonant development, no apical promotion.'),'Badaga':('O','tirugu|tirigu|tiruku|tiriku|tirigi|tiruki|tirugutirugu|tiri miṇike|iriki','Retained order with initial-consonant loss in iriki, not r-V metathesis.')},
        input_confidence='high for matched high-vowel formations; medium for eastern low-a input',references='DEDR 3246; K03 Rule 21; PSS83 p.229 nonautomatic application',boundary='Singleton velar, geminate labial/velar, nasal and low-a derivatives independently differentiated by southern morphology.')
    tokens('d3246','Telugu',R='tirugu|tiriyu|tirugali|tirugalli|tirigi|tiruga|tiripamu|tiripemu|tiripari|tiri|tiṟi|tirika|tiruguḍu|tirugudala|tirugã-baḍu',D='trippu|trikku|trippaṭa|trippari',A='trimmaṭa|trimmaṭakā̃ḍu|trimmaru|tipiri')
    tokens('d3246','Tulu',R='tirpuni|tirpu|tirpuḷi|tirŋgāvuni|tirŋgaṇɛ|tirŋgāṭa|tereḍuni|tirduni|tiri|siri',O='tippili')
    tokens('d3246','Kui',D='trēba (trēt-)|trehpa (treht-)|trespa (trest-)',R='terpa (tert-)',O='tija (tiji-)|tihpa (tiht-)')
    tokens('d3246','Kuwi',D="triv- (-it-)|tṛīcali|trepʰ'nai|rēnai|rēh- (-t-)|re'- (recc-)|rejali|rēvu",R='tiṛvali|tirvikīnai|termpinai|tēṛmbali',O='tipali')
    tokens('d3246','Kolami',R='tirg- (tirikt-)|tirgip- (tirgipt-)|tirgal',O='tip- (tipt-)')
    tokens('d3246','Naikri',R='tirg',O='tipp')
    tokens('d3246','Badaga',R='tirugu|tirigu|tiruku|tiriku|tirigi|tiruki|tirugutirugu|tiri miṇike',O='iriki')
