"""Difficult lookalikes and source-proposed alternatives, kept outside strict positives."""

def populate(add,tokens):
    add('d3364','jump, leap, be proud','*tuḷḷ-u',
        't','u','ḷḷ','u','CVCC-V','verb/noun',
        'Tamil tuḷḷu, Malayalam tuḷḷuka, Kannada tuḷḷu, Kodagu tuḷḷ and Tulu tuḷḷuni independently establish a geminate lateral with no additional rhotic.',
        'The widespread southern form and Telugu tuḷḷu favor earlier t-u-ḷḷ. Telugu truḷḷu retains that whole sequence and adds r, so ordinary transposition cannot derive it without an extra unsupported ancestral rhotic.',
        '*tuḷḷ-u > tuḷḷu; secondary literary r gives truḷḷu and its derivatives. K61 p.131 n.80 proposes hyperstandardization on the model of archaic Cr forms. This is a source proposal with strong segment-count evidence for addition, less direct evidence for its social mechanism.',
        'A central negative control: initial tr does not guarantee metathesis. It is inappropriate to reconstruct **tur-uḷḷ solely from the Telugu outcome. Gondi tul could have simplified gemination or be related through contact; neither supplies the missing r. K61 citation was visually checked in the prior investigation; this run’s attempt to reopen p.131 reached the authorized preview limit and did not independently reverify the page.',
        {'Tamil':('R','tuḷḷu|tuḷḷal','Independent geminate input.'),'Malayalam':('R','tuḷḷuka|tuḷḷikka|tuḷḷal|tuḷḷan','Same with causative and noun suffixes.'),'Kannada':('R','tuḷḷu','Same.'),'Kodagu':('R','tuḷḷ- (tuḷḷi-)','Same.'),'Tulu':('R','tuḷḷuni|tulluni|tuḷḷelɯ','Lateral place variation, no r.'),'Telugu':('O','tuḷḷu|truḷḷu|truḷḷagincu|truḷḷũbōtu|truḷḷinta|truḷḷaginta','Unaugmented form retained; r-augmented literary series is secondary.'),'Gondi':('R','tul','Initial vowel/lateral order retained.')},
        input_confidence='high',references='DEDR 3364; K61 p.131 n.80 (prior run page verification, reopened preview unavailable)',eligibility='secondary-r-control',boundary='Geminate root and subsequent derivatives, no reconstructible pre-vocalic rhotic.',mechanism='Secondary r; hyperstandardization plausible, not metathesis.')
    tokens('d3364','Telugu',R='tuḷḷu',O='truḷḷu|truḷḷagincu|truḷḷũbōtu|truḷḷinta|truḷḷaginta')

    add('d4194','burst, split, hatch, parch','*piḷ-i/a; competing Telugu *pir-al > *per-al',
        'p','i/e','ḷ / alternative r','i/a/unknown','CVC-V / CVC-V-l / CVC-K','verb/noun',
        'Tamil piḷ/piḷa, Malayalam piḷakka/piḷaruka and Kannada piḷigu support a lateral root, with independently distinct i/a formations. Telugu prēlu has both r and l, not a simple one-liquid reflex. K61 instead compares a rhotic separate root in entry 898 and reconstructs *pir-al for prēlu.',
        'Southern lateral forms establish p-V-ḷ for the DEDR group and support Kui pl-. They do not alone establish the two-liquid input required by Telugu prēlu. Gondi rhotics cannot settle r versus ḷ because ḷ has rhotic reflexes there independently.',
        'For the securely comparable eastern hatch stems, *piḷ-i/zero > plī/plin gives Kui plīva/pling(a), with stem-specific length and nasal morphology. Telugu alternatives: (1) K61 *pir-al > *per-al > prēlu > pēlu; (2) independently long/lengthened lateral pēlu with secondary literary r; (3) a two-liquid formation related to Malayalam piḷar- with a separate liquid-order change. None is established merely by fitting the modern form.',
        'Keep Telugu uncertain, not an automatic exception to the narrow r/ṟ/ẓ restriction or a confirmed lateral metathesis. K61 p.437 entry 859 treats pēlu separately and allows derivation from prēlu; p.445 entry 901 supplies *per-al. Those page images were verified in the prior investigation, not reverified after this run hit preview limits. Kolami pēl could be independently lengthened or borrowed. Gadaba pēlsap is explicitly a Telugu loan. Homophonous prattle d4430 must remain distinct absent evidence of analogical transfer.',
        {'Tamil':('R','piḷ|piḷa|piḷavu|piḷavai|piḷappu|piḷāccu|pīḷal','Short lateral root and separate long derivative.'),'Malayalam':('R','piḷakka|piḷarkka|piḷaruka|piḷarcca|piḷukkuka|peḷi|peḷika|peḷikka','Independent low/high and two-liquid formations.'),'Kannada':('R','piḷigu|hiḷgu|hiḷi|peḷavu|peḍasu','Initial p>h and medial lateral/stop changes, order retained.'),'Kota':('O','pi·ṭ- (pi·ṭy-)|pi·ṇṭ- (pi·ṇṭy-)','Medial cluster assimilation with length; no initial lateral promotion.'),'Tulu':('R','pulevu','Initial order retained, vowel differs.'),'Telugu':('A','prēlu|prēlalu|prēlālu|prēlucu|prēlcu|pēlu|pēlalu|pēlālu|pēlucu|pēlcu','Competing root/formation and secondary-r analyses.'),'Gondi':('R','pirrānā|piṛānā|piṛ|pirr|paṛ|piṛus|piṛkānā|piṛh|piṛiˀ','Medial apical retained; cannot independently choose original r versus ḷ.'),'Kui':('D','plīva (plīt-)|plīpa (plīt-)|plinga (plingi-)|pliki inba|plipka','Displacement with formation-specific quantity and additional k-p exchange.'),'Kuwi':('D',"plih'nai|brīpʰali",'Displacement with local voicing/rhotacism/aspiration; exact chronology unresolved.'),'Pengo':('D','pṛī- (-t-)|pṛip- (-t-)','Displaced intransitive/transitive stems with quantity contrast.'),'Manda':('D','pṛip','Displaced transitive stem.'),'Kolami':('A','pe·l- (pe·lt-)|pe·lip- (pe·lipt-)','Long lateral root, exact inheritance/contact unresolved.'),'Parji':('O','pil|piḍ- (piṭṭ-)|piḍip- (piḍit-)|pinḍp- (pinḍt-)','Retained root and internally altered paradigms.'),'Gadaba':('A','pili cen|pēlsap','Retained inherited-looking crack phrase versus explicit Telugu loan.'),'Badaga':('R','hiḷavu|hilḷu|hiḷḷāṭa','Lateral remains after first vowel; compound counts once.')},
        input_confidence='high for lateral group; low for uniquely linking Telugu prēlu',references='DEDR 4194; K61 p.437 entry 859, p.445 entry 901 and comparison entry 898 (prior verified reading)',eligibility='input-cognacy-contested',boundary='Do not invent *peḷal to fit Telugu; lateral/rhotic competing families must remain explicit.',mechanism='Eastern lateral displacement secure; Telugu root choice and possible secondary r unresolved.')
    tokens('d4194','Parji',R='pil|piḍ- (piṭṭ-)|piḍip- (piḍit-)',O='pinḍp- (pinḍt-)')
    tokens('d4194','Gadaba',R='pili cen',B='pēlsap')

    add('d2698','whirl, roll, revolve','*cuẓ-i/a; initial-loss *uẓ-al and related formations',
        'c/zero','u/o','ẓ','i/a','CVC-i / CVC-a-l / VC-a-l','verb/noun',
        'Tamil cuẓi/cuẓal alongside uẓal, Malayalam cuẓaluka/uẓaluka, and Kannada suẓi/toẓal/uẓal independently support both c-initial and initial-loss families, with a second lateral in the roll formation. Telugu suḍi retains the first type; ḍollu is compared with the second.',
        'Several branches establish vowel before ẓ and a following l in uẓal, giving a much stronger potential direction for roll ḍollu than for homophonous fall d2988. Initial c loss is independently attested, although whether it preceded displacement in Telugu itself is not directly dated.',
        'Possible *cuẓ-al > *uẓ-al > *oẓ-al > *ẓōl > ḍollu requires contraction followed by shortening/gemination, or an earlier syncope route with a consonantal derivative. K61 p.54 §1.127 discusses alternative suffix/quantity histories. Telugu suḍi continues *cuẓ-i without displacement. Kui ḍuṛi retains an apical after u and may have initial c>ḍ plus a medial rhotic; its initial ḍ is not sufficient evidence of the vowel-initial pathway.',
        'Telugu roll is a plausible displacement family, but exact input and collision with regional fall ḍollu d2988 prevent a strict mechanism claim. A pathway cẓ > ẓ after displacement would give the same surviving initial segment as c loss before displacement; chronology is not forced. Several Telugu fragments split ḍol(u)cu into bogus forms; restore only in source supplement, preserve raw data. Gondi uḍ/uḍḍ has medial change and retains initial u.',
        {'Tamil':('R','cuṛ̆i|cuṛ̆al|cuṛ̆aŋku|cuṛ̆aṟṟu|cuṛ̆ippu|cuṛ̆ivu|uṛ̆al|uṛ̆i|uṛ̆aṟu|uṛ̆aṟṟu|uṛ̆aṟṟi|uṛ̆alai|cūṛ̆|cūṛ̆al|cūṛ̆vu','Initial-present/lost and long/short formations retain vowel before apical.'),'Malayalam':('R','cuṛ̆aluka|cuṛ̆al|cuṛ̆alca|cuṛ̆ippu|cuṛ̆ivu|cuṛ̆aṟṟuka|uṛ̆aluka|uṛ̆aṟṟuka|uṛ̆iññal|cūṛ̆uka|cūṛ̆a','Same, including independently low-a roll input.'),'Kannada':('R','suṛ̆i|suṛ̆ivu|suṛ̆uvu|suṛ̆uhu|tuṛ̆i|toṛ̆al (toṛ̆ald-)|toṛ̆ali|uṛ̆al','First-consonant alternatives and full apical order.'),'Kota':('R','cuḷy|cuyg','Medial lateral/glide after initial vowel.'),'Toda':('R','tuḍy- (tuḍs-)|tuḍy-|tuḍs-|tuḍc-|tył̣y|ty ɫ ỵ|tȳs̱|ty·s̱','Initial vowel precedes apical reflex; rounded vowel y is not a consonant reversal.'),'Tulu':('R','suḷi|suḷiyuni|suḷipuni|tuḷipuni|tulipuni|tuliyuni|sulipini|sulipuni','Initial vowel/apical order retained.'),'Telugu':('A','suḍi|suḍiyu|suḍivaḍu|ḍollu|dolupu|ḍolucu|ḍolcu','Retained high-i whirl versus plausibly displaced roll with uncertain quantity history.'),'Gondi':('R','uḍ|uḍḍ','Initial c loss and medial change, no initial-vowel reversal.'),'Kui':('A','ḍuṛi|ḍoḍga (ḍoḍgi-)','Initial-stop and medial-apical histories unresolved; no automatic metathesis from ḍ.'),'Kurux':('O',"coē̃da'ānā",'Medial reduction and vowel sequence; no initial apical cluster.'),'Badaga':('O','sui|hālu suruku|gūde|gūde gundu','Medial loss in sui, retained r in churn; gūde cognacy/initial history uncertain.')},
        input_confidence='high for uẓ-al order; medium for exact Telugu trajectory',references='DEDR 2698; K61 p.54 §1.127 (prior page verification); original DEDR SQL rows 63979–63999; compare DEDR 2988',eligibility='conditional-displacement',boundary='Whirl *cuẓ-i versus roll *uẓ-al; initial c loss and long grade separately annotated.',mechanism='Plausible roll displacement with quantity alternatives and potential lexical convergence.')
    tokens('d2698','Telugu',R='suḍi|suḍiyu|suḍivaḍu',A='ḍollu|dolupu|ḍolucu|ḍolcu')
    tokens('d2698','Badaga',O='sui',R='hālu suruku',A='gūde|gūde gundu')
