"""Grammatical nasal displacement in literary Telugu, outside the apical core."""
def populate(add,tokens):
    add('d868','say, quotative; literary contracted grammatical forms','regional *an/en/in; proposed deeper *aHn; grammatical *an-an, *an-ā-baḍu etc.',
        'Ø','a/e/i','n','a/ā/u/zero','VC+infinitive/passive/negative morphology','verb/quotative',
        'Tamil eṉ, Kannada an/ennu, Tulu anpini/inpini and Telugu anu independently establish vowel before n; Old Telugu envānṟu preserves an e variant. K03 proposed *aHn explains wider vowel alternation but is not needed to establish local segment order.',
        'Sastri1969 p.72 explicitly aligns full anu derivatives with literary n-initial variants, independently of the modern base alone. Kota in:n also shows initial-vowel absence but need not share the Telugu mechanism.',
        'Telugu *an-an > nān and *an-ā-baḍu > nābaḍu can involve displacement/contraction; negative *an-aka > nāka requires merger/loss of one a. The source also gives anaru:naru with short a, so one unqualified long-output rule does not cover the whole paradigm. Analogical stem extension and phonological reduction compete; passage-by-passage morphology is needed.',
        'These are literary grammatical formations, not evidence that ordinary nasal roots joined the classical nonnasal apical rule. Nasal augmentation in negayu<egayu and nuṇḍi<uṇḍi is a different process. Tamil/central tense alternants n:nt/t/c/s reflect inherited morphology and assimilation, not initial movement. Kota n could be simple aphaeresis. Kurux long ā and the deep laryngeal reconstruction remain separate vowel-history questions. No exact date of the individual literary forms is established by Sastri’s period label.',
        {'Tamil':('R','eṉ|eṉpi|eṉkai','Full nasal root with morphology.'),'Malayalam':('R','ennuka','Full vowel-nasal order.'),'Kannada':('R','an (and-)|en (end-)|annu|ennu|anisu|anasu|enisu|enasu|ennisu|annisu|imbu|embu','Full root and derived/nasal-assimilated forms.'),'Tulu':('R','anpini|inpini|endruni','Vowel variants, order preserved.'),'Kota':('A','in- (iḏ-)|n- (-ḏ-)','Full versus aphaeretic root; mechanism not proven identical to Telugu.'),'Toda':('R','ɨn- (ɨḏ-)|ɨn-|ɨḏ-','Vowel-first tense variants.'),'Kodagu':('A','*enn- (emb-, end-)','Source starred reconstructed paradigm, not an independently attested simplex.'),'Telugu':('M','anu|anipincu|anukonu|anan|nān|anābaḍu|nābaḍu|anavuḍu|nāvuḍu|anaka|nāka|anaru|naru','Database base plus source-verified literary grammatical pairs.'),'OTelugu':('R','envānṟu','Seventh-century source claim, not a new independent root.'),'Gondi':('R','indānā (inj-)|in- (-t-)|ind- (itt-)','Full initial vowel with tense morphology.'),'Konda':('R','in- (iR-)','Full order.'),'Kui':('R','inba (is-)|ispa (ist-)','Full vowel; nasal/stop morphology.'),'Kuwi':('R','in- (icc-)|innai|inmbu|injali','Full vowel; tense and noun forms.'),'Pengo':('R','in- (ic-)','Full vowel.'),'Manda':('R','in- (ic-)','Full vowel.'),'Kolami':('R','en- (ent-)|in','Full vowel.'),'Naikri':('R','en- (ent-)','Full vowel.'),'Naiki':('R','en- (enḍ-)','Full vowel.'),'Parji':('R','en- (end-, ett-)','Full vowel.'),'Gadaba':('R','in','Full vowel.'),'Kurux':('R',"ānnā|ānta'ānā",'Long regional vowel, root order preserved.'),'Malto':('R','áne','Source stress accent not vowel length.'),'Badaga':('R','ennu|annu|endu|gana ennu|gaṇānu','Full and contracted compound; archaic tags retained.')},
        quantity='short regional roots; long northern grade and grammatical contractions',c2_structure='nasal with tense-conditioned cluster variants',references='DEDR868; Sastri1969 p.72 visually checked; K03 comparative reconstruction records',eligibility='nasal-grammatical-displacement',boundary='Full and reduced infinitive, passive, post-action and negative paradigms explicitly paired in source.',input_confidence='high for local an+suffix order; medium for phonetic mechanism',mechanism='Literary grammatical nasal displacement/contraction or analogical allomorphy; distinct from the classical nonnasal apical domain.')
    tokens('d868','Telugu',R='anu|anipincu|anukonu|anan|anābaḍu|anavuḍu|anaka|anaru',D='nān|nābaḍu|nāvuḍu|nāka|naru')
    tokens('d868','Kota',R='in- (iḏ-)',A='n- (-ḏ-)')
