"""Initial sibilant loss interacts with apical displacement; input uncertainty explicit."""

def populate(add,tokens):
    add('d2359','snake, cobra, krait','*car-a-(n)c(c)-; immediate Telugu *tar-a-ncc-',
        'c/t','a','r','a','CVC-a-(N)CC','noun',
        'Konda saras/sarasu and Gondi taras/taranj independently support initial s/t-a-r-a and a final s/nj alternation. Tamil ara/arā/aravu and Malayalam aravu agree in r following the first vowel but have lost initial c; they cannot alone reconstruct an originally vowel-initial root.',
        'Konda and Gondi favor C-a-r before eastern Cr. Southern initial loss is independently comparable with broader c-loss correspondences, not evidence that Telugu added t. Tamil final ā is analyzed by K03 through -ac > -ah > ā, separately from first-syllable metathesis.',
        'K03 reconstructs *car-a-ncc > regional *tar-a-ncc > *trā-ncc > trā̃cu. Kui *sar-as > srāsu/srācu; Kuvi/Pengo *srāc > rāc with first-member loss. Manda trehe retains the initial cluster but changes final consonant/vowel. Nasal/geminate and simple-s variants require distinct immediate formations.',
        'Direction is strongly comparative; exact shared innovation still depends on dating branch-specific s/t and suffix developments. Telugu nasal vowel and Gondi taranj support a nasal formation independently, while many cognates have no nasal. The Prakrit sarāhaya comparison in DEDR/K03 may reflect borrowing and is not an independent Dravidian denominator. Konda srāsu is quoted in K03 p.122 but absent from this database group; do not silently manufacture a database variant.',
        {'Tamil':('R','ara|arā|aravu|aravam','Initial c-loss and final-vowel development; r remains after initial vowel.'),'Malayalam':('R','aravu|aravam','Same broad retention with initial loss.'),'Telugu':('D','trā̃cu','Displaced nasal formation.'),'Gondi':('R','taras|tarāsh|tarās|tarasu|taranj ( tarask)|tārs|turashee','Retained initial vowel-r order despite medial syncope and quantity variants.'),'Konda':('R','saras|sarasu','Retained full order.'),'Kui':('D','srāsu ( srāska)|srācu','Displaced cluster retained.'),'Kuwi':('D','rācu|rācū ( rāska)|nāgarācu','First-member loss in displaced family; compound counts once.'),'Pengo':('D','rāc','Same.'),'Manda':('D','trehe','Initial cluster with separate final changes.'),'Gadaba':('O','tāsu','Medial r loss/assimilation or loan, no demonstrated tr stage.')},
        input_confidence='high for segment order; medium for exact common suffix',references='K03 pp.122–123 n.5(1); DEDR 2359; DNM sarāhaya cited there',boundary='Independent nasal/geminate variant distinguished from simple final s; southern vu is later morphology.')

    add('d2628','chironji tree and nut','*cir/cēr-V?; regional *ser/ sar-ēk',
        'c/s','i/e/a','r','e/unknown','CVC-V-K / CVVC','noun',
        'Kolami sire/cīre, Naikri śīre and Parji cīr independently support c-V-r but mix short/long grades. Gondi serkā/sirkā and sarēkā/saṛēka support a velar tree formation; exact V1/V2 before metathesis remains uncertain.',
        'Multiple central and Gondi forms favor s-V-r before Kui srēko. The imported *srēk-o reconstruction adopts the shifted cluster and cannot be used to claim that Gondi inserted its vowel without independent argument.',
        'Conditional *ser-V-k > srēk gives Kui; *srēk > rēk gives Kuvi/Pengo/Manda and some Gondi lects. Alternative regional borrowing of srēko/rēko is plausible for a culturally salient tree name. Long cīr and short serk cannot be collapsed to assert unrestricted long-vowel metathesis.',
        'No Telugu attestation in the linked corpus. The restricted geography and regional tree-name traffic weaken family-wide inheritance claims. Gondi full and r-initial variants preserve useful lect evidence, but distinct suffix vowels and quantity prevent a deterministic conditioning assignment. Latin B. latifolia is a parser fragment, not a Gondi word.',
        {'Gondi':('M','saṛēka|sarēkā|serkā|sirkā marā|rēka','Full and first-member-loss forms in different lects; contact alternative retained.'),'Kui':('D','srēko','Attested initial cluster, reconstruction direction supported outside Kui.'),'Kuwi':('D','rēko','Likely cluster simplification in displaced family, potentially through borrowing.'),'Pengo':('D','rēka mar','Same with independent tree noun.'),'Manda':('D','rēko','Same.'),'Kolami':('R','sire|cīre','Short/long full forms.'),'Naikri':('R','śīre','Long full root.'),'Parji':('R','cīr','Long full root.')},
        input_confidence='medium for order; low for exact vowels/quantity',references='DEDR 2628; Burrow–Emeneau 1972 DEN1 p.407 entry 2160; Southworth 2006 *cir/cīr',eligibility='regional-contact-uncertain',quantity='mixed, proto-quantity unresolved',boundary='Velar tree formation versus unsuffixed nut/tree root; no exact V2 class inferred from output.')
    tokens('d2628','Gondi',R='saṛēka|sarēkā|serkā|sirkā marā',D='rēka')
