from cluster_case_helpers import case
def populate(add,tokens):
 def c(*a,**k):case(add,tokens,*a,**k)
 c('d4971','rough, knotty; tree stump','*mur-aṭ; other roughness derivatives','m','u/o','r','a','CVC-a-Ṭ','noun/adjective',
 'Tamil muraṭu, Malayalam muraṭu and Kannada moraḍu independently establish a full low-a dental formation; Telugu moraḍu retains the same order.',
 'Full agreement favors Telugu mrōḍu innovation; Kui mrōjo independently has cluster order in the tree-base meaning.',
 '*mor-aḍ > mrōḍ by displacement/coalescence. Kui mrōjo adds dental-palatal correspondence. Nasal moṇḍi can reflect a separate assimilated derivative and is not proof of a previous mr stage.',
 'Exact full/cluster Telugu pair supports direction and quantity, but coexistence requires lexical/formation history: the stump submeaning changes while broader rough derivatives retain r medially. Do not define a phonological class by that outcome. Gravel words have Indo-Aryan comparisons and need separate transmission study.',
 [('Tamil','R','muraṭu|muruṭu|muraṇ','Full derivatives.'),('Malayalam','R','muraṭu|muraṭan','Full low-a.'),('Kannada','R','moraḍu|muruḍu|morḍi','Full and consonantal grades.'),('Kodagu','R','moraḍɨ','Full stump name.'),('Tulu','R','muraḍi|muruḍu','Full order.'),('Gadaba','R','morḍo','Full consonantal stump.'),('Telugu','R','moraḍu|moraṭu|morapa|moramu','Full order.'),('Telugu','D','mrōḍu','Displaced stump noun.'),('Telugu','O','moṇḍi','Medial nasal assimilation.'),('Kui','R','mursa (mursi-)','Full reckless derivative.'),('Kui','D','mrōjo','Displaced tree-base noun.'),('Badaga','R','morada|moraṭṭtu','Full order.'),('Kota','R','morṭ|morḍṇ','Full order.')])
 c('d4973','sound, murmur, roar','*mur-al/av; competing *muẓ-aŋk4989','m','u/o','r','a','CVC-a-C','verb/noun',
 'Tamil mural/muravu, Kannada moraḷ and Telugu morayu establish full r order. Telugu cluster forms are explicitly also assigned to4989.',
 'An initial apical displacement is plausible under either proposed root, but r versus ẓ and exact nasal/labial suffix cannot be decided by mrō alone.',
 'Conditional *mor-av > mrōv or *moẓ-aŋk > mrōŋg; analogy could extend one cluster stem through the sound paradigm. Full morayu may be retained or a distinct derivative.',
 'All disputed cluster forms remain A in both entries; sensitivity merge prevents repeated ambiguous-family evidence. More historical forms retaining the distinctive apical or exact suffix would decide. Expressive origin is possible, not itself proof of unrelatedness.',
 [('Tamil','R','mural|muravu|muravam','Full low-a series.'),('Kannada','R','moraḷ|more|mure','Full r.'),('Malayalam','R','muraḷuka|muruḷuka','Full r.'),('Tulu','R','morampu|muriya','Full r.'),('Parji','R','mur|murip- (murit-)','Full r.'),('Gondi','R','muri|mōr','Short/long full.'),('Kolami','R','moray- (morayt-)|morp- (moropt-)','Full root.'),('Naikri','R','moray|morap','Full root.'),('Kodagu','R','more','Full root.'),('Kuwi','R','muru muru ā|mūrūkīali','Full expressive forms.'),('Kui','R','muru inba','Full expressive.'),('Kurux','R','murrnā','Full r.'),('Malto','R','mure','Full root.'),('Brahui','A','marrām','Alternative5013 and expressive strengthening.'),('Telugu','R','morayu|morapamu|morayika','Full order.'),('Telugu','A','mrōvu|mrōyu|mrō̃gu','Explicit alternative4989.')],eligibility='alternative-cognacy')
 c('d4975','break, perish, kill','*mur-i; velar/nasal derivatives and long grade','m','u/ū','r','i/u/zero','CVC-V-C / CVVC','verb',
 'Tamil muri/murukku/muruŋku and central murk independently establish full short-vowel order; Malayalam mūruka is a long grade, not evidence all inputs were long.',
 'Full comparisons favor eastern mr and Telugu br innovations; m>b is separate from displacement.',
 '*mur-k > mruk, then Kui mruk-p > mrupk in the separate suffixal process. Telugu *mur-ŋg > *mruŋg > bruŋgu; *mur-y > bruyyu involves labial denasalization/strengthening. Full muruŋku leaves syncope versus later shortening open.',
 'Death/kill derivatives and ordinary breaking forms coexist. Do not count bruŋgu sink4993 as an independent reflex of this r root: it has a competing semantic history and different apical. Long mrūva versus short mrunga in Kui needs formation-level quantity analysis.',
 [('Tamil','R','muri|murukku|muruŋku','Full short derivatives.'),('Malayalam','R','mūruka','Long grade.'),('Tulu','R','muri|murku|mūruni','Full short/long.'),('Kolami','R','murk','Full cluster.'),('Kolami','B','muriyā','Explicit Telugu loan.'),('Naikri','R','mur|murk','Full root.'),('Pengo','R','mur','Full root.'),('Kurux','R','murᵘknā|murcnā','Full order.'),('Malto','R','murke|murkre','Full order.'),('Kodagu','R','muri- (murip-, muric-)','Full order.'),('Badaga','R','muri|mare','Full order.'),('Telugu','R','muriyu|muri|muriya|muri-konu','Full breaking root.'),('Telugu','D','bruŋgu|bruncu|bruyyu','Displaced death/kill derivatives, m>b separate.'),('Telugu','O','mukka','Medial assimilation.'),('Kui','D','mrupka|mrunga (mrungi-)|mrūva (mrūt-)|mroku inba','Displaced suffix variants.'),('Kuwi','O','muka','Internal r loss/assimilation.'),('Kota','R','mury','Full root.'),('Toda','R','myry- (myrs-)','Full order.')],quantity='short and independent long grades',eligibility='core-formation-uncertain')
 c('d4989','roar, resound; speak','*muẓ-aŋk; *moẓ-i; competing *mur4973','m','u/o','ẓ','a/i','CVC-a-NK / CVC-i','verb/noun',
 'Tamil muẓaŋku and Kannada moẓagu independently establish full approximant order and low-a roar formation; speech moẓi is a high-i derivative.',
 'Telugu mrō could continue this root or4973 mur; loss of the distinctive apical prevents unique assignment.',
 'Conditional *moẓ-aŋk > *mẓoaŋk > mrōŋg. Telugu mrōyu/mrōvu would then require suffix alternation or analogy; deriving all directly from muẓaŋku is not segmentally sufficient.',
 'A under both alternative roots, with family sensitivity merger. The database broad speech head must not replace the low-a roar formation. Need early apical reflex or comparative exact y/v derivatives to decide.',
 [('Tamil','R','muṛ̆aŋku|muṛ̆akku|moṛ̆i','Independent low-a and high-i formations.'),('Malayalam','R','muṛ̆aŋŋuka|muṛ̆akkuka|moṛ̆i','Same.'),('Kannada','R','moṛ̆agu','Low-a full form.'),('Konda','R','miṛi','High-i speech.'),('Kolami','R','muḍ- (muṭṭ-)','Full apical speech paradigm.'),('Naikri','R','muṛ- (muṭṭ-)','Full apical.'),('Kodagu','R','moḷi','Full lateral.'),('Toda','R','mɨḷ','Full lateral.'),('Kota','R','moṛv','Full apical.'),('Badaga','R','mōḷa','Full long instrument name.'),('Telugu','A','mrōyu|mrōvu|mrō̃gu','Competing4973.')],eligibility='alternative-cognacy')
 c('d5007','spoil, become mouldy; dirt','*muṟ-i; *muṟ-k/g','m','u','ṟ','i/zero','CVC-i / CVC-C','verb/noun',
 'Tamil muṟi, Telugu muṟiki/muṟugu, Gondi murk and Tulu murguni independently support full apical order and consonantal variants.',
 'Full and cluster comparanda favor Telugu mrukku innovation; r-less muggu has a direct internal assimilation alternative.',
 '*muṟ-k > mrukk with reordering/strengthening; *muṟ-ik > *muṟk by syncope is possible. mrukku > mukku is supported by the pair, while muggu could arise directly as in Kannada muggu.',
 'Distinguish same-surface ripen mruggu5017/5046 from mouldy mrukku. Dirt and putrefaction meanings fit one family, but cannot fix vowel deletion chronology. Long mūri stench is a separate grade.',
 [('Tamil','R','muṟi|muri','Full root.'),('Telugu','R','muṟiki|muṟugu','Full derivatives.'),('Telugu','D','mrukku|mrukka|mukku|mukka','Cluster and reduced pair.'),('Telugu','A','muggu|mugga','Direct assimilation or cluster reduction.'),('Gondi','R','murk','Independent consonantal stem.'),('Tulu','R','murguni','Independent medial cluster.'),('Tulu','O','mugga','Internal assimilation.'),('Kannada','R','muṟikil|mūri','Full order.'),('Kannada','O','muggu|muggalu','Internal assimilation.'),('Kolami','R','murr','Full root.'),('Naikri','R','murg','Full cluster.'),('Parji','R','mur|mura|muraṭ','Full order.'),('Konda','R','muRki','Full cluster, source capital R preserved.'),('Gadaba','R','muyuṛ','Full apical with glide development.'),('Badaga','O','muggu','Internal assimilation.'),('Malayalam','R','muṛ̆iŋŋu','Full apical, identity differs.')],eligibility='core-formation-uncertain')
 c('d5017','ripen, mature','*muṟṟ-u; alternative *mūẓ5046','m','u','ṟṟ','u','CVCC-V','verb',
 'Tamil/Malayalam muṟṟu independently establish a strong apical root; Tamil muṟuku adds a velar variant, but its exact historical segmentation is uncertain.',
 'Te mruggu might reflect a weakened/suffixed apical variant or5046; the source explicitly gives both options.',
 'Conditional *muṟ-kk > mrugg requires a singleton apical plus velar suffix independently distinguished from *muṟṟ-u; *mūẓ-k > mrugg additionally requires shortening. Neither is securely selected.',
 'Keep A, not a counterexample rescued by postulating degemination. Southern strong-root retention is an informative control. Historical full Telugu variant or cognate suffix paradigm would separate the analyses.',
 [('Tamil','R','muṟṟu|muṟṟi|muṟuku|muruku','Strong and velar variants.'),('Malayalam','R','muṟṟuka|muṟṟu','Strong full root.'),('Kota','R','mut- (muty-)','Full strong-root reflex; alternate4954 remains in source.'),('Toda','R','mut- (muty-)','Full strong-root reflex.'),('Tulu','R','muttuni','Full strong stem, semantic divergence.'),('Badaga','R','muttu','Full strong.'),('Telugu','A','mruggu|muggu','Explicit alternative5046.')],structure='geminate',eligibility='alternative-cognacy-geminate-control')
 c('d5046','ripen after plucking','*mūẓ; short *muṛ-k derivative','m','ū/u','ẓ','zero/unknown','CVVC / CVC-C','verb',
 'Tamil mūẓ and Gondi mūṛānā independently establish long root; Parji muṛ/muṛkip gives a short derivative.',
 'Te mruggu could belong here or strong5017. Both order and quantity histories depend on that choice.',
 'Conditional *muẓ-k > mrugg from a short derivative, or long *mūẓ-k plus shortening; a direct full same-u contraction is not established.',
 'Keep A and merge alternative-family evidence for sensitivity. Different ripening situations can motivate derivative semantics but cannot prove apical identity or regularity.',
 [('Tamil','R','mūṛ̆','Long full root.'),('Gondi','R','mūṛānā|muṛkstānā','Long and short cluster derivatives.'),('Parji','R','muṛ|muṛkip- (muṛkit-)','Short full root/derivative.'),('Malayalam','R','muṛ̆ukka','Full high-u derivative.'),('Telugu','A','mruggu|muggu','Competing5017.')],quantity='long root and independent short derivatives',eligibility='alternative-cognacy')
 c('d5087','goat; old cluster word of unknown meaning','regional *mē-k; Old Telugu mṛ̆ēka unglossed','m','ē','k','unknown','CVVC','noun',
 'Kannada mēke and central mēka/mēke support a goat word without a medial apical; source explicitly says Old Telugu mṛ̆ēka has unknown meaning.',
 'The unglossed Old Telugu cluster cannot establish metathesis of the goat word. Brahui mēṛ̆ẖ is expressly without etymology in the cited source.',
 'Possible expressive mē bleat + k animal name, regional diffusion or Indo-Aryan relationship; no demonstrated full mar/mer antecedent. Old cluster word could be unrelated.',
 'Exclude as a metathesis positive. Do not transfer goat gloss to the old form or Brahui word. Need the actual Old Telugu passage and semantic identification before proposing cognacy.',
 [('Telugu','R','mēka|mē̃ka','Nonapical goat forms.'),('Telugu','A','mṛ̆ēka','Meaning explicitly unknown.'),('Kannada','R','mēke|mē','Nonapical goat/bleat.'),('Gondi','R','mēka|mekā','Nonapical goat.'),('Kolami','R','me·ke','Nonapical goat.'),('Naikri','R','mēke','Same.'),('Gadaba','R','mēge','Same.'),('Parji','R','mēva|mēya','Velar weakening possible.'),('Kurux','R','mēxnā (mīxyas)','Call verb, possible expressive relationship.'),('Malto','R','méqe','Bleat verb.'),('Badaga','R','mē','Bleat, expressive.'),('Brahui','A','mēṛ̆ẖ','Source explicitly rejects known etymology.')],quantity='long',eligibility='unknown-gloss-and-nonapical-control')
 c('d5114','blunt, maimed, stump','*moṇṭ / *moṭ; long variants','m','o/ō','ṇṭ/ṭ','zero/u','CVNC / CVC','adjective/noun',
 'Tamil moṇṭi/moṭṭai and Kannada moṇḍu/mōṭu supply nasal/stop inputs; Telugu mrōḍu paḍu has extra initial r.',
 'No unique rhotic ancestor of this compound follows from the nasal-stop series; resemblance to4971 mrōḍu stump offers a concrete analogical candidate.',
 'Possible contamination of mōḍu blunt by mrōḍu stump4971, or a shared apical variant across the lexical families. Direct moṇḍu>mrōḍu requires more than segment exchange, including nasal loss/length change.',
 'Keep A. The proposed analogy is semantically specific but not attested chronology. Southern long ẓ variants offer another root link needing full comparative work; do not force them into a single protoform.',
 [('Tamil','R','moṇṭi|moṇṇai|moṭṭai','Full nasal/stop forms.'),('Tamil','A','mōṛ̆ai','Long approximant branch uncertain.'),('Malayalam','A','mōṛ̆a','Same.'),('Kannada','R','moṇḍu|moṇḍe|mōṭu','Full order.'),('Tulu','R','moṇḍu|mōṇṭɯ','Full nasal-stop.'),('Kota','R','moṇḍy|meḍ','Full stop.'),('Toda','R','muḍy','Full stop.'),('Konda','R','moṭo','Full stop.'),('Gadaba','R','moṭo','Full stop.'),('Kurux','R','muṭā','Full stop.'),('Badaga','R','mōṭa|moddu','Full stop.'),('Telugu','R','moṇḍi|mōḍu|mōṭu|moṇḍemu','Full nasal/stop.'),('Telugu','A','mrōḍu paḍu','Possible analogy4971, not proved.')],quantity='short and long grades',structure='nasal-stop/strong stop',eligibility='secondary-r-or-alternative-root')
 c('d5123','bow, kneel, salute','*moẓ-k/g; other apical derivatives','m','o/u','ẓ','zero','CVC-C','verb',
 'Kannada moẓgu, Gondi moṛk and Parji moṛk independently establish a medial apical-velar cluster.',
 'Full cluster agreement favors Telugu mrokku/mroggu innovation; Kannada mokku independently shows a direct medial reduction route.',
 '*moẓ-k/g > mrokk/mrogg with reordering and strengthening; Telugu mokku/moggu can be later r loss or direct assimilation. Kui mrōnga has a nasal-velar formation and unexplained long vowel relative to a short cluster input.',
 'Ritual salute forms may diffuse. Keep Naikri mokk ambiguous between contact, direct assimilation and hidden displacement. Kuvi bong cannot demonstrate the original apical without a fuller intermediate; b versus m and nasal place require additional history.',
 [('Kannada','R','moṛ̆gu|muṛ̆gu','Full medial cluster.'),('Kannada','O','mokku','Internal reduction.'),('Gondi','R','moṛk|moṛkānā|mōṛ|murrānā','Full short/long derivatives.'),('Parji','R','moṛk|muṛd','Full apical.'),('Gadaba','R','molk- (moluk-)|mulk','Full lateral cluster.'),('Malto','R','murɣre|murɣtre','Full r cluster.'),('Kurux','R','mulkʰrnā','Full lateral.'),('Kota','R','aḍ mug- (muṛt-)','Compound with full-order paradigm.'),('Telugu','D','mrokku|mroggu','Displaced clusters.'),('Telugu','A','mokku|moggu|moggatilu','r loss or direct assimilation.'),('Kui','D','mrōnga (mrōngi-)','Long cluster, quantity residual.'),('Kuwi','A','boŋg- (-it-)|bonginai','Apical/initial history uncertain.'),('Naikri','A','mokk','Assimilation/contact/concealed cluster.')],eligibility='core-formation-uncertain')
 c('d5250','stream, river, pit','regional *vant; extra-r variant','v','a','nt','zero/i','CVNC','noun',
 'Kolami/Naikri vanta and Telugu vanta independently supply a nasal-stop root without r.',
 'Telugu vranti adds r while retaining nt; this is not a simple permutation of the compared input.',
 'Possible secondary r, contamination by a flow/channel root such as the source cross-references5296/5356, or an older two-apical compound; none is established.',
 'Keep A for cluster. Need older full r-bearing form and source contexts for river versus pit. A word-initial cluster alone does not justify *var-anti.',
 [('Kolami','R','vanta|vantā','Full nonrhotic root.'),('Naikri','R','vanta','Same.'),('Telugu','R','vanta','Same.'),('Telugu','A','vranti','Extra r unexplained.')],structure='nasal-stop',eligibility='secondary-r-input-unresolved')
 c('d5368','perch, alight; fly','*vāl; extra-r variant','v','ā','l','zero/u','CVVC','verb',
 'Kannada vāluvike, Gadaba vāl and Parji vēl independently supply a long lateral root.',
 'Te vrālu retains l and adds r. Adjacent a-l reversal would yield vlā, not vrāl.',
 'Possible secondary r in vālu>vrālu, analogy with other vrā verbs, or a longer ancestral root. No independent second apical is available.',
 'Keep A. Compare5369 slope for possible shared polysemous root in sensitivity only; perching and inclination are a possible bridge, not proof. Need dated variants or fuller cognates.',
 [('Kannada','R','vāluvike','Full lateral.'),('Gadaba','R','vāl','Long lateral.'),('Parji','R','vēl|vēlpip- (vēlpit-)','Long lateral, vowel variant.'),('Telugu','R','vālu','Full lateral.'),('Telugu','A','vrālu','Extra r, lateral retained.')],quantity='long',eligibility='secondary-r-input-unresolved')
 c('d5369','incline, slope, bend','*vāl; extra-r variant','v','ā','l','zero/u','CVVC','verb',
 'Kannada vālu/ōlu and Telugu vālu establish a long lateral root. Initial v loss in Kannada ōlu is separate.',
 'Te vrālu adds r while retaining l, requiring more than a one-for-one exchange.',
 'Possible secondary r by analogy or a missing longer input; simple *vāl>vrāl is not metathesis. Perch5368 may be a related polysemy.',
 'Keep A; record the specific analogy hypothesis and its missing dated evidence. Do not reconstruct *varāl solely from the Telugu cluster.',
 [('Kannada','R','vālu|vāluvike','Full lateral.'),('Kannada','O','ōlu','Initial v loss.'),('Telugu','R','vālu|vālucu','Full lateral.'),('Telugu','A','vrālu','Extra r unresolved.')],quantity='long',eligibility='secondary-r-input-unresolved')
 c('d5372','live, flourish, livelihood','*wāẓ; short *waẓ-d-uk / regional *bar-d-uk','v/b','ā/a','ẓ/r','zero/u','CVVC / CVC-C-V-C','verb/noun',
 'Tamil vāẓ and Kannada bāẓ establish long root; Kannada barduku/barduŋku and baẓduŋku independently support a short expanded apical-dental formation.',
 'Kannada barduku favors Telugu braduku reordering without projecting the long bare-root vowel onto this derivative. Possible early regional borrowing would still permit local displacement.',
 '*bar-d-uk > bra-d-uk, with initial w>b and apical development preceding or independent of the observed order change; bratuku has dental voicing variation. baduku/batuku can be direct apical loss or later cluster loss.',
 'The apical is followed by d and a further u-k suffix: morphology is crucial. The apparent Telugu b&lt, br&lt and &gt are transcription/editorial fragments, not forms. Neither Arabic barkat cross-reference nor unrelated Badaga place names establish cognacy.',
 [('Tamil','R','vāṛ̆|vāṛ̆vu|vaṛ̆uttu','Long root and short expanded formation.'),('Malayalam','R','vāṛ̆uka|vaṛ̆uttuka','Long/short derivatives.'),('Kannada','R','bāṛ̆|barduku|barduŋku|baṛ̆duŋku','Independent full short apical-dental derivative.'),('Kannada','O','baduku|badiku|badaku','Apical loss in derivative.'),('Tulu','R','bāḷu|bāḷuni','Long full lateral.'),('Tulu','O','badukuni|badɯkɯ','Apical loss derivative.'),('Kodagu','R','ba·ḷɨ','Long full lateral.'),('Kodagu','O','badɨkɨ','Reduced derivative.'),('Telugu','D','braduku|bratuku|bradimi|bratikincu','Displaced derivative family.'),('Telugu','A','baduku|batuku|atuku','Direct loss, cluster reduction or editorial initial-vowel fragment.'),('Gondi','O','badaktōr','Reduced derivative.'),('Kolami','O','badk|bat- (batt-)','Reduced derivatives.'),('Naikri','O','batt|badkip','Reduced derivatives.'),('Konda','O','batku|batki- (-t-)','Reduced derivative.'),('Kuwi','O','batk- (-it-)|batku','Reduced derivative.'),('Parji','O','badk','Reduced derivative.'),('Kota','O','vadk- (vadky-)','Reduced derivative.'),('Badaga','R','bāḷu','Long lateral.'),('Badaga','O','baduku|badaku','Reduced derivative.'),('Kui','A','bārti','Different long dental formation.')],quantity='long root and independently short derivative',eligibility='core-morphology-and-contact-caveat')
 c('d5555','throw, strike, discharge','*wey; long grade and extra-r variants','v','e/ē','y','zero/unknown','CVC / CVVC','verb/noun',
 'Konda vey and Kuvi ve/vēp independently supply a nonrhotic root. Telugu vēyu/vaicu likewise has no medial r.',
 'Te vrēyu/vrēṭu adds r absent from the comparative input; neither the glide nor dental can simply exchange with a vowel to supply it.',
 'Possible analogical r in vēyu>vrēyu followed by derivative spread, or older fuller root/compound not yet identified. Labial/dental suffix alternations in eastern forms do not independently establish r.',
 'Keep A, including vrēṭu strike noun and compound. Need early full rhotic witness or a demonstrable analogical model. Modern Telugu r-less variants cannot alone establish r loss as the first history.',
 [('Konda','R','vey- (-t-)','Full nonrhotic root.'),('Kuwi','R',"ve'- (vet-)|vēp- (-it-)|vēnai",'Nonrhotic short/long forms.'),('Kannada','R','bese','Nonrhotic correspondence.'),('Tulu','R','bettuni|beppuni','Strong dental/labial forms.'),('Kodagu','R','be·ŋg- (be·ŋgi-)','Long nasal derivative.'),('Naikri','R','vayk','Nonrhotic derivative.'),('Telugu','R','vēyu|vaicu|vē̃ta','Nonrhotic forms.'),('Telugu','A','vrēyu|vrēṭu|vrē̃ta|vrēṭu-gonu','Extra r unresolved.')],quantity='short and long grades',eligibility='secondary-r-input-unresolved')
