"""Secondary nasals, compound aphaeresis and a stop-cluster comparison."""

def populate(add,tokens):
    add('d4737','eel, elongated fish','*mal-aŋ; regional fish-name variants',
        'm','a','l','a','CVC-a-NC','noun',
        'Tamil malaŋku and Gondi malanji establish m-a-l-a-N, with Telugu malũgu/maluga and Konda malŋu confirming medial lateral; the immediate comparative input is not nasal.',
        'The full lateral stems support an innovation in Kui mrāu/mrānga. Kuvi mṇiya may also descend from that family but does not itself establish a nasal proto-root.',
        '*mal-aŋ > *mlaaŋ > *mrāŋ with lateral-to-rhotic development and later final changes can account for Kui mrāu:mrānga. Kuvi mṇiya would need additional nasal assimilation and vowel/ending changes; these are not independently ordered. Kurux mińj may have lost the lateral in a cluster and changed vowel, rather than metathesizing it.',
        'Do not count this as primary-nasal metathesis because the current cluster contains ṇ. Fish taxonomy and differences between eel, elongated fish and tambū require field/source checking. Tulu malejji has a different ending, and Kuvi i is not predicted by simple a+a contraction; these remain genuine uncertain comparisons. Telugu high u is secondary/variable relative to independently low-a forms, not proof of a unique high-suffix input.',
        {'Tamil':('R','malaŋku','Full low-vowel lateral.'),'Tulu':('R','malejji','Lateral retained, ending differs.'),'Telugu':('R','malũgu|maluga','Lateral retained, variable ending.'),'Gondi':('R','malanji|malanj|malāj','Full and reduced lateral forms.'),'Konda':('R','malŋu moya','Medial syncope, fish compound.'),'Kui':('D','mrāu ( mrānga)','Displaced lateral-derived cluster.'),'Kuwi':('A','mṇiya','Possible secondary nasal in displaced cluster; vowel/taxonomy unresolved.'),'Kurux':('O','mińj','Possible medial lateral loss, not secure initial exchange.')},references='DEDR4737; DED(S,N)3877',eligibility='core-secondary-nasal-warning',input_confidence='high for lateral input; medium for exact eastern cognacy')
    add('d4756','man, husband, male','regional *maṟ/maẓ-s/c; vowel/grade uncertain',
        'm','a/u','r/ẓ','unknown','CVC-s / CVC-s-V plus gender suffixes','noun',
        'Gondi maṛso/maṛsur/māṛsāl and Malto muṛse/muṛso establish an apical after the vowel; no nasal is required by these full regional forms. The K03 *maẓc-a reconstruction is a proposal, not direct evidence for every suffix vowel.',
        'Gondi and Malto full stems versus Kui/Kuvi mṛeh-/mlēh-like forms support movement or displacement-family reduction of a nonnasal apical. Kuvi mneha/mṇēha is not independent evidence for primary nasal input.',
        'Regional *maṛ/maẓ-s-V > *mṛ/ẓV-s/h is the displacement-family comparison, with s/c>h and apical rhotic/lateral/nasal outcomes requiring separate histories. Low a to e/ē and variable length cannot be derived from one unqualified a+a contraction; a different formative, vowel change or lexical restructuring remains necessary.',
        'Gender endings in mṛehenju/mṛehali must be separated from the shared base, not counted as separate etyma. The sparse regional distribution and competing maṇ-s versus maẓc reconstructions leave deeper cognacy and order of apical assimilation unresolved. Gondi long māṛ- may be a separate grade; it is not proof the immediate displaced input was long. Nasal variants can reflect assimilation to initial m after displacement, but that chronology is a hypothesis.',
        {'Gondi':('R','maṛso ( -rk)|maṛsur|māṛsāl|māṛsālor|mai-mansāl','Full apical stems; mans variant preserved.'),'Malto':('R','muṛse|muṛso|muṛsoti|muṛs-maqe|muṛsti','Independent full apical forms.'),'Kui':('D','mṛeha|mṛehenju|mṛehali','Displaced base plus gender formations.'),'Kuwi':('D','mṛeha|mṛēha|mleha|mneha|mṇēha','Displaced cluster with secondary rhotic/lateral/nasal variants.')},quantity='short and long regional grades; immediate input uncertain',references='DEDR4756; K03 reconstruction records',eligibility='regional-displacement-vocalism-unresolved',input_confidence='high for full apical order, low for exact immediate vowels')
    add('d931','carry in loads, cart','*ok-; transitive *ok-p-',
        'Ø','o','k','zero','VC-p','verb',
        'Konda and Pengo ok-, Parji okp:okt and Kui past okt establish velar before labial in the transitive stem independently of the Kui present opka.',
        'The base ok and retained Parji okp directly support k-p as earlier than Kui p-k. This is not an apical input.',
        '*ok-p-a > opka in Kui, while past *ok-t yields okt. Parji preserves okp:okt; Konda okis is a different causative formative. Pengo bare ok supplies a root control, not the same -p formation.',
        'The red *kem head is a database linkage error and is excluded. Gadaba oskap has additional s and cannot independently establish a simple identical stem. Gondi akanā may reflect vowel lowering or different formation/cognacy. The source compares Tamil oy984, but the relationship k:y needs separate reconstruction. This supplies one additional Kui k-p formation, not a Telugu metathesis case.',
        {'Konda':('R','ok- (-t-)|okis','Nonapical root and alternative causative.'),'Pengo':('R','ok- (-t-)','Nonapical base.'),'Parji':('R','okp- (okt-)','Retained velar-labial formative.'),'Kui':('R','opka (&lt; ok-p-; okt-)','No apical event; k-p>p-k recorded separately.'),'Kuwi':('R','okʰ\'nai','Retained nonapical base.'),'Gadaba':('A','oskap- (oskat-)','Additional s complicates exact formation.'),'Gondi':('A','akanā','Vocalism/formation comparison uncertain.')},c2_structure='nonapical velar',references='DEDR931 p.90 directly read',eligibility='nonapical-kp-domain',boundary='Independent root ok plus transitive p, contrasted with past t.',input_confidence='high for velar-labial order',mechanism='Consonant-cluster k-p > p-k, separate from initial apical displacement.')
    add('d945','with, together; agree, reconcile','*uṭ-an / *oṭ-an; compound *oṭam#paṭ-',
        'Ø','u/o','ṭ','a','VC-a-n # verb; grammatical suffix variants','postposition/adverb/verb',
        'Tamil uṭaṉ and uṭam-paṭu, Malayalam uṭan/uṭam-peṭuka and Kannada oḍan/oḍam-baḍu independently establish a full comitative base and compound boundary.',
        'The matching full compound in several southern languages supports initial-vowel loss in Tulu dambaḍ-; Telugu also preserves the full compound, but is not the sole order witness.',
        '*oḍam#baḍ- > Tulu oḍam-baḍipuni beside dambaḍipuni by aphaeresis plus retroflex simplification; medial a remains and no output long vowel is required. Telugu oḍam/oḍã-baḍu has nasalization/loss at the boundary without initial apical movement. Grammatical -oṭu/-ōṭu and Toda -vɨṛ require their own clitic/prosodic history.',
        'Tulu initial d is therefore not automatic evidence for the Telugu contraction process. Loss of initial o alone plus ḍ>d accounts for the observed segment sequence; a literal exchange would additionally need vowel fusion/loss and offers no independent advantage here. Badaga ōṭalu hotel with a following postposition gloss is a parser conflation, not a cognate comitative word. Morphological compounds and suffix allomorphs are not independent roots.',
        {'Tamil':('R','uṭaṉ|uṭam-paṭu|uṭaṉ-paṭu|uṭaṉ-pāṭu|uṭam-paṭikkai|oṭu|ōṭu','Base, compounds and grammatical forms.'),'Malayalam':('R','uṭan|uṭam-peṭuka|uṭam-paṭi|uṭanma|uṭama|uṭappam|oṭu|ōṭu','Same structure with morphology/assimilation.'),'Kota':('R','o·ṛ','Comitative suffix, source hyphen lost in database.'),'Toda':('R','-vɨṛ|vɨṛ|vɨṭk','Suffix and together form, separate prosody.'),'Kannada':('R','oḍan|oḍam|oḍa|oḍam-baḍu|oḍa-baḍu|oḍa-baḍike','Full compound and base.'),'Telugu':('R','oḍam-baḍu|oḍã-baḍu|oḍam-baḍika|oḍã-baḍika|oḍam-baṟacu|oḍã-baṟacu|oḍã-bāṭu','Full initial vowel preserved; nasal boundary variants.'),'Tulu':('A','oḍa|oḍam-baḍipuni|oḍam-baḍigɛ|oḍam-baḍikɛ|dambaḍipuni|dambaḍiyuni|dambaḍisuni|dambaḍigɛ','Full versus aphaeretic compound; not diagnosed as literal exchange.')},quantity='short base with long grammatical variants',references='DEDR945 p.90 directly read',eligibility='compound-aphaeresis-comparison',boundary='Independently matching comitative plus paṭ/baḍ compound; n>m before labial.',input_confidence='high for full compound',mechanism='Tulu aphaeresis and stop simplification; no unique evidence for literal vowel-apical exchange.')
    tokens('d945','Tulu',R='oḍa|oḍam-baḍipuni|oḍam-baḍigɛ|oḍam-baḍikɛ',A='dambaḍipuni|dambaḍiyuni|dambaḍisuni|dambaḍigɛ')
