"""Individually reviewed *aẓ-, *aḷ- and alveolar-root comparisons."""

def populate(add, tokens):
    add('d276','burn, grieve, ember','*aẓ-al- / *aẓ-Vŋk-; possible older *c/t-initial cognate',
        'Ø','a','ẓ','a/u','VC-VC / VC-V-NC','verb/noun',
        'Tamil aṛ̆al and Malayalam aṛ̆aluka support *aẓ-al independently; Tamil aṛ̆uŋku supports a different high-vowel nasal extension. Old Kannada aṛ̆v and Tulu arluni corroborate the vowel-first root. The database head **aẓVnkV is not the sole reconstructed formation.',
        'The southern comparison favors V–ẓ order for the regional input. DEDR tentatively connects initial t-bearing fire vocabulary d3115: that would place earlier initial-consonant loss before the regional vowel-initial stage, but is not established by this set alone.',
        '*aẓ-al > Telugu aḍalu/aḍaru with ẓ>ḍ and final-liquid variation, without initial displacement. Kannada aẓ-kaj > akkaja illustrates cluster assimilation. Conditional *aẓ-V-mp > *ẓV̄mp > Konda ṛīmbu would require an independently justified high-vowel history; the modern ī is not sufficient to reconstruct that history.',
        'Konda ember and Kuvi blaze/light forms begin ṛī-, compatible with displacement but with unexplained vowel quality and different extensions. Gondi eṛki/eṛk explicitly carries DEDR’s warning that its vowel is difficult. Kota arl fever has an alternative d214 comparison. Tamil aṭalai and Kannada aḍalu/aṛ̆al are source-marked Telugu loans. Kurux aŋgnā may lose ẓ in a medial cluster; it is not evidence of initial relocation.',
        {'Telugu':('R','aḍalu|aḍaru','Postvocalic apical retained; later ẓ>ḍ is independently relevant to displaced families.'),
         'Tamil':('A','aṛ̆al|aṛ̆uŋku|aṭalai','Native vowel-first roots and a source-marked probable Telugu loan.'),
         'Malayalam':('R','aṛ̆al|aṛ̆aluka|aṛ̆aṟṟuka','Vowel-first low-vowel formations.'),
         'Kannada':('A','aṛ̆aṭu|aṛ̆kaja|akkaja|aḍalu|aṛ̆al (aṛ̆ald-)','Native retention/assimilation separated from source-marked Telugu loans.'),
         'pampa':('R','aṛ̆v','Old Kannada burn root retains order.'),
         'Kota':('A','aṛc- (aṛc-)|arl','Flame verb retains order; fever noun has an explicitly competing etymology.'),
         'Toda':('A','as̱','Initial vowel survives, but exact ẓ+l-to-s̱ history not yet checked.'),
         'Tulu':('R','arluni|aradɛ|aratɛ','Medial syncope/extensions, no initial displacement.'),
         'Gondi':('A','eṛki|eṛk|arkī|aṛkī','All vowel-first; source cautions specifically about vowel reconstruction and cognacy.'),
         'Konda':('A','ṛīmbu ( ṛīpku','Candidate displacement in an ember noun; ī and morphological correspondence unresolved.'),
         'Kuwi':('A','ṛīnj- (-it-)|ṛīh- (-t-)','Candidate displacement; high long vowel needs an independent account.'),
         'Kurux':('O','aŋgnā','Conditional medial ẓ loss/assimilation in the nasal formation; no initial relocation.'),
         'Badaga':('A','arukalu|oraca|orca','Worry and anger forms keep a vowel first; exact suffix and vowel histories unresolved.')},
        references='DEDR 276 and its comments on d214,281,3115',input_confidence='high',
        boundary='Low -al and high -uŋk independently distinguished; Konda/Kuvi extensions are not assigned an invented vowel to fit their outputs.')
    tokens('d276','Tamil',R='aṛ̆al|aṛ̆uŋku',B='aṭalai')
    tokens('d276','Kannada',R='aṛ̆aṭu|aṛ̆kaja',O='akkaja',B='aḍalu|aṛ̆al (aṛ̆ald-)')
    tokens('d276','Kota',R='aṛc- (aṛc-)',A='arl')

    add('d277','perish, destroy','*aẓ-i-; transitive *aẓ-i-mpp- and *aẓ-i-ntt-',
        'Ø','a','ẓ','i','VC-i-NPP / VC-i-','verb/noun',
        'Tamil aṛ̆i with transitive -pp-/-tt-, Malayalam aṛ̆iyuka/aṛ̆ikka and Kannada aṛ̆i/aṛ̆ipu independently support high i and vowel-first ẓ. K03 p.195 explicitly derives Telugu destruction forms from non-past *aẓ-i-mpp and past *aẓ-i-ntt.',
        'SD I and Gondi vowel-first stems, together with retained Telugu aṛ̆isina/aṛ̆ipuṭa, favor earlier aẓi-. Inscriptional Telugu ṛ̆accu has initial ẓ while still preserving its identity: displacement need not wait until ẓ has become ḍ.',
        'K03: *aẓ-i-ntt > *aẓ-i-cc > inscriptional ẓaccu; *aẓ-i-mpp > *ẓapp- > Telugu ḍappi. Palatalization after i must precede deletion of its conditioning vowel under this account. Initial ẓ>ḍ follows displacement in the labial formation; the inscriptional palatal formation directly attests the otherwise hidden initial-ẓ stage. These are related tense/voice formations, not two independent sound-change events.',
        'Sastri 1969 pp.310–311, inscription38 (dated there 890 CE), has displaced ḻassi line14 and retained aḻisina lines20–21, aḻiputa line35 in one text, but different grammatical formations: coexistence is not identical-context free variation. Earlier inscription16 (pp.291–292, dated 670–680) has ḻaccina; DHARMA00026 distinguishes this reading from older editorial ḍaccina. ṛ̆assi and ḍappi are displaced, but ḍakkā has a different extension and remains uncertain. Parji/Gadaba killing forms have an explicit alternative d309. Homophonous thirst ḍappi d109 must not be merged solely by spelling.',
        {'Telugu':('M','aṛ̆isina|aṛ̆ipuṭa|aḍiy-āsa|aḍava|aḍuva|ṛ̆assi|ḍappi|ḍakkā','Retentions, displaced forms and an uncertain velar-extension noun all preserved.'),
         'OTelugu':('D','ṛ̆accu','Dictionary lemma; actual inscriptional ḻaccina verified via DHARMA00026 and Sastri inscription16, dated there 670–680 CE.'),
         'Tamil':('R','aṛ̆i|aṛ̆ipu|aṛ̆ippu|aṛ̆impu','High vowel and nasal/strong formative contrasts visible independently.'),
         'Malayalam':('R','aṛ̆iyuka|aṛ̆ikka|aṛ̆ivu|aṛ̆ayuka','Original order; a/e variants not erased.'),
         'Kannada':('R','aṛ̆i|aṛ̆ipu|aṛ̆ivu|aṛ̆upu','Original order in multiple formations.'),
         'pampa':('R','aṛ̆kāḍu','Old Kannada compound/extension preserves root ordering.'),
         'Kota':('R','aḷc- (aḷc-)|aḷyv','Medial changes and syncope preserve vowel-first order.'),
         'Toda':('R','oḍy- (oḍs-)|oḍc-','Vowel/consonant correspondences change without initial relocation.'),
         'Tulu':('R','aliyuni|aḷiyuni|arpuni|areḍuni','Distinct lateral/rhotic extensions retain initial vowel.'),
         'Gondi':('R','aṛih','Muria destroy form retains order.'),
         'Kui':('R','āṛi āva','Root lengthening with retained order; light-verb construction kept intact.'),
         'Parji':('A','nanḍkip- (nanḍkit-)|anḍkip- (anḍkit-)','Alternative d309 and added nasal/velar morphology prevent secure assignment.'),
         'Gadaba':('A','anuyp|anuyk|anukci key','Alternative d309; exact consonant history unresolved.'),
         'Badaga':('O','aḷi|aḷicu|aḷida|ayeda','Retained lateral beside local lateral lenition/loss; not initial displacement.')},
        references='K03 pp.194–195; DEDR 277; Sastri 1969 pp.291–292 inscription16, pp.310–311 inscription38, p.350 index; https://dharmalekha.info/texts/INSTelugu00026',
        input_confidence='high',confidence='high',
        boundary='Tamil tense and transitivity morphology independently supports i plus labial versus dental strong extensions; K03 reconstructs nasal precursors.')
    tokens('d277','Telugu',R='aṛ̆isina|aṛ̆ipuṭa|aḍiy-āsa|aḍava|aḍuva',D='ṛ̆assi|ḍappi',A='ḍakkā')
    tokens('d277','Badaga',R='aḷi|aḷicu|aḷida',O='ayeda')

    add('d281','affection, desire','*aẓ-i-; *aẓ(i)-k-ar- and *aẓ-ti formations',
        'Ø','a','ẓ','i','VC-i-C / VC-C','noun/verb',
        'Malayalam aṛ̆ivu and Kannada aṛ̆ipu independently support vowel-first *aẓi; Kannada aṛ̆kaṟ beside akkaṟe directly supplies the relevant medial-cluster comparison.',
        'Kannada preserves both ẓk and kk, favoring assimilation after medial syncope. Telugu akkaṟa remains vowel-initial, so its missing ẓ does not require an earlier initial promotion.',
        '*aẓi-kar > *aẓkar > akkar gives Telugu akkaṟa and Kannada akkaṟe with regressive assimilation ẓk>kk. *aẓ-ti > arti retains the rhotic-order reflex in another formation; remaining suffix vowels vary independently.',
        'DEDR tentatively relates burn/grieve d276, so root independence needs a sensitivity collapse. Tulu arti has an alternative long-root d381 comparison. Toda arkyn and Kota akm have different final morphology; their exact full derivations are less secure than the initial-order diagnosis.',
        {'Telugu':('O','akkaṟa','Medial assimilation can account for absent apical; initial vowel remains.'),
         'Malayalam':('R','aṛ̆ivu','Independent high-i formation.'),
         'Kannada':('O','aṛ̆ipu|aṛ̆kaṟ|akkaṟe|akkaṟa|aṛ̆ti|arti','Attested precursor/result of medial assimilation, plus other formations.'),
         'Tulu':('A','arkame|akkare|arti','Retention/assimilation in rk; arti has an explicitly competing etymology.'),
         'Kota':('O','akm','Consistent with ẓk assimilation, final m formative correspondence conditional.'),
         'Toda':('R','arkyn','Vowel first; suffix history requires independent analysis.'),
         'Badaga':('R','ariti|arti|arta','Vowel-first forms with syncope and final-vowel variation.')},
        references='DEDR 281 and cross-references d276,381',input_confidence='high',
        mechanism='Medial syncope and regressive consonant assimilation, not initial apical displacement',
        boundary='i-stem and consonantal extensions independently attested; exact historical age of -kar unknown.')
    tokens('d281','Kannada',R='aṛ̆ipu|aṛ̆kaṟ|aṛ̆ti|arti',O='akkaṟe|akkaṟa')
    tokens('d281','Tulu',R='arkame',O='akkare',A='arti')

    add('d282','cry, weep, call','*aẓ-u- / *aẓ-ay-; regional vowel history unresolved',
        'Ø','a','ẓ','u/a','VC-V / VC-V-C','verb/noun',
        'Tamil aṛ̆u/aṛ̆ai, Malayalam aṛ̆uka, Kannada aṛ̆u and Gondi–Konda aṛ- independently establish vowel-first apical and at least u/ay formations. PSS83 pp.14–15 compares *aẓ-u; the database Starostin *jeẓ head is an alternative analysis, not adopted as a given.',
        'Agreement of SD I, Gondi–Konda, Central Dravidian and retained Pengo aṛ- favors earlier V–ẓ. Kui/Kuvi/Manda initial ṛ are innovative under this cognacy, but their ī needs a regional vowel explanation. Pengo causatives supply a within-language original/displaced contrast.',
        'Retained *aẓ-u > Telugu ēḍu- requires vowel fronting/lengthening before or alongside ẓ>ḍ; ēḍucu has an incorporated past palatal according to K03 p.193. Pengo aṛ-/aṛba versus ṛat/ṛatpa shows apical displacement in causative formations; a possible *aẓ-a-t > ṛat route remains conditional. Kui/Kuvi/Manda *aẓV > ṛī is directionally plausible, but a uniquely supported sequence yielding ī is not yet available.',
        'Telugu long ē does not mean metathesis: the apical is still after the vowel. Pengo ṛatpa is a source correction of earlier aratpa, which would reverse its outcome classification if not followed. Tulu leppuni/leppu/lāvu may involve local aphaeresis/contraction or another root; DEN1 corrects lāvu for earlier levu. Badaga aḷu/avu/au exemplifies lateral lenition/loss. Gondi R Epic aḍusānā could reflect contact and is not needed to establish native retention.',
        {'Telugu':('R','ēḍucu|ēḍupu','Order retained despite independent root-vowel and consonant changes.'),
         'Tamil':('R','aṛ̆u|aṛ̆ai|aṛ̆uŋku','Different formations retain order.'),
         'Malayalam':('R','aṛ̆uka|aṛ̆aykkuka','Both formations vowel-first.'),
         'Kannada':('R','aṛ̆u (aṛ̆t-, att-)|aṛ̆asu|arke','Root retention with tense-cluster assimilation and syncope.'),
         'Kota':('O','ag- (aṛt-)|aṛg- (aṛgy-)|akl','Velar-present/retroflex-past contrast; medial cluster loss, not promotion.'),
         'Toda':('R','oṛ- (oṛy-)','Order retained with vowel change.'),
         'Tulu':('A','arpini|leppuni|leppu|lāvu','Retained cry verb plus uncertain initial-liquid call/cry derivatives.'),
         'Gondi':('A','aṛ|ar|aṛah- (<i>Voc.</i> 84)|āṛānā|aḍusānā (<i>Voc.</i> 84)','Native rhotic forms retain order; epic ḍ extension merits contact check.'),
         'Konda':('R','aṛba','Extended stem retains order.'),
         'Kui':('D','ṛīva (ṛīt-)|ṛīka','Initial promotion likely; ī and dialectal formative history unresolved.'),
         'Kuwi':('D','ṛī- (-t-)|rīali|līnai|ṛi- (-t-)|ṛīt- (-h-)','Initial promotion in all listed dialects; quantity and liquid identity vary.'),
         'Pengo':('M','aṛ- (aṛt-)|aṛba|ṛat|ṛatpa','Base/intensive retained; causative and intensive causative displaced.'),
         'Manda':('D','ṛī','Initial promotion; long high vowel unresolved.'),
         'Kolami':('R','ar- (art-)','Vowel first.'),'Naikri':('R','ar','Vowel first.'),
         'Naiki':('R','al|alup','Base/causative vowel-first.'),'Parji':('R','aṛ|aṛtip- (aṛtit-)','Base/causative vowel-first.'),
         'Gadaba':('R','aṛ|aṛup- (aṛut-)|āḍ|āḍ- (āṭ-)','Ollari/Salur retained order; lengthening and stop correspondence separate.'),
         'Badaga':('O','aḷu|avu|avvu|au','Attested variants support local lateral weakening/loss, without relocation.')},
        references='DEDR 282; DEN1 1972 p.400 entry 240; PSS83 pp.14–15; K03 p.193',
        input_confidence='high',boundary='u/ay and causative formations independently attested; exact formative vowels for short Pengo and long Kui stems not forced.')
    tokens('d282','Kota',O='ag- (aṛt-)|akl',R='aṛg- (aṛgy-)')
    tokens('d282','Tulu',R='arpini',A='leppuni|leppu|lāvu')
    tokens('d282','Gondi',R='aṛ|ar|aṛah- (<i>Voc.</i> 84)|āṛānā',A='aḍusānā (<i>Voc.</i> 84)')
    tokens('d282','Pengo',R='aṛ- (aṛt-)|aṛba',D='ṛat|ṛatpa')
    tokens('d282','Badaga',R='aḷu',O='avu|avvu|au')

    add('d285','dip, press, immerse','*aẓ-unt- / *aẓ-utt-',
        'Ø','a','ẓ','u','VC-u-NP / VC-u-PP','verb/noun',
        'Tamil aṛ̆untu/aṛ̆uttu and Malayalam aṛ̆untuka/aṛ̆uttuka independently support high u and transitivity-related dental extensions. Kannada aṛ̆du beside addu preserves an intermediate medial cluster.',
        'Southern high-vowel stems and retained Kannada ẓd provide a direct route to Telugu dd by medial syncope and assimilation. No language in the reviewed set requires initial apical movement.',
        '*aẓ-unt/utt > *aẓd > addu in Telugu/Kannada; Kannada ajju and Kota aj require an additional local palatal-cluster development. Tulu arduni retains a rhotic-plus-stop cluster. The details of dental voicing/strengthening are conditional, but initial-vowel deletion is unnecessary.',
        'DEDR’s possible link to long-root d396 āẓ could change the remote root quantity; retain that as a sensitivity issue rather than assign long input from an uncertain cross-reference. Gadaba addap blot closely resembles Telugu addu and could be a loan; donor evidence is not explicit, so do not count it as independent phonological confirmation.',
        {'Telugu':('O','addu|addakamu|addincu','Medial assimilation, with incorporated/extended dental stem.'),
         'Tamil':('R','aṛ̆untu|aṛ̆uttu','Independent high-u transitivity alternation.'),
         'Malayalam':('R','aṛ̆untuka|aṛ̆uttuka','Same ordered extension.'),
         'Kannada':('O','aṛ̆du|addu|ajju|eddu','Retained medial cluster beside assimilation/palatal variants.'),
         'Kota':('O','aj- (aj-)','Palatal-cluster outcome; no initial apical displacement.'),
         'Tulu':('R','arduni','Medial syncope without initial movement.'),
         'Gadaba':('A','addap','Local development versus Telugu contact unresolved.')},
        references='DEDR 285 and tentative cross-reference 396',input_confidence='high',
        mechanism='Medial syncope and cluster assimilation; independent palatal outcomes',
        boundary='u plus dental intransitive/transitive extensions independently paired in Tamil/Malayalam.')
    tokens('d285','Kannada',R='aṛ̆du',O='addu|ajju|eddu')

    add('d295','measure, size','*aḷ-a-; *aḷ-a-p/-v and dental extensions',
        'Ø','a','ḷ','a','VC-a-C','verb/noun',
        'Tamil aḷa/aḷavu/aḷappu, Kannada aḷe/aḷavu and Kodagu aḷa independently support low a and postvocalic lateral. Telugu alavi supplies a retained related measure noun.',
        'SD I and retained Telugu alavi support earlier *aḷav rather than initial *lāv with repeated prothesis. Kui/Kuvi/Pengo initial apical forms are therefore innovations under the shared measurement comparison.',
        '*aḷ-av > *ḷāv > lāvu in Telugu, with separate ḷ>l. Related palatal extensions give Kuvi/Pengo lāc and Kui ḍās/ḍāc, requiring local lateral-to-stop correspondence. Tulu aḷapuni > lappuni is compatible with aphaeresis and strengthening; K03 p.117 explicitly groups its short-vowel counterpart under aphaeresis.',
        'Telugu alavi and lāvu are not independent roots. Tulu short lapp- should not be equated uncritically with Telugu long lāv-. Manda lēc has unexplained e, so quantity/quality tests exclude it pending a supported vowel history. Badaga ādu measured has an explicitly cited archaic aldu precursor, evidence for lateral loss plus contraction/lengthening, not promotion. Toda’s Q in the DEDR digital tense string is a transcription issue; retain raw data and use independent Toda citation for order.',
        {'Telugu':('M','alavi|lāvu','Retained and displaced measure nouns.'),
         'Tamil':('R','aḷa|aḷavu|aḷappu','Low-vowel input supported independently.'),
         'Malayalam':('R','aḷavu|aḷakka','Order retained in nominal and verbal formations.'),
         'Kannada':('R','aḷe (aḷad-, aḷed-)|aḷavu|aḷate','Order retained.'),
         'Kodagu':('R','aḷa- (aḷap-, aḷand-)|aḷate','Independent morphological alternation.'),
         'Kota':('R','aḷv- (aḷd-)|aḷv','Medial syncope preserves initial vowel.'),
         'Toda':('R','ał̣- (ał̣Q-)|aɫ-̣ (aɫθ-)̣','Both source strings preserve vowel-first order; tense glyphs not normalized into invented segments.'),
         'Tulu':('O','aḷapuni|aḷa|lappuni|lappu|lakkɛ','Retained base beside aphaeretic short-vowel formations.'),
         'Kui':('D','ḍāsa (ḍāsi-)|ḍāc','Long-vowel initial apical; ḷ-to-ḍ correspondence separate.'),
         'Kuwi':('D','lācali|lāc- (-it-)|lāsk- (-it-)|lācinai','Long-vowel displacement family, dialectal extension differences retained.'),
         'Pengo':('D','lāc- (-c-)','Long-vowel displacement in measure verb.'),
         'Manda':('A','lēc','Initial displacement likely but e requires a supported regional vowel account.'),
         'Badaga':('O','aḷavu|ac|ādu','Retained noun and consonant-loss verbal forms; archaic aldu cited in source gloss.')},
        references='DEDR 295; K03 p.117; Hockings & Pilot-Raichoor 1992 pp.4,38,43 (citing Emeneau 1939 p.46)',
        family='d291+d295',input_confidence='high',confidence='high',boundary='Low a and labial/dental derivative alternations corroborated independently in SD I.')
    tokens('d295','Telugu',R='alavi',D='lāvu')
    tokens('d295','Tulu',R='aḷapuni|aḷa',O='lappuni|lappu|lakkɛ')
    tokens('d295','Badaga',R='aḷavu',O='ac|ādu')

    add('d296','mix, join, approach, seize','*aḷ-a- / *aḷ-ay-; *aḷ-p-? and other formations',
        'Ø','a','ḷ','a','VC-ay / VC-a-C / VC-C','verb',
        'Tamil aḷai/aḷa/aḷavu and Malayalam aḷayuka independently support low a and lateral after the vowel. Kannada aḷa/aḷavu agree; Telugu alamu has a different labial extension from lāyu.',
        'The southern comparison and retained Telugu alamu favor V–ḷ. Initial l in Telugu lāyu and Konda/Pengo lap is innovative, but their different final formations prevent a single inferred vowel-quantity derivation.',
        '*aḷ-ay > *ḷāy > Telugu lāyu, with lateral merger; *aḷ-am > alamu retains order. Konda/Pengo *aḷ-p > lap/lab is one possible consonantal-formation displacement route; deriving them by shortening earlier *lāp requires independent evidence. Brahui halling retains a before l after initial h addition; h is not evidence for loss of the root vowel.',
        'Mix/measure d295 share similar shapes but are not merged just because their roots are homophonous. Brahui ha in and hatining are associated morphological comparisons in the source; they are not independently counted as three reflexes of this root. Exact origin of Brahui h and stem grades requires its local grammar. Konda/Pengo short vowels may test formative conditioning once their earlier suffix is recovered.',
        {'Telugu':('M','alamu|lāyu','Different retained and displaced verbal formations.'),
         'Tamil':('R','aḷai|aḷa|aḷavu|aḷāvu|aḷi','Low/high/long medial-vowel formations preserve initial order.'),
         'Malayalam':('R','aḷayuka','Original order.'),'Kannada':('R','aḷa|aḷavu|aḷavi','Original order.'),
         'Tulu':('R','aḷavuni|alavuni|alamuni|alejuni|allāvuni','Related derivatives/strengthening retain initial vowel.'),
         'Konda':('D','lap- (-t-)','Initial apical displacement; input formative and quantity history uncertain.'),
         'Pengo':('D','lap- (-t-)|lab- (lapt-)','Transitivity/tense contrast and short vowel preserved.'),
         'Brahui':('R','halling (present halē-, imper. haṛ̆ẖ, past halk-)','Initial h plus vowel-before-lateral; original ordering survives.')},
        references='DEDR 296; Brahui comparison cites Emeneau 1962 p.63',input_confidence='high',
        boundary='-ay and low-vowel labial formations independently visible; exact consonantal Konda/Pengo formative remains uncertain.')
    tokens('d296','Telugu',R='alamu',D='lāyu')

    add('d298','water, semiliquid','*aḷ-ak- / *aḷ-uk-?',
        'Ø','a','ḷ','a/u','VC-V-C','noun/adjective',
        'Tamil aḷakam and Kannada aḷaka/aḷḷaka support an initial vowel and lateral; the Telugu nasal correspondence is explicitly queried by DEDR.',
        'Under the cognacy, earlier V–ḷ is supported independently of Telugu. Telugu anuku remains vowel-first and therefore supplies no positive evidence of initial metathesis.',
        'DEDR suggests *aḷuku > *aṇuku > anuku, with lateral nasalization and loss of retroflexion. This is a conditional consonant-correspondence proposal; no unambiguous environment for ḷ>ṇ is established in this entry.',
        'Do not count the proposed nasal route as regular until other independently cognate cases establish its conditioning. Difference a/u in the second vowel and liquid-state semantics could reflect a genuine formation alternation or questionable cognacy; additional regional fluid adjectives would discriminate.',
        {'Telugu':('A','anuku','Questioned ḷ>ṇ>n history, not displacement.'),
         'Tamil':('R','aḷakam','Initial order retained.'),'Kannada':('R','aḷaka|aḷḷaka','Singleton/geminate variation without initial movement.')},
        references='DEDR 298',eligibility='cognacy-or-input-uncertain',input_confidence='medium',confidence='low',
        mechanism='Tentative lateral-to-nasal development; no initial metathesis',boundary='Exact segmentation and high-vowel counterpart uncertain.')

    add('d299','saltpan, salt marsh','*aḷ-am; compound *uppu + aḷam',
        'Ø','a','ḷ','a','VC-am as noninitial compound member','noun',
        'Tamil aḷam/uppaḷam and Malayalam aḷam/upp-aḷam independently attest the free base and salt compound. Telugu attests only upp-aḷamu in this group.',
        'Comparative free southern forms establish V–ḷ order of the second compound member. The Telugu compound does not itself supply a word-initial aḷ input at the time of sound change.',
        '*uppu + aḷam > upp-aḷamu retains the vowel–lateral sequence within a compound. A borrowed whole compound would give the same attested result; the Telugu retroflex lateral merits a source/history check.',
        'Exclude this from the decisive word-initial sound-law denominator unless the free base or date of composition can be established in Telugu. The compound is nevertheless a relevant boundary control. Native inheritance, preserved compound allomorph and borrowing remain alternatives; no loan is asserted merely from the ḷ spelling.',
        {'Telugu':('A','upp-aḷamu','Order retained inside compound; inherited versus borrowed status and historical word boundary uncertain.'),
         'Tamil':('R','aḷam|uppaḷam|aḷakkar','Free root and compounds retain order.'),
         'Malayalam':('R','aḷam|upp-aḷam','Free and compounded base retain order.')},
        references='DEDR 299',eligibility='noninitial-compound-control',input_confidence='high',
        boundary='Explicit independently recurring salt + saltpan compound; target sequence is internal in Telugu.')

    add('d301','love, desire, protect','*aḷ-i-; Telugu nasal-palatal extension unresolved',
        'Ø','a','ḷ','i','VC-i-C / VC-V-NC?','verb/noun',
        'Tamil aḷi and Malayalam aḷi/aḷikkuka independently establish high i; Kannada aḷipu/aḷupu supports related high-vowel labial formations. Telugu lā̃cu has a distinct nasal-palatal extension.',
        'Agreement of Tamil, Malayalam and Kannada favors earlier aḷi-. Telugu initial l is plausibly displaced, but neither its long ā nor the nasal-palatal suffix may be used to invent a low formative in the input.',
        'Conditional *aḷ-i-NC > *ḷaNC > lā̃cu would require later nasal loss with compensatory lengthening or a different independently reconstructed extension. A direct a+i > ā contraction conflicts with the short-vowel branch of K03 Rule 20. Without a matching derivative, the exact quantity history is unresolved.',
        'This is a candidate counterexample to an unrestricted prediction of short output after high-i input, not grounds for quietly changing i to a. Kota ayḷ mog twin children is semantically indirect; its glide/lateral order and relationship to unlinked ayḷ classificatory brother-in-law (f_cynufhnk3o6sm) need separate checking. The DEDR parse ayḷ with gloss mog twin children truncates the expression; Wolf’s source preserves the whole expression.',
        {'Telugu':('D','lā̃cu','Initial displacement plausible; lengthening/nasal derivation explicitly unresolved.'),
         'Tamil':('R','aḷi|aḷiyaṉ','Independent i-stem.'),'Malayalam':('R','aḷi|aḷikkuka','Independent i-stem and transitive extension.'),
         'Kannada':('R','aḷipu|aḷupu|aḷaviga','High-vowel and distinct low-vowel nominal extensions kept separate.'),
         'Kota':('A','ayḷ|ayḷ mog','Possible glide transposition but cognacy/morphology need direct source investigation.')},
        references='DEDR 301; Wolf Kota p.4 entry 3; compare K03 p.157 Rule 20',input_confidence='high',
        boundary='Independent root i, but no securely matched Telugu nasal-palatal derivative in the other languages.')

    add('d303','earthen vessel','*aḷ-Vk-; regional a/i variation',
        'Ø','a','ḷ','a/i','VC-V-C','noun',
        'Kannada aḷige/aḷage and Telugu alaki share vowel-first lateral and velar; the two-language comparison does not establish a unique formative vowel or deeper inheritance.',
        'Both languages retain V–lateral order; neither is assumed to be automatically conservative outside this comparison.',
        '*aḷVk > Kannada aḷige/aḷage and Telugu alaki, with lateral merger and final-vowel/velar differences. No initial movement is required.',
        'Narrow distribution leaves early borrowing versus inheritance open. The vowel variants must remain one variable-input class, not two classes defined by an expected metathesis outcome. An early attestation or additional cognate would strengthen eligibility.',
        {'Telugu':('R','alaki','Order retained.'),'Kannada':('R','aḷige|aḷage','Both vowel variants retained.')},
        references='DEDR 303 (DEDS 39)',eligibility='core-formation-uncertain',input_confidence='medium',
        boundary='No independently attested bare vessel root; formative segmentation tentative.')

    add('d304','prick, throb, be angry','*aḷ-Vk-; high-u and low-a variants',
        'Ø','a','ḷ','u/a','VC-V-C','verb/noun',
        'Kannada aḷuku/aḷaku and Telugu alugu/aluka independently show a vowel-first lateral/velar formation, but differ in the semantic focus prick versus take offence.',
        'Both languages agree on initial a before the lateral. This is a retained candidate with independently attested high vowel, not an exception explained by an invented root boundary.',
        '*aḷ-uk > Telugu alugu, Kannada aḷuku with later intervocalic voicing differences; Telugu aluvu may reflect additional velar lenition or an alternate extension. No initial metathesis is required.',
        'The physical-pain to displeasure semantic relation is plausible but does not independently prove cognacy. Kannada a/u variation prevents a unique V2 assignment. No evidence currently dates these particular extended stems before the Telugu change.',
        {'Telugu':('R','alugu|aluvu|aluka|alukuva','Vowel-first forms with velar/labial extension variation.'),
         'Kannada':('R','aḷuku|aḷaku','Independently attested high/low variants retain order.')},
        references='DEDR 304 (DEDS 40)',eligibility='core-formation-uncertain',input_confidence='medium',
        boundary='Velar extension visible in both languages; bare root and date of extension not established.')

    add('d305','sprinkle, scatter, bail water','*al/ḷ- with *-Vk and *-Vñc formations',
        'Ø','a','l/ḷ','unknown','VC-V-C / VC-C','verb',
        'Tamil alavu has plain l but is explicitly queried in DEDR p.29; Naikri aḷk has retroflex ḷ, and Kolami/Parji alk retain a medial lateral. Telugu aluku shares a velar formation; Kui/Kuvi/Manda forms have a nasal-palatal extension.',
        'Independent southern and Central Dravidian vowel-first forms favor older V–lateral order; initial liquids in Kui/Kuvi/Manda are innovative if the extended formations are cognate.',
        'Retained *al/ḷ-Vk > Telugu aluku, Kolami/Parji alk and Naikri aḷk. Conditional *aḷ-Vñc > lāñj/lanj/ṛanj accounts for initial displacement in eastern SCDr, but its vowel quantity and liquid identity require separately reconstructed regional changes.',
        'Kui lānja and lanj, Kuvi rānjali and ṛanj/lanjinai preserve real source/dialect quantity differences. Do not reconstruct a low formative solely for the long variants or a high formative for the short ones. DEDR refers to d3790 noḷ, raising an older initial-consonant/cognacy alternative to investigate.',
        {'Telugu':('R','aluku','Velar derivative retained.'),'Tamil':('A','alavu','Plain-l labial derivative, explicitly queried cognacy in original DEDR p.29.'),
         'Kui':('D','lānja (lānji-)|lanj','Initial displacement, unresolved short/long source variation.'),
         'Kuwi':('D','ṛanj|lanjinai|rānjali','Initial displacement, dialectal liquid/quantity differences.'),
         'Manda':('D','ṛanj','Short-vowel nasal-palatal derivative.'),
         'Kolami':('R','alk','Consonantal cluster retained.'),'Naikri':('R','aḷk','Retroflex lateral/velar cluster retained.'),
         'Parji':('R','alk','Medial cluster retained.')},
        references='DEDR 305 and cross-reference 3790',input_confidence='medium',
        boundary='Velar versus nasal-palatal formations independently distinguished; intervening proto-vowel unknown.')

    add('d314','know, understand, inquire','*aṯ-V-; regional *eṟ-uk/ŋk-',
        'Ø','a','ṯ','unknown','VC-V / VC-V-C','verb/noun',
        'Tamil aṟi, Malayalam aṟiyuka, Kannada aṟi and the independent K03 *aṯ-V reconstruction support a vowel-first alveolar root. Telugu eṟũgu has a distinct high-u velar/nasal extension; rare Tamil aruku supports investigating that formation but has a different rhotic spelling.',
        'Agreement of multiple southern languages and Brahui vowel-before-r favors V–alveolar order. Telugu eṟũgu is therefore a retained candidate, not a metathesized item concealed merely by initial e.',
        '*aṯ-V > southern aṟi; regional *a/eṟ-uk/ŋk > Telugu eṟũgu/eṟuka retains initial order while vowel and formative changes occur. Kota *ar-y > ayr is a separate glide/apical transposition; Brahui harrifing has initial h while preserving vowel-before-r.',
        'PSS83 p.229 explicitly lists the Telugu know form among exceptions to generalized apical metathesis. Unknown age and vowel of its exact extended input limit a fully specified law test, but are not proof that it was ineligible. Kolami erka is explicitly a Telugu loan. Badaga aḷi search has an unexplained lateral beside ari/aru forms and is not normalized to r.',
        {'Telugu':('R','eṟũgu|eṟuka|eṟukuva|eṟuku','Retained ordering in verb and associated nouns.'),
         'Tamil':('R','aṟi|aṟivu|aruku','Alveolar root with rare velar derivative/rhotic variant.'),
         'Malayalam':('R','aṟiyuka|aṟivu|aṟivikka','Original order retained.'),
         'Kannada':('R','aṟi (aṟid-, aṟit-)|aṟivu|aṟupu|aṟasu','Multiple independent extensions preserve root order.'),
         'Kota':('R','ayr- (arc-)|arv|arkym','No initial-vowel/apical exchange; separate y/r transposition in verb.'),
         'Toda':('R','aṟy- (aṟs-)','Vowel remains before apical.'),
         'Kodagu':('R','ari- (ariv-, ariñj-)|arivɨ|arɨp- (arɨpi-)','Order retained across morphology.'),
         'Tulu':('R','arike|arupu|aruhu','Vowel-first nominal formations.'),
         'Kolami':('B','erka','Explicit Telugu borrowing; no independent retention count.'),
         'Brahui':('R','harrifing','h plus vowel-before-r; local morphology needs its own account.'),
         'Badaga':('A','ari|aruvu|arivu|aḷi','r-bearing forms retained; search lateral and mixed ari gloss need source checking.'),
         'Koraga':('R','ade','Tappu search form preserves V–apical order with different consonant reflex.')},
        references='DEDR 314; PSS83 p.229; K03 reconstruction; Hockings & Pilot-Raichoor 1992 pp.28–29,38',
        input_confidence='high',eligibility='core-formation-uncertain',
        boundary='i-root and distinct u/velar expansion visible; exact regional proto-vowel and age of extension unresolved.')
    tokens('d314','Badaga',R='aruvu|arivu',A='ari|aḷi')

    add('d321','rock, stone','*aṯ-ay / regional *aṟ-ay; *aṟ-pp-? derivative',
        'Ø','a','ṯ','a','VC-ay / VC-C','noun',
        'Tamil aṟai, Kannada aṟe and Kota ar independently support a vowel-first alveolar and an ay formation; Toda aṟ corroborates the consonant class. Telugu ṟāyi/rāyi preserves two rhotic spellings.',
        'The shared SD I vowel-first forms favor *aṯ/ṟ-ay > ṟāy, not widespread insertion before an original *ṟāy. Kannada rāyi is explicitly borrowed from Telugu and cannot support an inherited Kannada innovation.',
        '*aṟ-ay > *ṟāy > Telugu ṟāyi > rāyi, with later ṟ/r merger. Short ṟappa small stone has a different strong labial extension; *aṟ-pp > ṟapp is plausible, but shortening an earlier long vowel is not uniquely supported.',
        'Badaga are is the lexical evidence; dozens of place names containing it are dependent derivatives and count as one family, with historical labels preserved. The precise *ṯ versus *ṟ reconstruction depends on the wider alveolar correspondence; modern Kannada is not assumed to preserve the proto manner of articulation.',
        {'Telugu':('D','ṟāyi|rāyi|ṟappa','Long ay formation and short geminate-labial derivative both displaced.'),
         'Tamil':('R','aṟai','Independent low-vowel ay input.'),
         'Kannada':('A','aṟe|rāyi','Native retention plus explicit Telugu loan.'),
         'Kota':('R','ar','Retained order after final-vowel loss.'),'Toda':('R','aṟ','Retained order.'),
         'Badaga':('R','are','Archaic flat-rock noun; attached toponyms not independent roots.')},
        references='DEDR 321; DEN1 1972 p.400 entry 271; Hockings & Pilot-Raichoor 1992 p.30',
        input_confidence='high',confidence='high',boundary='ay formation independently supported; separate pp formation has uncertain proto-vowel.')
    tokens('d321','Kannada',R='aṟe',B='rāyi')
