"""Fall apart, long river control, and the morphologically complex last-year comparison."""

def populate(add,tokens):
    add('d5411','open, split, go to pieces','*wir-i; *wir-i-nk/nkk; proposed *wir-il',
        'w','i','r','i/u/a','CVC-i / CVC-i-NK / CVC-i-l?','verb/noun',
        'Tamil viri, Malayalam viriyuka, Kannada biri and Konda viris/virs independently establish w-i-r and high-vowel formations. The extra lateral in Telugu vrīlu requires a derivative, and K61 explicitly says the proposed -il/-ul is unattested elsewhere.',
        'Many branches agree on w-V-r before Telugu/Kui/Kuvi vr-. Telugu virugu/viriyu retains order alongside vrīlu. An earlier *vir-il is a published immediate antecedent, not an independently verified Proto-Dravidian word.',
        'Conditional *wir-il > *wrīl > vrīlu gives the long displaced Telugu form if the suffix is established. *wir-i-nk > *wriŋk gives Kui vringa, while labial vrīva has its own quantity/formative history. Gondi rīk can follow *wrīk with w loss; source suffix comparison remains needed. Telugu viccu/vippu/vikku permits direct medial assimilation, independently paralleled by Kannada biccu and Tulu biccuni.',
        'Do not claim deterministic output conditioning from a suffix reconstructed only to yield ī. The broader displacement interpretation is stronger than the exact vowel/derivative chronology. Gondi rīk could involve regional borrowing or a distinct velar derivative; retain medium confidence. Kui birasakali is unshifted-looking but expressive/deverbal formation may differ. Sanskrit aravinda comparison concerns a compound and adds no independent root vote.',
        {'Tamil':('R','viri|virivu|virippu|viriyal|virical','Full high-vowel root and extensions.'),'Malayalam':('R','viri|viriyuka|virikka|virittuka|virivu|viriccal|virippu','Retained high-vowel formations.'),'Kannada':('O','biri|biriku|biruku|biruvu|biravu|bircu|biccu|biccata|biccaṛ̆ike|biccaṛ̆isu|are-viri|are-biri','Retained apical versus medial assimilation and compounds.'),'Kodagu':('R','biri- (biriv-, biriñj-)','Retained root and paradigm.'),'Toda':('R','pɨry- (pɨrs-)|pɨry-|pɨrs-','Initial p reflex, apical remains after vowel.'),'Tulu':('O','biriyuni|birkuni|birkɛ|beraŋka|berakaṇɯ|berakaṇṇi|beraŋkaṇṇi|beraŋkaṇṇu|biccuni|biccāvuni|biccāṭa|bicca|biccelɯ','Retained apical and medial assimilation.'),'Telugu':('M','viri|viriyu|virugu|viṟugu|virucu|viṟucu|virupu|viṟupu|virivi|viriviḍi|viṟigi|araviri|vrīlu|viccu|vijju|vippu|vikku','Retained root/velar, displaced lateral derivative and opaque medially assimilated forms.'),'Gondi':('M','viri|viriˀ|viriyānā|virih|virp|rīk|rīkānā','Full forms and first-member-loss velar scatter.'),'Konda':('R','viris- (-t-)|virs- (-t-)|viraŋ māl- (-it-)','Full/syncopated initial order retained.'),'Kui':('M','vrīva (vrīt-)|vringa (vringi-)|vripka (&lt; vrik-p-; vrikt-)|bringi brangi|bringi brangi inba|birasakali','Displaced stems/expressive variants versus unshifted-looking dispersed form.'),'Kuwi':('M','vrik|brīali|vir|vij- (-it-)','Displaced and retained stems, different formations.'),'Pengo':('R','vir- (-t-)|virpa- (-t-)','Retained intransitive/transitive order.'),'Manda':('R','virā','Retained verb.'),'Parji':('R','virŋg|virkip- (virkit-)','Retained initial order despite nasal/velar clusters.'),'Kurux':('R','berrnā (birryā)','Retained apical after vowel; gemination/grade differs.')},
        input_confidence='high for root; low for exact Telugu -il suffix',references='DEDR 5411; K61 p.67 §1.156 explicitly unattested derivative (prior verified reading); DEN1 1972 p.415 entry4438',boundary='High-vowel root independently attested; lateral derivative remains a hypothesis and cannot verify its own prediction.')
    tokens('d5411','Kannada',R='biri|biriku|biruku|biruvu|biravu|bircu|are-viri|are-biri',O='biccu|biccata|biccaṛ̆ike|biccaṛ̆isu')
    tokens('d5411','Tulu',R='biriyuni|birkuni|birkɛ|beraŋka|berakaṇɯ|berakaṇṇi|beraŋkaṇṇi|beraŋkaṇṇu',O='biccuni|biccāvuni|biccāṭa|bicca|biccelɯ')
    tokens('d5411','Telugu',R='viri|viriyu|virugu|viṟugu|virucu|viṟucu|virupu|viṟupu|virivi|viriviḍi|viṟigi|araviri',D='vrīlu',O='viccu|vijju|vippu|vikku')
    tokens('d5411','Gondi',R='viri|viriˀ|viriyānā|virih|virp',D='rīk|rīkānā')
    tokens('d5411','Kui',R='birasakali',D='vrīva (vrīt-)|vringa (vringi-)|vripka (&lt; vrik-p-; vrikt-)|bringi brangi|bringi brangi inba')
    tokens('d5411','Kuwi',R='vir|vij- (-it-)',D='vrik|brīali')

    add('d5159','river, water, thirst','*yĀṯ-u, oblique *yĀṯṯ-; regional *ēṯ',
        'y/zero','ā/ē','ṟ/ṯ','u/zero','(C)VVC / (C)VVCC','noun',
        'Tamil yāṟu/āṟu with oblique ṟṟ, Malayalam āṟu, Telugu ēṟu/ēṭi and Gondi yēr/yēt independently establish long quantity and an apical paradigm. The difference ā/ē is linked to the special initial-y vowel correspondence, not to metathesis.',
        'Long vowel precedes the apical across branches. Loss of initial y in southern forms does not move the apical, and eastern j/y/z/s reflexes remain after the vowel.',
        '*yĀṯu > āṟu/ēṟu retains order after initial glide loss and regional vowel developments. Oblique fortition gives Tamil āṟṟu and Telugu ēṭi. Kui ēju/ēsu and Pengo ēz/ēs show apical changes without initial displacement.',
        'A strong long-vowel control across Telugu and eastern languages. Tulu tārɯ/sārɯ/hārɯ add or preserve initial material requiring separate local explanation, but final r stays postvocalic. Gondi and central big-river compounds combine this root with per/bere big; do not screen that compound-initial per as the river input. Badaga proper names are not independent basic reflexes. Imported goat reconstruction is erroneous metadata.',
        {'Tamil':('R','yāṟu|āṟu','Long apical root with oblique fortition.'),'Malayalam':('R','āṟu','Same long input.'),'Kota':('R','peyv-e·r|te·lvie·r','Long river element within compounds; source notes alternative bank comparison.'),'Tulu':('R','ārɯ|tārɯ|hārɯ|sārɯ','Initial variants, final apical remains postvocalic.'),'Telugu':('R','ēṟu ( ēṭi','Long root and genitive stop alternation.'),'Gondi':('R','yēr (yēt-)|ēr (ēt-, <i>pl.</i> ēhk)|ēṛ|yeha-kkorr|yeh-gatā|atta yēr|aṭ-yār|berel|beriaṛ|etk','Long water root and its compounds/obliques; some gloss inheritance errors.'),'Konda':('R','ēṟ (obl ēR|ēṟu (obl ēR|ēRki','Long apical root and thirst derivative.'),'Kui':('R','ēju|ēsu|ēski','Long root with medial j/s.'),'Kuwi':('R','ēyu|ēyu (construed vitʰ pl. verb)|ēyū (construed vitʰ pl. verb)|ēski','Long root and plural agreement/derivative variation.'),'Pengo':('R','ēz|ēz ība|ēski|ēzuŋ (variant form ofēzused in certain combinations, e.g.ēs orliotter [lit. vater-rat])|ēs (variant form ofēzused in certain combinations, e.g.ēs orliotter [lit. vater-rat])','Long root and contextual variants.'),'Manda':('R','ey|ehki','Local short notation/quantity requires source check; initial vowel still precedes reflex.'),'Parji':('R','pered','Big-river compound, not primitive short per root.'),'Gadaba':('R','ber bereṭ','Big-river compound.')},
        input_confidence='high',references='DEDR 5159; K03 initial *yĀ and apical-oblique correspondence',quantity='long',boundary='Free water root versus oblique/number and big-river compounds; compound first member excluded from root screen.')

    add('d5153','year; this/last/next year compounds','*yĀṇṭ-u; K80 *nīt-yāṇṭ > *nir-ēṇḍ/*nir-ōṇḍ',
        'y/zero; compound n','ā/ē/ō; compound i','ṇṭ; compound r','compound boundary','(C)VVNC / CVC#VVNC','noun/adverb',
        'Tamil yāṇṭu/āṇṭu, Kodagu āṇḍɨ and Telugu ēṇḍu independently establish the long year root. Last-year r-initial forms contain additional material; the year root itself has no r that could be simply transposed to its beginning.',
        'K80 p.498 item18 proposes completed+year *nīt-yāṇṭ with regional nir-ēṇḍ/nir-ōṇḍ and quotes Konda nṛund. This supports a compound-based comparison, but the exact full compound and shortening are not independently attested in the present group.',
        'Bare *yĀṇṭ > āṇṭ/ēṇḍ/ōnḍ retains order after glide/vowel changes. Conditional *nir#ōṇḍ > *nrōṇḍ > ṛōnḍ and lowered ṛānḍ gives the last-year forms; merger, shortening and resegmentation at the compound boundary must be separately justified. Pengo/Manda ṛāṭihiŋ has further suffix and nasal-loss history.',
        'Do not count last-year as ordinary metathesis of the bare year root or use its morphology-free head to test a vowel rule. Kui ṛānḍu last year versus ṛōnḍu previous year preserve a meaning distinction, potentially analogical rather than free phonetic variation. K80 prints Kui twice where the second set appears to be Kuvi; DEDR independently confirms Kuvi r-initial forms. Corpus-wide Konda gloss search last year returned zero; K80 nṛund is a source-only observation. Complete-root component remains to be independently linked.',
        {'Tamil':('R','yāṇṭu|āṇṭu|āṭṭai|āṭṭāṇṭu|kīṛ̆-āṇṭai-ccikai','Long bare root, distributive and last-year compound.'),'Malayalam':('R','āṇṭu|kīṛ̆-āṇṭai','Long root and below/year compound.'),'Kota':('R','o·r a·ṛ|ōr āṛ|i·r a·ṛ','Long year in numeral compounds.'),'Toda':('R','vɨ·r o·ṛ|i·r o·ṛ|vɨ̄r ōṛ|īr ōṛ|ko·ḍ|kōḍ','Long year; last-year compound uses below, not automatically eastern completed compound.'),'Kannada':('R','ēḍu','Long year root.'),'Kodagu':('R','a·ṇḍɨ','Long year root.'),'Tulu':('R','iyyoḍu|mūvoḍu','Deictic/compound year forms.'),'Telugu':('R','ē̃ḍu|ē̃ḍādi|ē̃ḍuḍi|ēṇṭēṭa','Long year root with derivative/compound morphology.'),'OTelugu':('R','ēṇḍu|ēṇṭabaḍi','Long historical year/root compound.'),'Gondi':('R','ēnḍ|ēṇḍ|yēḍa|yēnḍ|yeṇṛ|īyenḍ|iyēnḍ|iyode|hayēnḍ|hēnḍ','Year root and deictic compounds, no automatic r-metathesis.'),'Konda':('A','ēṇḍad|ōnḍkaṛa|ōṭkaṛa|iyoṇḍ|nṛund','Bare/deictic forms retained; completed-year source-only cluster needs compound reconstruction.'),'Kui':('A','ōnḍu|ṛānḍu|ṛōnḍu|vāṛonḍi','Bare year retained; r-initial last/previous-year and next-year compound distinct.'),'Kuwi':('A','īyona|vāṇona|ṛānḍu|ṛāṇḍu|rānḍu','Deictic year versus uncertain completed-year formation.'),'Pengo':('A','iyonḍiŋ|ṛāṭihiŋ','This-year and last-year are different compounds.'),'Manda':('A','ī̃yuṭ|ṛāṭihiŋ','Same.'),'Kolami':('R','i· e·ḍ|a· e·ḍ','Deictic year compounds retain long root.'),'Naikri':('R','iyeṛ','This-year formation.'),'Naiki':('R','iyānḍ','Same.'),'Parji':('R','iyaḍ','Same.'),'Gadaba':('R','iyānḍ','Same.'),'markodi':('R','āṇdi|āṇḍŭ','Long year root.')},
        input_confidence='high for year; low for exact completed-year compound stages',references='K80 p.498 item18 directly visually checked; DEDR 5153',eligibility='compound-process-separate',quantity='long bare root; compound first-member quantity unresolved',boundary='Completed + year and deictic + year must be independently segmented; bare year supplies no initial rhotic.',mechanism='Bare root retention; proposed compound metathesis requires separate denominator.')
    tokens('d5153','Konda',R='ēṇḍad|ōnḍkaṛa|ōṭkaṛa|iyoṇḍ',A='nṛund')
    tokens('d5153','Kui',R='ōnḍu',A='ṛānḍu|ṛōnḍu|vāṛonḍi')
    tokens('d5153','Kuwi',R='īyona|vāṇona',A='ṛānḍu|ṛāṇḍu|rānḍu')
    tokens('d5153','Pengo',R='iyonḍiŋ',A='ṛāṭihiŋ')
    tokens('d5153','Manda',R='ī̃yuṭ',A='ṛāṭihiŋ')
