"""Remaining a-initial liquid comparisons, including lexical/compound controls."""

def populate(add,tokens):
    add('d203','nuptial gift','regional *araṇa-; internal segmentation unknown',
        'Ø','a','r','a','VCVCV, segmentation uncertain','noun',
        'Kannada araṇa and Telugu araṇamu independently agree on the whole stem. DEDR only tentatively compares grace d227, so a bare *ar plus a formative is not established.',
        'Both attested languages have vowel-first order; their agreement supports the regional stem, while inheritance versus early borrowing is unresolved.',
        'Regional araṇa > Kannada araṇa and Telugu araṇamu by final nominal adaptation. No initial displacement is required.',
        'The possible relationship to aruḷ grace would require a lateral/nasal correspondence and a different stem vowel. Do not use that uncertain comparison to supply a decisive reconstructed sound-law input. The cultural gift term needs earlier textual and contact evidence.',
        {'Telugu':('R','araṇamu','Whole stem retains initial order; historical eligibility uncertain.'),
         'Kannada':('R','araṇa','Independent regional attestation, no displacement.')},
        references='DEDR 203 and tentative comparison 227',eligibility='core-formation-uncertain',input_confidence='medium',
        boundary='No independently demonstrated root/formative boundary.')

    add('d211','trunk, post, pillar','*ar-ay / *ar-aḷ-?; Telugu -ḍ extension uncertain',
        'Ø','a','r','a','VC-ay / VC-a-C','noun',
        'Tamil arai trunk and Kannada araḷe post independently support initial ar- and low vowel; Telugu rāḍu and Kolami rāḍ/rāl have different final consonants. The database initial *rāḍ head is not automatically the earlier comparative input.',
        'A low-vowel *ara- regional input is favored by the Tamil/Kannada comparison and the broader displacement correspondence, but the final y/ḷ/ḍ variation weakens a fully specified reconstruction.',
        'Conditional *ar-aḌ > *rāḌ > Telugu rāḍu, or *aray plus a later ḍ-bearing nominal formation. The exact final consonant and morphological sequence remain unknown. Gondi rāyi and Kolami rāḍ/rāl may share the innovation or be loans from Telugu.',
        'Do not reconstruct final *ḍ solely because Telugu has it. Trunk/post/peg semantics are compatible, but culture-word diffusion is a real competing explanation for the regional r-initial forms. A dated donor form, a wider pattern of Kolami ḍ/l variation, or a matching southern ḍ-bearing derivative would discriminate.',
        {'Telugu':('A','rāḍu','Probable initial displacement but exact reconstruction/cognacy not decisive.'),
         'Tamil':('R','arai','Vowel-first trunk noun.'),'Kannada':('R','araḷe','Vowel-first post noun with different final lateral.'),
         'Gondi':('A','rāyi|rayee','Innovated-looking post noun; donor and final-consonant history unresolved.'),
         'Kolami':('A','rāḍ|rāl','Same post/peg semantic field; contact and local consonant variation unresolved.')},
        references='DEDR 211; DEN1 1972 p.400 entry 174',input_confidence='medium',confidence='low',
        eligibility='cognacy-or-input-uncertain',boundary='Root versus nominal extensions not uniquely reconstructed.')

    add('d215','rice, rice cake','*ari; *ar-i-ci / *ar-ki- formations',
        'Ø','a','r','i','VC-i-C / VC-C','noun',
        'Tamil ari/arici, Malayalam ari and Tulu ari/argi independently attest vowel-first r. Kannada/Kodagu akki and Kota/Toda forms require medial cluster histories; Telugu arise is a rice-food derivative.',
        'Bare ari and cluster-bearing argi favor earlier V–r order, making akki explainable by medial assimilation rather than apical promotion.',
        'Conditional *ar-ki > *arki > akki in Kannada/Kodagu, beside preserved Tulu argi; Tamil arici has a palatal formation or different development. Telugu arise retains ar-; mapping its s directly onto the whole arici formation remains a hypothesis requiring source history.',
        'Rice terminology has a wider contact history, but this entry alone does not decide ultimate origin. Telugu attests a particular food name, not the basic rice word: late culinary borrowing could make it ineligible for an inherited sound law. Toda nel-compounds and Badaga dish names are derivatives, not additional roots. A Tulu bibliographic fragment is not a lexical record.',
        {'Telugu':('R','arise','Initial order retained in rice-cake name; derivative/contact chronology uncertain.'),
         'Tamil':('R','ari|arici','Root and extended grain noun retain order.'),'Malayalam':('R','ari','Vowel-first rice noun.'),
         'OMal':('R','arici','Historical extended grain noun; source Kauṭ Epic.'),
         'Tulu':('O','ari|argi|akki','Retained r forms plus compound-bound akki, possible assimilation or contact.'),
         'Kannada':('O','akki','Medial-cluster assimilation hypothesis, no initial movement.'),
         'Kodagu':('O','akki','Same type of cluster simplification.'),'Kota':('O','aky','Apical absent after medial developments; no initial relocation.'),
         'Toda':('O','ašky|aśky','Medial cluster outcome; initial vowel survives.'),
         'Badaga':('O','akki','One grain root; dish and plant compounds do not increase denominator.'),
         'markodi':('R','ari','Vowel-first grain word.')},
        references='DEDR 215; comparative origin beyond the regional input unresolved',eligibility='core-formation-uncertain',
        input_confidence='medium',mechanism='Retention and medial assimilation; exact velar/palatal formation history unresolved',
        boundary='Bare ari versus extended grain forms independently visible; Telugu food derivative not assumed to be primordial.')
    tokens('d215','Tulu',R='ari|argi',O='akki')

    add('d241','confusion, tumult','alaŋkōlam / allakallōla; complex or contaminated stem',
        'Ø','a','l','a','complex lexical formation, single/geminate variants','noun',
        'Tamil/Malayalam alaŋkōlam and Kannada/Telugu allakallōla share a complex stem. DEDR compares both shake alaŋku d240 and Sanskrit kallola wave; this is not secure evidence for a uniform simple proto-root.',
        'All forms preserve initial a. The mixed shape can reflect lexical remodeling or a compound/echo formation rather than any displacement of the initial lateral.',
        'A shake-root formation associated with alaŋku may have converged with kallola wave; gemination and the repeated all-/kall- shape require lexical/morphological history. The evidence does not uniquely order those developments.',
        'Exclude this opaque complex formation from the decisive singleton-root denominator. It remains relevant to how analogy/borrowing can create apparent controls. Tulu allambra has a different final cluster and cannot be generated by simply swapping a and l.',
        {'Telugu':('A','allakallōlamu','Retained initial vowel, complex formation and Sanskrit association unresolved.'),
         'Tamil':('A','alaŋkōlam','Related complex stem, historical segmentation uncertain.'),
         'Malayalam':('A','alaŋkōlam','Same complex cultural/abstract term.'),
         'Kannada':('A','allakallōla|allōlakallōla','Repeated/echo-like variants, no initial apical promotion.'),
         'Tulu':('A','allambra','Different final morphology; no unique comparative derivation.')},
        references='DEDR 241 and cross-reference 240; Sanskrit kallola comparison; CDIAL 2955',
        eligibility='complex-or-contact-input-uncertain',c2_structure='singleton-and-geminate-formations',input_confidence='low',confidence='low',
        boundary='Possible compound/echo formation; components and chronology not independently established.')

    add('d242','pulse, cowpea','regional alasand-/alasaṇḍ-; ultimate origin undetermined',
        'Ø','a','l','a','VCVCVNC, lexical crop name','noun',
        'Malayalam alaśaṇṭa/alasāndram, Kannada alasande and Telugu alacandalu support a regional vowel-first crop name. DEDR compares Prakrit ālisaṃdaga/ālisaṃdaya and Marathi aḷasudā, so deep Dravidian inheritance is not established.',
        'Tulu brahmin alasaṇḍɛ and non-brahmin lattaṇḍɛ/lattanɛ supply a source-labeled initial-loss contrast. Other Dravidian forms agree on initial a, but this does not settle the ultimate loan direction.',
        'Tulu alasaṇḍ- > alataṇḍ- (attested B-K variant) > lattaṇḍ-/lattan- is an illustrative sequence of s/t change, initial loss, strengthening and cluster simplification; exact ordering and variant ancestry are not proven. Telugu alacand-/alasand- keeps initial al-.',
        'Five Kannada forms were misassigned Malayalam by the parser; corrected only in research. Botanical Latin is excluded. Tulu sociolinguistic labels are preserved and not assumed to represent successive historical periods. An inherited sound-law denominator would require an independently dated Dravidian entry of the crop name, so this is a contact/lexical control.',
        {'Telugu':('R','alacandalu|alasandelu|alasandiyalu','All recorded variants retain initial order.'),
         'Malayalam':('R','alaśaṇṭa|alasāndram','Only these two source forms are Malayalam.'),
         'Kannada':('R','alasandi|alasande|halasandi|halasande|alasandige','Research-corrected language; h variants preserve vowel before l.'),
         'Tulu':('O','alasaṇḍɛ|alataṇḍɛ|lattaṇḍɛ|lattanɛ','Retained brahmin/source forms versus non-brahmin initial-loss variants.')},
        references='DEDR 242 p.23, original language headings inspected; B-K/Männer/BRR source labels',
        eligibility='complex-or-contact-input-uncertain',input_confidence='medium',
        mechanism='Regional lexical diffusion and local aphaeresis/assimilation candidate',boundary='No independently established bare al- root; entire crop-name history matters.')
    tokens('d242','Tulu',R='alasaṇḍɛ|alataṇḍɛ',O='lattaṇḍɛ|lattanɛ')

    add('d256','waterlily','*alli (geminate lateral)',
        'Ø','a','l','i','VCCV','noun',
        'Tamil, Malayalam, Tulu and Telugu independently attest alli with ll. The singleton *ali reconstruction displayed in an imported record is not supported by a singleton reflex in this comparison.',
        'The four-language agreement favors earlier geminate ll for the shared lexical input; there is no reason to delete one l merely to place this root in the metathesis-eligible class.',
        '*alli > alli across the reviewed languages; Tulu allige adds a nominal extension. No apical promotion occurs.',
        'Tamil pulli is explicitly contrasted stamen vocabulary, not another reflex of alli; the Latin plant name is a gloss, not a Tamil form. Ultimate plant-name borrowing cannot be excluded, but the independent gemination makes this a useful structural control without relying on outcome.',
        {'Telugu':('R','alli','Geminate plant name retained.'),'Tamil':('R','alli','Geminate input independently supported.'),
         'Malayalam':('R','alli','Geminate input supported.'),'Tulu':('R','alli|allige','Base and extension retain ll.')},
        references='DEDR 256 p.24, original entry inspected',c2_structure='geminate',eligibility='geminate-control',
        input_confidence='high',boundary='Root-internal gemination supported across languages, not inferred from Telugu alone.')

    add('d257','iron-wood tree','*al/alli; compound *ali-mar',
        'Ø','a','l','i/a','VCV / VCCV + tree noun','noun',
        'Tamil/Telugu alli and Kannada alle have ll, but Tulu alimarɯ/alimārɯ and Kannada alamar show singleton l in tree compounds. Unlike d256, whole-family gemination is not secure.',
        'All languages retain an initial vowel before l. Compound forms establish singleton evidence independently, without implying that bare and compounded variants had identical historical shapes.',
        'A plant base al/ali plus mar tree gives alimar-/alamar- compounds, beside strengthened alli/alle. Kodagu uḍɨt-ale has the plant component noninitial. No initial promotion is observed.',
        'Roxburgh-mediated Telugu attestation and regional plant-name diffusion merit a provenance check. Do not merge with waterlily d256 solely because alli is homophonous, or use the tree compounds as evidence that waterlily had singleton l. Botanical Memecylon has been separated from the Tulu form in a research-only source observation.',
        {'Telugu':('R','alli','Geminate bare plant name, Brown quoting Roxburgh.'),'Tamil':('R','alli','Geminate bare plant name.'),
         'Kannada':('R','alle|alamar','Bare geminate and singleton tree compound.'),
         'Tulu':('R','alimarɯ|alimārɯ','Singleton tree compounds; second form recovered from appended Latin gloss.'),
         'Kodagu':('R','uḍɨt-ale','Plant component inside compound, not a word-initial law test.')},
        references='DEDR 257 p.24, original entry inspected',c2_structure='singleton-and-geminate-formations',
        eligibility='complex-or-contact-input-uncertain',input_confidence='medium',boundary='Tree component -mar independently identifiable; bare-base strengthening and date unresolved.')

    add('d291','strength, size, ability','*aḷ-; *aḷ-av-; long-root alternative *āḷ?',
        'Ø','a','ḷ','a','VC-a-C','noun/adjective',
        'Tamil aḷ strength and Kannada aḷa/aḷavu/aḷavi support short a and postvocalic lateral independently. Telugu alavi/alavu retain exactly the kind of low-vowel expansion compared in measure d295.',
        'Independent southern vowel-first forms and Konda alvi favor *aḷav > lāv. The long Konda āl is a retained-order quantity variant, not evidence of an original initial lā-.',
        '*aḷ-av > *ḷāv > Telugu lāvu, alongside retained alavi/alavu. Gondi lāv, Kolami la·v and Parji lāv could reflect the same historical development or spread of the Telugu adjective/noun; local donor diagnostics are needed.',
        'Treat d291 and d295 as one conservative root family: Kannada/Telugu repeat alavi/alavu and lāvu with overlapping size, power and capacity meanings. This does not assert that every measurement-verb suffix was already part of one undifferentiated proto-lexeme. DEDR’s comparison with long-root d399 is tentative and should be tested as a quantity alternative. Konda lāvu much resembles the Telugu broad adjective and may be borrowed.',
        {'Telugu':('M','alavi|alavu|lāvu','Retained and displaced strength/size formations; same contrast as measure family.'),
         'Tamil':('R','aḷ','Short free root retained.'),'Kannada':('R','aḷa|aḷavu|aḷavi|alavu','Low-vowel extensions and lateral variation retained.'),
         'Gondi':('A','lāv','Possible Telugu contact; independent inherited displacement not established.'),
         'Konda':('A','alvi|āl|lāvu','Retained energy/endurance forms beside possible loan much.'),
         'Kolami':('A','la·v','Fat adjective in Telugu contact zone; chronology/donor unresolved.'),
         'Parji':('A','lāv','Strength noun could be inherited or borrowed from Telugu.')},
        family='d291+d295',references='DEDR 291,295; tentative cross-reference 399',input_confidence='high',
        boundary='Bare strength root plus independent -av formation; root-family collapse based on repeated forms and intersecting meanings.')
    tokens('d291','Telugu',R='alavi|alavu',D='lāvu')
    tokens('d291','Konda',R='alvi|āl',A='lāvu')

    add('d306','fear, start, be frightened','*aḷ-uk(k)-, beside *aḷ-ar/ik-',
        'Ø','a','ḷ','u','VC-u-C(C)','verb/noun',
        'Tamil aḷukku, Malayalam aḷukkuka, Kannada aḷuku and Telugu aluku independently establish high u following a singleton lateral. The database *nari jackal head and reconstruction record are unrelated contamination, excluded from historical inference.',
        'Vowel-before-lateral order agrees across the southern languages and Telugu. Tulu aḷkuni shows medial syncope without initial promotion.',
        '*aḷ-uk(k) > Tamil aḷukku, Kannada aḷuku, Telugu aluku; *aḷ-uk > Tulu aḷk-/alk-. Kannada -ar and -ik extensions and local l/ḷ variation are separate developments.',
        'Fear d306 and anger/pricking d304 overlap in Kannada aḷaku/aḷuku and Telugu aluku with related affective semantics; conservative sensitivity should collapse them. Retention cannot be explained by a root geminate: the geminate is the later velar, while the target lateral is singleton. Telugu aḷuku = aluku is an editorial equivalence string, not a third lexical root.',
        {'Telugu':('R','aluku|aḷukari|aḷuku = aluku','Original sequence retained; dictionary equivalence preserved as source metadata.'),
         'Tamil':('R','aḷukku','Independent high-u formation.'),'Malayalam':('R','aḷukkuka|aḷukkam|aḷarkka','High-u core and different -ar extension.'),
         'Kannada':('R','aḷuku|aḷaku|aḷiku|aḷku|aḷkaṟ','Vowel/syncope/formative variation with initial order retained.'),
         'Tulu':('R','alkuni|aḷkuni|alkɯ','Medial syncope; initial vowel survives.')},
        references='DEDR 306 p.29; erroneous nari head excluded by direct source comparison',input_confidence='high',
        boundary='High-vowel velar derivative independently supported in four languages; lateral itself remains singleton.')

    add('d307','enclose, cover, spread','*aḷ-V- with *-r, *-m and nasal-palatal extensions',
        'Ø','a','ḷ','unknown','VC-V-C','verb/noun',
        'Kannada aḷur and Telugu alamu independently agree on initial aḷ/al but have different high versus low medial vowels and final formatives. Konda almi supplies vowel-first lateral plus labial consonant.',
        'Vowel-first ordering in Kannada and Konda supports the retained Telugu alamu as an earlier-type stem; Telugu lā̃ncu/lā̃pu are innovated formations under the cognacy.',
        'Conditional *aḷ-a-NC > *ḷāNC > lā̃ncu, with nasal developments, and related noun lā̃pu. An alternative high formative followed by nasal loss/lengthening remains possible. The velar/palatal versus labial morphology must be reconstructed separately from initial displacement.',
        'The source gives lā̃ncu as intransitive and lā̃pu as its noun; the latter was absent from the parsed group and is explicitly supplemented from DEDR p.29. Kannada aḷur does not independently prove the low vowel required by a simple long-output derivation. Compare mix/seize d296 alamu as a family-overlap sensitivity; the evidence does not warrant silently merging desire d301 merely because its lā̃cu looks similar.',
        {'Telugu':('M','alamu|lā̃ncu|lā̃pu','Retained and displaced formations; source-only noun linked to existing entry.'),
         'Kannada':('R','aḷur|aḷurke','Different -ur formation retains order.'),
         'Konda':('R','almi- (-t-)','Labial formation with medial syncope, no initial displacement.')},
        references='DEDR 307 p.29, original source checked',input_confidence='medium',
        boundary='Different final r/m/nasal-palatal formations independently visible; a unique shared suffix vowel is not recovered.')
    tokens('d307','Telugu',R='alamu',D='lā̃ncu|lā̃pu')

    add('d308','hole, cave, burrow','*aḷ-ay; labial and velar formations of uncertain relationship',
        'Ø','a','ḷ','a','VC-ay / VC-V-C','noun',
        'Tamil aḷai, Malayalam aḷa and Kota aḷ independently support vowel-first *aḷay. Malayalam aḷḷāppu and Kurux alap add labial morphology; Telugu lā̃ga has a different velar/nasal extension. The displayed **aḷVppV head must not erase this mismatch.',
        'The southern vowel-first base supports innovative initial l in Telugu, but the exact velar formation is not recovered solely from Telugu. Kurux lātā has different final morphology from alap and cannot automatically be called the same metathesis.',
        'Conditional *aḷ-aŋk > *ḷāŋk > Telugu lā̃ga requires an unattested but morphologically plausible velar extension; *aḷay plus a later noun suffix is an alternative. Kurux alap > lātā cannot follow by initial a loss alone because p/t differs. Badaga ae can follow lateral loss in *aḷay without initial promotion.',
        'PSS83 p.56 example63 proposes moving Toda oḷb to the concealment family (old DED853, current d1015), because a before ay should not yield Toda o. That objection depends on comparing the identical ay formation; an independently justified different labial derivative could weaken it. Keep Toda cognacy ambiguous. The Kurub. aḷe source is mislabeled Malayalam and its precise lect is unresolved; neither it nor the parsed heading is counted as Malayalam evidence.',
        {'Telugu':('D','lā̃ga','Initial displacement plausible; the full velar/nasal derivation is not secure.'),
         'Tamil':('R','aḷai','Independent low-vowel ay formation.'),'Malayalam':('R','aḷa|aḷḷāppu','Bare/strong labial formations retain order; exclude mislabeled Kurub. record.'),
         'Kota':('R','aḷ','Retained order after final-vowel loss.'),'Toda':('A','oḷb','PSS83 proposes concealment-root alternative based on vowel correspondence.'),
         'Kurux':('A','alap|lātā','Retained labial form; different t-bearing initial-liquid form has unresolved cognacy/morphology.'),
         'Badaga':('O','ae','Lateral loss/contraction candidate; no positive evidence of initial promotion.')},
        references='DEDR 308 p.29; PSS83 p.56 example63; comparison d1015',input_confidence='high',
        boundary='ay input secure for southern bare noun, not for every labial/velar derivative.')
    tokens('d308','Kurux',R='alap',A='lātā')

    add('d310','palm of hand, sole of foot','*aṟ-a(n) + hand/foot compound',
        'Ø','a','ṯ','a','VCV(N) + body-part noun','noun',
        'Tamil aṟaŋ-kai, Telugu aṟa-cēyi/aṟa-kālu and Kolami ārankei/árungkei independently attest an aṟ/an-bearing first component in body-part compounds. Its precise sense and nasal segmentation are unresolved.',
        'All source forms retain a vowel before the apical. These are initial compound members, so the compound boundary is after the candidate sequence rather than before it as in saltpan d299.',
        '*aṟa(n)+kai gives the compared palm compounds, with hand replaced by Telugu cēyi and foot kālu in parallel formations. Kolami length and n/ŋ variants have separate source histories; no initial apical displacement occurs.',
        'The source explicitly says ārankei has n, not ŋ. The parser split that editorial correction into fragments, including a spurious standalone ŋ. Do not count the compound as a bare free root; equally, a following compound boundary alone cannot explain its retention, since anvil d86 changes in that position. Possible connection to half/inner/partition vocabulary needs independent semantic evidence.',
        {'Telugu':('R','aṟa-cēyi|aṟa-kālu','Initial first component retained in parallel hand/foot compounds.'),
         'Tamil':('R','aṟaŋ-kai','Related first component with nasal.'),
         'Kolami':('R','ārankei|árungkei','Two source spellings; first recovered from the editorial fragment.')},
        references='DEDR 310 p.29 (DEDS(N) 42), original source checked',
        input_confidence='medium',eligibility='compound-formation-control',
        boundary='First component before hand/foot noun is independently comparable; exact lexical status of that component unknown.')

    add('d313','Tamil people/language, regional name','aruvā/arava regional ethnonym; proto-root unspecified',
        'Ø','a','r/ṟ','u/a','VCVCV, regional name','proper noun/ethnonym',
        'Tamil aruvā-nāṭu/aruvar, Kannada arava/aruvu and Telugu aṟavamu share a regional ethnonym. Cross-language attestation does not establish inheritance from Proto-Dravidian or a unique earlier r/ṟ.',
        'All languages preserve a before the apical. The names may have spread between languages, so their agreement cannot be treated as multiple independent retentions of an established proto-input.',
        'Regional aruvā/arava forms undergo ethnonym and language-name suffixation, medial-vowel variation and Kannada syncope arva. No initial apical displacement is observed.',
        'Proper-name chronology is essential here: no dated earliest local attestation has yet established whether the Telugu ethnonym existed before metathesis. The ṟ versus r mismatch is retained as evidence, not normalized to fit an input class.',
        {'Telugu':('R','aṟavamu|aṟavalu','Regional ethnonym/language name retains order.'),
         'Tamil':('R','aruvā|aruvā-nāṭu|aruvar|aravar','Toponym and ethnonyms; one lexical family.'),
         'Kannada':('R','arava|aravu|aruvu|arva','Vowel variants and medial syncope.'),'Tulu':('R','arava','Same regional name, contact chronology unknown.')},
        references='DEDR 313 p.29',eligibility='proper-name-contact-control',input_confidence='low',
        boundary='No independently reconstructed simple root/formative segmentation.')

    add('d315','sever, cut, decrease, scratch','*aṯ-u- / *aṯ-al- and velar/labial formations',
        'Ø','a','ṯ','u','VC-u-C / VC-a-C','verb/noun',
        'Tamil aṟu, Malayalam aṟuka and Kannada aṟu independently establish a high-u sever root; Tamil aṟal supplies a separate low-vowel detachment formation. Telugu aṟu retains the root, while ṟakku/rakku has a velar extension.',
        'Broad southern vowel-first evidence and Brahui harring support earlier V–alveolar ordering. Telugu scratch ṟakku is innovative under this cognacy; the velar derivative’s exact vowel is not automatically identical to that of the bare sever stem.',
        '*aṯ-u > Telugu aṟu; conditional *aṟ-uk(k) > *ṟakk > ṟakku/rakku gives short a after a different high vowel. Alternative consonantal *aṟ-kk formation yields the same output, so suffix-vowel identity is not uniquely recovered. Brahui harring adds h before the retained vowel-r sequence.',
        'K61 p.56’s proposed comparison for Telugu rālu invokes Tamil aṟal from this family, linking it to d233 as an alternative analysis. Do not count this source cross-family borrowing of evidence twice. Kolami/Naikri ark may instead belong to cut d175. DEDR also compares n-initial naṟukku d3625: initial n loss versus separate lexical roots needs testing. Badaga place/plant compounds and archaic harakada do not all have equally secure cognacy.',
        {'Telugu':('M','aṟu|aṟa|aṟagoṟa|ṟakku|rakku','Bare/deprivation forms retained; scratch velar formation displaced.'),
         'Tamil':('R','aṟu (aṟuv|aṟal|aṟuppu','Parsed paradigm fragment linked to original complete aṟu paradigm; low/high formations distinct.'),
         'Malayalam':('R','aṟuka|aṟukka|aṟuppu','High-u root and transitive formations.'),
         'Kannada':('R','aṟu|aṟaka|aṟake','Bare root and low-vowel nominal expansions retained.'),
         'Kodagu':('R','ara- (arap-, arat-)','Low-vowel derivative retains order.'),
         'Kota':('R','arv- (art-)|armbaṛ- (armbaṭ-)','Consonantal extensions, no initial movement.'),
         'Toda':('R','aṟf- (aṟt-)','Consonantal transitivity/tense formation retains order.'),'Tulu':('R','arpuni','Efface verb retains initial V.'),
         'Kuwi':('R','arna','Harvest/grain noun retains order; nominal derivation needs separate analysis.'),
         'Kolami':('A','ark- (arakt-)','Source alternative d175 prevents secure root assignment.'),'Naikri':('A','ark','Same explicit alternative as Kolami.'),
         'Brahui':('R','harring','Initial h addition, root vowel before r.'),
         'Badaga':('A','harakada|araṭṭi','Archaic injured form and isolated-place noun have indirect semantic/morphological connections.')},
        references='DEDR 315 p.29; K61 p.56; cross-references d175,233,3625',input_confidence='high',
        boundary='Independent high-u bare sever stem versus low-al and velar/labial expansions; no single extension assigned across all reflexes.')
    tokens('d315','Telugu',R='aṟu|aṟa|aṟagoṟa',D='ṟakku|rakku')

    add('d316','digest, wear away, indigestion','*aṯ-u-; *aṟ-ak/uk- and labial formations',
        'Ø','a','ṯ','u/a','VC-V-C','verb/noun',
        'Tamil aṟu digest and Kannada aragu/aṟave independently support vowel-first apical and different extensions. Telugu aṟugu, Konda aṟgi and Kuvi arg provide a directly comparable regional velar stem.',
        'SD I and SD II agree on vowel-before-apical in the core digestion comparison. Tulu reñjuni and Gondi rokk are initial-r outliers whose vowels and extensions must be checked before accepting metathesis.',
        '*aṟ-Vk > Telugu aṟugu, Konda aṟgi and Kuvi arg with regional vowel/syncope differences. Tulu arkame/akku supplies a plausible medial rk>kk route. Conditional *ar-Vñc > reñjuni would require initial loss/displacement plus a separately supported e history.',
        'Original DEDR explicitly questions the Gondi rokkānā/rokk comparison; its o and kk cannot be explained by writing an invented earlier *oru solely to fit it. Kui ārgagāṭi giva is a full light-verb construction whose nominal component may have a contact history. The indigestion subentry has ṟ/ẓ variation and different nouns; do not treat every nasal/velar form as the same input.',
        {'Telugu':('R','aṟugu|aṟakamu|aṟukuva|aṟupu-konu','High/low/compound formations retain initial order.'),
         'Tamil':('R','aṟu','Independent bare digestion root.'),
         'Kannada':('A','aragu|aṟave|aṟambe|aṛ̆kame','Retained core; exceptional ẓ in indigestion noun needs correspondence/cognacy check.'),
         'Tulu':('A','aragɯ|arkame|akku|reñjuni','Core retention, medial assimilation and an uncertain initial-loss candidate.'),
         'Gondi':('A','rokkānā|rokk','Cognacy explicitly queried by DEDR.'),'Konda':('R','aṟgi- (-t-)','Regional velar stem retained.'),
         'Kui':('A','ārgagāṭi giva','Vowel-before-r survives; exact inherited versus contact status of nominal component unresolved.'),
         'Kuwi':('R','arg- (-it-)','Regional velar stem retained.'),'Gadaba':('R','arg-ēr','Retained stem plus auxiliary/extension; possible regional contact not independently diagnosed.')},
        references='DEDR 316(a,b) p.30, original question mark on Gondi checked',input_confidence='high',
        boundary='Regional velar formation independently corroborated; other labial/nasal-palatal formations not forced into it.')
    tokens('d316','Kannada',R='aragu|aṟave|aṟambe',A='aṛ̆kame')
    tokens('d316','Tulu',R='aragɯ|arkame',O='akku',A='reñjuni')

    add('d317','abide, preserve, secure','*aṯ-u-; labial extension *-p',
        'Ø','a','ṯ','u','VC-u-p / VC-u-','verb/noun',
        'Tamil aṟu and aṟuppu fort independently support the high-u base and labial formation; Telugu aṟupu is a keep/preserve verb. Tamil aṟai camp has a different low-vowel formation.',
        'Both languages preserve a before the alveolar, supporting the compared regional input. No displaced form is attested in this group.',
        '*aṟ-u-p > Telugu aṟupu; Tamil stronger *aṟ-u-pp > aṟuppu fort. Tamil aṟku/alku may reflect medial syncope and consonant variation but are explicitly questioned by the source.',
        'A two-language semantic bridge between dwell and preserve is plausible, not certain. A independently established early Telugu p-formation would strengthen its status as a counterexample to general metathesis; no such date is inferred just from modern retention. Do not explain it away as a free root: the Telugu form is visibly extended.',
        {'Telugu':('R','aṟupu','Extended high-u form retains order.'),
         'Tamil':('A','aṟu|aṟuppu|aṟai|aṟku|alku','Core forms retained, queried velar/lateral alternatives separate.')},
        references='DEDR 317 p.30; Annamalai Tamil dictionary p.875 for aṟuppu',input_confidence='medium',
        eligibility='core-formation-uncertain',boundary='Labial extension independently compared; chronology of regional lexicalization unknown.')
    tokens('d317','Tamil',R='aṟu|aṟuppu|aṟai',A='aṟku|alku')

    add('d318','cloth, rag, curtain','*aṟ-Vv-ay / *aṟ-ay; quantity of formative variable',
        'Ø','a','ṯ','u/a/i','VC-V-v-ay / VC-ay','noun',
        'Tamil aṟuvai/aṟai, Kannada aṟave/aṟive/aṟuve and Tulu arve independently establish vowel-first alveolar and labial/ay formations. Telugu aṟa is a shorter rag noun.',
        'All reviewed languages retain initial V–apical; Tulu arve shows medial syncope rather than initial movement.',
        '*aṟ-Vv-ay > aṟuvai/aṟave/arve with vowel variation and syncope; a shorter ay or contracted formation yields Telugu aṟa. The exact relation of the two noun shapes is not uniquely established.',
        'DEDR compares blouse d5163 (i)ravikkai, an apparent initial-r counterpart with contact possibilities that needs separate review. A semantic derivative of cut d315 is conceivable for cloth pieces, but is not assumed without morphological evidence. V2 is kept variable; no single vowel is selected to fit retention.',
        {'Telugu':('R','aṟa','Shorter rag noun retains order.'),'Tamil':('R','aṟuvai|aṟai','Two formations retain initial vowel.'),
         'Kannada':('R','aṟa|aṟave|aṟive|aṟuve','Different vowels retain order.'),'Tulu':('R','arve','Medial syncope.'),
         'Badaga':('R','aruve','Related rag noun retains initial sequence.')},
        references='DEDR 318 p.30 and cross-reference 5163',input_confidence='medium',
        eligibility='core-formation-uncertain',boundary='Labial/ay morphology supported, exact shorter Telugu formation uncertain.')

    add('d319','sound, shout, ring, prattle','*aṯ-ay / *aṯ-a-; *-c/-p/-ŋk and consonantal extensions',
        'Ø','a','ṯ','a','VC-a-C / VC-C','verb/noun',
        'Tamil aṟai and Kannada aṟacu/aṟicu/aṟucu independently establish V–alveolar ordering and several extensions; Telugu aṟacu/aṟapu supply retained related forms. The exact input of rajju is less specific than the head *aṟ-a.',
        'Multiple southern vowel-first forms favor earlier aṟ-. Telugu initial ṟ/r formations are innovative under the cognacy. Naiki arap and Gadaba arg support retained initial order outside SD I/Telugu.',
        'K61 p.55 compares rajju with consonantal *ar-j; Telugu ṟaŋke can reflect a nasal-velar derivative with displacement, while aṟacu/aṟapu retain order. Kui ṛaspa has a separate s/p cluster; its origin is not explained by simply adding -pa to modern Telugu. Kannada racce may reflect local displacement plus strengthening, but its cognacy/contact history remains unresolved.',
        'Kannada racce was stranded in a gloss and would be missed by a search limited to Form; it is source-verified and added as one research observation. Gondi rāŋ(g) is explicitly queried by DEDR, so its long vowel does not automatically confirm a shared innovation. Kolami raz could be inherited or borrowed; no automatic Telugu loan is assumed. Koraga ajike lacks r and needs a local cluster-loss/cognacy explanation.',
        {'Telugu':('M','aṟacu|aṟapu|ṟaŋke|ṟantu|rajju','Retained verbal/labial forms and displaced consonantal/nasal extensions.'),
         'Tamil':('R','aṟai','Independent low-vowel ay input.'),
         'Kannada':('A','aṟacu|aṟicu|aṟucu|arcu|racce','Retained derivatives plus uncertain local displacement/contact candidate racce.'),
         'Tulu':('R','areduni','Low-vowel dental derivative retains order.'),'Naiki':('R','arap','Chanda crow verb retains order.'),
         'Gadaba':('R','arg','Ollari bellow verb retains order.'),'Kui':('D','ṛaspa (ṛast-)','Initial displacement with short vowel and different formative morphology.'),
         'Gondi':('A','rāŋ|rāŋg','Cognacy queried in original source; do not count dialect duplicates as separate events.'),
         'Kolami':('A','raz- (rast-)','Initial displacement plausible; contact and exact consonant history unresolved.'),
         'Koraga':('A','ajike','Speech noun without rhotic; requires local correspondence or revised cognacy.')},
        references='DEDR 319 p.30, original entry checked; K61 p.55 §1.130',input_confidence='high',
        boundary='Independent variation in formative vowels and consonants; K61 reconstructs rajju with consonantal extension.')
    tokens('d319','Telugu',R='aṟacu|aṟapu',D='ṟaŋke|ṟantu|rajju')
    tokens('d319','Kannada',R='aṟacu|aṟicu|aṟucu|arcu',A='racce')

    add('d322','room, partition','*aṯ-ay; regional strengthened *aṟṟa',
        'Ø','a','ṯ','a','VC-ay / VCCV','noun',
        'Tamil aṟai and Malayalam aṟa independently support singleton alveolar and ay formation; Telugu aṟa beside aṟṟa shows strengthening in a regional variant. Tulu adɛ has a stop reflex.',
        'Shared vowel-first ordering supports older aṟay. Telugu singleton aṟa cannot be excluded from an eligible input class merely because the same entry also has a strengthened variant.',
        '*aṟay > Tamil aṟai, Malayalam aṟa, Telugu aṟa; regional gemination yields Telugu aṟṟa and potentially Gondi arra. Tulu adɛ and Badaga -ādu require local alveolar/stop and quantity histories, without initial relocation.',
        'This is a near input match to displaced rock d321: a short initial vowel, singleton alveolar and ay noun. Different meanings do not create a phonological condition. Gondi arrā/arra could reflect Telugu contact; Muria ahpi has a substantially different cluster requiring an independent account. Badaga attests only compound components, so their word-boundary eligibility differs.',
        {'Telugu':('R','aṟa|aṟṟa','Singleton and strengthened variants both retained.'),'Tamil':('R','aṟai','Independent singleton ay noun.'),
         'Malayalam':('R','aṟa','Original order.'),'Tulu':('R','adɛ','Apical stop change, no promotion.'),
         'Gondi':('A','arrā|arra|ahpi','Possible contact for geminate forms; ahpi correspondence unresolved.'),
         'Badaga':('A','kīyādu|mēlādu','Noninitial room components with unresolved quantity/stop correspondence.')},
        references='DEDR 322 p.30; compare DEDR 321',input_confidence='high',
        c2_structure='singleton-and-geminate-formations',boundary='Independent singleton input; later regional strengthening must not determine whole-family eligibility.')

    add('d328','fit, suitable, fertile','*an-V-v-; possible older *can- comparison',
        'Ø','a','n','u/a','VC-V-C','adjective/noun',
        'Kannada anu/anavu/anuvu, Telugu anuvu and Kota anv support a nasal after the initial vowel and a labial extension. Tamil a/aṁ beauty is explicitly questioned; DEDR compares c-initial cannu d2423.',
        'The regional vowel-first nasal input is supported independently of Telugu. A possible earlier initial c loss does not imply n has subsequently exchanged with a.',
        '*an-V-v > Telugu anuvu and Kannada anavu/anuvu, Kota anv by medial syncope; Tulu anutana adds another nominal formative. No initial nasal displacement is observed.',
        'Use as a nasal control, not as an automatic test of a rule restricted to nonnasal apicals. The Tamil loss/nasalization comparison and possible older c-bearing root need separate reconstruction. Vowel quality of the intervening syllable is variable rather than fixed from Telugu alone.',
        {'Telugu':('R','anuvu','Nasal order retained.'),'Kannada':('R','anu|anavu|anuvu','Independent vowel variants retain order.'),
         'Kota':('R','anv','Medial syncope, initial nasal remains postvocalic.'),'Tulu':('R','anutana','Different nominal extension, same initial order.'),
         'Tamil':('A','a|aṁ|ammai','Questioned beauty comparison; precise consonant history unknown.')},
        references='DEDR 328 p.30 and cross-reference 2423',input_confidence='medium',eligibility='nasal-control',
        boundary='Regional labial derivative independently visible; possible older initial c is an unconfirmed deeper stage.')

    add('d329','send, leave, start off','*an-V-p-; high-u regional extension',
        'Ø','a','n','u','VC-u-p / VC-p','verb/noun',
        'Tamil aṉuppu and Malayalam anuppuka independently establish high u and nasal before labial; Telugu anupu preserves the uncontracted order. Kannada ampaka, Kurux ambnā and Malto ambe support a consonantal nasal-labial variant.',
        'Independent uncontracted southern forms plus Telugu anupu show that ampu need not reflect initial nasal metathesis: medial vowel deletion and place assimilation are sufficient.',
        '*an-up > *anp > amp gives Telugu ampu and related labial-cluster forms; Telugu anucu/ancu needs a separate palatal extension or stem remodeling, not a p-to-c change assumed without context. Brahui hamp- adds initial h while preserving a before the nasal cluster.',
        'These are related derivatives and must count once per root. The relationship between full-vowel and consonantal formations could partly be inherited morphology rather than one universal syncope event. Gadaba anisp load on cart has an i/s extension whose history is not supplied by the basic send comparison.',
        {'Telugu':('O','anupu|ampu|ampakamu|anucu|ancu','Retained form, labial assimilation and distinct palatal forms separated.'),
         'Tamil':('O','aṉuppu|ampakam','Uncontracted send verb plus consonantal leave/permission noun.'),
         'Malayalam':('R','anuppuka','Independent high-vowel full stem.'),'Kannada':('O','ampaka','Nasal-labial cluster; no initial movement.'),
         'Kurux':('O','ambnā|ambā (imper.)','Nasal place assimilation/cluster formation; prohibitive is dependent morphology.'),
         'Malto':('O','ambe|amba','Leave verb/prohibitive, one family.'),'Brahui':('O','hamping|hampifing|hamp','Initial h plus preserved a and nasal-labial cluster.'),
         'Gadaba':('A','anisp- (anist-)','Load verb with additional i/s morphology, exact cognacy/formation history unresolved.')},
        references='DEDR 329; Kobayashi 2022 reconstruction record *anVp-; Brahui source cites Emeneau 1962 p.63',
        input_confidence='high',eligibility='nasal-control',mechanism='Medial vowel loss and nasal place assimilation, no initial nasal displacement',
        boundary='Independent high-u stem and consonantal/labial variants; palatal and s-bearing derivatives kept distinct.')
    tokens('d329','Telugu',R='anupu|anucu',O='ampu|ampakamu|ancu')
    tokens('d329','Tamil',R='aṉuppu',O='ampakam')
