"""Deictic paradigms: a/i are contrastive bases, but one process family."""

def populate(add,tokens):
    add('d1','distal demonstratives and adverbs','*a-t(u), *a-w-an/-ar; oblique *ad-an-i / *aw-an-i, *aw-att-i',
        'Ø','a','t/w/b','a/i/u/variable','deictic base + gender/number + oblique augment','pronoun/adverb',
        'Tamil atu/avaṉ, Malayalam atu/avan, Kannada adu/ava and eastern ad/adi/avan establish a before the dental/labial. Tamil at-an-ai and Kannada ad-ar-ke independently establish a vowel-initial oblique augment (K03 p.222). This is morphological comparative evidence, not inference from Telugu dāni alone.',
        'The same deictic a and proximal i precede gender/number elements throughout the family. Telugu and Konda apical/labial-initial obliques and masculine nominatives are innovative within that morphological alignment; they do not justify reconstructing initial d/v for the whole family.',
        'Proposed *ad-an-i > *daan-i > dāni; *aw-an-i > *waan-i > vāni, with modern plural vāṭi from a distinct *aw-att-i augment. Konda dani/vani can reflect subsequent shortening in obliques, but a directly contracted short outcome is not excluded. Telugu vā̃ḍu and Konda vānṟu require gender-formative history in addition to labial displacement. Konda abe/abeṇi : bān/bāṇi establishes a local labial-initial locative variant, with contraction and reformation not uniquely sequenced.',
        'Count the distal and proximal entries as one deictic process family in the primary partition, not every inflected form as an independent root. Nominative adi and oblique dāni coexist by grammatical conditioning; simple claim all short V-apical words change is false. Labial participation is outside a narrowly apical lexical rule. K03 p.223 n.14 explicitly leaves shared Telugu–Konda innovation versus early Telugu borrowing unresolved. K03 p.222 n.13 proposes Old Telugu generalized the singular augment whereas spoken Telugu preserves *-att in the plural; this is a historical morphological hypothesis, not an independently dated sound change here. DEDR parser assigns obl broadly to whole paradigms and fragments Tamil forms/glosses; those tags are not all accurate POS analyses. Unrelated deictic compounds are preserved in full appendix but not counted as separate metatheses.',
        {'Tamil':('R','atu (before consonant)|avaṉ (before consonant)|avaḷ (before consonant)|avar (before consonant)|avai','Base precedes dental/labial; exact source parenthetical context preserved.'),'Malayalam':('R','atu|avan|avaḷ|avar|ava','Same order.'),'Kannada':('R','adu|ava|avaḷ|avar|avu','Same order; case augment independently documented in K03.'),'Telugu':('M','adi|dāni-|avi|vāṭi-|vā̃ḍu ( vāni-)|vāru ( vāri-)|vāṇḍlu|ataḍu|atanu|ātaḍu|ātanu','Split source paradigms retain direct and oblique contrasts; long ā forms remain vowel-first.'),'Konda':('M','adi|dani-|avi|vanka-|vānṟu ( vani-)|vāru ( vari-)|vār ( vari-)|abe|abeṇi|bān ( abeṇ-/bāṇ-)|bāṇi','Dental and labial displacement, retained direct forms and local locative alternatives.'),'Gondi':('R','ad|av|had|hav|ōl ( ōn-)|ōr|ōṛ|ōnḍu','Dental retained; contracted masculine vowels do not move the final apical to word onset.'),'Kui':('R','aanju|aaru|āvi|āri|āmba','Vowel-first nominatives/locatives; no claim these exhaust oblique morphology.'),'Kuwi':('R','āasi|ādi|āati|āari|amba','Vowel-first source paradigms.'),'Pengo':('R','adi|avan|avar|aven|avek|avaŋ|adel|abe|habe|ambe','Vowel-first paradigms and labial locative controls.')},
        family='deictic-a-i',references='DEDR1; Krishnamurti2003 pp.158,222–223 nn.13–14',eligibility='morphological-pronoun-domain',quantity='short deictic input; secondary long formations',c2_structure='morphological dental/labial elements',boundary='Gender/number and oblique augments independently comparative; direct and oblique forms are distinct cells of one paradigm.',input_confidence='high for order and morphological augment; medium for exact immediate sequence',mechanism='Morphologically restricted displacement/contraction plus analogy; labials participate.')
    tokens('d1','Telugu',R='adi|avi|ataḍu|atanu|ātaḍu|ātanu',D='dāni-|vāṭi-|vā̃ḍu ( vāni-)|vāru ( vāri-)|vāṇḍlu')
    tokens('d1','Konda',R='adi|avi|abe|abeṇi',D='dani-|vanka-|vānṟu ( vani-)|vāru ( vari-)|vār ( vari-)|bān ( abeṇ-/bāṇ-)|bāṇi')
    add('d410','proximal demonstratives and adverbs','*i-t(u), *i-w-an/-ar; oblique *id-an-i / *iw-an-i, *iw-att-i',
        'Ø','i','t/w/b','a/i/u/variable','deictic base + gender/number + oblique augment','pronoun/adverb',
        'Tamil itu/ivaṉ, Malayalam itu/ivaṇ, Kannada idu/iva and Pengo/Manda idi/ivan establish initial i followed by gender/number material. The a- oblique augment is independently comparative in the matching distal paradigm (K03 p.222); the lexical source does not independently supply every uncontracted proximal oblique.',
        'The a:i demonstrative opposition and the same following morphology across several branches support vowel-before-dental/labial input. Konda deni is particularly valuable because it does not simply copy the surface Telugu high vowel in dīni.',
        'K03 proposes lowering in *id-an-i > *ed-an-i before displacement/contraction, followed by Konda deni, while Telugu dīni is remodeled to preserve the opposition to interrogative dēni; this is analogy, not a phonetic i+a>ī rule. Compare *iw-an-i > Konda veni versus Telugu vīni, modern plural vīṭi from *iw-att-i with corresponding analogical possibilities. Konda ibe/ibeṇi : bēn/bēṇi supplies labial locative restructuring; Pengo ibe/ibṇi retains initial i even with syncope.',
        'The anti-homophony account for Telugu dīni is a plausible hypothesis (K03 p.223 n.14), not demonstrated by a directly attested earlier *deni stage. Sastri1969 pp.178,184 explicitly treats historical dēni as interrogative; an inscriptional English translation this grant is not sufficient to identify a proximal ancestral stage. Konda current DB plural oblique venka differs from K03 veni: preserve both source claims and do not silently replace morphology. Konda short deni versus long bēn shows formation-specific quantity. This cannot be used to validate a single phonetic outcome rule for all pronouns. Te nisuvu/nisũgu child is a separate semantic/cognacy issue within the giant deictic entry and is not evidence for nasal metathesis of the deictic base. Direct and oblique forms are research-split with links to their original unsplit database records.',
        {'Tamil':('R','itu (before consonant)|ivaṉ (before consonant)|ivaḷ (before consonant)|ivar (before consonant)|ivai','Comparative initial i; parser parentheticals retained.'),'Malayalam':('R','itu|ivaṇ|ivaḷ|ivar|iva','Same order.'),'Kannada':('R','idu|iva|ivaḷ|ivar|ivu','Same order.'),'Telugu':('M','idi|dīni-|ivi|vīṭi-|vī̃ḍu ( vīni-)|vīru ( vīri-)|vīnḍlu|itanu|ītanu','Direct vowel-first forms versus displaced obliques and masculine forms.'),'Konda':('M','idi|deni-|ivi|venka-|vēnṟu ( veni-)|vēru ( veri-)|vēr ( veri-)|ibe|ibeṇi|bēn ( ibeṇ-/bēṇ-)|bēṇi','Dental/labial displacement and local locative paradigms.'),'Pengo':('R','idi|ivan|ivar|iven|ivek|ivaŋ|idel|ibe|ibṇi','Retained direct forms and labial locative with syncope.'),'Manda':('R','idi|ivan|idel|ība','Retained direct forms; no oblique claim.')},
        family='deictic-a-i',references='DEDR410; Krishnamurti2003 pp.158,222–223 nn.13–14',eligibility='morphological-pronoun-domain',quantity='short deictic input; secondary long formations',c2_structure='morphological dental/labial elements',boundary='Gender/number and oblique augments; proximal and distal members of one productive paradigm.',input_confidence='high for order; medium for immediate oblique prehistory',mechanism='Morphologically restricted displacement/contraction; Telugu high vowels plausibly analogical, not independent evidence for phonetic output.')
    tokens('d410','Telugu',R='idi|ivi|itanu|ītanu',D='dīni-|vīṭi-|vī̃ḍu ( vīni-)|vīru ( vīri-)|vīnḍlu')
    tokens('d410','Konda',R='idi|ivi|ibe|ibeṇi',D='deni-|venka-|vēnṟu ( veni-)|vēru ( veri-)|vēr ( veri-)|bēn ( ibeṇ-/bēṇ-)|bēṇi')
