"""Manual vowel-initial controls and difficult input comparisons.

Imported by annotations.py after the shared annotation functions are defined.
"""
def populate(add, tokens):
    add('d61','shoot, discharge','regional *aṭ-a- (Te -r-, Tu -k-)',
        'Ø','a','ṭ','a','VC-a-C','verb',
        'Tulu aḍakuni and Telugu aḍarucu/aḍarincu agree in aḍa-, with different final extensions. The database PSTDr reconstruction rests on only this two-language comparison.',
        'Both comparative members are vowel-initial; no independent displaced member motivates an earlier alternative order.',
        '*aṭ-a-r- > aḍarucu in Telugu; *aṭ-a-k- > aḍakuni in Tulu, conditionally on cognacy. No vowel/apical exchange is necessary.',
        'A low second vowel is directly shared, but the narrow distribution and final r:k mismatch limit the reconstruction level. The contrast is retained as a narrow comparison, not elevated to secure PDr evidence.',
        {'Telugu':('R','aḍarucu|aḍarincu','Retained ordering in both listed formations.'),
         'Tulu':('R','aḍakuni','Retained order, different extension.')},
        eligibility='narrow-comparison-control',input_confidence='low',references='DEDR 61',
        boundary='Different final extensions support segmentation only provisionally.')

    add('d64','betel pouch','*aṭ-a-ppay / *aṭay-ppay',
        'Ø','a','ṭ','a','VC-a(y) + pp-ay','noun',
        'Tamil aṭappam/aṭaippam, Malayalam aṭappam and Kannada aḍapa support aṭ-a-pp-. DEDR 88 supplies Tamil aṭaippai and explicitly cross-refers to this pouch family.',
        'All daughter forms retain the vowel before ṭ/ḍ. Optional h in Kannada, Tulu and Telugu does not reverse the vowel/apical sequence.',
        '*aṭay-ppay (areca + bag) > aṭappam/aṭaippam and aḍapa-mu, with compounding and nominal-final alternation. The exact relation of pp-ay to -ppam needs separate morphology; no metathesis is needed.',
        'Count together with d88, since the pouch is an areca compound and d88 actually repeats its Tamil form and Telugu derivatives. h-prothesis may mark regional transmission, but is not alone proof of a particular loan direction. This cultural vocabulary supplies an attested retention comparison with uncertain inheritance chronology.',
        {'Telugu':('R','aḍapamu|haḍapamu','Both variants preserve a before ḍ.'),
         'Tamil':('R','aṭappam|aṭaippam','Both compound shapes retain order.'),
         'Malayalam':('R','aṭappam|aṭappan','Nominal ending varies; order retained.'),
         'Kannada':('R','aḍapa|haḍapa','h varies independently.'),
         'Tulu':('R','aḍapa|haḍapa','h varies independently.')},
        family='d64+d88',eligibility='compound-contact-control',references='DEDR 64,88; K03 reconstruction in CLDF',
        boundary='Areca + bag comparison is explicit in DEDR 88; probable cultural diffusion is not independently dated.',input_confidence='high')

    add('d75','earthen pot','*aṭ-V-k-? / *aṭ-V-',
        'Ø','a','ṭ','unknown','VC-V-C / VC-C','noun',
        'Kannada aḍigera, Telugu aṭika and Gondi aṛka/aṭkā suggest *aṭ-Vk-. Tulu aḍḍyara and Kurux aṛī have different extensions; reconstruction of one fully specified word is unwarranted.',
        'SD I, Telugu, Gondi and Kurux agree on V–apical ordering, independently supporting a vowel-initial base.',
        '*aṭ-ik- > aṭika is compatible with Telugu, but i is not securely common to all extensions; *aṭ-Vk- > Gondi aṛka/aṭkā illustrates medial syncope. No initial displacement.',
        'Tulu gemination and the final r/k correspondence require formation-level history. Gondi Chanda adka and aṛka include broken editorial gloss fragments; use the securely glossed dialect rows for semantics. Pot terminology could diffuse, so inheritance at PDr level remains provisional.',
        {'Telugu':('R','aṭika','No displacement; single t is retained in source.'),
         'Kannada':('R','aḍigera','Gowda/Arebhashe source.'),'Tulu':('R','aḍḍyara','Geminate with retained initial vowel.'),
         'Gondi':('R','aṛka|aṭkā','Internal cluster produced without initial reordering.'),
         'Naikri':('R','aṛka','Order retained; inherited versus regional loan unresolved.'),
         'Kurux':('R','aṛī','Different extension, same root ordering.')},
        eligibility='core-formation-uncertain',references='DEDR 75',input_confidence='medium')

    add('d76','cook, burn; pancake','*aṭ-u- / *aṭ-; strengthened *aṭṭ-u noun',
        'Ø','a','ṭ','u','VC-u; VC-CV; derivatives and compounds','verb/noun',
        'Tamil aṭu (aṭuv-, aṭṭ-), Malayalam aṭuka and Kannada aḍu (aṭṭ-) support singleton *aṭ- and high-vowel verb formations independently of the geminate food noun *aṭṭu displayed at the DEDR head.',
        'Both southern and south-central languages have vowel-initial roots, including Kui aṭa and Kuvi aṭ. An initial ṭ reconstruction would require unmotivated widespread prothesis.',
        '*aṭ-u- > retained cooking verbs; tense/noun strengthening yields aṭṭ- and Telugu aṭṭu. Telugu aḍugaṇṭu retains the singleton in a compound. Kui aṭa and Konda aṭk- retain order in heat/burn formations.',
        'The pancake head is not the only reconstructed input of this etymon. Counting all members as geminate-root exclusions would discard eligible singleton derivatives. Conversely the geminate pancake alone does not test movement of a singleton. Telugu aḍasāla contains a separate kitchen component and may be regionally transmitted. Badaga aṭra/attara hot variants require local cluster/epenthesis history, not the initial metathesis examined here; nāgaṭṭte plant name has uncertain linkage.',
        {'Telugu':('R','aḍugaṇṭu|aḍasāla|aṭṭu|aṭṭ-uppu','Singleton compound and strengthened food/salt formations all retain original order.'),
         'Tamil':('R','aṭu|aṭuppu|aṭucil|aṭṭu','Inflected and derived shapes preserve ordering.'),
         'Malayalam':('R','aṭuka|aṭuppu','Root and derivative retained.'),
         'Kannada':('R','aḍu (aṭṭ-)|aḍige|aḍuge|aṛ̆ke','Stem strengthening and high-vowel syncope are separate.'),
         'Kodagu':('R','aḍigeka·rə','Compound derived cook noun.'),
         'Kota':('R','aṛ- (aṭ-)','Tense allomorphs retain vowel-first order.'),
         'Toda':('R','oṛ- (oṭ-)','Local vowel change plus tense allomorphy.'),
         'Tulu':('R','aḍɯpini|aḍkala|aḍigɛ','Medial syncope in cooking-shed compound.'),
         'Gondi':('R','aṭ|aṭṭ|aṭṭānā|aṭáná','Dialect and tense/stem strength differences preserved.'),
         'Konda':('R','aṭk- (-t-)','Consonantal extension retains original order.'),
         'Kui':('R','aṭa (aṭi-)','Low-vowel heat verb retains order.'),
         'Kuwi':('R','aṭ|aṭi ki','Burn base and light-verb construction retain order.'),
         'Naiki':('R','aṭ|aṭay|aṭap|aṭil','Different dry/cook formations retain order.'),
         'Badaga':('A','attu|adige|aṭra|attara|nāgaṭṭte','Cook forms retained; hot variants and plant-name linkage are not independently resolved.')},
        references='DEDR 76; K03 pancake reconstruction in CLDF',input_confidence='high',
        boundary='Root singleton versus tense/noun gemination is independently supported by Tamil and Kannada paradigms; compounds not treated as independent roots.')
    tokens('d76','Badaga',R='attu|adige',A='aṭra|attara|nāgaṭṭte')

    add('d83','close, obstruct, transverse','*aṭ-ay- beside *aṭṭ-a- / *aṭṭ-i-',
        'Ø','a','ṭ','a','VC-ay and VCC-V','verb/noun/adjective',
        'Tamil aṭai and Malayalam aṭayuka support singleton *aṭ-ay, while Tamil aṭṭam, Kannada aḍḍa and Telugu aḍḍamu independently support a strengthened transverse/obstruction formation. Both must be represented.',
        'Numerous SD I and SD II forms retain initial a. Initial ḍ in Kui ḍākoli could be displaced, but the word is not segmentally identical to the native simple closing stems and needs independent history.',
        'Retained *aṭay > Tamil aṭai / Tulu aḍe-vuni; strengthened *aṭṭa > Telugu aḍḍa(mu). Telugu aḍucu-konu retains the singleton in a derived construction. Hypothetical *aṭ-a-k... > *ḍāk... for Kui shield remains unverified.',
        'Do not classify the entire etymon as a geminate blocker from Telugu aḍḍa alone. Kui aḍa is explicitly said to be from Oriya; ḍākoli shield could be inherited, compounded or borrowed, with no independently recovered complete input. Brahui āṛ and Malto aṛatre have explicit IA doubts. The broad IA obstruction series is contact evidence, not extra independent Dravidian controls. Kuvi kīnai is an extracted light verb, not a standalone cognate of aṭ-.',
        {'Telugu':('R','aḍḍamu|aḍḍu|aḍucu-konu|aḍḍi','Both singleton and strengthened formations retain order.'),
         'Tamil':('R','aṭai|aṭaippu|aṭṭam','Singleton and strengthened formations retained.'),
         'Malayalam':('R','aṭayuka|aṭṭam|aṭavu','Multiple derivative shapes retained.'),
         'Kannada':('R','aḍḍa|aḍa|aḍḍi','Strength alternation, no displacement.'),
         'Kodagu':('R','aḍa- (aḍap-, aḍat-)|aḍe- (aḍev-, aḍand-)|aḍḍa','Paradigm and strengthened crosswise base retained.'),
         'Tulu':('R','aḍevuni|aḍeŋguni|aḍḍa','Singleton and geminate formations retained.'),
         'Kota':('R','aṛv-|aḍ','Separate blocked/transverse stems retain order.'),
         'Toda':('R','aṛf-|oḍ','Separate closing/transverse formations retain order.'),
         'Gondi':('R','aḍḍam|aḍam|aḍām','Quantity/strength varies by dialect; all retain ordering.'),
         'Konda':('R','aḍi- (-t-)|aṛk|aḍam','Medial syncope in conceal verb does not promote apical.'),
         'Kui':('A','aḍa|aḍa giva|ḍākoli','Oriya borrowing stated for aḍa; shield history unresolved.'),
         'Kuwi':('A','addunga|addu ānai|aḍḍe ānai|kīnai','Obstruction base retains order; isolated light verb is a parsing/cognacy issue.'),
         'Pengo':('R','aḍgel','Medial syncope only.'),'Naiki':('R','aḍḍam','Order retained.'),
         'Parji':('R','aḍḍom|aḍḍom er','Base and light-verb construction retained.'),
         'Kurux':('R','aḍnā (aḍcas/aḍḍas)|aṛkī|aḍḍē','Order retained; stem/suffix strengthening separate.'),
         'Malto':('A','aṛatre|aṛare','Order preserved, but source raises IA borrowing.'),
         'Brahui':('A','aṛ|aṛī|aḍ|āṛ','Vowel-first; shelter āṛ explicitly has IA doubt and wider donor sorting is unresolved.'),
         'Badaga':('R','ade|adda|adḷu','Local syncope does not invert initial order.')},
        c2_structure='singleton-and-geminate-formations',eligibility='mixed-input-formations',references='DEDR 83',input_confidence='high',
        boundary='Singleton -ay verbal root and strengthened crosswise noun supported across SD I; root-family relation plausible but not a license to erase stem distinctions.')
    tokens('d83','Kui',B='aḍa|aḍa giva',A='ḍākoli')
    tokens('d83','Kuwi',R='addunga|addu ānai|aḍḍe ānai',A='kīnai')

    add('d84','collect, crowd, increase','*aṭ-ay- / *aṭ-ar-; strengthened *aṭṭ-',
        'Ø','a','ṭ','a','VC-ay / VC-ar / VCC','verb/noun',
        'Tamil aṭai/aṭar, Kannada aḍe/aḍar and Telugu aḍaru establish short a, singleton apical and low vowel extensions. These are independent of the strengthened pile nouns.',
        'SD I, Telugu, Konda aḍar and Pengo aḍer all put a before the apical; no reversal is required.',
        '*aṭ-ar- > aḍaru in Telugu and aḍar in Kannada/Konda. *aṭ-ay- > aṭai/aḍe; strengthened *aṭṭ- appears in pile nouns. Pengo e after the apical is a local vowel development without displacement.',
        'Telugu eṭṭam differs in V1, and aṭṭaḍi/aṭṭava have strengthened compound-like shapes: these are not examples of initial displacement. The root is semantically close to pile d80 and approach d79; audit an alternative broad family collapse rather than treating semantic similarity as proof of one root.',
        {'Telugu':('R','aḍaru|aḍa|aḍi|aṭṭamu|eṭṭam|aṭṭaḍi','Singleton, geminate and vowel variants all retain original order.'),
         'Tamil':('R','aṭai|aṭar|aṭi|aṭacu','Multiple extensions and stem classes retain order.'),
         'Malayalam':('R','aṭal|aṭa-maṛ̆a|aṭṭi keṭṭuka','Retained formations and compounds.'),
         'Kannada':('R','aḍe|aḍar|aṭṭu|aḍḍa','No displacement in any compared formation.'),
         'Tulu':('R','aḍarɯ|aṭṭi|aṭāra','Quantity differs inside root extensions, no initial reordering.'),
         'Toda':('R','oḍyk','Root-vowel change, apical remains postvocalic.'),
         'Konda':('R','aḍar','Herd noun retains order.'),'Pengo':('R','aḍer','Herd noun retains order; e requires local suffix history.')},
        references='DEDR 84',input_confidence='high')

    add('d88','areca nut and its implements','*aṭ-ay-kkāy; *aṭay + tool/bag',
        'Ø','a','ṭ','a','VC-ay + compound noun','noun',
        'Tamil aṭaikkāy, Malayalam aṭakka/aṭekka and Kannada aḍake support the areca + fruit compound; Kannada aḍa and tool compounds support a reduced first member independently.',
        'Vowel-first ordering is supported by several SD I languages. Koraga initial ḍ can arise by loss of initial a in a locally contracted areca word, without importing a Telugu history.',
        '*aṭay-kkāy > aṭaikkāy / aḍake, then in Tappu Koraga *aḍakke > ḍakke by aphaeresis and local compound reduction. Telugu aḍa-katti etc. retain the first member; aḍḍa-kattera has additional strengthening.',
        'Koraga preserves short a after the initial stop and a following geminate, so this is compatible with straightforward aphaeresis; a literal vowel/stop exchange is not demonstrated. Telugu has tools/bag attendants, not the identical inherited fruit noun; contact among areca-using communities remains plausible. Kannada Areca catecʰu is a botanical Latin fragment misparsed as a Kannada form and is excluded. Count d64+d88 once as the areca/bag family.',
        {'Telugu':('R','aḍa-kottu|aḍa-katti|aḍḍa-kattera|aḍapakatte|aḍapa','Compounds preserve initial V–ḍ.'),
         'Tamil':('R','aṭaikkāy|aṭaippai','Fruit/bag compounds share one root family.'),
         'Malayalam':('R','aṭakka|aṭekka','Vowel variants, same ordering.'),
         'Kannada':('R','aḍake|aḍike|aḍa|aḍakottu','Fruit/tool compounds and reduced base retain order.'),
         'Kodagu':('R','aḍake','Retained order.'),'Kota':('R','aṛky','Internal contraction/syncope, not initial reversal.'),
         'Toda':('R','aḍky','Internal contraction, initial a retained.'),
         'Tulu':('R','aḍḍa-katteri|iḍa-katteri','Initial vowel variant and strengthening preserve V–ḍ order.'),
         'Badaga':('R','adake','Retained order.'),
         'Koraga':('O','ḍakke','Tappu source; local aphaeresis suffices, Telugu-like long-vowel contraction is not shown.')},
        family='d64+d88',eligibility='compound-contact-control',references='DEDR 88,64; K03 SD I areca reconstruction',input_confidence='high',
        boundary='Fruit, bag and tool components compared independently; root is shared with d64.')

    add('d89','sign, token','regional *aṭay-āḷ-am? (internal analysis uncertain)',
        'Ø','a','ṭ','a','VCay-VVCV(m)','noun',
        'Tamil aṭaiyāḷam, Malayalam aṭayāḷam and Kannada aḍayāḷa agree in a long word; Telugu has aḍiyālamu. The inherited morpheme structure is not independently established.',
        'All comparison languages have a before the apical. The Toda source explicitly compares Tamil, so Toda is not an independent proto-stage witness.',
        'Regional aṭayāḷam > aḍayāḷa / aḍiyālamu is a plausible transmission/adaptation series; exact vowel, lateral and direction of loans need separate evidence. No displacement is required.',
        'Do not use the starred database PSTDr string as proof of ancient inheritance. This word may have spread after the sound change or contain an ineligible boundary. Neither explanation is established by its retained outcome, so it remains outside the decisive inherited denominator.',
        {'Telugu':('R','aḍiyālamu','Ordering retained, but historical entry date unknown.'),
         'Tamil':('R','aṭaiyāḷam','Retained order.'),'Malayalam':('R','aṭayāḷam','Retained order.'),
         'Kannada':('R','aḍayāḷa','Retained order.'),'Badaga':('R','adeyāḷa','Retained order; inherited/loan status unknown.'),
         'Toda':('A','oḍyo·ḷm|oḍyōḷm','Source gives Tamil comparison; contraction and vowel changes do not prove independent inheritance.')},
        eligibility='compound-contact-control',input_confidence='low',references='DEDR 89; Emeneau 1984 p.10 via Toda record',
        boundary='Opaque internal segmentation; no outcome-based boundary is invented.')

    add('d109','thirst, hunger','*aṭ/ẓ/ṇṭ-? plus Telugu *-p(p)- formation',
        'Ø','a','uncertain-apical','unknown','VC(-C) plus P formation','noun/verb',
        'Kannada nīr-aṛ̆ke/nīr-aḍike, Kolami aḍḍ-, Naikri aḍ and Parji/Gadaba anḍ suggest a vowel-initial apical base, but disagree on apical identity and pre-apical nasal/gemination. Starostin marks the reconstruction questionable.',
        'All non-Telugu comparanda favor a before an apical; Telugu ḍappi could be displaced if the comparison is correct. Their divergent consonants prevent a unique detailed proto-form.',
        'Conditional *aḍ-p- > *ḍa-pp- > ḍappi > dappi, with formative strengthening, is compatible with the short vowel. An older nasal or *ẓ requires different consonant developments. No *aḍa- input is inserted just to predict ā and then explain it away.',
        'This is evidence for investigating displacement, but not a secure geminate exception or proof of a low-vowel shortening rule. Kannada aṛ̆ is a distinct historical apical, while Parji/Gadaba have a nasal. Etymon d277 also contains ḍappi in the sense distress/perishing: evaluate lexical conflation and possible semantic overlap. A primary source paradigm for thirst dayyu and an early dated ḍappi would help separate analyses.',
        {'Telugu':('A','ḍappi|dappi|dappika','Displacement plausible, complete input/cognacy unresolved.'),
         'Kannada':('A','nīr-aṛ̆ke|nīr-aḍike|nīr-aḍisu','Vowel-initial base inside water compound; apical alternation requires explanation.'),
         'Kolami':('R','aḍḍ- (aṭt-)','Original V–apical order retained, geminate root variant.'),
         'Naikri':('R','aḍ','Original ordering in a bare noun.'),
         'Parji':('A','anḍ|anḍkuḍ','Nasal cluster creates reconstruction uncertainty.'),
         'Gadaba':('A','anḍ|anḍkir|aṇ- (aṇḍ-)','Different sources preserve nasal cluster/tense variant; not identical *aḍ.')},
        eligibility='cognacy-or-input-uncertain',c2_structure='singleton/geminate/nasal-cluster-uncertain',
        input_confidence='low',confidence='low',references='DEDR 109; compare DEDR 277',
        boundary='Telugu -pp- is a possible formative, not independently recovered from the compared stems.')
