"""Nonmetathetic contraction and alternative cognacy relevant to K80 lowering."""

def populate(add,tokens):
    add('d2674','salt, brackish/astringent','*cup; *cow-ar/*cov-ar > *ow-ar',
        'c/zero','u/o','p/w','a/zero','CVC / CVw-ar','noun/verb/adjective',
        'Central sup/cup preserves an initial consonant also reflected by Gondi savvar/hovar, while southern uppu and uvar independently support a stop versus intervocalic labial alternation and the low-a extended formation. Tamil uvar and Gondi havar/savvar are independent of the eastern long-vowel outcomes.',
        'Comparative evidence favors an earlier full labial-containing *cow-ar/*ov-ar, not treating modern long sōr/sār as an original root. The r is already final in the extension and never becomes pre-vocalic in eastern forms.',
        '*cow-ar > *cōr > Konda sōru, Pengo sōr, versus Kui sāru/Kuvi hāru/Manda jār involves intervocalic labial loss/contraction and eastern lowering. Lowering may precede contraction through *cawar or follow contraction of a low-a formation; the outputs alone do not determine which. Southern *ov-ar gives uvar/ogar, with Malayalam ōr showing an independent contraction parallel. Telugu vagaru may involve initial labial/prothetic or analogical restructuring, not established vowel-r metathesis.',
        'This is evidence about lowering in contracted roots, not an apical metathesis positive. It helps separate the two processes and avoids defining lowering by the presence of Cr. K80 p.498 prints Pengo hōr where DEDR gives sōr: preserve the source discrepancy, do not silently replace the database. Salt vocabulary can diffuse; the full southern/central contrast still independently establishes the earlier order. Nihali copo is a contact comparison, not a Dravidian language vote.',
        {'Tamil':('R','uppu|uvar|uvarppu|uvari|uppaḷam|umpaḷam','Bare and low-a extended formations.'),'Malayalam':('O','uppu|uvar|uvari|ōr','Retained forms and contracted ōr.'),'Kota':('R','up','Bare nonapical root.'),'Toda':('R','up','Same.'),'Kannada':('R','uppu|ogar','Bare and full extended formations.'),'Kodagu':('R','uppɨ','Bare root.'),'Tulu':('R','uppu|ugarɯ|ogarɯ|ubarɯ|ubārɯ|uppārɯ|ogaruni','Full labial/velar extended forms.'),'Telugu':('A','uppu|uppani|uppana|uppaḷamu|ogaru|vagaru','Full root/extension retained; vagaru initial material unresolved.'),'Gondi':('R','savvar|savvor|havar|hovar|ovar|ovor','Full extended forms across dialects.'),'Konda':('O','sōru','Contraction without lowering.'),'Kui':('O','sāru','Contraction and lowering.'),'Kuwi':('O','hāru|hārū','Same with initial fricative change.'),'Pengo':('O','sōr','Contraction without lowering; K80 hōr differs.'),'Manda':('O','jār','Contraction/lowering and initial change.'),'Kolami':('R','sup','Initial c/s and labial root.'),'Naikri':('R','supp','Same.'),'Naiki':('R','sup','Same.'),'Parji':('R','cup','Same.'),'Gadaba':('R','cuppu|sup','Dialect reflexes.'),'Badaga':('R','uppu','Bare root.'),'markodi':('R','uppŭ|uppⁱ','Bare root.')},
        input_confidence='high for full low-a extension; exact vowel grades differ',references='K80 p.498 item4; DEDR2674; K03 p.97 example10 (ogaru perhaps a Kannada loan; Gondi sawwor vowel metathesis)',eligibility='nonapical-contraction-control',boundary='Bare *cup and low-a labial extension distinguished independently.',mechanism='Labial loss/contraction; not initial apical metathesis.')
    tokens('d2674','Malayalam',R='uppu|uvar|uvari',O='ōr')
    tokens('d2674','Telugu',R='uppu|uppani|uppana|uppaḷamu',A='ogaru|vagaru')

    add('d2456','incline, side; disputed eastern descend','*cāy; alternative eastern *i/eṟ-a (d516)',
        'c','ā','y','zero/a','CVVC / alternative VC-a','verb/noun',
        'Tamil cāy, Malayalam cāyka and Telugu cāya independently support initial c with long ā and following glide. Eastern jāpa and Manda jē/hē can instead be compared with the descend root d516; their initial consonants and vowels do not settle cognacy by themselves.',
        'The southern incline group has unambiguous c-ā-y order. K80 reassigns some eastern forms to *eṟ-a and a displacement/lowering history, while DEDR places them under cāy and cites Burrow1976 pp.40–41.',
        'Southern *cāy > cāy/cāya and Malayalam āyka/āñcuka involves initial c loss and stem/tense changes, not apical transfer. If eastern *cāy-p is right, jāpa need not metathesize. If the d516 comparison is right, *eṟ-a-p > *ṟēp > jāpa involves displacement, lowering and apical-to-j; Manda jē/hē preserves a nonlow vowel and needs its own vowel history.',
        'Keep the competing etymologies explicit; do not count the same Kui/Manda words once as retained incline and again as metathesized descend. Burrow1976 A sketch of Manda grammar in comparison with Pengo, Dravidian Linguistics V pp.39–56 has been identified, but pp.40–41 have not been read directly. Its argument is therefore not reconstructed from the citation. Needed: full Manda paradigm, comparative c/j versus ṟ/j correspondences and shared derivative morphology.',
        {'Tamil':('R','cāy|cāyal|cāyvu|cāyppu','Independent long incline root.'),'Malayalam':('R','cāyka|cāykka|cāyal|cāccal|cāyvu|cāyippu|āyka|āñcuka','Initial-loss and stem variants, no apical transfer.'),'Kodagu':('R','taye- (-p-, -t-)','Initial correspondence and shortened quantity; exact history separate.'),'Tulu':('R','cācuni','Stem extension/palatal change.'),'Telugu':('R','cāya','Long incline/side root.'),'Kui':('A','jāpa (jāt-)|jāppa (jāpt-)','Competing cāy and eṟ-a etymologies.'),'Manda':('A','jē|hē|jēpa- (for Manḍ. and its relationship vitʰ Kui in tʰis entry, see Burrov 1976, pp. 40-1)|hēpa- (for Manḍ. and its relationship vitʰ Kui in tʰis entry, see Burrov 1976, pp. 40-1)','Competing origin; preserve nonlow vowel.')},
        quantity='long in southern root; short under alternative eastern etymology',input_confidence='high southern; low eastern cognacy',references='DEDR2456 and516; K80 pp.498–499; Burrow1976 pp.40–41 cited by DEDR, not directly consulted',eligibility='alternative-cognacy-control',boundary='Two competing roots are alternatives, not two independent eastern observations.',mechanism='Southern retention; eastern cognacy determines whether any metathesis occurred.')
