"""Initial-a liquid families, including retention and alternative processes."""
def populate(add, tokens):
    add('d201','king, royalty','Sanskrit *rājan- > regional *(a)rāca- / araca-',
        'r','ā','j','a','CVVCVC donor; prothetic recipient form','noun',
        'DEDR explicitly derives the family from Sanskrit rājan-. K03 pp.476–477 independently identifies Tamil aracan and Kannada arasu as early adapted loans with prothetic a. Toda source explicitly says Kannada/Sanskrit borrowing.',
        'Comparative direction is donor r-initial > recipient ar-initial, not Proto-Dravidian ar- > r-. Modern initial a in several Dravidian languages therefore does not establish inherited a-r ordering.',
        'Sanskrit rājan- > regional *arāca- > araca(n)/arasu/arusu, with prothesis, quantity adaptation, intervocalic consonant adaptation and recipient endings. Intermediate recipient steps are schematic; a single shared borrowing episode is not established.',
        'The PSTDr starred database head is a regional comparison, not evidence that this is inherited PDr. Telugu rāju elsewhere is not automatically a metathesized doublet of arusu: separate Sanskrit loan strata must be tested. DEDR cites a 2nd-century Śātavāhana coin form arahaṇasha, but identifies its language as unknown and only presumably South Dravidian; it cannot securely date specifically Telugu metathesis.',
        {'Telugu':('B','arusu','Adapted king word; donor/recipient distinction removes it from inherited controls.'),
         'Tamil':('B','aracaṉ|aracu|araiyaṉ','Source explicitly gives Sanskrit derivation.'),
         'Malayalam':('B','aracan|arayan|aracu','Same loan family, separate recipient adaptations possible.'),
         'Kannada':('B','arasu|arasa (in cpds. ara-)','Sanskrit derivation explicit in K03.'),
         'Tulu':('B','arasu|arase','Regional loan family.'),'Kodagu':('B','aramane','King-house compound of loan noun.'),
         'Kota':('B','arc|arman','Government official/palace terminology.'),
         'Toda':('B','ars|arman','Source explicitly derives king from Kannada/Sanskrit.'),
         'Badaga':('B','arasu|arasa|arasi|aramane','Regional titles and palace terms; proper names not independent etyma.')},
        quantity='long',c2_structure='singleton',eligibility='loan-input-control',input_confidence='high',confidence='high',
        references='DEDR 201 editorial note; K03 pp.476–478; Sircar 1961 EI 35:247–252 cited by DEDR (not independently checked)',
        mechanism='Prothesis and loan adaptation, not inherited apical displacement',boundary='Sanskrit nominal stem and recipient nominal/compound morphology.')

    add('d205','banana, plantain','regional *ar-Vṇṭṭi; independent earlier form uncertain',
        'Ø','a','r','unknown','VC-V-NPPV','noun',
        'Telugu araṭi/araṇṭi/arãṭi and anaṇṭi/anãṭi/aṇṭi provide internal variation. The only non-Telugu evidence, Gondi arṭi, is explicitly marked borrowed from Telugu; K03 labels the reconstruction SD II, but the current set does not independently justify a shared proto-stage.',
        'Telugu variants favor an older r-containing local stem, but no independent inherited cognate establishes exact early segment order or V2. The Gondi loan reproduces recipient syncope after borrowing.',
        'Within the local family araṇṭi > arãṭi/araṭi is compatible with nasal weakening/loss; araṇṭi > anaṇṭi suggests regressive nasal assimilation; reduction gives aṇṭi. Relative order of these reductions is not uniquely recoverable.',
        'No initial *rā- reflex occurs, and the loss of r in aṇṭi does not require concealed metathesis. Treat as a single-language reconstruction problem, not an independently reconstructed unchanged success. The Kittel-only variants may preserve valuable dialect history; independent historical spellings could decide the r/n chronology.',
        {'Telugu':('O','araṭi|araṇṭi (coll.)|arãṭi (coll.)|anaṇṭi|anãṭi|aṇṭi','Retention and assimilation/reduction variants; none demands initial displacement.'),
         'Gondi':('B','arṭi|arti','DEDR explicitly gives Telugu source; parser splits the Chanda/Seoni gloss.')},
        references='DEDR 205; K03 SD II reconstruction in CLDF',eligibility='single-language-input-uncertain',input_confidence='low',
        mechanism='Nasal assimilation, nasal loss and stem reduction; no displacement demonstrated',boundary='Botanical stem segmentation opaque.')
    tokens('d205','Telugu',R='araṭi|araṇṭi (coll.)|arãṭi (coll.)',O='anaṇṭi|anãṭi|aṇṭi')

    add('d207','interlace, spread as a creeper','*ar-il- / *ar-al-?',
        'Ø','a','r','i/a','VC-VC','verb/noun',
        'Tamil aril and Telugu aralu independently provide initial ar- plus a later lateral. Telugu allu and Salur Gadaba all lack the rhotic. Tamil i versus Telugu a prevents recovering one exact medial vowel.',
        'The rhotic-bearing Tamil and Telugu forms favor an earlier ar-V-l sequence; rhotic assimilation after medial syncope produces ll more economically than a vowel–rhotic swap followed by reinsertion of initial a.',
        '*ar-V-l- > *ar-l- > *al-l- > Telugu allu, Gadaba all, conditional on cognacy. Telugu aralu retains the longer formation. This orders vowel loss before rl assimilation, but does not independently date either.',
        'The lexeme may be related to weaving d260; evaluate a merged family sensitivity because allu occurs in both with closely related senses. The r-bearing witnesses prevent automatically treating every all- as original geminate l. Whether Gadaba borrowed Telugu allu rather than inherited the assimilation remains open.',
        {'Telugu':('O','aralu (K.)|allu','Retained r-bearing formation and assimilated shorter verb.'),
         'Tamil':('R','aril','Comparative witness for both r and final l.'),
         'Gadaba':('A','all','Assimilation or Telugu contact; no independent direction between the languages.')},
        references='DEDR 207; compare DEDR 260',eligibility='core-formation-uncertain',input_confidence='medium',
        mechanism='Medial syncope and rhotic–lateral assimilation; not initial displacement',boundary='Final lateral may be a formative, but independent morphological status is unknown.')
    tokens('d207','Telugu',R='aralu (K.)',O='allu')

    add('d216','tax, debt, pay','*ar-i tax; *ar-VC and strengthened derivatives uncertain',
        'Ø','a','r','i','VC-i; VC-VC; VCCV','noun/verb',
        'Tamil ari and Telugu ari agree in the tax noun; Telugu aruvu supplies another rhotic formation. The relationship of Kannada/Telugu accu and Telugu appu to these nouns is not a regular consequence of metathesis.',
        'Vowel-first ari is independently supported, but it does not alone reconstruct the entire debt series. A hypothetical *ar-pp > appu requires assimilation and a separately motivated formative, not initial-r movement.',
        '*ari > retained tax noun. Conditional *ar-pp- > *app- > appu and *ar-cc- > *acc- > accu invoke regressive assimilation or loss of the rhotic after suffix combination. Their exact formative origins are unresolved. No initial *rV- stage is necessary.',
        'DEDR cross-refers to d223 arukku take, snatch, demand; that may explain the payment verb semantically, but must be reviewed before a single derivation is accepted. Tamil appu and Kuvi aruvu/aṛvū are explicit Telugu loans. They do not independently corroborate a common *ar-pp stage.',
        {'Telugu':('A','ari|aruvu|accu|appu','Tax noun retains order; relationships of strengthened debt formations unresolved.'),
         'Tamil':('R','ari|appu','Inherited/old tax noun retained; appu explicitly borrowed from Telugu.'),
         'Kannada':('A','accu|accike','Rhoticless debt verb could reflect assimilation or distinct formation; input not uniquely recovered.'),
         'Kuwi':('B','aruvu|aṛvū','Explicit Telugu loans in both source variants.')},
        eligibility='cognacy-or-input-uncertain',references='DEDR 216 and cross-reference to 223',input_confidence='low',
        mechanism='Possible suffix-triggered cluster assimilation, not evidence for apical displacement')
    tokens('d216','Telugu',R='ari|aruvu',A='accu|appu')
    tokens('d216','Tamil',R='ari',B='appu')

    add('d222','approach, near, edge','*ar-u-k- / *ar-u-v- and high-vowel variants',
        'Ø','a','r','u/i','VC-high-C','verb/noun',
        'Tamil aruku/aruvu, Malayalam ariku/aruvu and Kannada arugu/arigu independently show short ar- and high-vowel extensions; Telugu arugu and aṟu/aṟuta have rhotic spelling variation.',
        'Multiple southern languages place the root vowel before r. Telugu agrees; no displacement or restoration of an earlier displaced form is demanded.',
        '*ar-uk- > aruku/arugu; *ar-uv- > aruvu; short base *ar-u > aṟu and related locative/adverbial extensions. Telugu arudencu contains additional come/go morphology rather than a reversed root.',
        'Kannada aragu has a low-vowel variant, and Gondi araluk is a more extended close/follow expression; neither can be used to assign the same historical V2 to all forms. Kurux arbar-parbar is a paired/echo expression with uncertain exact cognacy. Telugu ṟ/r history needs early spellings, but both preserve vowel-first order.',
        {'Telugu':('R','arugu|aruta|aṟuta|aṟu|arudencu','Original order in both rhotic spellings and extended verb.'),
         'Tamil':('R','aruku|aruvu','Two independent high-vowel extensions.'),
         'Malayalam':('R','ariku|aruvu|aru','High-vowel variants and base retained.'),
         'Kannada':('R','arugu|arigu|aragu','V2 variants retained.'),
         'Tulu':('R','aru|arugu','Base and extension retained.'),
         'Gondi':('R','araluk vaiānā','Betul extended expression retains order; lexical transmission still possible.'),
         'Kurux':('A','arbar-parbar','Echo-like neighboring expression; exact morphology and cognacy unresolved.')},
        references='DEDR 222; DEN1 p.400, entry185',input_confidence='high',
        boundary='Bare aru and parallel -k/-v extensions support root/formative distinction without recourse to outcomes.')

    add('d227','grace, favor, affection','*ar-uḷ- (internal boundary uncertain)',
        'Ø','a','r','u','VCVC root/extension','noun/verb',
        'Tamil aruḷ, Malayalam aruḷ and Telugu arulu independently support the two-liquid stem, with Telugu merger of retroflex lateral. Kota arḷ has medial vowel loss.',
        'The ordering ar-u-ḷ is common to the southern and Telugu evidence; Kota syncope supports loss of the medial vowel rather than a shift of the rhotic to the start.',
        '*aruḷ > Telugu arulu, with ḷ>l; *aruḷ > Kota arḷ by syncope. Neither change requires metathesis. Date and direction of possible religious vocabulary transmission are unknown.',
        'The source compares d381 ārvam and tentatively d203 araṇa; neither proves a productive -uḷ formative. Treat this as an eligible root-shape comparison with uncertain morphological status, not an invented free-root exception. Affection and divine utterance differ semantically but have ordinary potential links through favor/command.',
        {'Telugu':('R','arulu','Both consonants remain in original order, with lateral merger.'),
         'Tamil':('R','aruḷ|aruḷal','Base and derivative preserve order.'),
         'Malayalam':('R','aruḷ|aruḷuka','Same ordering.'),'Kota':('R','arḷ','Medial vowel deletion only.')},
        references='DEDR 227',eligibility='core-formation-uncertain',boundary='Historical separability of -uḷ is unproved.',input_confidence='high')

    add('d232','gain, enjoyment, good luck','*ar-b-? / *ar-V-b-?',
        'Ø','a','r','unknown','VC-C / VC-V-C','verb/noun',
        'Kota and Toda arb have r before b; Telugu abbu and Kuvi abbinai have a geminate b and compatible enjoyment/prosperity semantics. The shared Nilgiri form is not independent evidence for a particular lost vowel.',
        'If cognate, arb > abb by assimilation is preferable to reconstructing initial r and then losing it while restoring a. The current evidence does not determine whether rb was original or produced by syncope.',
        '*ar(V)b- > *arb- > abb- > Telugu abbu, conditionally on cognacy. Kuvi abb- may share assimilation or be influenced by Telugu. No initial apical displacement is needed.',
        'The reconstructed boundary and vowels are unknown; label this a probable competing mechanism, not a regular retained liquid outcome. Nilgiri extreme happiness versus Telugu acquire/Kuvi prosper is semantically plausible but not proof. An uncontracted matching derivative outside Nilgiri or early Kuvi evidence would strengthen the comparison.',
        {'Telugu':('O','abbu','Rhotic assimilation offers a direct alternative to concealed metathesis.'),
         'Kota':('R','arb','r retained in the medial cluster.'),'Toda':('R','arb','r retained in the medial cluster.'),
         'Kuwi':('A','abbinai','Assimilation or Telugu contact; exact inheritance unestablished.')},
        references='DEDR 232',eligibility='cognacy-or-input-uncertain',c2_structure='cluster-or-syncopated-unknown',input_confidence='low',
        mechanism='Probable rb assimilation, with syncope optional and cognacy provisional')

    add('d244','weeds, leguminous plants','regional *al-a/u-b/m- (medial nasal uncertain)',
        'Ø','a','l','a/u','VC-V-C','noun',
        'Kannada alabu/alubu and Telugu alamu agree on vowel-first al-, but b:m and a:u variation do not uniquely support the full starred *alamb- supplied in CLDF. Gondi allam is explicitly a Telugu loan.',
        'The two non-identical comparison stems both preserve a before l. There is no displaced form from which an earlier reversed order can be independently inferred.',
        'A regional *al-Vmb- could yield Kannada alabu and Telugu alamu by different cluster reductions, but neither the nasal cluster nor a common V2 is securely attested. No metathesis is required.',
        'Botanical identifications and semantic breadth need primary lexicographic checking. The Kannada Latin genus record Alysicarpus is a parsing artifact. This narrow comparison is useful for recording uncertainty, not for proving a PDr unchanged control.',
        {'Telugu':('R','alamu','Initial ordering retained, but exact input uncertain.'),
         'Kannada':('R','alabu|alubu','Quality variants with same initial ordering.'),
         'Gondi':('B','allam','Explicit Telugu loan, no independent innovation.')},
        eligibility='narrow-comparison-control',references='DEDR 244',input_confidence='low',
        boundary='No secure independent formative boundary; reconstructed nasal cluster is only a hypothesis.')

    add('d245','chatter, roar, noise','*al-a- with *-r/ṟ, *-mp and other extensions',
        'Ø','a','l','a','VC-a-C','verb/noun',
        'Tamil alappu/alampu/alaṟu, Malayalam alappu/alaṟuka and Old Kannada alaṟu support a low-vowel initial al-a- base independently. Telugu has different alikiḍi/alabalamu formations.',
        'Independent southern arousal/noise stems support a before l; Irula lā·ru is plausibly an innovative initial-loss/contraction outcome of the roaring derivative.',
        '*al-aṟ- > alaṟu in Tamil/Old Kannada; possible *alaṟ- > *lāṟ- > Irula lā·ru. This could involve vowel coalescence with apical displacement or aphaeresis and compensatory lengthening. Telugu alikiḍi has a high-vowel extension not identical to the roaring stem.',
        'Do not group by expressive meaning to exempt words from sound change: the morphological and segmental inputs still need reconstruction. Malayalam aḷavan boaster is explicitly an alternative comparison with measure d296, so retroflex ḷ is not silently regularized to l. Irula length and donor/native status require a local source history before counting a shared SCDr innovation.',
        {'Telugu':('R','alikiḍi|alabalamu','Retained ordering in different noise-noun formations.'),
         'Tamil':('R','alappu|alampu|alaṟu|alar','All root extensions retain initial order.'),
         'Malayalam':('A','alappu|alaṟuka|alavan|aḷavan','Native low-vowel forms retained; retroflex boaster may belong to measure family.'),
         'pampa':('R','alaṟu','Old Kannada source PBh.; original order retained.'),
         'Irula':('A','lā·ru','Initial loss/contraction plausible; exact mechanism and historical transmission unresolved.')},
        references='DEDR 245; compare DEDR 296',input_confidence='high',
        boundary='Distinct -pp/-mp/-ṟ verbal extensions independently compared; Telugu suffixes are not forced into the same shape.')
    tokens('d245','Malayalam',R='alappu|alaṟuka|alavan',A='aḷavan')

    add('d246','wash, rinse, smear','*al-ay- / *al-a-mp- / *al-a-k(k)-; *al-uk-',
        'Ø','a','l','a/u','VC-V-C','verb/noun',
        'Tamil alaicu/alampu, Malayalam alakkuka/alampuka and Kannada ale/alambu independently support vowel-first al- and low-vowel formations. Kannada alumbu and Telugu aluku supply high-vowel variants.',
        'Southern cognates favor earlier initial al-. Tulu lumbuni can be derived directly from the attested alumbuni by aphaeresis; Kui akali requires a different account of k and l positions.',
        '*al-amp- > retained alamp-/alamb-; *al-ump- > Tulu alumbuni > lumbuni by initial a loss. Telugu alãdu and aluku have separate consonantal extensions. Conditional *al-akk- > *ak-al- > Kui akali would be nonadjacent consonant transposition, but the exact input/formation is not independently established.',
        'Tulu retains u after l and a nasal cluster, so an initial vowel/stop exchange is unnecessary. Kui akali is genuinely printed in a Kui vocabulary, with akali-pakali and light-verb constructions; it is not merely a Jambu typo. The existence of that noun does not prove its DEDR etymology. Toda as̱p- lacks l and may involve a local lateral-plus-stop development; its exact history must be checked separately.',
        {'Telugu':('R','alamu|alãdu|aluku','Original initial order retained across different derivatives.'),
         'Tamil':('R','alaicu|alampu|alacu|alaittal','Source/dialect labels and duplicate DEN attestation retained, not counted twice.'),
         'Malayalam':('R','alakkuka|alampuka','Low-vowel extensions retain order.'),
         'Kannada':('R','ale|alambu|alumbu|alasu','V2/extension differences retain initial order.'),
         'Tulu':('O','alambuni|alumbuni|lumbuni','Attested precursor alumbuni supports direct aphaeresis.'),
         'Toda':('A','as̱p- (as̱py-)','Consonant correspondence requires local phonological analysis.'),
         'Kui':('A','akali','Possible nonadjacent l/k transposition or different etymology; not initial apical displacement.')},
        references='DEDR 246; Winfield 1929, A Vocabulary of the Kui Language, p.3; NBU handle 123456789/1942 (title and entry visually checked)',
        input_confidence='high',mechanism='Retentions plus independent aphaeresis; possible other consonant metathesis in Kui',
        boundary='-ay, -mp, -kk and -k extensions have independent southern evidence; no single suffix is assigned to all.')
    tokens('d246','Tulu',R='alambuni|alumbuni',O='lumbuni')

    add('d247','blossom, expand, flower','*al-ar- (two distinct liquids)',
        'Ø','a','l','a','VC-VC with L...R','verb/noun',
        'Tamil alar, Malayalam alar and Telugu alaru support older l...r order, independently of Kannada/Tulu variants. Kannada retains alar beside aral/araḷ, so both orders occur within one language.',
        'Concordant l...r in Tamil, Malayalam and Telugu plus retained Kannada alar favors *alar > aral, not *aral as the uniform family input. There is no evidence that the initial vowel has moved.',
        '*alar > Kannada/Tulu aral by nonadjacent consonant metathesis; *aral > araḷ by a separate lateral change. Kannada alal may instead reflect r-to-l assimilation. Kannada arlu involves medial syncope, plausibly after the r...l ordering had developed.',
        'This is a real comparative metathesis candidate outside Telugu, but a different process from initial apical promotion. R in the main outcome matrix means the target initial V–apical order remains; an orthogonal process annotation records the l/r exchange. DEDR tentatively relates beauty d248, which must be collapsed in a conservative family sensitivity. Marathi araḷ/arala is a contact comparison, not an independent Dravidian language vote.',
        {'Telugu':('R','alaru|alarcu','Older l...r order preserved; causative/extension retains it.'),
         'Tamil':('R','alar|alari|alarttu','Older liquid order, no initial promotion.'),
         'Malayalam':('R','alar|alaruka','Older liquid order.'),
         'Kannada':('R','alar|aral|araḷ|alal|arlu','No initial apical promotion; l/r exchange and assimilation are separately annotated.'),
         'Tulu':('R','alaruni|araluni|araḷuni','Both liquid orders, no initial apical promotion.'),
         'Badaga':('R','araḷu','r...l order, possibly shared with or transmitted from Kannada; independent date unknown.')},
        references='DEDR 247 and editorial cross-references to DEDR 248 and Marathi',input_confidence='high',confidence='high',
        mechanism='Nonadjacent l...r > r...l metathesis in Kannada/Tulu; no initial-vowel displacement',
        boundary='Whether -ar is a separable formative is unresolved; the consonant order is directly comparable.')

    add('d248','beauty, please, shine','*al-ar-? beside *al-amp-?',
        'Ø','a','l','a','VC-a-C; different extensions','noun/verb',
        'Tamil alari and Telugu alarincu/alarāru support al-ar; Kannada alampu has a different labial/nasal extension and lampu lacks initial a.',
        'Vowel-first ordering is supported by the Tamil/Telugu comparison and by Kannada alampu itself. The lampu variant is therefore an innovation, without requiring a displaced shared proto-root.',
        'Kannada alampu > lampu by aphaeresis gives the attested short a directly. Telugu alarāru is an extended shine/suit verb retaining initial al-; its internal long vowel is not evidence of initial metathesis.',
        'DEDR tentatively cross-refers to blossom d247; the overlapping shine/rejoice semantics suggest a derivative relationship, but do not prove it. Treat root-family merging as a sensitivity test. Kannada -mp versus -r needs a derivative or cognacy account independent of aphaeresis.',
        {'Telugu':('R','alarincu|alarāru','Retained initial sequence in extended forms.'),
         'Tamil':('R','alari','Retained form, probable semantic derivative of flower family.'),
         'Kannada':('O','alampu|lampu','Direct attested aphaeresis alternation; final derivative differs from Tamil/Telugu.')},
        eligibility='core-formation-uncertain',references='DEDR 248,247',input_confidence='medium',
        mechanism='Local Kannada aphaeresis, not proof of SCDr vowel–apical metathesis')
    tokens('d248','Kannada',R='alampu',O='lampu')

    add('d249','habit, become accustomed','Telugu ala-vaḍ-/ala-vaṟ-; earlier independent base unknown',
        'Ø','a','l','a','VCV + verbal element','verb/noun',
        'Telugu ala-vaḍu, ala-vaṟucu and ala-vāṭu show local derivative alternation. The Tamil alavāṭṭu is explicitly borrowed from Telugu, so it supplies no independent earlier input.',
        'The current evidence gives only a local vowel-first stem, not a comparative proof of a Proto-South-Central *ala-. The database starred PSD2 root overstates what this isolated group can establish.',
        'Telugu ala-vaḍu : ala-vaṟucu : ala-vāṭu exhibits verb/causative/nominal morphology. No initial consonant movement is observed; chronology and origin of the first component are unknown.',
        'This cannot become a secure retained sound-law counterexample merely because it looks like ala-. Conversely, absence of independent cognates does not prove it entered Telugu too late for the sound change. A dated early compound and independently cognate first member would resolve eligibility.',
        {'Telugu':('R','ala-vaḍu|ala-vaṟucu|ala-varincu|ala-vāṭu','Only local derivative evidence; no initial promotion.'),
         'Tamil':('B','alavāṭṭu','Source explicitly gives Telugu loan.')},
        references='DEDR 249',eligibility='single-language-input-uncertain',input_confidence='low',
        boundary='Local compound/derivative segmentation plausible, proto-stage not independently recovered.')

    add('d259','bowstring','*al-k-?; weaving-family formation',
        'Ø','a','l','Ø','VC-C','noun',
        'Parji alka and Telugu alle/alliya support al- plus a possible consonantal extension; DEDR explicitly cross-refers to weave d260.',
        'Both languages keep the initial vowel. If the forms are cognate, lk > ll accounts for Telugu without moving l across the vowel.',
        '*al-k- > alka in Parji; *alk- > *all- > alle/alliya in Telugu with progressive cluster assimilation and nominal-final development. A stem without *k plus distinct formations is also possible.',
        'Count together with weave d260 in the conservative main family partition; the bowstring is a plausible woven-product noun, not automatically a separate root. The absence of an attested Telugu k-bearing precursor keeps the assimilation route conditional.',
        {'Telugu':('O','alle|alliya','Probable lk>ll assimilation, initial vowel retained.'),
         'Parji':('R','alka','Preserves the medial cluster, no initial movement.')},
        family='d259+d260',references='DEDR 259,260',eligibility='consonantal-formation-control',
        input_confidence='medium',mechanism='Possible progressive cluster assimilation; no initial apical displacement',
        boundary='Consonantal -k may be an instrument/product formative; relationship to weaving supported by semantics and source cross-reference.')

    add('d260','weave, plait, intertwine','*al- with consonantal *-p/-t and strengthened *all-',
        'Ø','a','l','Ø','VC-C / VC and VCC derivatives','verb/noun',
        'Kolami al-, Konda al-/aṛ-, Kui alpa and Kuvi al- support a singleton lateral root and consonantal extensions. Tamil/Kannada/Telugu allu is a strengthened formation, not proof that the entire proto-root was geminate.',
        'SD I, SD II and Central Dravidian agree on an initial vowel before the lateral. There is no evidence that the root began l- and acquired a independently in every branch.',
        '*al-p- > Konda/ Kui alpa; *al-t- gives relevant tense/extended clusters; strengthened *all- > Telugu/Tamil/Kannada allu. Konda al- : aṭ-/aṇ- reflects separately conditioned tense allomorphy. None requires initial movement.',
        'Five forms assigned Gondi in the corpus are actually under the Konda heading in DEDR p.25; research corrections are ID-specific and preserve original labels. The only genuine Gondi form is Koya all-. Brahui allī has an explicit source question mark and cannot prove inherited North Dravidian cognacy. Bowstring d259 is conservatively one root family; creeper d207 is a further uncertain relationship, with r-bearing evidence that could indicate a different earlier root.',
        {'Telugu':('R','allu|alluḍu','Strengthened root and derived noun retain order.'),
         'Tamil':('R','allu','Strengthened root retained.'),'Kannada':('R','allu','Same root order.'),
         'Gondi':('R','all','Only Koya all- is correctly labeled Gondi; contact with Telugu possible but not stated.'),
         'Konda':('R','al- (aṭ-, aṇ-)|alpa- (-t-)|aṛpa- (-t-)|aṛ|alṭay ā','Corrected language labels from original source; consonantal formations retain order.'),
         'Kui':('R','alpa (alt-)','Consonantal formative yields internal lp, no initial displacement.'),
         'Kuwi':('R','allinai|al- (-it-)','Source variants of singleton/strengthened stem.'),
         'Kolami':('R','al- (alt-)|all','Singleton/strengthened forms retain order.'),
         'Naikri':('R','all','Strengthened root retained.'),
         'Parji':('R','alc|alṭ|alṭayp- (alṭayt-)','Various medial consonantal extensions, no initial promotion.'),
         'Gadaba':('R','all','Salur form, order retained.'),
         'Brahui':('A','allī','Source explicitly marks cognacy questionable.')},
        family='d259+d260',c2_structure='singleton-and-geminate-formations',eligibility='consonantal-formation-control',
        references='DEDR 260 p.25 and 259; original DSAL p.25 directly inspected',input_confidence='high',
        boundary='Consonantal p/t and tense allomorphs independently documented in Konda, Kui and Kolami; geminate southern stems are kept distinct.')
