"""Individually reviewed initial ir/il lexical families; primary sources override display heads."""

def populate(add,tokens):
    add('d475','jujube','regional *ir-a-; nasal/velar and dental tree-name formations',
        'Ø','i','r/l','a','VC-a-NC / VC-a-C','noun',
        'Tamil irati/irantai/ilantai, Malayalam ilanta and Kannada era/elaci support an initial vowel and medial liquid independently. The exact nasal-velar formation of Telugu rē̃gu is not matched by every southern tree name.',
        'Independent retained southern forms favor earlier ir-/il- order. Original DEDR p.46 supplies actual Telugu rē̃gu/rēnu; the database instead mislabeled Kolami rēŋga as Telugu and omitted those Telugu forms.',
        'Conditional *ir-aŋk > *eraŋk > *rēŋk > Telugu rē̃gu, with voicing/nasal developments; rēnu requires a different consonant change or variant. Tamil r/l alternation and dental rather than velar suffix need separate formation histories. Malayalam ilanta > lanta is straightforward initial vowel loss.',
        'Kannada rēgu is explicitly borrowed from Telugu. Gondi, Kolami, Naikri/Naiki, Parji and Gadaba rēŋg-type tree names might spread with the plant name; no independent innovation is inferred just from initial r. More southern velar derivatives or historical recipient attestations would discriminate inheritance from diffusion. Malto ilkru has a different cluster. Source supplements do not add roots.',
        {'Telugu':('D','rē̃gu|rēnu','Probable displacement; fuller nasal/velar history conditional.'),
         'Tamil':('R','irati|iratti|irantai|ilantai|ilatai','Liquid and dental/nasal variants preserve order.'),
         'Malayalam':('O','ilanta|lanta','Retained and initial-loss variants.'),
         'Kannada':('A','era|elaci|elci|eḷaci|ilici|egaci|rēgu','Retained/local consonant variants plus explicit Telugu loan.'),
         'Gondi':('A','rēŋgā','Regional tree-name diffusion versus inherited displacement unresolved.'),
         'Kolami':('A','rēŋga|reŋā','Corrected source language; possible Telugu-area loan.'),
         'Naikri':('A','rēŋga','Possible regional loan.'),'Naiki':('A','rēŋga','Possible regional loan, distinct source lect retained.'),
         'Parji':('A','rē̃ga','Possible regional loan.'),'Gadaba':('A','rēŋ','Possible regional loan.'),
         'Malto':('A','ilkru','Vowel-first wild-plum comparison, exact cluster/cognacy unresolved.')},
        references='DEDR 475 p.46 directly checked; Southworth 2006 imported *irak is a proposal, not an attestation',
        input_confidence='medium',boundary='Low vowel independently observed; exact dental/nasal/velar tree-name formatives are not assumed identical.')
    tokens('d475','Malayalam',R='ilanta',O='lanta')
    tokens('d475','Kannada',R='era|elaci|elci|eḷaci|ilici',A='egaci',B='rēgu')

    add('d476','deer, antelope','*ir-al-ay, r/l order variation',
        'Ø','i','r','a','VC-a-C-ay','noun',
        'Tamil iralai and Kannada/Tulu eraḷe agree on initial vowel and r before later lateral; Malto ilaru has the liquids in the opposite order. Old Telugu iri also begins with a vowel.',
        'The southern r...l agreement favors earlier *iral provisionally; Malto may show internal liquid reversal. Telugu lēḍi would require movement of a different liquid and an additional final consonant history, not just initial i/r metathesis.',
        'Retained *iralay > eraḷe in Kannada/Tulu; reduced Old Telugu iri and strengthened iṟṟi require morphological/cluster changes. A proposed *ilara > *lēra > lēḍi path would need both an independent liquid reversal and a regular r/ḍ development; neither is established by this set.',
        'DEDR explicitly prefixes a question mark to Telugu lēṭi/lēḍi. Keep them uncertain rather than forcing them into a lateral-metathesis class. Malto internal reversal is separately plausible but not proved directionally by simple majority. Badaga iya may reflect liquid loss but is source-uncertain. Historical iri is the reliable Telugu retained comparison.',
        {'Telugu':('A','iṟṟi|lēṭi|lēḍi','Retained-order strengthened noun, plus explicitly queried l-initial antelope words.'),
         'OTelugu':('R','iri ( irulu)','Historical stag noun; plural stem retains ordering.'),
         'Tamil':('R','iralai','Independent r...l formation.'),'Kannada':('R','eraḷe|erale','Lateral quality variation, vowel-first.'),
         'Tulu':('R','eraḷe','Vowel-first noun.'),'Malto':('A','ilaru','Possible internal r/l reversal, exact ancestry unresolved.'),
         'Badaga':('A','iya','Possible liquid loss, source-cognacy uncertainty.')},
        references='DEDR 476 p.46 directly checked, including question mark before lēṭi/lēḍi',input_confidence='medium',
        boundary='Whole deer noun compared; later l/ḍ material in Telugu has no demonstrated identical formative ancestry.')
    tokens('d476','Telugu',R='iṟṟi',A='lēṭi|lēḍi')

    add('d477','cassia tree','*ir/ṟ-al/ḷ-i; regional liquid identity uncertain',
        'Ø','i','r/ṟ','a','VC-a-C-i','noun',
        'Tamil iraḷi/iṟali preserves an initial vowel plus two differently ordered-quality liquids. Kannada/Telugu rēla and Gondi rēlā share an r-initial plant name; only Tamil supplies the unshifted word here.',
        'Earlier *iral- is plausible by the low-vowel contraction correspondence, but a Tamil prothetic adaptation of a regional rēl word remains possible without wider retained evidence.',
        'Conditional *iral > *eral > *rēl > Telugu rēla-ceṭṭu; historical ṛēla gives an older r-initial attestation. Gondi rērkā requires an added velar and lateral/rhotic change; Kannada and Gondi may have borrowed the tree name.',
        'Do not treat the imported *rēl as proved proto-input or Tamil as necessarily conservative. The old Telugu rhotic is transcribed ṛ in this source and should not be assigned a phonetic value without its inscriptional edition. Cassia is a Latin gloss incorrectly parsed as Telugu. Exact cognacy/donor history keeps this out of the decisive reconstructed-input cohort.',
        {'Telugu':('A','rēla-ceṭṭu','Probable initial-displacement plant name, but direction/contact unresolved.'),
         'OTelugu':('A','ṛēla','Historical initial-r attestation; input direction remains uncertain.'),
         'Tamil':('R','iraḷi|iṟali','Sole unshifted witness, liquid variants preserved.'),
         'Kannada':('A','rēla','Potential Telugu-area diffusion.'),'Gondi':('A','rēlā|rērkā','Regional forms with divergent final morphology.')},
        references='DEDR 477 p.46 directly checked',eligibility='cognacy-or-input-uncertain',input_confidence='medium',
        boundary='Plant-name ending independently present in Tamil; exact historical donor and rhotic quality unestablished.')

    add('d480','be, sit, abode','*ir-u-; *ir-u-v / *ir-a-v place nouns',
        'Ø','i','r','u/a','VC-u / VC-V-v / VC-C formations','verb/noun',
        'Tamil iru/iruppu, Kannada iru/irdu and Kodagu ir- independently support a vowel-first existential root. Telugu iruvu/iravu retains noun formations; Malayalam irippu differs in formative vowel from Tamil iruppu.',
        'The broad existential comparison favors earlier ir-. Kui rīnda/rīspa is innovative under its related steady/stand meaning, but its high-i length and added consonants require separate reconstruction.',
        'Retained *iru-v > Telugu iruvu, with a-bearing iravu; Kannada irke > ikke and Telugu ikka are compatible with medial syncope plus assimilation. Tulu ippuni/itt- can continue r+labial/dental cluster assimilation. Kui *ir-i-nt/*ir-i-sp could yield rīnda/rīspa, but i in those exact formations is not independently established. Kota ig-/ir-/it- is a paradigm, not initial promotion.',
        'Low-vowel Telugu iravu must not be erased by choosing only the high-u root label. Telugu iŋkuva has DEDR’s explicit alternative demonstrative iṅku d420. Kui rītka includes plural morphology and possible consonant-order changes, not another etymon. Badaga negative illa/ille is cross-linked but belongs to a separate negative-base analysis, not straightforward irregular sound change of iru.',
        {'Telugu':('O','iravu|iruvu|irugu|iravāru|iravupaḍu|ikka|iŋkuva','Retained stems, medial assimilation candidate and alternative demonstrative derivation.'),
         'Tamil':('R','iru|iruppu|irukkai|iruttu','Existential and causative/nominal formations retain order.'),
         'Malayalam':('R','irikkuka|irippu|iruttuka','Different high formative, retained order.'),
         'Kannada':('O','iru (irdu, iddu)|ir|irke|ikke|iravu|irapu','Retained roots and medial cluster assimilation.'),
         'Kodagu':('R','ir- (-ipp-, iñj-)','Retained initial ordering across inflection.'),
         'Kota':('A','ig- (ir|it-)|irp|igc- (igc-)','Database splits the irregular paradigm; fire causative needs semantic/derivational check.'),
         'Toda':('R','ɨr-|ɨθ-|ɨṣt-|īṣk','Medial changes and quantity alternations preserve first vowel.'),
         'Tulu':('O','ippuni (itt-)','Medial apical assimilation/loss, no evidence of initial promotion.'),
         'Kui':('D','rīnda (rīndi-)|rīspa (rīst-)|rītka (rītki-)','Displacement probable; exact high-vowel and plural-formation history unresolved.'),
         'Kuwi':('A',"re'nai",'Vowel and consonant/morphological correspondence not yet independently recovered.'),
         'Badaga':('R','iru','Retained existential; negative and compounds not counted independently.')},
        references='DEDR 480; DEN1 p.400 entry407; K03 existential reconstruction; alternative d420 for iŋkuva',input_confidence='high',
        boundary='Existential high-u root and a/u place-noun formations distinguished; Kui suffix vowels not chosen from outputs.')
    tokens('d480','Telugu',R='iravu|iruvu|irugu|iravāru|iravupaḍu',O='ikka',A='iŋkuva')
    tokens('d480','Kannada',R='iru (irdu, iddu)|ir|irke|iravu|irapu',O='ikke')
    tokens('d480','Kota',R='irp',A='ig- (ir|it-)|igc- (igc-)')

    add('d481','great, vast','*ir-u, compound-bound; Telugu inu-',
        'Ø','i','r','u','VC-u + compound member','adjective',
        'Tamil iru great and irumai greatness provide the independent rhotic comparison; Telugu has inu- in compounds, especially inumikkili very great.',
        'Tamil rhotic versus Telugu nasal can reflect assimilation before a following m in the compound. There is no evidence of r moving before the initial vowel.',
        'Conditional *iru-mikkili > *inu-mikkili by anticipatory nasal influence, followed by extraction/generalization of inu- as a combining form. Compare Telugu inu māṟu twice (d474) and inumu iron (d486), without assuming all three have identical history.',
        'Only a narrow two-language adjective comparison; no free Telugu inu paradigm is supplied, and the corpus inu is an in-construction fragment. Do not classify it as metathesis concealed by r loss unless an initial r-stage is independently attested. Compound-bound status is visible before outcome classification.',
        {'Telugu':('O','inu|inumikkili','Nasalized compound base, not apical promotion.'),'Tamil':('R','iru|irumai','Retained rhotic adjective and noun.')},
        references='DEDR 481; DEN2 p.475 S²9',eligibility='compound-formation-control',input_confidence='medium',
        boundary='Only Telugu combining form attested; following m is independently present in the comparison compounds.')

    add('d483','blackwood tree','*ir-u-? plus tree-name formations; bīṭi series uncertain',
        'Ø','i','r','u','complex plant-name derivatives','noun',
        'Malayalam iruviḷ/irūḷ, Kannada iruguṇḍi and Telugu iruguḍu/iruvuḍu support a vowel-first dark/tree component, tentatively compared with darkness d2552. Tamil īṭṭi and Tulu bīṭi differ too much to be the same simple input.',
        'A retained ir-u formation is credible for part of the set. The b/v-initial wood names may reflect another tree word, compound reduction or contact, rather than relocation of r.',
        'Telugu iruguḍu/iruvuḍu retain ir-; ibbaḍa/ibbeḍa could reflect reduction/assimilation in a different compound or stem. Deriving bīṭi from iruguḍu by metathesis alone is impossible; additional consonant loss and formation differences are required.',
        'Keep the complex plant-name family uncertain for inherited-law counts. The fact that blackwood can be named after darkness is a semantic hypothesis, not evidence for every segment. Tulu kari-bīṭi independently adds black, which can support either reinforcement or a different lexical base. No unsupported chain is selected.',
        {'Telugu':('A','iruguḍu|iruvuḍu|ibbaḍa|ibbeḍa','Vowel-first ir stems plus reduced/assimilated variants of uncertain full ancestry.'),
         'Malayalam':('A','iruviḷ|irūḷ|vīṭṭi','Different dark/wood formations or contact words.'),
         'Kannada':('A','iruguṇḍi|ibaḍi|ibbaḍi|bīṭe','Complex family; no single deterministic change proposed.'),
         'Tamil':('A','īṭṭi','Long vowel and geminate, precise relationship unresolved.'),
         'Tulu':('A','bīṭi|kari-bīṭi','No initial-r movement observable; wood-name component distinct.')},
        references='DEDR 483; tentative darkness comparison d2552',eligibility='complex-or-contact-input-uncertain',input_confidence='low',confidence='low',
        boundary='Plant-name segmentation remains uncertain; do not infer a simple proto-root from one surface variant.')
    tokens('d483','Telugu',R='iruguḍu|iruvuḍu',A='ibbaḍa|ibbeḍa')

    add('d484','axle','*ir-u-c/s; regional technical term',
        'Ø','i','r','u','VC-u-C','noun',
        'Tamil irucu, Kannada irucu/iricu/iracu and Telugu irusu support vowel-first r plus a final coronal; second-vowel alternatives are independently attested.',
        'Vowel-first order agrees across the independent southern witnesses. Gondi/Kuvi/Gadaba forms are explicitly Telugu loans and cannot supply independent confirmation.',
        '*ir-u-c > Telugu irusu is a possible coronal correspondence; Kannada ircu has medial syncope without initial movement. Gondi nirsu adds initial n and Kuvi hīrsū adds h/length after borrowing; these do not move r to word beginning.',
        'Preserve a high-u control but flag the technical lexeme’s undated dissemination. Its possible wider loan origin should be researched before treating it as ancient inherited vocabulary. Kolami i·rcu is not explicitly marked a loan in this snippet, but its length and donor chronology remain uncertain. Parser Br/Early-Vedic tag on that form is not evidence of a Dravidian dialect.',
        {'Telugu':('R','irusu','High-u order retained.'),'Tamil':('R','irucu','Independent high-u form.'),
         'Kannada':('R','irucu|iricu|iracu|ircu|irci|irasu|era-kōlu','Vowel/compound variants, all retain vowel before r.'),
         'Gondi':('B','irsu|irs|nirsu','DEDR explicitly < Telugu; n addition in recipient.'),
         'Kuwi':('B','hīrsū','DEDR explicitly < Telugu; h and length recipient developments.'),
         'Gadaba':('B','irsu','DEDR explicitly < Telugu.'),'Kolami':('A','i·rcu','Retained order but contact chronology unresolved.')},
        references='DEDR 484',eligibility='core-formation-uncertain',input_confidence='high',
        boundary='Whole technical stem compared; u/i/a variation recorded independently, origin and date of dissemination unresolved.')

    add('d485','mahua tree','*ir-u-ppay / *ir-V-p; r/l variants',
        'Ø','i','r','u','VC-u-PP-ay / VC-C','noun',
        'Tamil iruppai/iluppai/irumpai, Malayalam iruppa/iluppa, Tulu irippe and Gondi/Parji irup support initial vowel plus liquid and a labial formation. Kui irpi : ripi directly attests the relevant short closed-syllable alternation.',
        'Shared vowel-first forms and attested irp clusters favor earlier irup > irp. Kui ripi is an initial i/r reversal of a structure independently present as irpi, unlike Telugu ippa, where the first vowel remains.',
        '*ir-up(p) > *irp(p) > Telugu ippa through medial assimilation/loss, matched by Tamil ippai and Kannada ippe. Kui irpi > ripi exchanges initial vowel and rhotic with no added length; this can follow medial syncope. Kuvi irpi retains that same cluster. Gondi hirp/hiruk and long forms have h/quantity/plural morphology separate from initial displacement.',
        'The same plant family offers competing outcomes: retention, medial assimilation and short displacement. It does not establish that metathesis occurred to prevent assimilation as a purposeful process. Konda ipa maran could be an assimilated inherited base or contact form. Badaga irippe kāi is glossed as chironji, not mahua, so cognacy/species association is uncertain and should be checked against d2628.',
        {'Telugu':('O','ippa','Medial apical loss/assimilation; no evidence for a prior initial r-stage.'),
         'Tamil':('O','iruppai|iluppai|irumpai|ippai','Retained variants plus assimilation.'),
         'Malayalam':('R','iruppa|irippa|iluppa|ilippa','r/l and u/i variants preserve initial order.'),
         'Kannada':('O','ippe|hippe','Assimilation/loss plus possible h addition.'),
         'Tulu':('O','irippe|ippe','Attested full and assimilated forms.'),
         'Gondi':('R','irp|irpi|irup|iṛum|hirp|hiruk|hirūk|īruk|iṛū|īṛu māṛa','Order retained across source lects and tree/flower formations.'),
         'Konda':('O','ipa maran','Medial-loss/assimilation candidate, possible Telugu contact.'),
         'Kui':('M','irpi|ripi','Unshifted and metathesized variants; K. source label on ripi preserved.'),
         'Kuwi':('R','irpi|irpi kāṛu','Retained base and liquor compound.'),
         'Kolami':('O','ippa|ippā','Medial assimilation/loss or contact, not initial promotion.'),
         'Naiki':('R','irpu','Retained cluster.'),'Parji':('R','irup|irpa','Full and syncopated forms.'),
         'Gadaba':('R','irpa','Retained vowel-first cluster.'),
         'Badaga':('A','irippe kāi','Different botanical gloss; species/cognacy needs verification.')},
        references='DEDR 485; DEN1 p.400 entry410; K03 reconstruction *ir-u-ppay',input_confidence='high',
        boundary='Labial plant-name formation independently attested; exact vowels and nasal/geminate variants retained rather than flattened.')
    tokens('d485','Tamil',R='iruppai|iluppai|irumpai',O='ippai')
    tokens('d485','Tulu',R='irippe',O='ippe')
    tokens('d485','Kui',R='irpi',D='ripi')

    add('d486','iron','regional *ir-ump; earlier *cir-ump proposed',
        'Ø','i','r','u','VC-u-NP','noun',
        'Tamil/Malayalam irumpu and Kodagu irɨmbɨ support initial vowel, liquid and labial nasal-stop. The proposed initial c belongs to a deeper darkness comparison d2552, not an attested initial consonant in these iron words.',
        'The independent southern words establish earlier irump- for the regional comparison. Kui rumba has lost the first vowel under a straightforward account; its surviving vowel is the original u, so literal i/r exchange is not independently demonstrated.',
        '*irump > Telugu inumu may combine weakening of mp and anticipatory nasal influence on r; the exact sequence is unresolved. Kota/Toda ib requires medial cluster simplification. Kui irumba > rumba is compatible with aphaeresis; a displacement-plus-vowel-assimilation route is possible but adds unsupported steps here.',
        'Iron is a cultural term, so the time of lexical diffusion and possible deep *c loss matter. Neither Telugu n nor absence of r in Kota/Toda proves concealed metathesis. Kolami inum may be borrowed from Telugu; no independent event is counted. Compare inu-mikkili d481 and inu māṟu d474 for a testable r/n-before-m pattern, without declaring it exceptionless yet.',
        {'Telugu':('O','inumu','Medial nasal/cluster changes, no evidence of initial promotion.'),
         'Tamil':('R','irumpu','Independent high-u nasal-labial input.'),'Malayalam':('R','irumpu|irimpu','Formative-vowel variation, retained order.'),
         'Kodagu':('R','irɨmbɨ','Retained order with central vowel/voicing.'),'Kota':('O','ib','Medial simplification, initial vowel survives.'),
         'Toda':('O','ib|ɨb','Needle as semantic extension; initial vowel survives.'),
         'Kui':('A','rumba vaḍi','Ironstone compound, likely initial vowel loss; not a decisive exchange of i and r.'),
         'Kolami':('A','inum ( inmul)','Possible Telugu loan; plural allomorph not another etymon.')},
        references='DEDR 486; K03 deeper *cir-umpu reconstruction; darkness d2552',input_confidence='high',
        boundary='Regional ir-ump formation independently supported; deep initial c and cultural diffusion require separate evidence.')

    add('d489','roar, noise, cough','*ir-a/um(p)- versus expressive *ramp-; direction uncertain',
        'Ø','i','r','a/u','VC-V-NP or original expressive CVC','verb/noun',
        'Tamil irai/iraŋku/irumu and Malayalam irampuka/irumal have vowel-first forms, whereas Kannada/Kodagu/Tulu/Telugu ramp/ramb forms cluster in expressive noise senses. DEDR calls Telugu ṟ probably expressive.',
        'An earlier iramp with local initial loss is plausible, but expressive r-initial formation and later southern prothesis or contamination also fit. Neither a modern Tamil word nor the imported *ramp head alone establishes direction.',
        'Conditional iramp > ramp by aphaeresis retains the following a. A regular lowered i+a contraction would instead need an explained route from ē to a/shortness; that route is not established. Cough irum- may be a distinct derivative or related expressive formation, not the exact same input as rampu.',
        'Keep this outside the secure inherited input cohort. Sanskrit-like aspirated rambʰa/rambʰāṭa forms warrant a contact/source check; aspiration is not proof of inherited Proto-Dravidian phonology. Parji ran ban is an echo-like expression with a different second component. Need historical unshifted ramp-family attestations or a reliable donor history to choose among analyses.',
        {'Telugu':('A','ṟampu|ṟampilu|ṟampillu|rampilu','Expressive rhotic and related derivatives, direction unresolved.'),
         'Tamil':('R','irai|iraŋku|irumu|irumal|iraippu','Vowel-first noise/cough formations; not all assumed one exact proto-stem.'),
         'Malayalam':('R','irampuka|irampal|irumal|ireppu|erampam','Retained order with independent vowel variants.'),
         'Kannada':('A','rampa|rambu|rambʰa','Initial-r expressive/contact history unresolved.'),'Kodagu':('A','rampa','Possible Kannada contact or local loss.'),
         'Tulu':('A','rambāroṭi|rambārūṭi|rambʰārūṭi|rambʰāṭa','Complex expressive words, no single unsupported derivation.'),
         'Kolami':('A','rampam','Possible Telugu-area diffusion.'),'Parji':('A','ran ban','Echo-like formation; exact cognacy unresolved.')},
        references='DEDR 489; DEN1 p.400 entry414; source expressive ṟ note',eligibility='expressive-or-contact-input-uncertain',
        input_confidence='low',confidence='low',boundary='a/u and echo/compound formations differ; no outcome-selected common vowel assigned.')

    add('d494','house','*il; strengthened free form *ill-u/am',
        'Ø','i','l','none','VC root / VCCV free form','noun',
        'Tamil/Malayalam il, Konda ilu, Pengo/Manda il and Telugu illu support a monosyllabic lateral root with strengthened free forms. Seven imported *iẓi descend paradigm reconstructions are erroneous links, not alternative house inputs.',
        'The wide vowel-first house root supports original il. Kui iḍu changes the medial lateral realization without moving it before the initial vowel.',
        '*il > illu/illam in free/extended forms; language-specific oblique stems include Telugu iṇṭi and Pengo inj-. Those require oblique suffix/cluster assimilation, not an initial metathesis. Konda ilku and Kuvi ilka preserve a lateral before plural material.',
        'Classify the independently supported VC root and strengthened free form separately from a hypothetical singleton VCV input. Do not use the spurious *iẓi data to predict displacement in house. Kolami iltam is explicitly a Telugu loan tied to residence with a wife’s family; related iltāmā may be contact-associated, whereas ella house is a separate retained-order witness.',
        {'Telugu':('R','illu ( iṇṭi)|illaṭamu|illaṇṭramu','Initial order retained; oblique allomorph and residence derivatives distinguished.'),
         'Tamil':('R','il|illam|illāḷ|illāḷaṉ','Bare root and strengthened/compound forms.'),'Malayalam':('R','il|illam','Bare and extended noun.'),
         'Kodagu':('R','illavən','Relative/person compound, initial order retained.'),'Tulu':('R','illɯ','Strengthened free form.'),
         'Gondi':('R','il','Adilabad source root.'),'Konda':('R','ilu ( ilku)','Singular/plural preserve order.'),
         'Kui':('R','iḍu','Medial lateral-to-stop outcome, no promotion.'),'Kuwi':('R','illu|illū ( ilka)|il ( ilka)','Quantity and number variants retain order.'),
         'Pengo':('R','il ( inj-, ilku)','Oblique/plural stem variants retain initial vowel.'),'Manda':('R','il','Bare root.'),
         'Kolami':('A','ella|iltam|iltāmā','Native-looking house base plus source-marked/candidate Telugu residence loans.'),
         'Naikri':('R','ella','House noun retains order.'),'Parji':('R','il podi','House root in roof compound.'),
         'markodi':('R','illŭ','Three source lects, one root.')},
        references='DEDR 494; K03 *il house versus *iẓi descend (d502) distinguished',eligibility='root-shape-control',
        c2_structure='root-final-singleton-with-strengthened-free-forms',input_confidence='high',
        boundary='VC bare root, free-form strengthening and oblique/plural morphology independently visible across languages.')
    tokens('d494','Kolami',R='ella',B='iltam',A='iltāmā')
