"""Long-root control, inherited initial retroflex lookalikes, and opaque fire family."""

def populate(add,tokens):
    add('d2237','stick, shaft, long','*kōl',
        'k','ō','l','zero/a/u','CVVC / CVVC-V','noun/adjective',
        'Tamil, Malayalam, Kannada and Konda kōl independently establish a long-vowel free root; Telugu kōla and eastern kōl/kōḍu continue that input.',
        'The long vowel precedes the lateral across several branches. Toda initial kv contains a labial associated with the rounded vowel, not the displaced reflex of root-final l, whose fricative reflex remains after the vowel.',
        '*kōl > kōla/kōlu retains order. Kui kōḍu and plural kōṭka change the medial/final lateral to a stop without promoting it. Toda kōl > kvɨ̄s̱ requires vowel breaking and lateral fricativization, not k-l metathesis.',
        'A strong independent long/free-root control, including Kui/Kuvi plural formations that retain initial order. Short Gondi kola/Kolami kolā cannot establish original short V against the broad long comparison and may be local shortening. Many Badaga stick compounds and proper names are not independent etyma. The imported *kōy-il palace reconstruction is unrelated metadata, excluded.',
        {'Tamil':('R','kōl','Long free root.'),'Malayalam':('R','kōl','Same.'),'Kannada':('R','kōl|kōlu','Same with final vowel.'),'Kota':('R','kōl|ko·l|ortkōl','Free root and compound.'),'Toda':('O','kvɨ̄s̱|kvɨ·s̱','Vowel breaking and lateral change, no apical displacement.'),'Kodagu':('R','ko·lɨ','Long root.'),'Tulu':('R','kōlu|kōlɯ','Same.'),'Telugu':('R','kōla|kōlana|kōlani','Long root and adjectival derivatives.'),'Gondi':('R','kōla|kōlā|kola','Long majority and short local spelling retained.'),'Konda':('R','kōl','Long pestle root.'),'Kui':('R','kōḍu ( kōṭka)','Long root, apical stop paradigm.'),'Kuwi':('R','kōlu ( kōlka)|kōlū ( kōlka)','Long root retains order even in plural cluster.'),'Pengo':('R','kōl','Same.'),'Manda':('R','kūl','Height change with long quantity.'),'Kolami':('R','kōla|kolā','Quantity distribution differs, no reversal.'),'Naiki':('R','kōl','Long free root.'),'Parji':('R','kōl','Same.'),'Badaga':('R','uppu kōl|ode kōl|ode kōlu|hasini kōl|nīḷa kōlu|neli kōlu|sekkōlu','Selected clear stick compounds; counted once.')},
        input_confidence='high',references='DEDR 2237; PSS83 pp.229–230 long/free-root restriction',quantity='long',boundary='Independently free root; later compounds and plurals do not make independent roots.')

    add('d2929','fire, blaze, live coal','*nir-/ner-; labial *nir/ner-upp and velar derivatives',
        'n','i/e','r','u/unknown','CVC-u-PP / CVC-V / CVC-K','noun/verb',
        'Tamil neruppu, Malayalam nerippu, Gondi nirvānā and Parji nir independently support n-V-r, with i/e and labial/velar formative variation. Neither imported *nijur nor **nirVvV is treated as uniquely established.',
        'Several branches retain initial n-V-r. Telugu nippu lacks r; Kui drē instead has r immediately after a stop that may continue n through denasalization.',
        'Telugu *nir-pp > nipp via medial r-p assimilation is sufficient; a hidden *nripp > nipp trajectory remains possible but unproved. Kui *nir-V > *nrē > drē combines displacement/contraction and n>d, with exact ancient V2 unresolved. Kurux niyū̃r requires additional medial vowel/glide history and is not simple evidence for the same immediate input.',
        'The geminate labial environment alone does not certify Telugu metathesis: nippu is opaque without an attested nr/dr intermediate. This is a crucial comparison with trippu and krovvu. Related burning eri d811 may involve nasal prothesis/loss, but that deeper union remains a sensitivity hypothesis. Initial n is independently recoverable here and must not be removed to make a vowel-initial metathesis case.',
        {'Tamil':('R','neruppu','Full labial fire formation.'),'Malayalam':('R','nerippu|ñerippu|ñeri','Full apical order with initial nasal variation.'),'Kota':('O','nep','Medial rhotic loss/assimilation.'),'Toda':('O','nep','Same.'),'Telugu':('O','nippu|nippuka','Medial assimilation sufficient; concealed displacement unproved.'),'Gondi':('R','nirvānā|nirustānā (<i>Voc.</i> 1991)','Retained fire verbs.'),'Kui':('D','drē|drēna|drē inba','Displaced family plus initial denasalization; V2 uncertain.'),'Kolami':('O','nipp|nipka','Medial assimilation or contact with Telugu possible.'),'Naikri':('O','nipka','Same uncertainty.'),'Parji':('R','nir|nirkip- (nirkit-)','Retained root and causative.'),'Gadaba':('R','niruk|nirik','Retained root with V2 variants.'),'Kurux':('A',"niyū̃r",'Additional syllable/quantity history unresolved.'),'Malto':('R','nare|narɣe|nargtre','Initial order retained with low vowel and suffix variation.')},
        input_confidence='high for n-V-r; medium for exact vowels/formations',references='DEDR 2929; K03 Rule 21 denasalization; comparison DEDR 811',boundary='Labial noun and velar/intransitive verbs separate; relationship to vowel-initial burn uncertain.',mechanism='Opaque Telugu medial reduction; eastern displacement with denasalization.')

    add('d2988','fall, lie down, die','*ḍol-/ḍul- (regional); relationship to ūḍu unresolved',
        'ḍ','o/u','l','zero/u','CVC / CVC-C','verb',
        'Gondi, Kolami and Kui/Kuvi independently have initial ḍ/d before the vowel and a following lateral or its loss. The lone Telugu ūḍu has a different shape and long vowel, insufficient to reverse the comparative direction for the whole family.',
        'Broad regional agreement favors earlier ḍ-V-l for this set; there is no independently attested common *uḍal input here. Telugu ūḍu may be a related different formation, analogical associate or separate cognate hypothesis.',
        '*ḍol > ḍollu/ḍol, and *ḍol-p > ḍōpa with lateral loss/assimilation and compensatory quantity, are local candidate developments. Deriving all initial ḍ from vowel/apical exchange would require independent evidence not supplied by these reflexes.',
        'Initial retroflexion is not a metathesis diagnosis. The near-homophonous rolling forms in d2698 may have converged with this fall/death set, but conflating them would falsely supply a southern unshifted cognate. Long ūḍu versus short ḍul- deserves dictionary/historical morphology work; for now code its direction uncertain. No confirmed metathesis count from this entry.',
        {'Telugu':('A','ḍullu|ḍulupu|ḍulcu|ḍulucu|ḍollu|ḍolligillu|ūḍu','Regional ḍ-initial fall forms versus unmatched long vowel-initial alternative.'),'Gondi':('R','ḍol|dolanā','Retains regional initial ḍ/d order.'),'Kui':('O','ḍōpa (ḍōt-)','Lateral loss/assimilation and quantity change, no demonstrated initial exchange.'),'Kuwi':('R','dulh|ḍul- (-it-)|dūlinai|ḍō- (-t-)','Initial stop retained; final lateral and quantity vary.'),'Kolami':('R','ḍol- (ḍolt-)|ḍolp- (ḍolopt-)','Root and causative retain order.')},
        input_confidence='medium; regional reconstruction, deeper source unresolved',references='DEDR 2988; compare DEDR2698 and K61 p.54 §1.127 alternative derivations (prior verified reading)',eligibility='lookalike-unresolved',boundary='Regional root and long vowel-initial alternative not assumed identical.',mechanism='Initial-retroflex lookalike; no established earlier reversed order.')
    tokens('d2988','Telugu',R='ḍullu|ḍulupu|ḍulcu|ḍulucu|ḍollu|ḍolligillu',A='ūḍu')

    add('d3014','remain, stay, be obtained','*taŋ-k / *tak-k',
        't','a','nonapical','u','CVNK / CVKK','verb/noun',
        'Tamil taŋku/takku, Malayalam taŋŋuka/takkuka, Kannada taŋgu/dakku and central tak independently establish initial t and a velar/nasal medial cluster. No postvocalic apical is reconstructed.',
        'Initial t/d/ḍ precedes a in all relevant cognates. Telugu ḍakku does not show reversal of an independently reconstructible *aḍ input.',
        '*tak-k > takku/dakku/ḍakku involves initial voicing/retroflexion or lexical variant association; *taŋ-k > taŋgu/tagg involves nasal/velar developments. These are distinct from initial vowel/apical displacement.',
        'A false-positive control for searching Telugu initial ḍ. K61 p.53 §1.126 proposes hyperstandard ḍ for d in ḍakku; this is an alternative to metathesis, not a demonstrated ancient sound law. The same discussion finds no evidence for an assumed lost nasal source. Uncertainty about this consonant is not positive metathesis evidence. Related takku/takkin(a) morphology and cognates support the original t-initial analysis.',
        {'Tamil':('R','taŋku|takku|taŋkal|takkam','No target medial apical.'),'Malayalam':('R','taŋŋuka|taŋŋal|taŋŋikka|takkuka|tañcuka|tañcam','Velar/nasal changes separate.'),'Kannada':('R','taŋgu|dakku|dakkisu','Initial voicing, no exchange.'),'Kota':('R','taŋg- (taŋgy-)','Same input order.'),'Toda':('R','tok- (toky-)|tok-|toky-|toζ|toz̡','Velar derivatives and vowel change.'),'Tulu':('R','daksuni|daksāvuni|dakkāvoṇuni|dakkati','Voiced initial and suffix history.'),'Telugu':('R','takku|takkina|dakku|ḍakku','Initial stop variants, no target medial apical.'),'Gondi':('R','tagg|taggānā','Medial nasal/velar cluster change.'),'Kolami':('R','tak- (takt-)','Retained order.'),'Naikri':('R','tak','Same.')},
        input_confidence='high',references='DEDR 3014; K61 p.53 §1.126 (prior verified reading)',eligibility='nonapical-control',boundary='Velar/nasal stem formations independently supported.',mechanism='Initial voicing/retroflexion, not metathesis.')
