"""Final comparative review of nasal clusters and an apparent Telugu r exception."""
def populate(add,tokens):
    add('d1079','vomit, regurgitate','*kak; possible regional *kaẓ-k beside kak',
        'k','a','k / possible ẓ','zero/u','CVC / possible CVC-C','verb/noun',
        'Tamil kakku, Malayalam kakkuka, Gondi kakk/kokk, Konda kak and the Pengo/Manda kak bases independently support the nonapical root. Kannada kaṛ̆ku (=kaẓku) supplies a real apical-bearing variant beside kakku, so an apical input cannot simply be rejected because the headword is kak.',
        'A regional *kaẓ-k could give Kannada kaẓku and Telugu krakku, but the many nonapical forms do not uniquely establish whether the apical is inherited, secondary or belongs to a different convergent formation.',
        'Two alternatives remain: (1) *kaẓ-k > *kẓak > krakku, with separate k strengthening, while other branches assimilate ẓk to kk; (2) inherited *kak > kakku, with secondary r in Telugu on the literary Cr pattern and a separately remodeled Kannada variant. Pengo kak + intensive-ba > kabga has a distinct velar–labial alternation, independently supported by its simple stem.',
        'Telugu krakku is not counted as a secure classical displacement positive. Kannada kaẓku is the evidence that could favor that analysis, but its age and wider correspondences need checking. Cough/vomit vocabulary also permits expressive expansion. DEDR comparison1477 kāl is not accepted without independent semantic/phonological review. Badaga proper names and repeated God Šiva stories do not add lexical roots. The Kondh intensive and Telugu initial-r problem are separate processes in one family.',
        {'Tamil':('R','kakku|kakkal','Nonapical root and noun.'),'Malayalam':('R','kakkuka|kakkikka','Nonapical verb and causative.'),'Kota':('R','kak- (kaky-)|kakc- (kakc-)','Base and causative; no initial apical cluster.'),'Toda':('R','kak- (kaky-)|kakc- (kakč-)','Base and causative.'),'Kannada':('R','kaṛ̆ku|kakku|kakkisu','Apical-bearing and assimilated/independent variants; neither promotes the apical.'),'Kodagu':('R','kakk- (kakki-)','Nonapical root.'),'Tulu':('R','kakkuni|kakkāvuni|kakkāṭa','Root and derivatives.'),'Telugu':('A','krakku|kakku|kakkuḍu|kakkũ-devulu','Retained nonapical forms and ambiguous r-bearing variant.'),'Gondi':('R','kokk|kakkānā','Nonapical root, vowel variants.'),'Konda':('R','kak- (-t-)','Base and past.'),'Kuwi':('R','kakv- (-it-)|kakva|kakvinai|kokovi|kakkivi ānai','Velar/labial derivatives; no initial apical change.'),'Pengo':('R','kak- (-t-)|kabga','Initial k-a order retained; separate medial velar/labial exchange in intensive.'),'Manda':('R','kak|kabga','Same.'),'Gadaba':('R','kak','Nonapical root.'),'Malto':('R','qagjre','Nonapical root and suffix.'),'Badaga':('R','kakku','Common lexical verb only.')},
        c2_structure='velar singleton/geminate; alternative apical+velar cluster',eligibility='input-uncertain-secondary-r-comparison',boundary='Intensive -ba independently contrasts with kak; Telugu r history is a separate question.',input_confidence='high for kak family; low for apical antiquity',references='DEDR1079; Garrett and Blevins2009 p.538 ex.20b; panel-030',mechanism='Ambiguous earlier apical versus secondary r in Telugu; separate Kondh morphological velar/labial alternation.')
    tokens('d1079','Telugu',R='kakku|kakkuḍu|kakkũ-devulu',A='krakku')

    add('d4806','bamboo, thorny bamboo','regional *māṇ/ṛ-i; Kuvi mṇāhu formation',
        'm','ā','ṇ/ṛ','i / unknown','CVVC-i / CVVC-s?','noun',
        'Kui māṇi/māṛi and Kuvi Ḍ. māṛi, S. mādi independently support a long vowel before an apical. Their nasal/rhotic/dental correspondences do not determine one uniquely original apical identity.',
        'The full Kui and Kuvi forms favor m-ā-apical before Isr. mṇāhu. The ṇ could reflect promotion of an older nasal or assimilation of a promoted liquid next to m; these are distinct analyses.',
        'Conditional *māṇ-s > *mṇā-s > mṇāhu (plural mṇāska), with an h/s stem alternation, provides a displaced nasal formation. Alternatively *māṛ-s > *mṛā-s > mṇā-s adds liquid-to-nasal assimilation. The s-formative is inferred from the Kuvi paradigm, not directly matched to full māṛi.',
        'The long input is independently supported, so this is outside the narrow short-vowel Telugu domain. Exact noun formation and nasal chronology remain uncertain. Thorny bamboo versus a generic bamboo bush could reflect lexical specialization or borrowing. The dictionary explicitly removes Kurux mās as a pronunciation of Indo-Aryan bā̃s; it cannot be used as a northern cognate.',
        {'Kui':('R','māṛi|māṇi','Full long forms, rhotic/nasal variation.'),'Kuwi':('M','mṇāhu ( mṇāska)|dēru mādi|māṛi','Israel displaced singular/plural versus other sources full apical forms.')},
        quantity='long independently established',c2_structure='nasal/rhotic singleton; immediate suffixal s cluster inferred',eligibility='late-kuvi-long-apical-variable',boundary='Kuvi singular h versus plural sk; full i-ending noun is a different formation.',input_confidence='high for long vowel and full order; medium for segment and formation',references='DEDR4806; DED(S)3929; Pfeiffer1972 correction cited in source',mechanism='Long apical displacement-family; nasal before/after reordering unresolved.')
    tokens('d4806','Kuwi',R='dēru mādi|māṛi',D='mṇāhu ( mṇāska)')

    add('d4831','die, cease, extinguish, erase','*māḷ; short *maḷ-a/u-NK; regional *maṇ-k',
        'm','ā/a','ḷ/ṇ','a/u/zero','CVVC / CVC-V-NK / CVC-C','verb',
        'Tamil māḷ and Kannada māḷ independently establish a long lateral root. Tamil maṭku, Telugu malugu/malãgu/manũgu and Kuvi maṇk support shorter and nasal formations independently; the short grade is not invented from the displaced outcome.',
        'Southern m-V-lateral forms and retained Kuvi maṇk favor m-V-apical before mṇeŋg/mṇek. Nasal identity has independent regional support but cannot simply replace the deeper lateral.',
        'Short *maḷ-k > *maṇ-k > *mṇak, or *maḷ-k > *mḷak > *mṇak, are alternatives preceding Kuvi mṇek; the a>e quality remains unexplained. The intransitive nasal-velar mṇeŋg contrasts with stronger mṇek. F. mṛakʰali has r and a and may preserve a different assimilation/quality history. Telugu retains mal/man order through its short and long formations.',
        'Kuvi e is a genuine residual, not a reason to reconstruct unsupported *meṇ. DEDR assigns these forms to the same family; the exact short-grade derivation, semantics and source differences need a fuller paradigm. Badaga buru māle naked has insufficient semantic evidence and is not counted as a cognate. Nasal/stop alternation in Tamil māḷ:māṇṭ is a morphological control, not initial metathesis.',
        {'Tamil':('R','māḷ|māṭṭu|māṇṭār|maṭku','Independent long root and short/strong derivatives.'),'Kannada':('R','māḷ|māṇ','Full long lateral/nasal variants.'),'Tulu':('R','mānāvuni|māṇāvuni','Full long nasal causatives.'),'Telugu':('R','manũgu|malugu|malupu|malãpu|mālucu|mālu|malãgu|manuvu','Short/long and nasal/lateral formations retain order.'),'Kuwi':('M','mṇeŋg- (-it-)|mṇek- (-h-)|mṛakʰali|maṇk','Full short nasal base versus displaced nasal/rhotic derivatives; e remains unresolved.')},
        quantity='independent long root and short derivatives',c2_structure='lateral/nasal; short consonantal formations',eligibility='late-kuvi-mixed-quantity-secondary-nasal',boundary='Short/long grade and transitive/intransitive formations independently distinguishable, exact nasal chronology unknown.',input_confidence='high for full order; medium for grades; low for e outcome',references='DEDR4831, DED3958; source labels in panel-030',mechanism='Displacement-family supported, with unresolved a/e quality and secondary nasal chronology.')
    tokens('d4831','Kuwi',R='maṇk',D='mṇeŋg- (-it-)|mṇek- (-h-)|mṛakʰali')

    add('d5124','ladle, draw water by dipping','*moḷ-k / *muḷ-k',
        'm','o/u','ḷ','zero','CVC-C','verb',
        'Tamil moḷ and Malto mulɣe independently establish vowel-before-lateral order across southern and northern branches. Malto also supports a velar extension independently of the eastern clusters.',
        'The two separated full comparisons favor *mVḷ-k before eastern ml/mr/mṇ forms. A deeper nasal root is not independently supported by these witnesses.',
        '*mo/uḷ-k > *mḷo/uk > Kui mluk, Pengo/Manda mṛuk; Kuvi mṇok adds lateral-to-nasal assimilation before or after cluster formation. Kuvi mrokʰ-nai retains a rhotic alternative. Root o/u and the gloss merge in Schulze need separate scrutiny.',
        'This case cannot be counted as independent evidence that inherited nasals entered the original Telugu rule: the comparative input is lateral. Whether Kuvi assimilated a liquid after promotion or had a preexisting nasal allomorph is unresolved. DEDR3790 noḷ is an explicitly suggested comparison; initial m/n variation and semantics require review before merging families.',
        {'Tamil':('R','moḷ','Full lateral root; nasal past in source paradigm separate.'),'Malto':('R','mulɣe','Independent full root and velar formation.'),'Kui':('D','mluk','Short lateral cluster.'),'Kuwi':('D','mṇok- (-h-)|mrokʰ\'nai','Nasal/rhotic displaced variants, semantic/source difference.'),'Pengo':('D','mṛuk- (-t-)','Short rhotic cluster.'),'Manda':('D','mṛuk','Same.')},
        c2_structure='lateral plus velar formative',eligibility='core-cluster-secondary-nasal',boundary='Velar extension independently supported by Malto; exact vowel quality varies.',input_confidence='high for earlier order; medium for root vowel and common inheritance',references='DEDR5124, DED(S)4209; comparison3790 not merged',mechanism='Consonantal apical displacement-family plus secondary nasal assimilation in Kuvi.')

    add('d5146','steal, deceive; mouse as thief','regional *mṛā / *mṇā; precluster input unknown',
        'm','unknown','r/n input order unknown','unknown','attested CCVV; older structure unknown','verb/noun',
        'Kui mṛāpa, Pengo mṛā and Kuvi mṇā all already contain initial clusters. No full vowel-between-consonants cognate in this group independently establishes the earlier sequence.',
        'r/ṇ variation is observable, but the direction of earlier metathesis cannot be reconstructed from cluster forms alone. A database *mṇā reconstruction restates one daughter outcome.',
        'Possible older *mVr-a > *mrā followed by rhotic/nasal variation is only a schematic hypothesis. Alternatively the cluster may be inherited at the immediate common stage. Pengo mṛā-kʰa thief and mouse compounds suggest agentive morphology followed by a rodent noun, not extra root changes.',
        'Leave the earlier input and presence of historical reordering unresolved. Needed: an independently cognate full root, regular r/n correspondences and the semantics of the mouse compound. Do not infer borrowing simply to avoid the missing input, or use the already clustered proto-head as evidence of a Telugu-like change.',
        {'Kui':('A','mṛāpa (mṛāt-)','Cluster directly attested; prior order unknown.'),'Kuwi':('A','mṇā- (-t-)|mṇāski orli|mṛākli or\'i','Nasal/rhotic variation and rodent compounds.'),'Pengo':('A','mṛākʰa|mṛā- (-t-)','Agent and verb are related formations.'),'Manda':('A','mṛākʰi urli','Mouse compound; no full root supplied.')},
        quantity='unknown before observed long cluster',c2_structure='precluster structure unknown',eligibility='unreconstructible-input-cluster-comparison',boundary='Agent/animal compound independently distinguishable; earlier root boundaries unknown.',input_confidence='low for precluster input',confidence='low',references='DEDR5146; DEDS820',mechanism='Cluster distribution and rhotic/nasal variation only; metathesis not established.')
