"""Late Kuvi paradigm control and northern comparisons requiring distinct histories."""
def populate(add,tokens):
    add('d4449','louse, flea','*pēn; Kuvi plural *pēn-ka',
        'p','ē','n','zero/u','CVVC + plural-k(a)','noun',
        'Tamil pēṉ, Kannada pēn, Kota pe·n, Telugu pēnu and northern pēn forms independently support long ē before n. Kuvi retained pēnu:pēnka and Konda pēni:pēnku supply the plural formation directly.',
        'The regional full singular and retained Bisamkatak plural independently establish pēn-ka before the Sunkarametta pṇēka order. This does not assume Telugu uniquely preserves the input.',
        'pēn-u + plural-ka > pēn-ka > pṇē-ka, with the nasal preceding the long vowel and n/ṇ place variation. The displaced and retained plurals have different source/dialect labels; their coexistence in an aggregated language is not evidence of free variation in one speaker. Telugu pēnu:pēlu changes plural n to l without moving either consonant before ē.',
        'The louse and god4438 paradigms are segmentally similar but semantically distinct roots; do not merge them as derivatives. Gondi parki/purki louse belongs to4203, not this family. Pengo/Manda short pen has regional shortening but retains vowel-nasal order. Badaga hēnu:ēnu is initial labial weakening/loss, not nasal displacement. The long louse reconstruction also attached to4395 is a database crosslink error, not independent evidence. New unlinked Kurux/Kannada Kurumba cognate candidates remain in the separate candidate ledger, without adding etyma.',
        {'Tamil':('R','pēṉ','Long nasal root.'),'Malayalam':('R','pēn','Long nasal root.'),'Kota':('R','pe·n','Long nasal root.'),'Toda':('R','pø·n|pēn|pø̄n','Vowel quality and source variants, same root.'),'Kannada':('R','pēn','Denominal verbal usage remains one family.'),'Kodagu':('R','pe·nɨ','Long nasal root.'),'Tulu':('R','pēnɯ','Long nasal root.'),'Telugu':('R','pēnu ( pēlu)','Plural nasal/lateral substitution retains order.'),'Konda':('R','pēni ( pēnku)','Consonantal plural retains order.'),'Kui':('R','pēnu','Long nasal root, flea gloss.'),'Kuwi':('M','pēnū|pēnu|pēnka|pṇēka','Full singular and Bisamkatak plural versus Sunkarametta displaced plural.'),'Pengo':('R','pen ( -ku)','Short regional root.'),'Manda':('R','pen (pl. -ke)','Short regional root.'),'Kolami':('R','pe·n ( -kul)','Retained plural.'),'Naikri':('R','pēn','Long root.'),'Naiki':('R','pēn','Long root.'),'Parji':('R','pēni ( pēnul)','Retained plural.'),'Gadaba':('R','pēn ( pēnil)','Ollari retained plural.'),'Kurux':('R','pē̃n|allā-pē̃n','Nasalized root and dog compound, not two roots.'),'Malto':('R','pénu','Accent retained exactly; no independent quantity inferred.'),'Badaga':('R','hēnu|ēnu','p>h>zero, initial vowel still precedes nasal.')},
        quantity='long independently established; short regional Pengo/Manda',c2_structure='nasal',references='DEDR4449, DED(S)3643; Kujur and Dash2025 p.119 cites Kuvi louse via Steever2019',eligibility='late-kuvi-long-nasal-plural',boundary='Singular and retained/displaced plurals explicitly supplied with dialect labels.',input_confidence='high',mechanism='Direct paradigm supports long vowel–nasal reordering; phonetic implementation and date remain unknown.')
    tokens('d4449','Kuwi',R='pēnū|pēnu|pēnka',D='pṇēka')
    add('d789','long-bow','regional *eṛ-et/eth or *eṛt with anaptyxis',
        'Ø','e','ṛ','e/zero','VCVC / VCC','noun',
        'Kurux eṛetʰ and Malto eṛtu establish initial vowel before the rhotic, but only one full-vowel comparison supports medial e. Database *eṛt is a northern reconstruction, not a Proto-Dravidian input.',
        'Both database languages keep initial V-r. The external Kunha iṛtū can arise from a medial-cluster formation without exchanging the initial vowel and rhotic. Kurux full form versus Malto/ Kunha clusters does not by itself decide syncope versus Kurux anaptyxis.',
        'Possible *eṛetʰ > *eṛt > Malto eṛtu, Kunha iṛtū, with initial raising and final vowel formation/length in Kunha. Alternatively inherited *eṛt plus Kurux medial e insertion. Either account preserves the target initial order. The archer derivative eṛtyo adds morphology without an extra metathesis event.',
        'Kujur and Dash2025 p.119 calls the Kurux/Kunha comparison metathesis, but the changed vowel quality and final quantity require additional assumptions; the segment sequence is equally compatible with syncope and final vocalism. No Telugu attestation and no southern cognate establish a shared Telugu event. Northern morphology, older Kurux forms and stress data would distinguish the alternatives.',
        {'Kurux':('R','eṛetʰ','Initial order retained; medial e may be old or inserted.'),'Malto':('R','eṛtu|eṛtyo','Medial cluster and archer derivative.')},
        references='DEDR789; Kujur and Dash2025 p.119',eligibility='northern-medial-reduction-comparison',c2_structure='singleton or cluster input uncertain',quantity='short initial vowel',boundary='Archer derivative independent; final u of bow not independently segmented.',input_confidence='high for initial order; low for medial e versus zero',mechanism='No target initial displacement; medial syncope versus anaptyxis remains unresolved.')
    add('d3520','armpit, side of body, flank','*tok-k / regional *tolokʰ, *tolkʰ',
        't','o','l/k','o/zero','CVCVC / CVCC','noun',
        'Malayalam tokku and Kurux tolᵒkʰ/tolokʰ are the complete attested database comparison. The southern form lacks l, so the immediate northern sequence is more secure than a common reconstructed lateral root.',
        'Kurux directly supports t-o-l order, and external Kunha tolkhō preserves that same initial sequence. Moving a medial vowel to a final position is not the initial sonorant displacement found in Telugu.',
        'Regional tolokʰ > *tolkʰ > tolkhō is possible through medial syncope and final vowel morphology/epenthesis; direct o/kʰ exchange plus lengthening is another description. Malayalam tokku could reflect lk assimilation if cognacy is valid, but no independent full southern tolok formation confirms that history.',
        'The dictionary itself queries the reconstructed *Tok root. Do not infer metathesis from a reconstructed l that only the northern branch has. Kunha source pairs an armpit term with Kurux side/flank; semantic continuity is plausible but exact polysemy needs elicitation. Full older forms, suffixal paradigms and additional southern cognates would resolve the alternatives.',
        {'Malayalam':('O','tokku','No lateral; assimilation versus separate cognacy unresolved.'),'Kurux':('R','tolᵒkʰ|tolokʰ','Full/reduced medial vowel transcription; same initial order.')},
        references='DEDR3520, DEDS550; Kujur and Dash2025 p.119',eligibility='northern-medial-reduction-comparison',quantity='short',c2_structure='lateral only in northern forms; deeper k/l uncertain',boundary='No independently established final-vowel morpheme.',input_confidence='medium for local northern order; low for wider cognacy',mechanism='Medial reduction/final-vowel alternation; literal exchange not demonstrated.')
