"""Final vowel-initial controls and eastern-only comparisons from the contiguous u block."""

def populate(add,tokens):
    add('d706','butt, gore, crush nits','*uṯ-/uṟ-; velar/labial derivative uncertain',
        'zero','u','ṟ','zero/unknown','VC / VC-C','verb',
        'Konda uṟ with fortis uRt, Kuvi ur, Pengo uz/ust and Parji ud independently support u before an alveolar apical. Kui ubga instead has a velar/labial formation whose exact relationship to the apical root is less certain.',
        'All clear apical cognates retain initial u. Kuvi ūrhali adds quantity, not reversed order. Kui ubga provides independently explicit g-b > b-g locally, but no initial apical metathesis.',
        '*uṯ > uṟ/ur/uz/ud retains order with apical reflex changes. Kui ug-b > ubg is suffix-cluster exchange; root apical-to-g history is not established here.',
        'No Telugu linked attestation. Bare and consonantal stems provide an eastern nonmetathesizing comparison; do not infer a required a formative from their infinitival citation endings. Kui ubga occurs also under happen d710; it cannot create two independent cluster-metathesis votes without disambiguating the lexeme and morphology.',
        {'Konda':('R','uṟ- (uRt-)','Bare root and fortis paradigm retain order.'),'Kuwi':('R','ur- (-h-)|ūrhali','Short/long root variants retain order.'),'Pengo':('R','uz- (ust-)','Medial apical reflex and past cluster.'),'Manda':('R','uy','Medial apical-to-glide reflex.'),'Parji':('R','ud','Short root in nit-crushing phrase.'),'Kui':('A','ubga','Local g-b exchange secure, apical cognacy less secure.')},
        input_confidence='high for apical set; low for Kui velar linkage',references='DEDR 706 p.69 directly checked; compare DEDR 710',boundary='Bare apical root versus uncertain velar/labial derivative; identical Kui ubga not independent from d710.')

    add('d709','sip, suck, inhale','*uṯ-i; *uṯ-i-nc',
        'zero','u','ṟ','i','VC-i / VC-i-NC','verb',
        'Tamil uṟi/uṟiñcu and Malayalam uṛiñcuka independently support u before apical and a high-i formation. Pengo uj reinforces the initial-vowel order with its own apical reflex.',
        'Several branches favor u-apical before Kuvi jū. Simple deletion of the first vowel of uṟi would yield ṟi, not jū, so vowel interaction/transfer or a different high-u formation is needed.',
        '*uṯ-i > *ṯu-i > *ṯū > jū is a plausible displacement/contraction chain, with the apical-to-j stage potentially preceding displacement. Pengo uj retains u before j. Tulu ujumbu has added nasal/labial formation without initial exchange.',
        'A clear eastern-only order contrast, though the exact segment-exchange mechanism and relative j development remain inferred. Telugu and Kui are absent from this linked set. Kolami ūmburseng explicitly includes ūmb from d2621 and cannot be treated as an ordinary unsuffixed uṟ reflex; Badaga ūtu kudi has distinct compound morphology. Kannada queried uṟita preserves the source’s cognacy doubt.',
        {'Tamil':('R','uṟi|uṟiñcu','Independent high-i formative.'),'Malayalam':('R','uṛiñcuka','Same with source ṛ notation.'),'Toda':('R','ɨṟ- (ɨṟQ-)|ɨṟ-|ɨṟθ-','Initial vowel retained in paradigm.'),'Kannada':('A','urpu|? uṟita','Retained labial formation and explicitly queried noun.'),'Tulu':('R','ujumbu|ujumbuṇa','Initial u remains before medial apical reflex.'),'Kuwi':('D',"jū'nai",'Apical precedes long u; simple aphaeresis of high-i formation insufficient.'),'Pengo':('R','uj- (ucc-)','Medial apical/past reflex remains after u.'),'Kolami':('A','ūmburseng','Compound involving another root; exact relation uncertain.'),'Badaga':('A','ūlu|ūtu kudi','Long lateral form and compound; exact ancestral formation unclear.')},
        input_confidence='high for order/high-i core',references='DEDR 709 p.70 directly checked',boundary='High-i sip root and nasal-palatal extension independently supported; mixed-root compounds separate.')
    tokens('d709','Kannada',R='urpu',A='? uṟita')

    add('d715','suffer, be afflicted','*uṯ-u; velar/causative formations',
        'zero','u','ṟ','u/unknown','VC-u / VC-V-K','verb/noun',
        'Tamil uṟu with uṟuv/uṟṟ and Malayalam uṟuttuka support a short-u apical root and high-u formation; independently long Tamil ūṟu is a separate nominal grade.',
        'Southern u-before-apical establishes the direction toward Kui jūga. The exact vowel before its velar suffix is not independently fixed by the bare high-u root alone.',
        '*uṯ-u > *ṯū > jū, then velar/intransitive or causative formation, gives a plausible chain; the relative age of velar suffix and contraction is not proved. Kui jūk-p > jūp-k is independently established by the source’s jūkt past.',
        'No Telugu attestation in this group. The high-u base supports long contraction but should not be counted as direct attestation of every intermediate in the Kui velar formation. Related happen/obtain uṟu d710 may share a deeper root; keep a family-sensitivity link rather than assuming either total independence or identity.',
        {'Tamil':('R','uṟu|uṟuttu|uṟukaṇ|uṟuval|ūṟu','Short paradigm, compounds and separate long noun retain order.'),'Malayalam':('R','uṟuttuka','Retained high-u causative formation.'),'Kannada':('R','uṟisu','Retained apical with high-i suffix.'),'Kui':('D','jūga (jūgi-)|jūpka','Displaced apical family and separate suffix-cluster exchange.')},
        input_confidence='high for root order; medium for exact Kui formation',references='DEDR 715 p.70 directly checked',boundary='High-u root versus velar and causative extensions; long nominal grade distinguished.')

    add('d811','burn, blaze, smart, pungency','*er-i; related high/low and long derivatives',
        'zero','e','r','i/a/u','VC-i / VC-V-C / VVC','verb/noun',
        'Tamil eri, Malayalam eriyuka, Telugu eriyu and Konda er independently establish e-r with a high-i burn formation. Long causatives/nouns and wildfire compounds have different morphology.',
        'The broad full-form comparison favors initial e before r. Kui rīva has reversed order but i rather than e, so it cannot simply be treated as the expected result of transferring the first vowel e.',
        'Telugu eriyu retains order; high-vowel loss and compensatory quantity can give ērcu/ērpu without metathesis. Kui rīva could reflect an older *ir-i grade plus contraction, or aphaeresis of *eri with separate lengthening/formative change. Kui ēṛ/ērpa causative retains initial e and needs a distinct formation history.',
        'A strong Telugu short-vowel/high-i retained control. Kui exact mechanism and input vowel remain uncertain despite the r-initial form; no invented *iri should count as independently verified conditioning. The relation to n-initial fire d2929 is a possible prothesis/loss connection, not a license to merge all fire formations. Toda row/sitting and Kota scooping senses reflect polysemy/homonym alignment issues; only the cited brightness meanings support this comparison. Badaga scattering senses need separate semantic review.',
        {'Tamil':('R','eri|eriyal|erivu|ericcal|erippu','Full high-i fire root and derivatives.'),'Malayalam':('R','eri|eriyuka|erikka|erivu|eruvu|erippu|ericcal','Full order retained.'),'Kota':('R','erv- (erd-)|erv-|erd-','Brightness sense only; homonymous scooping not additional evidence.'),'Toda':('O','er- (erQ-)|er-|erθ-|ēf|e·f','Retained brightness root and medially reduced fever.'),'Kodagu':('R','eri- (erip-, eric-)|erivɨ','High-i burning sensation.'),'Tulu':('R','eri|eriyuni|eriyāvuni','Full root/cause formations.'),'Telugu':('R','eriyu|eriyincu|ērcu|ērpu|eravali|eragali|talay-ēru','Short root, long derived forms and compound retained.'),'Gondi':('R','erītānā|ērītānā|ers|ars|arrī','Full order with quantity/vowel/gemination variation.'),'Konda':('R','er- (-t-)|eris','Retained simple/causative.'),'Kui':('A','ērpa (ērt-)|rīva (rīt-)','Retained causative, r-initial intransitive with unresolved vowel/mechanism.'),'Kuwi':('R','er|er- (-t-)','Retained kindle root.'),'Kolami':('R','erk- (erekt-)','Medial cluster, initial order retained.'),'Naikri':('R','erk','Same.'),'Naiki':('R','erk','Same.'),'Parji':('R','erip- (erit-)','Retained labial formation.'),'Kurux':('R','ercᵉrnā','Retained apical in perspire comparison.'),'Badaga':('R','ere|erevadu|kiccu eradara','Fire/glow senses; excluded scattering-only and proper names.')},
        input_confidence='high for e-r core; low for Kui earlier vowel',references='DEDR 811; DEN1 1972 p.401 entry694; comparison DEDR 2929',boundary='High-i burn versus long causative and other-vowel derivatives; no automatic reverse inference from Kui ī.')
    tokens('d811','Toda',R='er- (erQ-)|er-|erθ-',O='ēf|e·f')
    tokens('d811','Kui',R='ērpa (ērt-)',A='rīva (rīt-)')
