"""Low-formative comparisons, long roots and morphological quantity contrasts."""

def populate(add,tokens):
    add('d3559','skin, bark, rind','*tokk; *tok-al > *tōl; short *toli',
        't','o/ō','l / earlier k...l','a/i','CVVC / CVC-a-l / CVKK','noun/verb',
        'Tamil/Malayalam tōl alongside tokku, Malayalam tukal, Kannada togal/toval and Tulu tugal independently motivate velar-bearing *tok-al and contracted long *tōl. Telugu tōlu is already a long-root control at the apical-metathesis stage, not an arbitrary long outcome.',
        'Full togal/tugal retains k before a final l; lenition k>g/v and loss plus vowel contraction gives tōl without moving l. The separate tokka/tokku has no apical target.',
        '*tok-al > togal/toval > tōl is the comparative contraction analysis. *tōl > tōlu/ṭōḍu retains initial vowel/apical order; Toda tvɨ̄s̱ involves vowel breaking and final lateral fricativization. No l is promoted into the onset.',
        'This distinguishes vowel contraction from metathesis and provides a long/free-root control across many branches. Gondi tolka and central compounds/plurals do not change the inherited long-root analysis without further evidence. Badaga dai wet is explicitly alternatively linked to d3555 and not skin evidence; Nihali ṭōl is marked borrowed and lies outside Dravidian rates. Short toli peeling may reflect another formation/grade, not a compulsory pre-metathesis shortening of every skin noun.',
        {'Tamil':('R','tōl|tokku|toli','Long skin, nonapical geminate and short peel formations.'),'Malayalam':('R','tōl|tokku|tukal|toli|tolikka','Full velar+l and contracted long comparisons.'),'Kannada':('R','togal|toval|tōl|tōlu','Contraction chain supported by variants.'),'Tulu':('R','tugalɯ|tolikɛ','Full velar-l and short peel formations.'),'Kota':('R','to·l|to·krl','Long root, compound independently segmented by source.'),'Toda':('O','tvɨ̄s̱|tvɨ·s̱','Rounded-vowel breaking and final lateral change.'),'Kodagu':('R','to·lɨ|toli- (tolip-, tolic-)|tolip','Long noun versus short verb.'),'Telugu':('R','tōlu|tokka','Long lateral noun and nonapical velar noun.'),'Gondi':('R','tōl|tōla|tōlu|tolka|tōlu ( tōlku)|tōl ( tōlku)','Long root and plural/formation variants.'),'Konda':('R','tōl|tōlu|toko','Long lateral and nonapical root.'),'Kui':('R','ṭōḍu ( ṭōṭka','Initial order retained despite retroflex stops.'),'Kuwi':('R','tōlū|tōlu|tōlu ( tōlka)','Long noun and plural retained.'),'Pengo':('R','tōl','Long noun.'),'Kolami':('R','tōl','Same.'),'Naikri':('R','tōl','Same.'),'Naiki':('R','tōl','Same.'),'Parji':('R','tōl','Same.'),'Gadaba':('R','tōl|tokka|tokkā','Long lateral and short geminate velar.'),'Badaga':('R','tōlu','Clear skin reflex; ambiguous wet entry excluded.'),'Koraga':('R','tōru','Lateral/rhotic change without displacement.'),'markodi':('R','tol|tōl|ttōl','Lect quantity/initial variants retained.')},
        input_confidence='high',references='DEDR 3559; K03 *tok-al/*tōl reconstruction; PSS83 long/free-root condition',quantity='long contracted root versus distinct short formations',boundary='Velar loss creates long root before assessment of apical metathesis; tokka has no apical.')

    add('d3754','moon, month, moonlight','*nel-a-nc/-ncc; *nel-V',
        'n','e/i','l','a','CVC-a-NC / CVC-V','noun',
        'Kodagu nelaci, Gondi nelenj/nalenj and Parji neliñ independently support n-V-l followed by a palatal/nasal formation. Tamil nilā/nilavu and Malayalam nilā are linked through final *-ac > -ah > ā in K03, independently distinguishing later final ā from the first-syllable quantity.',
        'Multiple branches establish n-V-l before eastern lēnj. Gondi/Konda retain full and l-initial variants; medial nasal/palatal material survives and supports cognacy beyond the initial resemblance.',
        '*nel-anc > *nlēnc > lēnj with initial nasal loss gives the standard eastern chain; Kui lēnj > lānj > ḍānju adds lowering and lateral-to-stop change. Gondi lelenj/lalenj may instead assimilate initial n to l before reduction, so precise segment exchange versus assimilation plus contraction is not uniquely fixed. Telugu nela retains original order. Thiyya Malayalam nilāvu > lāvu is simple initial-syllable loss, retaining the second vowel.',
        'Telugu nonapplication accords with exclusion of post-C l from its narrow class. Kui ā versus Kuvi/Pengo/Manda ē supports language-specific lowering after, or during, contraction rather than one inherited identical vowel outcome. The exact extinct *nl cluster is reconstructed, not directly observed here. Gondi n/l assimilation supplies a concrete competing pathway, to be tested with dialect chronology and stress. Moon and month do not add independent roots.',
        {'Tamil':('R','nilā|nilavu','Initial order retained; final contraction separate.'),'Malayalam':('O','nilā|nilāvu|lāvu','Full forms retain order; Thiyya aphaeresis loses initial syllable.'),'Toda':('R','nes̱of ( nes̱ot-)|nes̱of','Apical fricative remains after first vowel.'),'Kodagu':('R','nelaci|nelaci boḷi','Full nasal/palatal formative evidence.'),'Telugu':('R','nela|ven nela','Retained root and compound.'),'Gondi':('M','nelenj|nalenj|nalēnj|nalenj ( nalesk)|lelenj|lalenj|lēnj|lenj','Full n/l variants and reduced displaced-family forms.'),'Konda':('M','nela|neleŋ|lēnz|lēnzu','Full and reduced forms with morphology and source labels preserved.'),'Kui':('D','ḍānju ( ḍāska)','Lowered displaced family with lateral stop reflex.'),'Kuwi':('D','lēnju|lēnju ( lēska)|lenjū ( leska)','Displaced family, quantity variants.'),'Pengo':('D','lēnj ( lēc-, lēcku)','Displaced family with number/oblique morphology.'),'Manda':('D','lēnj','Same.'),'Kolami':('R','nela','Retained root.'),'Naikri':('R','nela','Same.'),'Parji':('R','neliñ ( nelñil)','Full root/plural.'),'Gadaba':('R','nelling|neliŋ|nelā ( nelŋīl, nelingīl)','Full initial order, number suffixes.'),'markodi':('R','nilav','Retained order.')},
        input_confidence='high for order and formative family',references='K03 pp.122–123 n.5(5), pp.159–160 Rule 21; DEDR 3754; K80 lowering examples',boundary='Nasal/palatal moon formation versus unextended month forms; final ā is a separate contraction.',mechanism='Eastern displacement family; initial assimilation plus contraction remains an alternative in some Gondi forms.')
    tokens('d3754','Malayalam',R='nilā|nilāvu',O='lāvu')
    tokens('d3754','Gondi',R='nelenj|nalenj|nalēnj|nalenj ( nalesk)|lelenj|lalenj',D='lēnj|lenj')
    tokens('d3754','Konda',R='nela|neleŋ',D='lēnz|lēnzu')

    add('d3949','spread, crawl, bed, expanse','*par-a; *par-a-k(k), *par-a-pp, *par-u-w; long *pār',
        'p','a','r/ṟ','a/u','CVC-a-K / CVC-a-PP / CVC-u-w / CVVC','verb/noun',
        'Tamil para/parakku/parappu, Malayalam parakka/parattuka and Kannada pare/parapu independently support low-a formations. Tamil/Malayalam pār independently supports a long grade, and Telugu high-u paruvu is a distinct derivative.',
        'Many branches establish p-a-r before Telugu prāku and Kui pr-. Telugu itself retains para-/paṟa- formations, so the head *para cannot be assigned one automatic outcome.',
        '*par-a-k > *prā-k > prāku, then r loss in pākul-āḍu, is the displaced crawl pathway; Tamil parakku supplies a matched velar formation but original gemination versus later simplification needs separate assessment. Telugu paracu/parapu/paragu retains order in other low-a formations. Kui prahpa/brāḍa and Kuvi pressali have distinct causative/voice extensions and vowel histories.',
        'This is a genuine within-family lexical/morphological residual: low-a alone does not determine Telugu application, and the exact velar contrast cannot be repaired simply by assigning all crawl meanings to an invented class. Konda rēs metal plating may involve displaced *prēs with first-member loss, but e versus independently a requires another grade or contact and remains uncertain. Southern pammu/habbu/pabb and Gadaba pamp permit medial assimilation; do not invent hidden pr. Badaga initial p/h loss leaves r after a and is not metathesis.',
        {'Tamil':('O','para|parakku|parappu|parattu|paravu|parampu|paravai|pār|pāram|pāri|pammu|pampu|pampal','Retained low/long forms versus medial nasal assimilation.'),'Malayalam':('R','parakka|parappu|parattuka|paravuka|paranna|parampu|parava|pār','Low and long retained formations.'),'Kannada':('O','pare|paraḍu|parapu|parepu|parvu|parbu|parayisu|parṇḍi|habbu','Retained r and medially assimilated labial.'),'Kota':('R','pard- (pardy-)|part- (party-)','Medial syncope retains initial order.'),'Toda':('R','par- (parQ-)|par-|parθ-','Same.'),'Kodagu':('O','para- (parap-, parand-)|parat- (parati-)|palambɨ|pabb- (pabbi-)','Retained r/l order and labial assimilation.'),'Tulu':('R','paraḍuni|parbuni|parapuni|paraturuni|parataruni|parambuni|borambu|parētɛ','Full and syncopated retained order.'),'Telugu':('M','paracu|paṟacu|parcu|paṟucu|parapu|paṟapu|paṟupu|paravu|paruvu|parvu|paragu|parãgu|paṟãgu|pāru|pāṟu|prāku|pākul-āḍu','Displaced crawl versus retained low/high and long formations.'),'Gondi':('R','parhānā|pārˀ|pārŋ|pariŋg','Retained root with quantity/formative variants.'),'Konda':('A','paR- (-t-)|pārpu|rēs- (-t-)','Retained spread and plate; metal-plating rēs exact input uncertain.'),'Kui':('D','prahpa (praht-)|brāḍa (brāḍi-)|brāṭpa (brāṭt-)','Displaced spread formations with independent initial/suffix changes.'),'Kuwi':('M','parpu|pressali','Retained mattress versus displaced spread verb.'),'Kolami':('R','pārakeng','Long crawl formation; cannot assume same immediate short input as Telugu.'),'Parji':('R','parp- (part-)','Retained labial cluster.'),'Gadaba':('O','pamp- (pamup-)','Medial assimilation sufficient.'),'Badaga':('R','harutu|arutu|are','Initial weakening/loss without r promotion.'),'pampa':('R','parakalisu','Historical Kannada retained form, not separate modern language.')},
        input_confidence='high for broad formations; medium for exact velar quantity',references='DEDR 3949; K03 *par-a reconstruction; K61 immediate-antecedent principle',quantity='short and independent long grade',boundary='Low-a velar, labial and high-u forms remain distinct; semantic classes alone cannot force regularity.')
    tokens('d3949','Tamil',R='para|parakku|parappu|parattu|paravu|parampu|paravai|pār|pāram|pāri',O='pammu|pampu|pampal')
    tokens('d3949','Kannada',R='pare|paraḍu|parapu|parepu|parvu|parbu|parayisu|parṇḍi',O='habbu')
    tokens('d3949','Kodagu',R='para- (parap-, parand-)|parat- (parati-)|palambɨ',O='pabb- (pabbi-)')
    tokens('d3949','Telugu',R='paracu|paṟacu|parcu|paṟucu|parapu|paṟapu|paṟupu|paravu|paruvu|parvu|paragu|parãgu|paṟãgu|pāru|pāṟu',D='prāku|pākul-āḍu')
    tokens('d3949','Konda',R='paR- (-t-)|pārpu',A='rēs- (-t-)')
    tokens('d3949','Kuwi',R='parpu',D='pressali')

    add('d3982','husked rice, grain of boiled rice','*per/par-V; velar, labial and plural formations',
        'p','e/a','r','unknown','CVC-V / CVC-V-K / CVC-V-m','noun',
        'Gondi pere/perek/paṛem, Konda per/peru and central perku/peruk independently establish p-V-r. Tamil parukkai/poruku supplies a possible related grain formation but does not settle the exact vowel of the bare eastern rice root.',
        'Several branches favor p-V-r before Telugu prālu, Kui prāu/prāma and Pengo/Manda preyi. The earlier order is clearer than the original V1/V2 qualities.',
        'A candidate *par-a > prā, with Telugu plural lu, gives prālu; a candidate *per-a > prē followed by eastern lowering gives Kui prāu. These are competing input assignments, not independently demonstrated steps for each language. Kui compound kōruvrau > kōruvau loses r after p>v in the compound, providing a directly attested local simplification pair.',
        'The shared rice semantics and regional distribution permit inheritance or old agricultural borrowing. Telugu ā should not be used to reconstruct a-a while Kui ā is used to infer earlier e-a without independent evidence. Exact V2 and whether Telugu lu is synchronically/plausibly plural need historical lexical evidence. Gondi kuṭkī is an explanatory species name, not a cognate. Keep this case outside strict vowel-conditioning counts, while retaining secure order comparison.',
        {'Tamil':('R','parukkai|poruku|porukku|peṟukkal','Retained order in differently suffixed grain terms.'),'Telugu':('D','prālu','Displaced order plausible; exact input and plural history uncertain.'),'Gondi':('R','pere|perek|paṛek|paṛēk|paraik|paraík|pariku|paṛem','Retained order and number morphology.'),'Konda':('R','per|peru','Retained root, plural perku in gloss.'),'Kui':('D','prāu|prāma|kōruvrau|kōruvau','Displaced rice stems and compound r-loss pair.'),'Pengo':('D','preyi','Cluster with uncontracted/altered final sequence.'),'Manda':('D','preyi','Same.'),'Naiki':('R','perku','Retained plural formation.'),'Parji':('R','peruk','Retained root/plural formation.')},
        input_confidence='high for order; low for exact vowel reconstruction',references='DEDR 3982; K80 rice/lowering comparison',eligibility='vowel-input-uncertain',boundary='Rice root and grain/number suffixes separated; Telugu lu analysis requires further morphological confirmation.')
