"""Brahui candidates and matched controls, read against PSS83 and Emeneau 1997."""

def populate(add,tokens):
    add('d1595','whirl, be giddy, turn a mill','*kiṟ-u/i/a; expressive strong and reduplicated formations',
        'k','i','ṟ','u/i/a','CVC-V / CVC-C / reduplication','verb/noun/expressive',
        'Tamil kiṟukiṟu/kiṟukku, Kannada giṟi/giṟu/giṟa and Tulu giriyuni independently establish k-i-apical order and several formations.',
        'The comparative full stems agree with retained Brahui kirrefing, not an initial kr- stem.',
        'Intervocalic voicing and ṟ>r vary by language; expressive gemination gives giṟṟ-/girr- without initial displacement. Emeneau analyzes Brahui kirrefing as causative of hypothetical *kirreng, explicitly not an attested simplex.',
        'This is a k-initial retention control for the very small Brahui t/p-heavy sample. Its expressive geminates and several suffix vowels prevent treating every form as one identical singleton formation. Telugu gīra has secondary or separate quantity; Badaga kiri moguḍu funeral object is semantically uncertain. Marathi girakṇẽ is a contact comparison, not an independent inherited Dravidian vote.',
        {'Tamil':('R','kiṟukiṟu|kiṟukku','Full and expressive strong stems.'),'Malayalam':('R','kiṟukiṟukka|kiṟukkam','Full stems.'),'Kannada':('R','giṟi|giṟu|giṟa|giṟiki|giṟaki|giṟike|giṟake|giṟṟane','Variable suffixes and gemination.'),'Tulu':('R','giriyuni|girigiṭṭi','Whirl stem and toy derivative.'),'Telugu':('R','giragira|giraka|gilaka|girra|gilla|gīra|giṟṟuna','R/l and quantity variants preserve initial order.'),'Gondi':('R','kīrkand','Long compound derivative.'),'Brahui':('R','kirrefing','Directly checked new causative in Emeneau 1997 p.444 §10.'),'Badaga':('A','kiri moguḍu','Uncertain semantic linkage.')},c2_structure='singleton and expressive geminate',references='DEDR1595; Emeneau1997 p.444 §10',eligibility='expressive-retention-control')
    add('d3195','sift, winnow','*taṟ- / *tāṟ-; proposed Brahui *tar-añc-',
        't','a','ṟ','i / unknown formative','CVC-V / CVVC / CVC-NC','verb',
        'Tamil short taṟi and long tāṟṟu/tāttu, Tulu sāruni and Telugu tālucu establish full t/s-a-apical order with independent quantity alternants. Newly reported Brahui tāring preserves that order.',
        'Brahui tāring and southern full roots favor derivation of dranzing/drãzing within the same sift family; they do not independently attest the exact proposed short *tarañc stem.',
        'Emeneau proposes *tarañc- > *trañc- > dranz-/drāz-, with displacement-family contraction or aphaeresis, initial voicing and nasal/affricate changes. The long retained tāring is a different formation/grade, not necessarily the immediate input to dranz-.',
        'Emeneau 1997 p.445 §12 removes the older query and rejects placement under d3402 *tūr as less economical. The original database drãzing spelling is preserved, not silently changed into drāzing. The -añc vowel is reconstructed, not independently supported by Tamil taṟi, so this does not prove a low-V2 law. Pengo dalŋgi ki has a different cluster/formative. Do not count the two Brahui derivatives as two roots.',
        {'Tamil':('R','taṟi|tāṟṟu|tāttu','Short and long independent grades.'),'Tulu':('R','sāriyuni|sāruni','Full long stem.'),'Telugu':('R','tālucu|tālcu','Full and medially syncopated long stem.'),'Pengo':('R','dalŋgi ki','Full initial CVC order; different cluster.'),'Brahui':('M','tāring|dranzing|drãzing','Retained and displaced family members, differing formation/quantity.')},quantity='short and long independent grades',references='DEDR3195; Emeneau1997 p.445 §12; Emeneau1971 pp.192–194 cited by 1997, not directly obtained',eligibility='brahui-displacement-comparison',input_confidence='high for root order, conditional for exact displaced formative')
    tokens('d3195','Brahui',R='tāring',D='dranzing|drãzing')
    add('d3402','winnow, scatter, sprinkle','*tūr / *tūṯ- strong formation',
        't','u','ṟ/ṯ','u','CVVC / CVVC-C','verb/noun',
        'Tamil tūṟṟu, Malayalam tūṟṟuka, Kannada tūṟu and Telugu tūru independently support long ū before the apical.',
        'The full order is shared across southern, Gondi and eastern stems; no initial cluster requires exchange.',
        'Southern apical strong/weak alternants and eastern ṭūṭ have apical/initial stop assimilation or correspondence changes while ū stays between the consonants. Tulu tūpu can reflect medial cluster assimilation/loss. Telugu compound tūru-pettu > tūrpettu shows medial syncope.',
        'Emeneau 1997 explicitly rejects deriving Brahui dranz- here; a cross-reference is not a Brahui attestation. Kolami tūrpet may be a Telugu compound loan but the source does not decide it. Badaga tūravare/purāvare bean names are not secure winnow cognates. The source query comparing Sanskrit śūrpa is not a settled borrowing direction.',
        {'Tamil':('R','tūṟṟu','Long strong stem.'),'Malayalam':('R','tūṟṟuka','Long strong stem.'),'Kannada':('R','tūṟu','Long full stem.'),'Telugu':('R','tūru|tūru-paṭṭu|tūran-ettu|tūrupettu|tūrpettu|tūrpiḍi','Full base and compounds.'),'Gondi':('R','tūrānā|turehtáná','Quantity varies by source.'),'Kuwi':('R','ṭūṭ- (-h-)','Changed stops, retained vowel order.'),'Pengo':('R','ṭūṭ- (-t-)','Changed stops, retained vowel order.'),'Manda':('R','ṭūṭ','Changed stops, retained vowel order.'),'Tulu':('O','tūpu|tūpuni','Medial apical no longer visible.'),'Kolami':('A','tūrpet- (tūrpett-)','Possible borrowed compound.'),'Badaga':('A','tūravare|purāvare','Bean names; questionable link.')},quantity='long',c2_structure='singleton and strong apical formation',references='DEDR3402; Emeneau1997 p.445 §12',eligibility='long-vowel-control')
    add('d4986','waist, back, loins','*mol / *mul-k',
        'm','o/u','l','zero / a','CVC / CVC-k','noun',
        'Telugu mola, Konda mola and Gondi molkī establish medial l; Kolami/Naikri mulke and Parji mulka preserve the cluster needed for the Brahui comparison.',
        'Full regional l and lk support loss of cluster-initial l in Brahui mux, without requiring initial ml-.',
        '*mul-k > *muk > mux by lateral loss and velar frication is Emeneau 1997 p.441 §2.2. Regional o/u and Telugu malugu/malumu require vowel/derivational histories independent of metathesis.',
        'Brahui mux is an opaque other development, not a retained-apical negative and not evidence for hidden metathesis. The independently attested lk cluster makes direct lateral loss economical. Duplicate DEDR and 1997 records of mux supply one family-language observation.',
        {'Telugu':('R','mola|malugu|malumu','Full and derivative medial lateral.'),'Konda':('R','mola','Full lateral.'),'Gondi':('R','molkī','Medial cluster.'),'Kolami':('R','mulke','Medial cluster.'),'Naikri':('R','mulke|mulkene ḍā̃ḍ','Base and compound.'),'Parji':('R','mul būla|mulka būla','Base/cluster compound variants.'),'Brahui':('O','mux','Direct medial lateral loss supported by comparison.')},c2_structure='singleton or preconsonantal lateral',references='DEDR4986; Emeneau1997 p.441 §2.2',eligibility='cluster-loss-control',mechanism='Medial l loss before k; no independent evidence of initial metathesis.')
    add('d5078','soft, weak, gentle; knead','*mel; *mel-k; strong *mell-',
        'm','e','l','i/u/a / zero','CVC-V / CVC-k / CVCC','adjective/verb/adverb',
        'Tamil mel/meli/melku, Malayalam mel/meliyuka, Kannada mel/melu/melpu and Kota melg:melk independently support e-l and a velar formation.',
        'Brahui bēɣ- can be derived directly from medial mel-k; Kui mṛērna has a cluster absent from the full comparanda but its exact formative is uncertain.',
        'Emeneau 1997 p.442 §4 derives *mel-k > *bel-k > bēɣ with front-vowel-conditioned m>b, e>ē and cluster lateral loss. The exact order of lengthening and loss is not proved. Kui *mel-V-r/n > *mlV-r/n > mṛērna is a possible displacement comparison, with suffix and long ē still underdetermined.',
        'The database reconstruction *mēl high/west is a wrong homonymous association, excluded. Strong mell- adverbs are not independent root votes. Brahui ē is not proof of a long proto-root: Emeneau treats it as the reflex of earlier short e under a contact-affected vowel inventory. Gadaba mellaga may be a Telugu loan; source checking is needed.',
        {'Tamil':('R','mel|meli|melku|mella|melli','Singleton, velar and strong formations.'),'Malayalam':('R','mel|meliyuka|melluka','Full and strong stems.'),'Kannada':('R','mel|melu|melpu|mella|mellane','Full and strong formations.'),'Kota':('R','melg- (melgy-)|melk- (melky-)','Velar stem contrast.'),'Toda':('R','mely|mes̱x- (mes̱xy-)|mes̱k- (mes̱ky-)','Medial reflexes, not initial displacement.'),'Kodagu':('R','melle','Strong adverb.'),'Tulu':('R','mella|meliyuni|melipuni|melippu','Full and strong formations.'),'Telugu':('R','melãta|melãtuka|mella|mellani|mellãgā|mellãga|mellana|mellanan|melamella|melamellãgā','Singleton nouns and strong adverbs.'),'Konda':('R','melesa|meleka','Full e-l.'),'Kui':('A','mṛērna','Likely displacement-family comparison but exact formation uncertain.'),'Brahui':('O','bēɣ-','Direct cluster lateral loss plus independent vowel/initial changes.'),'Gadaba':('A','mellaga','Possible Telugu loan.'),'Badaga':('R','melle|melēna|melīsu','Retained order, varying formation.')},c2_structure='singleton and geminate and l-k cluster',references='DEDR5078; Emeneau1997 pp.441–442 §§2.1–4',eligibility='cluster-loss-control',input_confidence='high for mel-k order; conditional for Kui exact formative')
    add('d2883','flow, pour, drip; blood/drop','*cor/tar? regional *cur/tor with short and long grades; labial drop derivative',
        'c/t','o/u','r','i/u/a / unknown','CVC-V / CVVC / CVC-m-p','verb/noun',
        'Tamil cori/cura/cōr and tōr, Kannada suri/sōr/tore, Kota corv/toyr and Telugu torūgu/torāgu/toṟãgu establish full vowel-before-r order with several initial and quantity correspondences.',
        'Brahui curring retains full order whereas trump/tramp have r before the vowel. PSS83 p.245 treats drop as a stronger metathesis example than simple aphaeresis, because output vowel is not the expected second i.',
        'A pre-Brahui full *tur/tor-V-mp > *tr-V-mp > trump/tramp is a displacement-family comparison. Exact V2, t/c development and a/u outcomes are not jointly established; the modern Telugu long suffix vowels are not automatically the Brahui input. Parji cōrp > cōp illustrates direct medial r loss. Toda tvar has a preceding glide but r remains after a.',
        'The traditional seven-item Brahui sample calls most roots t-initial, but this family has independently attested c/t variants, so a categorical Proto-Dravidian c exclusion is not justified. Telugu jobbillu is opaque assimilation or questionable cognacy, not positive metathesis. Markodi cre blood beside core-like forms is a fresh possible local syncope/displacement comparison, not automatically the old Telugu change. Konda sō- has an alternative d2867 link. A compound torgi stranded in a gloss still needs original-page recovery.',
        {'Tamil':('R','cori|cura|cōr|tōr (neyttōr','Full short/long roots and initial alternants.'),'Kannada':('R','suri|sōr|tore','Full related stems.'),'Kota':('R','corv- (cord-)|toyr- (torc-)','Full order despite medial changes.'),'Toda':('R','tvar','Glide before vowel, r after it.'),'Telugu':('A','torūgu|torāgu|toṟãgu|jobbillu','Full r stems plus opaque labial derivative.'),'Brahui':('M','curring|trump|tramp','Full verb versus displaced drop nouns; not identical formation.'),'Konda':('A','sō- (-t-)','Alternative cognacy d2867.')},quantity='short and long grades',references='DEDR2883; PSS83 pp.244–245 citing Emeneau1971 pp.192–194',eligibility='brahui-displacement-comparison',input_confidence='high for full r order; conditional for exact drop stem')
    tokens('d2883','Telugu',R='torūgu|torāgu|toṟãgu',O='jobbillu')
    tokens('d2883','Brahui',R='curring',D='trump|tramp')
    add('d3119','sprout, flourish','*taẓ-a / *teẓ; derivative with k',
        't','a/e','ẓ','a/i/unknown','CVC-V-k','verb',
        'Tamil taṛ̆ai and Malayalam taṛ̆a/taṛ̆ekka plus Kannada taṛ̆e establish medial apical order; vowel alternants and strong extensions are independent of Brahui.',
        'Full southern stems and Kui dalga favor earlier t-V-apical versus Brahui trikking/trikk. The exact Brahui suffix vowel is not independently recovered.',
        '*taẓ-V-kk > *tẓV-kk > trikk is a plausible displacement-family sequence, with apical merger to r. If V2 was i, simple loss of V1 would also yield trik-; if low a, additional vowel change is needed. The available data do not decide.',
        'PSS83 p.245 includes this among examples compatible with aphaeresis. Do not invent a high-i formative solely to derive the observed i. Brahui trikking is homophonous with d3244 wither but the two comparative roots and meanings remain separate pending evidence for a semantic bridge.',
        {'Tamil':('R','taṛ̆ai|taṛ̆aivu|taṛ̆aippu','Independent full apical.'),'Malayalam':('R','taṛ̆a|taṛ̆ekka|taṛ̆appu|teṛ̆uku|teṛ̆ukka','Full stems and vowel alternants.'),'Kannada':('R','taṛ̆e|daḷi|daḷe|daḷḷisu','Apical variants, full order.'),'Kui':('R','dalga (dalgi-)','Medial apical cluster.'),'Brahui':('D','trikking|trikk','Displacement family, exact mechanism uncertain.')},references='DEDR3119; PSS83 pp.244–245',eligibility='brahui-displacement-comparison',input_confidence='high for order, low for exact displaced formative')
    add('d3158','dance, jump, leap','*tā-ṇṭ-',
        't','a','ṇṭ','u','CVV-NP','verb',
        'Tamil tāṇṭu and matching Malayalam/Kannada forms independently support long ā and nasal-stop cluster; Telugu dā̃ṭu and Konda ḍāṭ agree after nasal loss.',
        'No comparative medial r supports deriving Brahui traḍḍing by the ordinary apical-exchange process.',
        '*tāṇṭ > Telugu dā̃ṭu/Konda ḍāṭ can proceed by initial voicing and nasal loss. Brahui traḍḍing requires unexplained r insertion/restructuring, a different reconstruction, borrowing or false cognacy; one-for-one metathesis is not established.',
        'This is an explicit long nasal-cluster comparison, not a positive merely because Br has tr-. The Sanskrit tāṇḍava comparison has unresolved borrowing direction. Independent evidence for an r-bearing pre-Brahui stem would change the diagnosis.',
        {'Tamil':('R','tāṇṭu','Long nasal-stop input.'),'Telugu':('R','dā̃ṭu','Long vowel before nasalized stop.'),'Konda':('R','ḍāṭ- (-t-)','Nasal loss, retained order.'),'Brahui':('A','traḍḍing','Unexplained additional r.')},quantity='long',c2_structure='nasal-stop cluster',references='DEDR3158',eligibility='long-nasal-cluster-control',mechanism='Brahui r unexplained; ordinary exchange not demonstrated.')
    add('d3244','wrinkle, wither, be dried up','*tir-aŋ/k; *tir-ay',
        't','i','r','a','CVC-a-NC / CVC-a-kk / CVC-ay','verb/noun',
        'Tamil tiraŋku/tirakku/tirai and Malayalam tira independently establish i-r-a order. Kannada tere, Kodagu tere and Telugu tera agree with full order after vowel developments.',
        'Brahui trikking retains i after r. Simple deletion of first i from independently supported *tirakk would give trakk, making this a stronger vowel-preservation argument than same-vowel cases.',
        '*tir-a-kk > *tri-a-kk > trikk is a possible literal-exchange plus vowel-loss derivation. Assimilation of the two vowels followed by loss of the first also remains possible; the comparison establishes displacement-family history more securely than its phonetic implementation.',
        'PSS83 p.245 identifies wither and drop as stronger metathesis cases. The precise relation of nasal tiraŋku, strong tirakku and nominal tirai must remain morphological. Brahui trikking sprout d3119 is not counted as the same root solely on homophony.',
        {'Tamil':('R','tiraŋku|tirakku|tirai','Independent a formative.'),'Malayalam':('R','tira|tirekkuka','Full order.'),'Kannada':('R','tere','Full order.'),'Kodagu':('R','tere','Full order.'),'Telugu':('R','tera','Full order.'),'Brahui':('D','trikking','i preserved after r, independent low a in cognate formation.')},references='DEDR3244; PSS83 pp.244–245',eligibility='brahui-displacement-comparison',input_confidence='high for i-r-a in southern strong stem; medium for exact Brahui identity')
    add('d3358','pluck, nip off','North Dravidian *tur/tuṛ-(u)-k',
        't','u','r','u/zero uncertain','CVC-(V)-k','verb',
        'Kurux tuṛᵘxnā and related forms supply a full t-u-r sequence independently of Brahui trukking.',
        'The geographically separated Kurux full stem versus Brahui trukking favors reduction/displacement in Brahui. Superscript u in Kurux transcription must not automatically be treated as a full independent suffix vowel.',
        '*tur-(u)-k > *tru-k > trukk is the comparison. Literal u/r exchange and loss of initial u from a two-u stem cannot be distinguished without establishing the status of the Kurux superscript vowel and the pre-Brahui stem.',
        'PSS83 p.245 lists this among cases compatible with aphaeresis. Only two northern branches attest the reviewed family; no Telugu denominator vote arises from their presence.',
        {'Kurux':('R','tuṛᵘxnā|tuṛxᵘrnā|tuṛxa\'ānā','Full order and morphology; superscript vowel caution.'),'Brahui':('D','trukking','Displacement-family comparison, mechanism uncertain.')},references='DEDR3358; PSS83 pp.244–245',eligibility='brahui-displacement-comparison',input_confidence='high for order, uncertain for V2 phonemic status')
    add('d3367','stuff, crowd, thrust in','*tuṯ/tuṟ-u; strong and velar/labial derivatives',
        't','u','ṯ/ṟ','u/a','CVC-V-C / CVCC','verb',
        'Tamil tuṟu/tuṟumu/tuṟumpu and strong tuṟṟu, Malayalam tuṟuka and Kannada tuṟugu/tuṟagu independently establish u before an apical and several following formations.',
        'Full southern and central stems support derivation of Brahui trujjing from a fuller t-u-apical stem; the affricate formative does not have an exact independently matched full stem here.',
        '*tuṯ/ṟ-u-C > *tṯ/ṟu-C > trujj- is a displacement-family hypothesis; same-u aphaeresis remains possible. Telugu tuṟugu/turugu and tuṟumu/turumu retain order. Strong tukku/tuttu and eastern cuc/tuc can arise by medial assimilation and are not automatic evidence for concealed initial metathesis.',
        'PSS83 p.245 includes this among aphaeresis-compatible examples. ṯ versus ṟ and affricate development require independent correspondence reconstruction; assigning a unique apical from the outcome would overstate the data. Strong and weak formations are kept in one root family with mixed input structure.',
        {'Tamil':('R','tuṟu|tuṟumu|tuṟumpu|tuṟṟu','Full and strong variants.'),'Malayalam':('R','tuṟuka|tuṟuttuka|tuṟuku','Full order.'),'Kannada':('R','tuṟugu|tuṟagu|tuṟuku|tuṟaku|tuṟubu|tuṟumbu','Independent suffix variation.'),'Telugu':('A','tuṟugu|turugu|tuṟumu|turumu|tuṭṭe','Retained singleton and opaque strong derivative.'),'Konda':('R','tuṟbi- (-t-)','Medial apical.'),'Brahui':('D','trujjing','Displacement-family cluster, exact suffix unresolved.')},c2_structure='singleton and strong apical formations',references='DEDR3367; PSS83 pp.244–245',eligibility='brahui-displacement-comparison',input_confidence='high for u-apical order; conditional for affricate formation')
    tokens('d3367','Telugu',R='tuṟugu|turugu|tuṟumu|turumu',O='tuṭṭe')
    add('d4177','twist, roll into a coil','*pur-i / *pir-i; velar and labial formations',
        'p','u/i','r','i','CVC-i-k / CVC-i-p','verb/noun',
        'Tamil puri/piri, Malayalam puriyuka/piriyuka, Kannada puri and Kodagu piri independently establish a full apical root with high i formative; the root vowel varies independently.',
        'Kui priu/prīpa have r before the vowel while Brahui pirɣẖing retains it after i. The latter is the explicit retention exception to the traditional Brahui closed-stem generalization.',
        'Kui *pir/pur-i-p > *pri-i-p > prīp is a possible contraction; priu has separate final morphology. Brahui *pir-k > pirɣ preserves the medial cluster, contrasting with the other t/p-initial Brahui cases. Telugu piri/puri and compounds retain full order.',
        'PSS83 p.245 acknowledges the Brahui exception despite a following consonant. It cannot be excluded from the class simply because it did not change. Root-vowel variation and different velar/labial formations may matter, but no demonstrated deterministic blocker is available. Winfield 1928 p.10 priu:prīnga plural morphology corroborates the Kui family without adding an independent root.',
        {'Tamil':('R','puri|piri','Full independent order.'),'Malayalam':('R','puriyuka|piriyuka|pirikka|piri','Full and strong stems.'),'Kannada':('R','puri','Full order.'),'Kodagu':('R','piri- (pirip-, piric-)|biri- (birip-, biric-)|pirip','Full stem and transitive formation.'),'Telugu':('R','piri|puri|pirigonu','Full order.'),'Kui':('D','prīpa (prīt-)|priu','Displaced base and labial formation.'),'Brahui':('R','pirɣẖing','Explicit closed-stem counterexample.')},references='DEDR4177; PSS83 pp.244–245; Winfield1928 p.10',eligibility='brahui-retention-counterexample',input_confidence='high for full high-vowel stem')
    add('d4183','squeeze, express liquid, milk','*piẓ-i; nasal-stop derivatives *piṇṭ-',
        'p','i','ẓ','i','CVC-i / CVC-NC / CVNC','verb/noun',
        'Tamil piṛ̆i and Malayalam piṛ̆iyuka, Kannada piṛ̆i and Konda piṛs establish singleton piẓ order independently; piṇṭi/piṇḍu oilcake and squeeze formations separately establish nasal-stop derivatives.',
        'Kui pṛihpa and Brahui princing have the apical before the vowel, whereas Brahui piṛ̆ẖing/bīṛing and Telugu piḍucu retain the full sequence. Nasal derivatives do not prove a primary nasal input for the displaced cluster.',
        '*piẓ-i-C > *pẓi-C > pri-C is the displacement-family comparison, with same-vowel contraction or aphaeresis underdetermined. Kui vṛīsa/bṛīc add initial voicing/frication and quantity; Kuvi ṛīsk could lose initial labial after a cluster, while vīskinai could lose the apical by another route. Telugu piṇḍu/piṇḍi involve medial assimilation, not initial reversal.',
        'The red database piṇṭ head does not replace the independently supported singleton input of piẓi. Brahui bīṛing milk is a distinct long formation. Emeneau 1997 p.443 §7 prefers d4135 for pisfing; it is not counted here. DEDR frontmatter says 4135/4183 were repartitioned on phonological grounds, so their cognacy assignments are hypotheses to test, not independent confirmation of an exceptionless sound rule. Exact Brahui piṛ̆ẖ transcription still merits original-page checking.',
        {'Tamil':('R','piṛ̆i|piṇṭi','Singleton verb and nasal noun.'),'Malayalam':('R','piṛ̆iyuka|piṇṭi','Independent singleton plus nasal derivative.'),'Kannada':('R','piṛ̆i|piṇḍu|hiṇḍu','Singleton and assimilated formations.'),'Telugu':('R','piḍucu|piṇḍu|piṇḍi','Order retained across apical strengthening/assimilation.'),'Konda':('R','piṛs','Medial apical.'),'Kui':('D','pṛihpa (pṛiht-)|vṛīsa (vṛīsi-)|vṛīska (vṛīski-)|bṛīc','Displaced cluster, distinct quantities/formations.'),'Kuwi':('A','ṛīsk- (-it-)|vīskinai','Possible post-displacement initial loss versus opaque apical loss.'),'Brahui':('M','princing|piṛ̆ẖing|bīṛing','Displaced and retained formations.')},c2_structure='singleton plus nasal-stop derivatives',references='DEDR4183; DEDR frontmatter phonological repartition note; PSS83 pp.244–245; Emeneau1997 p.443 §7',eligibility='brahui-displacement-comparison',input_confidence='high for singleton full order; medium for exact cross-language formations')
    tokens('d4183','Brahui',D='princing',R='piṛ̆ẖing|bīṛing')
    tokens('d4183','Kuwi',D='ṛīsk- (-it-)',O='vīskinai')
