"""Boundary controls and apparent exceptional targets; exclude mislinked proto-heads."""

def populate(add,tokens):
    add('d533','fly, bee','*ī; formations with -p/-k and compounds',
        'Ø','ī','Ø','none','V long root + nominal extensions','noun',
        'Tamil ī, Malayalam īcca, Kota īp and Toda īpy support a vowel-only long root with distinct extensions. Telugu ī̃ga has a velar/nasal formation. Prawn *eṯ-V-y under this entry is a mislinked reconstruction.',
        'There is no reconstructed initial vowel–apical sequence to reverse in the fly simplex. Initial consonants in honey/flower compounds belong to their first members, not a moved segment of ī.',
        'Telugu *ī-Nk > ī̃ga retains initial long vowel. Kolami/Naikri nīŋga may add n or preserve a different formation. Tamil tēṉ-ī, Gondi pʰuk+ī, Kui pūk+i and Kurux tīn+ī are compounds, not evidence for original *tēn as the fly root.',
        'The imported *tēn fly/bee reconstruction conflates compound material with the simplex hypothesis unless independently argued. Brahui hīṛ̆ẖ has prothetic/extended consonants requiring its own history. Tulu ippi is strengthened and denotes fly eggs. Latin Bombinatrix glabra is not a Telugu word. These are scope controls, excluded from the apical denominator.',
        {'Tamil':('R','ī|īccai','Vowel-initial fly root; cc derivative separate.'),'Malayalam':('R','īcca','Vowel-first strengthened derivative.'),
         'Kota':('R','i·p','Long vowel plus labial suffix.'),'Toda':('R','īpy','Long vowel plus labial/glide suffix.'),
         'Telugu':('R','ī̃ga','Long-vowel nasal/velar formation.'),'Kuwi':('R','īpu','Vowel-first maggot derivative.'),
         'Tulu':('R','ippi','Vowel-first strengthened derivative.'),'Irula':('R','i·ppi','Vowel-first derivative.'),
         'Kolami':('A','ni·ŋga','Nasal onset origin unresolved.'),'Naikri':('A','nīŋga','Nasal onset origin unresolved.'),
         'Gondi':('O','pʰukī','Source explicitly segments flower+fly compound.'),'Kui':('O','pūki','Source explicitly segments pūk+i.'),
         'Kurux':('O','tīnī|ēxā','Compound fly name and separately extended gadfly noun.'),'Malto':('A','téni','Compound-origin hypothesis, exact development requires independent support.'),
         'Brahui':('A','hīṛ̆ẖ','Initial h and final consonants do not instantiate apical displacement.')},
        quantity='long',c2_structure='absent',eligibility='outside-target-control',input_confidence='high',references='DEDR 533',
        boundary='Compound first members and simplex nominal extensions distinguished.',mechanism='No eligible apical in the inherited simplex; compound and extension histories separate.')

    add('d561','finger/toe nail; finger','regional *ukir, *gōr/*kōr, *or-kk; deeper order unresolved',
        'Ø','u/o','k','i/u/unknown','VC-VC / CVC / VC-CC regional formations','noun',
        'Tamil/Malayalam ukir, Kannada ugur and Tulu uguru establish southern vowel–velar–vowel–rhotic. Telugu/Konda gōru, Central Dravidian gōr and Brahui hōr form another regional set; Kurux orᵒx and Malto orgu have r before velar. K03 p.484 deliberately lists distinct regional reconstructions.',
        'The broad southern sequence favors *ukir for SD I, but cannot by itself decide whether all gōr and ork forms arose from that exact proto-input. A universal *okar selected to yield gōr would use the outcome to choose the second vowel.',
        'Conditional *ok-ar > *ko-ar > kōr > gōru would require exceptional displacement of a velar, contraction and voicing. Alternatively a separate *kōr stem and an expanded southern *ukir need a deeper morphological/phonological explanation. Kurux/Malto could show *ukir > *urk > ork with liquid/velar reversal, but inherited *ork is also possible; direction is not fixed.',
        'This is not evidence that the ordinary Telugu apical condition freely extends to k. The same gōr family spans several subgroups and Brahui, so a late Telugu-only event is insufficient. Kui unguli looks like an Indo-Aryan finger term and must be checked against the original source instead of counted as a conservative ukir reflex. Parji gēri has a separate vowel history. Related d926/d2257 comparisons remain to adjudicate.',
        {'Tamil':('R','ukir','Southern order.'),'Malayalam':('R','ukir','Southern order.'),
         'Kannada':('R','ugur|ugi','Southern order, variable final rhotic.'),'Tulu':('R','uguru','Southern order.'),
         'Kota':('O','u·r|u·r-gaṇ','Medial consonant/vowel loss with lengthening.'),'Toda':('O','ȳr','Medial consonant loss and fronting/lengthening.'),
         'Kodagu':('O','oy','Medial loss and local rhotic development.'),
         'Telugu':('A','gōru','Exceptional velar displacement versus distinct regional formation.'),
         'Konda':('A','gōru','Same unresolved regional relationship.'),'Kui':('A','gōra|unguli|unjuli','Regional gōr and separate likely Indo-Aryan finger words.'),
         'Gondi':('A','gōr','Source supplement; same regional gōr relationship.'),'Gadaba':('A','gēre','Source supplement; e-vowel form comparable with Parji gēri.'),
         'Kuwi':('A','gōru|gōrū','Regional gōr series; exact deeper input unresolved.'),'Manda':('A','gūr ( -ke)','Regional gōr-type finger noun with high vowel.'),
         'Kolami':('A','go·r ( go·ḍl)','Regional gōr with plural consonant alternation.'),'Naikri':('A','gōr ( gōrḷ)','Regional gōr with plural suffix.'),
         'Naiki':('A','gōr','Regional gōr.'),'Parji':('A','gēri ( gēril)','Different vowel quality; direction unresolved.'),
         'Kurux':('A',"orᵒx (Grignard'soṛᵒxis erroneous; Pfeiffer)",'r precedes velar; source explicitly rejects retroflex transcription.'),
         'Malto':('A','orgu','r precedes velar; possible internal reversal.'),'Brahui':('A','hōr','Related regional consonant-first stem, h/k history separate.'),
         'Badaga':('R','ugilu','Southern vowel-first velar order; r/l correspondence separate.')},
        eligibility='exceptional-nonapical-input',input_confidence='low',quantity='mixed/uncertain',references='DEDR 561; K03 pp.109,484; PSS83 exceptional *okar discussion',
        boundary='Multiple regional formations recorded; no fully specified single Proto-Dravidian input asserted.',
        mechanism='Competing regional reconstructions; nonapical displacement and internal consonant reversal remain hypotheses.')

    add('d570','suspending cord, load-rope knot','regional *ukk/ugg-; relation to *uṟ-V unresolved',
        'Ø','u','kk','unknown','VCC-V nominal formations','noun',
        'Kannada ugga/ukkaḍa, Telugu uggamu and Tulu oggi establish a geminate velar regional cord name. The displayed **uṯVkV depends on a deeper comparison with d708, not on an apical attested in these core reflexes.',
        'All present lexical witnesses are vowel-initial; an earlier apical plus assimilation is a hypothesis needing the separate d708 comparison.',
        'Regional *ugg > Telugu uggamu/Kannada ugga involves nominal endings, not initial displacement. Naiki ugur/uggur/ogur shows consonant strength and vowel variation, with a rhotic after the velar.',
        'Tamil ukkam is explicitly a Telugu loan and supplies no independent proto-input. A related Prakrit ukkā well-lever term is cited by DEDR, leaving diffusion direction and scope open. Count as a geminate/control formation, not an independently established singleton apical counterexample.',
        {'Tamil':('B','ukkam','Source explicitly < Telugu.'),'Kannada':('R','ugga|ukkaḍa','Geminate velar vowel-first names.'),
         'Tulu':('R','oggi','Vowel-first cord noun.'),'Telugu':('R','uggamu','Vowel-first nominal formation.'),
         'Naiki':('R','ugur|uggur|ogur','Vowel-first variants; rhotic occurs after velar.'),'Kurux':('R','ugī','Vowel-first knot term.')},
        c2_structure='geminate',eligibility='input-or-contact-uncertain-control',input_confidence='medium',references='DEDR 570 and its comparisons with d708 and Prakrit ukkā',
        boundary='Nominal expansions are regional; deeper apical reconstruction is not treated as established.')

    add('d572','finger ring','regional *uŋgar- / *uŋgur-',
        'Ø','u','ŋg','a/u','VNCVC regional noun','noun',
        'Kannada uŋgara/uŋgura, Telugu uŋgaramu and Badaga ungara agree on an initial nasal–velar cluster after the vowel. The displayed pestle *ula-kk-V is wrongly linked and is not evidence for a lateral input.',
        'The regional forms support vowel–ŋg order; shorter uŋgra lacks only the medial vowel and does not reverse segments.',
        '*uŋgara > uŋgra through medial syncope, independently attested beside fuller Kannada and Telugu forms. Tulu uŋgila and Naiki uŋgriyam have distinct vowel/liquid and suffix histories.',
        'Identical regional ring names may diffuse, so their agreement is not proof of Proto-Dravidian antiquity. Toda ugorm is explicitly borrowed from Badaga. This is an outside-apical control that the erroneous pestle head would otherwise make appear relevant.',
        {'Kannada':('R','uŋgara|uŋgura|uŋgra','Full and syncopated variants retain segment order.'),
         'Tulu':('R','uŋgila','Vowel-first nasal-velar name, liquid variant.'),
         'Telugu':('R','uŋgaramu|uŋgramu','Full and syncopated variants; no swap.'),
         'Kolami':('A','oŋgaram','Likely regional diffusion, donor history not established.'),'Naiki':('A','uŋgra|uŋgriyam','Regional name and recipient ending.'),
         'Badaga':('R','ungara','Vowel-first ring name.'),'Toda':('B','ugorm','Explicit Badaga loan used in song.')},
        c2_structure='nasal-stop-cluster',eligibility='outside-target-control',input_confidence='high',references='DEDR 572; Hockings–Pilot-Raichoor 1992 p.62',
        boundary='Whole regional noun; shorter variants result from medial syncope.',mechanism='Medial vowel deletion, not metathesis.')

    add('d586','body, belly','*uṭ-al / *uṭ-amp-; expressive belly formations',
        'Ø','u','ṭ','a','VC-al / VC-a-mp','noun',
        'Tamil uṭal/uṭampu, Malayalam uṭal and Kannada oḍal independently support vowel-first retroflex with low second vowel. Konda oṛol and Kota oṛḷ preserve the same consonant order.',
        'Broad vowel-first body nouns favor original V–ṭ. Telugu oḷḷu contains later medial assimilation from oḍalu, not initial movement of ḍ.',
        '*uṭ-al > *oḍal > Telugu oḍalu > oḷḷu via medial-vowel loss and retroflex/lateral assimilation. Kannada ḍoḷḷu/doḷḷu and Tulu ḍoḷḷu/ṭoḷḷu could involve aphaeresis/displacement plus expressive strengthening, but may instead be separately expressive belly words.',
        'The independently matched low-a body noun is a substantive Telugu retained-order case. The southern consonant-initial potbelly forms should not be counted as inherited metathesis until their derivation or early attestations are established. Toda v before its reflex is prothesis, not movement of the medial retroflex. Badaga bodily cloth compounds do not create new root evidence.',
        {'Tamil':('R','uṭal|uṭalam|uṭar|uṭampu','Retained order in distinct nominal expansions.'),
         'Malayalam':('R','uṭal|uṭalam|uṭampu','Retained order.'),'Kota':('R','oṛḷ','Syncope, vowel first.'),
         'Toda':('R','vɨṛḷ','Prothetic v with retained vowel before original apical.'),
         'Kannada':('A','oḍal|oḍambi|oḍambe|ḍoḷḷu|doḷḷu','Retained body series plus expressive/initial-loss belly forms.'),
         'Tulu':('A','uḍalɯ|uḍālɯ|oḍālɯ|ḍoḷḷu|ṭoḷḷu|toḷḷɛ','Retained body nouns and uncertain consonant-initial potbelly series.'),
         'Telugu':('O','oḍalu|oḷḷu','Retained body noun plus medial assimilation.'),
         'Konda':('R','oṛol','Vowel-first body noun, harmony/oblique alternation separate.'),
         'Badaga':('A','odalu|odambu|doḷḷu|doḷḷa|doḷḷi','Retained body words plus uncertain expressive stout-person series.')},
        input_confidence='high',references='DEDR 586',boundary='Body -al and -amp expansions independently observed; expressive potbelly derivatives not assumed identical.',
        mechanism='Telugu medial assimilation; southern initial-loss/expressive alternatives unresolved.')
    tokens('d586','Telugu',R='oḍalu',O='oḷḷu')
    tokens('d586','Kannada',R='oḍal|oḍambi|oḍambe',A='ḍoḷḷu|doḷḷu')
    tokens('d586','Tulu',R='uḍalɯ|uḍālɯ|oḍālɯ',A='ḍoḷḷu|ṭoḷḷu|toḷḷɛ')
    tokens('d586','Badaga',R='odalu|odambu',A='doḷḷu|doḷḷa|doḷḷi')
