"""Independently motivated free-root, quantity and root-cluster controls."""

def populate(add,tokens):
    add('d3986','tooth; toothstick compounds','*pal; *pal#kar tooth-stick',
        'p','a','l','zero','CVC free root / CVC#CVC','noun',
        'Tamil pal, Malayalam pal, Kota pal, Gondi pal and Central Dravidian pal/pel independently establish a short closed free root, with no original second root vowel. Final u in some languages is not evidence for a formative *-u.',
        'Agreement across southern, south-central, central and northern branches supports p-a-l. The toothstick compounds independently contain the second member kar/kaṟ wood (DEDR1389), so their internal liquid order must be examined separately.',
        '*pal > Telugu palu/pallu and eastern pal/palu retains order. Telugu plural paṇḍlu and singular pannu are a morphological/cluster problem: DEDR explicitly calls pannu a back-formation. Toda pas̱ is lateral fricativization, Tulu paru a rhotic correspondence. Gondi palkār > parkal and Parji perkal plausibly reverse the two compound liquids, without placing a lateral before the first vowel.',
        'This supports a free-root restriction more directly than choosing only verbs with positive outcomes. The Telugu parser puts paṇḍlu/pannu in gloss text; those forms are source claims, not independent parsed lexical rows. Kuvi kaṟ/kar/kaṟal are pieces of an editorial cross-reference to1389, not additional tooth reflexes. The unrelated *pāl milk head is excluded. Compound liquid reversal could be shared or borrowed between neighboring Gondi/Parji; the dialect distribution alone does not date it.',
        {'Tamil':('R','pal|pallaṉ|palli|paluku|palaki','Free root and derivatives.'),'Malayalam':('R','pal|pallu|pallan','Free root.'),'Kota':('R','pal','Free root.'),'Toda':('R','pas̱|pas','Final lateral fricativization.'),'Kannada':('R','pal|palla|haluve|halube|halive|halike|halaku','Initial p>h in derivatives, no reversal.'),'Kodagu':('R','pallɨ','Free root with final vowel.'),'Tulu':('R','paru|parkaḍḍi|parkaḍi','Root and compound, no initial displacement.'),'Telugu':('R','palu|pallu|palugarra|palu-goṟṟu|palugu','Retains first vowel/apical order.'),'Gondi':('R','pal|val|palkār|parkal|pelkiaṛ','Initial order retained; compound liquid reversal separate.'),'Konda':('R','pal|palaŋaṟu','Free root and toothstick compound.'),'Kui':('R','paḍu','Source also palu/palka; final-l changes not metathesis.'),'Kuwi':('R','palu|pallu (palka)|pallū (palka)|pallakara','Free root, plurals and compound.'),'Manda':('R','pal','Free root.'),'Kolami':('R','pal','Free root.'),'Naikri':('R','pal','Free root.'),'Naiki':('R','pal','Free root.'),'Parji':('R','pel|perkal|perkela','Initial order retained; internal compound reversal separate.'),'Gadaba':('R','pallū|pal|palkara','Free root and compound.'),'Kurux':('R','pall','Free root.'),'Malto':('R','palu','Free root.'),'Badaga':('R','hallu|allu','p>h>zero, lateral remains after vowel.')},
        input_confidence='high',confidence='high',references='DEDR3986 and1389; PSS83 p.229 free-root control (oldDED3288)',eligibility='free-root-control',boundary='Bare monosyllabic noun established across branches; added final vowel and toothstick compounding are independent of outcome.',mechanism='Retention of initial order; compound liquid reversal tracked separately.')

    add('d1479','leg, foot, quarter','*kāl',
        'k','ā','l','zero','CVVC free root','noun',
        'Tamil, Malayalam, Kannada, Gondi, Konda, Pengo and Manda independently attest kāl, establishing both long quantity and a free-root shape.',
        'k precedes the long vowel and l follows it throughout the independently compared branches. Toda ō and Parji ē are local vowel reflexes, not transferred vowels.',
        '*kāl > Telugu kālu, Kui kāḍu, Kuvi kāl retains original order; Kui l>ḍ is compatible with the same change in displaced lateral roots but here occurs without displacement. Toda kōl and compound kōs̱ show vowel change and conditioned final fricativization. Tulu kārɯ has the lateral/rhotic correspondence.',
        'The long free root is doubly outside the canonical short bound-root domain. Brahui trikkal is a compound whose initial tr belongs to the numeral material, not a reversal of kāl; inherited status and quantity of its kal member need separate contact investigation. Markodi short kar versus kār preserves source quantity variation, which cannot establish Proto-Dravidian short quantity. No independent bare-root metathesis is present.',
        {'Tamil':('R','kāl|kālāḷ|kāli','Free root and compounds.'),'Malayalam':('R','kāl|kāli|kālāḷ','Same.'),'Kota':('R','ka·l','Long root.'),'Toda':('R','ko·l|kōl|ko·s̱|kōs̱|me·ṇ go·s̱|mēṇgōs','Long root and compound final-l changes.'),'Kannada':('R','kāl|kālāḷ|kālu-naḍe','Long free root.'),'Kodagu':('R','ka·lɨ','Same.'),'Tulu':('R','kārɯ|kālɯ','Rhotic/lateral reflexes by meaning.'),'Telugu':('R','kālu|kālari','Long root and footsoldier.'),'Gondi':('R','kāl','Long root.'),'Konda':('R','kāl','Same.'),'Kui':('R','kāḍu','Medial/final l>ḍ without metathesis.'),'Kuwi':('R','kāl ( -ka)','Long root with plural suffix.'),'Pengo':('R','kāl','Long root.'),'Manda':('R','kāl','Long root.'),'Kolami':('R','kāl','Long root.'),'Parji':('R','kēl ( kēlul)','Long root, local vowel change.'),'Gadaba':('R','kāl ( kālgil)','Long root.'),'Brahui':('A','trikkal','Compound; short member and contact history unresolved.'),'Badaga':('R','kāl|kālu','Long root.'),'markodi':('R','kar|kār|kāli','Quantity and derivation vary, order stable.')},
        quantity='long',input_confidence='high',confidence='high',references='DEDR1479; PSS83 p.229 (oldDED1238)',eligibility='long-free-root-control',boundary='Free root; compounds cannot supply a primitive CCr onset.',mechanism='Retention with vowel and lateral correspondences.')
    add('d1906','paddy, grain','*kūl-i / *kūl-am',
        'k','ū','l','i/a','CVVC-i / CVVC-am','noun',
        'Tamil kūlam and Konda/Kui/Kuvi/Pengo/Manda kūli independently support long ū before l, with distinct final formations.',
        'The southern long root and eastern long forms agree on k-V-l order. No reconstructed short *kul is required by this set.',
        '*kūl-i > Kui kūḍi, Kuvi/Pengo/Manda kūli preserves order; l>ḍ does not depend on an earlier initial cluster. Brahui xōlum could match a different suffix and vowel history, but DEDR explicitly offers an Indo-Aryan alternative.',
        'A long-vowel bound-formation control, unlike the doubly restricted free root kāl. Agricultural vocabulary can diffuse, so repeated eastern attestations do not alone prove inheritance; the relevant negative phonological observation remains long kūl rather than klū. Brahui xōlum is not a secure inherited vote because the source also compares Sanskrit godhūma through DBIA123. Do not confuse this entry with neighboring kūli wages1905.',
        {'Tamil':('R','kūlam','Independent long southern root.'),'Konda':('R','kūli','Long root with i.'),'Kui':('R','kūḍi','Lateral>stop, no displacement.'),'Kuwi':('R','kūli','Both documented dialect groups retain order.'),'Pengo':('R','kūli','Same.'),'Manda':('R','kūli','Same.'),'Brahui':('A','xōlum','Alternative Indo-Aryan etymology explicitly supplied.')},
        quantity='long',input_confidence='high for regional long root; deeper borrowing uncertain',references='DEDR1906; DEN1 1972 p.416 entryS278; PSS83 p.229',eligibility='long-vowel-control',boundary='Long root independently present with both -i and -am; suffix difference does not create long quantity.',mechanism='Long-input retention; Brahui cognacy unresolved.')

    add('d4039','pig','*pan-ṯ-i / *panṯ-i',
        'p','a','nṯ','i','CVNC-i','noun',
        'Tamil paṉṟi, Kannada/Kodagu/Telugu pandi, Konda panṟi and Pengo/Manda panji independently establish a nasal-apical cluster, not a singleton r.',
        'The cross-branch nasal-plus-apical correspondences favor original p-a-nṯ order. Gondi paddi and Malayalam panni show assimilation of different parts of that cluster.',
        '*panṯi > pandi/panṟi retains cluster order; assimilation gives panni/paddi, and palatal developments give panji/pañji and paji. Later nasal loss or cluster simplification does not establish that an earlier singleton was eligible for metathesis.',
        'A strong nasal-cluster control. The several Gondi records repeat dialect/source evidence, not independent roots. Badaga handi/andi shows p>h>zero, not apical transfer. Kui paji looks like a simple intervocalic consonant synchronically, but comparative evidence independently reconstructs the blocking cluster. The exact segmentation pan-ṯ versus lexical panṯ remains open and is not needed for the cluster classification.',
        {'Tamil':('R','paṉṟi|vaṉṟi','Cluster and initial variants.'),'Malayalam':('R','panni','Assimilation of the inherited cluster.'),'Kota':('R','paj','Palatal outcome after vowel.'),'Toda':('R','pody|poḏy','Cluster/quantity history, order retained.'),'Kannada':('R','pandi','Nasal-stop retained.'),'Kodagu':('R','pandi','Same.'),'Tulu':('R','pañji','Palatalized cluster.'),'Telugu':('R','pandi','Nasal-stop retained.'),'Gondi':('R','paddi|paddī|paddal','Assimilated cluster and derivative.'),'Konda':('R','panṟi','Nasal-apical retained.'),'Kui':('R','paji','Simplified medial cluster.'),'Kuwi':('R','paji|pajji','Local gemination contrast.'),'Pengo':('R','panji','Nasal palatal cluster.'),'Manda':('R','panji','Same.'),'Parji':('R','pend|penḍ','Root vowel change and cluster retained.'),'Gadaba':('R','panḍu ( panḍkīl)|panḍ','Cluster retained.'),'Badaga':('R','handi|andi|kādandi','Initial loss and compound, no transfer.')},
        c2_structure='nasal-stop cluster',input_confidence='high',confidence='high',references='DEDR4039; PSS83 p.229 oldDED3326',eligibility='root-cluster-control',boundary='Cluster membership established independently; root/suffix segmentation not required.',mechanism='Cluster assimilation/palatalization, not metathesis.')

    add('d4335','anthill','*puṯṯ / *punṯṯ-V; regional *puṭṭ',
        'p','u','ṯṯ/ṇṯṯ','a/u/i','CVCC-V / CVNCC-V','noun',
        'Tamil/Malayalam puṟṟu, Kannada puttu and Telugu puṭṭa support a strong apical cluster; Tulu puñca and Koraga huñca/huntu motivate an additional nasal reconstruction. Both alternatives are nonsingleton inputs.',
        'Southern and central double-apical reflexes with nasal evidence establish original p-u-cluster order; eastern puci/pusi need not derive from a primitive singleton c.',
        '*pu(n)ṯṯV > puttu/puṭṭa and nasal/palatal puñca, with eastern pucci/puci/pusi after cluster simplification. Initial p>h>zero gives Kannada hutta/utta and Koraga huntu, independent of metathesis. Kuvi pūci may reflect local compensatory length from a strong cluster; no prior pr/pl onset is needed.',
        'Geminate versus nasal-plus-geminate reconstruction is unresolved but does not affect exclusion from the singleton class. The database attaches a Kurumba pitti form to Malayalam because of an embedded heading; do not count it as a Malayalam outcome. Toda vɨt-xuḏy is independently explained as rising+pit in its newer dictionary, weakening its membership in this root and requiring an ambiguous code. North/central comparisons have possible lexical diffusion but no evidence of initial reversal. PSS old number was initially misread3556/3566; DEDR4335 is the verified mapping.',
        {'Tamil':('R','puṟṟu|puṟṟam','Strong apical cluster.'),'Malayalam':('R','puṟṟu','Same; misassigned pitti omitted.'),'Toda':('A','vɨt-xuḏy|vɨt-moṇ','Alternative rising+pit/earth analysis in newer source.'),'Kannada':('R','puttu|putta|huttu|hutta|utta','Initial lenition/loss, strong medial consonant.'),'Kodagu':('R','puttɨ','Strong apical.'),'Tulu':('R','puñca','Nasal/palatal cluster.'),'Telugu':('R','puṭṭa','Geminate retroflex.'),'Gondi':('R','putti|puttī|puttu','Geminate dialect forms.'),'Konda':('R','puṭa|puRi|puR seṭi|puRi seṭi','Simple/strong apical and derivatives.'),'Kui':('R','pusi|pucci','Fricative versus geminate palatal.'),'Kuwi':('R','puci|pūci|pucci','Quantity and cluster variation.'),'Pengo':('R','puci','Palatal outcome.'),'Kolami':('R','puṭṭa','Strong apical.'),'Naikri':('R','puṭṭa','Same.'),'Parji':('R','puṭṭa|putta|puṭkal|putkal (putkacil)','Strong cluster and lateral extension.'),'Gadaba':('R','puṭkal','Strong cluster/lateral extension.'),'Kurux':('R','puttā|putbelō','Strong cluster and compound.'),'Malto':('R','pute','Local simplification.'),'Koraga':('R','huñca|huntu','Independent nasal evidence.')},
        c2_structure='geminate or nasal-plus-geminate',input_confidence='high for nonsingleton; medium for nasal',references='DEDR4335; K03 p.100 example16; PSS83 p.229',eligibility='root-cluster-control',boundary='Nonsingleton root input independently motivated; exact nasal reconstruction not fixed by metathesis outcomes.',mechanism='Cluster changes and uncertain Toda cognacy, no initial displacement.')
