"""Long-vowel rise set: preserve the challenge rather than invent a short input."""

def populate(add,tokens):
    add('d916','rise, ascend, rouse; dawn; water-lift','*ēṟ / *ēl; displaced regional rē/lē derivatives; alternative *sal?',
        'Ø','ē','ṟ/l','u/zero/unknown','VVC / VVC-V; disputed earlier short derivatives','verb/noun',
        'Tamil ēṟu/ēl, Malayalam ēṟuka/ēlkka, Kannada ēṟu, Kota ēṯ/ēr and Toda long-apical forms independently establish long root quantity and vowel-before-apical order. No independently full short *er-V derivative matching Telugu rēgu/lēcu is supplied by the present set.',
        'Widespread southern long V-apical order contrasts with Telugu rē-/lē- in the same broad rise/rouse meanings. This supports displacement-family comparison, but does not by itself prove that a long vowel was the immediate input: an independently documented earlier short grade or different root would change that conclusion.',
        'A direct *ēṟ > rē or *ēl > lē reverses a long vowel and apical, outside the short-input rule. Alternatively an earlier short extended *er/el-V could yield the long displaced forms, but that intermediate is currently unsupported. Telugu reccu needs its own shortening/strong derivative history. Water-lift ētamu preserves V-apical order after strong dental development. Konda ēṟasi versus defective le/leˀ e/ledu shows formation/morphological contrast, not a simple dated sound-change sequence.',
        'Keep this as a genuine challenge in the long-input class, with immediate prehistory uncertain, rather than silently moving it to short input. The alternative *sal? reconstruction is connected to Brahui saling and requires a separate initial-s and vowel history; Brahui alone does not demonstrate a common *sal that explains every southern form. The unrelated *ñāl dog head is a database linkage error. Kannada rēgu and Tulu rēgiyuni could be shared regional developments or Telugu loans; no donor proof is available here. Central les/lēp also requires contact evaluation. Gondi cooking forms and Kuvi re\'nai are explicitly questioned in DEDR; the Kuvi source disagrees ascend versus descend. Relation to short *eẓ rise851 could involve conflation or analogy but is not assumed; ẓ versus ṟ/l needs independent justification.',
        {'Tamil':('R','ēṟu|ēṟa|ēṟṟu|ēṟṟam|ēl','Independent long root and lateral/alveolar paradigm.'),'Malayalam':('R','ēṟuka|ēṟa|ēṟṟuka|ēṟṟam|ēṟṟu|ēlkka (ēṟṟ-)|ēttam','Long roots and strong water-lift noun.'),'Kota':('R','e·r- (e·ry-)|e·r|e·re·r|e·rr|e·ṯ- (e·c)|e·ṯl|ēr|ēr-|ēry-|ēric- (ēric)','Long root and paradigms; unrelated bank alternatives not selected.'),'Toda':('R','ø·ṟ- (ø·ṟy-)|ø̄ṟ-|ø̄ṟy-|ø·ṟc- (ø·ṟč-)|ø̄ṟc-|ø·ł (ø·ṯ-)|ø̄ɫ (ø̄ṯ-)|eṯ- (eṯy-)|eṯ-|eṯy-','Long root and separately short raising compound verb.'),'Kannada':('A','ēṟu|ēṟi|ēṟike|ēṟuta|ēṟuvike|ēṟisu|ēta|rēgu','Long retained root plus regional rēgu, possible contact.'),'Kodagu':('R','ə·r- (ə·ri-)|ə·ra','Long root.'),'Tulu':('A','ēruni|ērāvuni|erkɯ|ertɛ|yāta|rēgiyuni','Long retained forms, shorter compounds and uncertain displaced/contact verb.'),'Telugu':('M','ēṭavālu|ētamu|ētām|ettam|ātam|āṭakarra|āṭamānu|rēgu|rē̃gu|rēvu|rēyu|ṟē̃cu|rē̃cu|rē̃pu|rēpu|ṟēpu|rēpakaḍa|reccu|lēcu|lēpu','Retained long/strong water-lift forms versus displaced rise/rouse/dawn formations.'),'Konda':('M','ēṟasi|le|leˀ e|ledu','Retained adjective and source-restored defective displaced verb.'),'Kuwi':('A',"eski|re'nai",'Uphill retains V-first; queried verb has conflicting glosses.'),'Kolami':('A','les|le·p- (le·pt-)','Potential displaced regional verb, contact unresolved.'),'Naikri':('A','lēp','Same, semantically generalized apply/kindle.'),'Gondi':('A','ehī|eh|ah','Source queries cooking comparison.'),'Brahui':('A','saling|salīng','Alternative s-initial root hypothesis; infinitive morphology must be removed.'),'Badaga':('R','ēru','Archaic long root retained.')},
        quantity='long independently attested; immediate displaced input unresolved',input_confidence='high for comparative long root; low for immediate displaced derivative',confidence='medium',references='DEDR916 p.88 directly read; contrast DEDR851 p.82',eligibility='long-input-challenge',boundary='Different rise, dawn, imperative and water-lift formations; no unverified short grade treated as established.',mechanism='Displacement-family comparison supported; direct long-vowel metathesis versus lost short grade or etymological conflation unresolved.')
    tokens('d916','Kannada',R='ēṟu|ēṟi|ēṟike|ēṟuta|ēṟuvike|ēṟisu|ēta',A='rēgu')
    tokens('d916','Tulu',R='ēruni|ērāvuni|erkɯ|ertɛ|yāta',A='rēgiyuni')
    tokens('d916','Telugu',R='ēṭavālu|ētamu|ētām|ettam|ātam|āṭakarra|āṭamānu',D='rēgu|rē̃gu|rēvu|rēyu|ṟē̃cu|rē̃cu|rē̃pu|rēpu|ṟēpu|rēpakaḍa|reccu|lēcu|lēpu')
    tokens('d916','Konda',R='ēṟasi',D='le|leˀ e|ledu')
    tokens('d916','Kuwi',R='eski',A="re'nai")
