from cluster_case_helpers import case
def populate(add,tokens):
 def c(*a,**k):case(add,tokens,*a,**k)
 c('d4175','rattan, cane','*pir-amp; strengthened labial variant','p','i/e','r','a','CVC-a-NP','noun',
 'Tamil pirampu and Malayalam perampu independently establish full r order and low-a labial extension.',
 'Agreement of full southern forms favors a cluster innovation in Telugu. Kannada prabbali may share regional transmission, not necessarily inherited metathesis.',
 '*pir-amp > *priamp > prēmu, with coalescence and nasal/labial simplification; prabba/prabbili require a strengthened short-vowel formation, not this exact sequence. pēmu can follow r loss.',
 'Rattan names may travel with the object. Kannada prabbali cannot alone prove a Kannada sound law; its vowel, suffix and gemination pattern require source history. Long and short Telugu derivatives count as one family.',
 [('Tamil','R','pirampu','Full low-a input.'),('Malayalam','R','perampu|purampu','Full order, vowel variants.'),('Malayalam','O','punampu','Medial nasal assimilation.'),('Badaga','R','perumbu','Full order.'),('Telugu','D','prēmu|prabba|prabbili|pēmu','Displaced and reduced series.'),('Kannada','A','prabbali|habbe','Regional transmission or secondary reduction unresolved.')],eligibility='core-contact-caveat')
 c('d4176','separate, split, loosen','*pir-i; *pir-k / nasal and labial derivatives','p','i','r','i/zero','CVC-i / CVC-C','verb',
 'Tamil piṟi, Malayalam piriyuka, Kannada hiri and Brahui pirɣẖing establish full r order independently.',
 'Full cognates favor Telugu pr and eastern pr as innovations. Brahui preserves the full order in this root, unlike its separately reviewed scratch/lick changes.',
 '*pir-k > prik in Kuvi; Telugu *pir-id-ul or *pir-d-ul > pridulu remains a formation hypothesis. Kui prīva can reflect same-i coalescence, priŋg a consonantal derivative.',
 'Do not restore missing Tamil paradigm fragments as standalone words. The d-ul ending of pridulu is not independently matched, so its short i cannot establish the exact input. No evidence makes all derivatives a single obligatory rule.',
 [('Tamil','R','piṟi|pirivu|pirippu','Full order.'),('Malayalam','R','piriyuka|pirikka','Full order.'),('Kannada','R','hiri','Full order after p>h.'),('Kodagu','R','piriv','Full order.'),('Tulu','R','piripu|biripu','Full order.'),('Telugu','D','pridulu','Displaced derivative, suffix uncertain.'),('Kui','D','priŋg|prīva (prīt-)','Short/long derivatives.'),('Kuwi','D','prik|prik- (-h-)','Consonantal formation.'),('Gadaba','R','pirg- (pirig-)|pirukp','Full order.'),('Brahui','R','pirɣẖing','Full order retained.'),('Malto','R','pirce','Full order.'),('Badaga','R','hiri|hiricu','Full order.'),('Koraga','R','pirpi','Full order.'),('Kota','R','piryv','Full order.'),('Toda','R','pɨrc-','Full order.')],eligibility='core-formation-uncertain')
 c('d4193','intestine, bowel','*piẓ-ul / *piẓ-uv-ul; Telugu velar derivative','p','i/e','ẓ','u/unknown','CVC-V-C','noun',
 'Parji piṛul/piṛuvul, Gadaba puṛug and Gondi pīr give independent medial apical order, with divergent vowels and suffixes.',
 'The comparative apical supports prēgu as a displaced-family form; pēgu may lose r. It does not supply the exact pre-Telugu V2.',
 'Conditional *piẓ-V-g > *pẓiVg > prēgu > pēgu; low-a coalescence is not independently supported here. Southern-central apical-to-velar/stop developments and noun morphology must be distinguished.',
 'Long ē challenges an automatic short prediction from Parji high-u if those suffixes are equated; their l/g mismatch prevents that equation. Gondi long pīr is another grade. Need older full velar derivative and dialect vowel evidence.',
 [('Parji','R','piṛul|piṛuvul','Full apical order.'),('Gadaba','R','puṛug','Full apical.'),('Gadaba','O','puḍḍug|puḍgul|puḍg (puḍug)','Medial stop/cluster.'),('Gondi','R','pīr','Long full grade.'),('Brahui','R','piḍ','Full apical-stop correspondence.'),('Telugu','D','prēgu|pēgu','Displaced and reduced pair.'),('Kolami','A','pegū|pe·gul','Medial loss/convergence/contact unresolved.'),('Naikri','A','pēguḷ','Same.'),('Naiki','O','piggu|pigu','Medial velar development.')],quantity='short and long comparison grades',eligibility='quantity-and-formation-residual')
 c('d4283','protect, nourish, support','*pur-a; palatal/labial/dental derivatives','p','u/o','r','a','CVC-a-C','verb/noun',
 'Tamil pura/puravu and Kannada pore support low-vowel full order independently; Gondi porp and Parji porip add full consonantal/high-i formations.',
 'Full southern and central forms favor Telugu prō- innovation.',
 'Conditional *por-a-c/d/p > prōc/d/p with coalescence; exact suffixes differ. prāpu requires an a-grade, later vowel change or analogical influence, not the same o+a contraction.',
 'Keep prāpu as an explicit vowel residual. Nourishment and support meanings plausibly belong together, but do not supply a missing reconstructed vowel. D counts order only, not a solved quantity/quality history.',
 [('Tamil','R','pura|puravu|purappu','Full low-a root.'),('Kannada','R','pore','Full order.'),('Gondi','R','porp|porpanā','Full labial.'),('Parji','R','porip- (porit-)','Full high-i derivative.'),('Kolami','R','purāy','Full order.'),('Kota','R','por','Full root.'),('Badaga','R','hore','Full order.'),('Telugu','D','prōcu|prōdi|prōpu|prōpaḍu|prāpu','Displaced family; ā unexplained.')],eligibility='core-formation-uncertain')
 c('d4312','worm, decay','*puẓ-u; labial/velar and plural formations','p','u/i','ẓ','u/i/zero','CVC-V / CVC-C','noun/verb',
 'Tamil/Malayalam puẓu, Kannada puẓu, Konda piṛvu and Telugu puruvu/purvu independently support full order and both vowel-bearing and consonantal branches.',
 'Te purvu:pruvvu and Kui source piṛu:pṛiu provide direct directional comparisons; multiple full branches rule out assuming Telugu clusters ancestral.',
 '*puẓ-v > pruvvu after cluster reordering/strengthening; alternative *puẓ-uv > *pẓuuv with later shortening cannot be excluded. Kui piṛu > pṛiu > pṛīu provides a high-vowel displacement/coalescence comparison; Kuvi pliguli includes lateral outcome and separate morphology.',
 'Short Telugu pruvvu is not proof of original zero V2 because puruvu exists. puccu/puppi can be internal assimilation or later r loss; classify A. Brahui pū and Kota pū can lose the apical without metathesis. Toda u· is explicitly a Badaga loan.',
 [('Tamil','R','puṛ̆u|puṛ̆uppu','Full order.'),('Malayalam','R','puṛ̆u|puṛ̆ukka','Full order.'),('Kannada','R','puṛ̆u|puṛ̆a|puṛ̆i','Full order, V2 variants.'),('Kodagu','R','puḷu','Full lateral.'),('Tulu','R','puri|puru|pura|purkuni','Full root.'),('Telugu','R','puruvu|purugu|purgu|purvu','Full and consonantal inputs.'),('Telugu','D','pruvvu|pruccu|pruppi|pruŋguḍu','Displaced derivatives.'),('Telugu','A','puccu|puppi','Direct assimilation or later r loss.'),('Konda','R','piṛu|piṛvu (piṛku)','Full order.'),('Kui','D','pṛiu|pṛīu','Source explicitly compares full piṛu.'),('Kuwi','D','pliguli|plīginai|pṛiyuli|prīyūli','Cluster variants and morphology.'),('Pengo','D','pṛī','Long cluster.'),('Gondi','R','puṛi|puṛī|puṛ','Full order.'),('Parji','R','puṛut','Full order.'),('Kolami','R','purre','Full r.'),('Naikri','R','purre','Full r.'),('Naiki','R','purre|pure','Full r.'),('Brahui','R','pul-makkī|pul-makī','Full native first member, Persian second.'),('Brahui','O','pū','Apical loss/contraction.'),('Kota','O','pu·','Apical loss/contraction.'),('Toda','B','u·|ū','Explicit Badaga loan.'),('Toda','R','puf','Full-order correspondence.'),('Badaga','O','hū|ū','Internal apical loss/contraction.'),('Kurux','O','pocgō','Affricate development.'),('Malto','O','pocru|posɣo','Affricate/suffix restructuring.'),('Gadaba','R','puḍut','Full apical stop.')],eligibility='core-formation-uncertain')
 c('d4537','parch, fry; hearth','*por-i; y/d/n/s formations','p','o/u','r','i/zero/unknown','CVC-i / CVC-C','verb/noun',
 'Tamil pori, Kannada puri, Tulu poriyuni and Gondi poṛs independently establish full r order.',
 'Full comparanda favor Telugu proyyi and Kui/Kuvi pr as innovations; Kuvi porndali:prond provides an internal contrast.',
 '*por-y > proyyi with strengthening; possible high-i loss before this stage. poyyi may lose r, while Kannada burugalu and Telugu borugulu preserve medial r in a separate grain noun. Eastern long brō/brū forms have different dental/nasal morphology.',
 'Do not reconstruct a shared low vowel merely for Kui long outputs. Kolami/Naikri poy can be apical loss or contact with Telugu poyyi. Kui uncertain ash brūḍa retains source question mark and is not counted as independent root evidence.',
 [('Tamil','R','pori|poriyal','Full high-i.'),('Malayalam','R','pori|poriyuka|porikka','Full high-i.'),('Kannada','R','puri|burugalu','Full r derivatives.'),('Tulu','R','poriyuni|poripuni','Full order.'),('Kodagu','R','pori- (-p-, -c-)','Full order.'),('Gondi','R','poṛs|boṛs','Full r.'),('Kurux','R','poroc|porcō','Full r.'),('Kota','R','poyr- (porc-)','No initial pr; internal y/r history separate.'),('Telugu','R','porãṭu|borugulu|boruvulu','Full r formations.'),('Telugu','D','proyi|proyyi|poyi|poyyi','Cluster and r-loss hearth.'),('Kui','D','prospa (prost-)|pronda (prondi-)|brōṭpa (brōṭt-)|brōnḍa (brōnḍi-)','Distinct cluster derivatives.'),('Kuwi','R','porndali','Full nasal derivative.'),('Kuwi','D','prot- (-h-)|prond- (-it-)|pṛotʰali','Cluster derivatives.'),('Kolami','A','poy','Contact or apical loss.'),('Naikri','A','poy','Same.'),('Badaga','R','pori|puri','Full order.')],eligibility='core-formation-uncertain')
 c('d4545','earring','*por-c; Telugu nasal-velar formation','p','o','r','zero/unknown','CVC-C','noun',
 'Parji porca and Gondi porskeng independently supply medial r in earring names.',
 'Full central order favors Telugu prō̃gu innovation, if these differently suffixed ornaments are inherited cognates.',
 'Conditional *por-Vŋg > prō̃gu > pō̃gu; *por-c cannot directly yield the long vowel and nasal velar without additional morphology or sound changes.',
 'Rare object term, only three attested languages. Contact and nonmatching suffixes make exact chronology uncertain; no low-a reconstruction is licensed merely by ō. More older source forms are needed.',
 [('Parji','R','porca','Full r.'),('Gondi','R','porskeng','Full r cluster.'),('Telugu','D','prō̃gu|pō̃gu','Cluster/reduced pair, conditional exact input.')],eligibility='core-contact-and-formation-uncertain')
 c('d4559','sun, day, time','*poẓ-ut; *poẓ-t; deictic compounds','p','o','ẓ','u/zero','CVC-u-T / CVC-T','noun',
 'Tamil poẓutu, Kannada poẓtu/portu and Gondi poṛdu independently establish full and consonantal orders. The database ap-pōẓ head is a compound, not the ancestor of every member.',
 'Comparative full apical favors proddu innovation. Kannada portu:pottu independently demonstrates that internal assimilation can create pott without a pr stage.',
 '*poẓ-t > *pẓot > proddu with stop strengthening/voicing; high-u syncope may precede exchange. Telugu poddu may lose r; eastern pod forms could instead assimilate directly. appuḍu/ippuḍu/eppuḍu have deictic boundaries and a separate reduction history.',
 'Treat deictic compounds separately; their initial ap/ep sequence cannot be scored as retained plain por. No first-member-loss rule is required for Konda podu. Long pōtu elsewhere can be contraction without initial metathesis.',
 [('Tamil','R','poṛ̆utu|pōṛ̆tu','Full order, short/long grades.'),('Tamil','O','pōtu','Apical loss/contraction.'),('Malayalam','R','poṛ̆utu','Full order.'),('Kannada','R','poṛ̆tu|portu','Independent consonantal input.'),('Kannada','O','pottu|hottu','Internal assimilation.'),('Tulu','R','poḷtu|portu','Full consonantal order.'),('Gondi','R','poṛd|poṛdu','Full consonantal order.'),('Kota','R','poṛt','Full order.'),('Toda','O','poṭ|pošt','Internal developments.'),('Telugu','D','proddu|poddu','Cluster and reduced pair.'),('Telugu','A','appuḍu|ippuḍu|eppuḍu','Separate deictic compound reductions.'),('Konda','A','podu','Internal assimilation or concealed cluster.'),('Kolami','A','pod','Same.'),('Naikri','A','podd','Same.'),('Naiki','A','pod','Same.'),('Pengo','A','podna|padna','Different nasal formation.'),('Kodagu','R','poḷɨdɨ','Full lateral.'),('Badaga','O','hottu|ottu','Internal assimilation/initial loss.')],eligibility='core-formation-and-boundary-sensitive')
 c('d4591','heap','*pōr; short *por-aḷ formation','p','ō/o','r','zero/a','CVVC / CVC-a-C','noun',
 'Tamil/Malayalam pōr and Konda pōri give independent long root; Kannada poraḷi gives a short expanded grade.',
 'The comparative full order supports Telugu prōgu/prōka innovation, but neither grade uniquely supplies its velar suffix.',
 'Possible *pōr-k > prōk or short *por-a-k > prōk with contraction. The independently attested short derivative ends in ḷ, not k, so exact contraction remains conditional.',
 'Long-root exception if the long stem is immediate input; a low-a suffix cannot be selected to remove that exception. Heap semantics does not make homophonous thread4599 or earring4545 the same root.',
 [('Tamil','R','pōr|pōrpu|pōrvu','Long full root.'),('Malayalam','R','pōr','Long full root.'),('Konda','R','pōri','Long full.'),('Gadaba','R','pōrp','Long full labial.'),('Kannada','R','poraḷi','Short low-a formation.'),('Badaga','R','pōru','Long full.'),('Telugu','D','prōgu|prōka','Displaced velar formation.')],quantity='long root and independent short derivative',eligibility='quantity-and-formation-residual')
 c('d4599','split into threads; strand','*pōẓ; nasal-velar/palatal derivatives','p','ō','ẓ','zero/unknown','CVVC-C','verb/noun',
 'Tamil pōẓ, Kannada pōẓ and Parji pōṛ establish a long full apical root independently.',
 'Full southern/central order favors Telugu prō- innovation, while nasal extensions are regional morphology.',
 'Possible *pōẓ-ŋg/j > prōŋg/j with displacement; an unrecorded short expanded allomorph is another hypothesis, not an independently reconstructed fact. pō̃gu/pō̃ju can follow r loss.',
 'This is a genuine long-input residual for any short-only application law. Nasalization and thread-specific semantics require separate derivation. Similar Telugu prō̃gu earring4545 is not a reason to merge the roots.',
 [('Tamil','R','pōṛ̆|pōṛ̆vu','Long full order.'),('Kannada','R','pōṛ̆|pōṛ̆al','Long full order.'),('Parji','R','pōṛ','Long full order.'),('Telugu','D','prō̃gu|prō̃ju|pō̃gu|pō̃ju','Cluster/reduced nasal derivatives.'),('Telugu','A','ponju|pō̃cu','Quantity/strengthening history uncertain.'),('Malto','O','póye','Internal apical weakening.'),('Tulu','O','poṭṭɛ','Strong medial stop.'),('Kota','O','bo·ṭ','Strong stop/contraction.'),('Badaga','R','pōre','Long full r.')],quantity='long',eligibility='long-input-residual')
 c('d4608','smear, rub','regional *prām/prēm; earlier full order unknown','p','ā/ē','r','unknown','CCVV-C','verb',
 'Only Telugu prāmu:pāmu and Manda prēmba are supplied; neither language supplies an independent medial-r antecedent.',
 'r loss prāmu>pāmu is possible, but the original full order cannot be established from two cluster forms.',
 'Possible *par-am/*pir-amb > clusters remains speculative; alternatives include regional expressive formation or a loan adapted with a cluster. Manda ē versus Telugu ā is not explained.',
 'A positive-looking cluster is deliberately not a D vote. Need a credible full cognate or dated derivation before reconstructing metathesis.',
 [('Telugu','A','prāmu|pāmu','Earlier input unresolved.'),('Manda','A','prēmba','Earlier input and vowel relation unresolved.')],quantity='unknown',eligibility='no-independent-input',confidence='low')
 c('d4680','burn, blaze','*maṇṭ; regional *maṛ-g and nasal derivative','m','a','ṇṭ/ṛ','zero/unknown','CVNC / CVC-C','verb',
 'Tamil maṇṭu and central manḍ give a nasal-stop root; Gondi maṛg/maṛū independently supply a regional apical series.',
 'Kui mṛahpa can be compared directionally with Gondi maṛg, but Telugu mrandu also retains n+d and does not transparently exchange the nasal-stop sequence.',
 'Regional *maṛ-g-p > mṛahp with velar weakening is plausible. Telugu mrandu may combine this apical series with nasal maṇḍu by analogy, or contain an older additional suffix. Direct maṇḍu>mrandu is not a segment permutation.',
 'Keep Telugu A; the Gondi apical is real evidence but does not prove a common proto-root with southern maṇṭ. Need sound correspondences and morphology connecting the two series. Earlier head *manḍ alone is inadequate.',
 [('Tamil','R','maṇṭu|maṭu','Full nasal/stop branch.'),('Kolami','R','manḍeng','Nasal-stop branch.'),('Naikri','R','manḍ','Nasal-stop branch.'),('Gondi','R','maṛg|maṛgānā|maṛū','Regional full apical.'),('Kui','D','mṛahpa (mṛaht-)','Regional apical displacement, root relationship conditional.'),('Telugu','R','maṇḍu|maṇṭa|maṇḍincu','Full nasal-stop.'),('Telugu','A','mrandu','Additional r/nasal history unresolved.')],structure='mixed nasal-stop/apical',eligibility='alternative-root-shapes')
 c('d4710','drowsy, close eyes','expressive *mar-a-mar-a; possible simple *mar','m','a','r','a','reduplicated CVC-a','adjective/verb',
 'Tulu maramara provides a full r sequence, but specifically in a reduplicated expressive adjective, not an independently matched Telugu verb.',
 'A full-root origin of Telugu mrā- is possible; comparison does not uniquely establish a shared inherited simple stem or suffix.',
 'Conditional *mar-a-l/ŋg/nc > mrāl/mrāŋg/mrānc; or independent expressive formations/analogical extension among sleepy-eye words. Compound gannu eye is not part of the proposed metathesizing root.',
 'Keep A because the sole comparator and all Telugu derivatives differ in morphology. Need nonreduplicated full cognates and historical verb attestations. This is stronger evidence than no comparator, but insufficient for a secure D.',
 [('Tulu','R','maramara','Full expressive reduplication.'),('Telugu','A','mrālu|mrā̃gu|mrāncu|mrā̃-gannu','Conditional shared root and suffixes.')],eligibility='expressive-cognacy-uncertain',confidence='low')
 c('d4716','emetic nut tree','*maru#kārai?; regional nasal-velar tree name','m','a','r','u','CVC-u#CVC','noun',
 'Tamil marukkārai/matukkārai provides a full r/t variation in a plant compound; Kannada maŋgāre-muḷḷu and Telugu mraŋga differ substantially in suffix shape.',
 'Possible older maru favors movement in Telugu, but word borrowing and compound truncation can create the same cross-language shape contrast.',
 'Conditional *maru-ŋg > mraŋga > maŋga, with a nasal formation not directly matched by Tamil -kkārai; alternatively contact/truncation/reanalysis of the tree compound.',
 'Keep Telugu A rather than force a high-u rule from a nonmatching compound. Badaga maru mane/kēdu mane are home terms and appear falsely grouped; exclude from cognacy evidence.',
 [('Tamil','R','marukkārai|matukkārai','Compound with r/t variants.'),('Kannada','A','maŋgāre-muḷḷu','Compound/suffix correspondence uncertain.'),('Telugu','A','mraŋga|maŋga','Order, morphology and transmission unresolved.')],eligibility='compound-contact-cognacy-uncertain',confidence='low')
 c('d4728','darkness, cloud, stupor','*mar-b / *mar-v','m','a','r','zero','CVC-C','noun/adjective',
 'Kannada marbu/marvu and Tulu marbu independently establish a medial r-labial cluster, beside assimilated mabbu.',
 'Full cluster order favors Telugu mrabbu innovation; southern mabbu independently shows that apical loss does not uniquely diagnose earlier initial mr.',
 '*mar-b > mrabb with reordering and strengthening; mabbu can follow either mrabbu r loss or direct marbu assimilation. Gondi mabbu explicitly comes from Telugu.',
 'Strong directional consonantal case, but transmission of the cloud submeaning may involve contact. Distinct darkness/stupor derivatives are one family; proposed connections with4750/4753 remain unproved.',
 [('Kannada','R','marbu|marvu','Full medial cluster.'),('Kannada','O','mabbu|mobbu','Internal assimilation.'),('Tulu','R','marbu','Full medial cluster.'),('Tulu','O','mabbu|mappu','Internal assimilation.'),('Tamil','O','mappu|mammal','Strong nasal/labial outcomes.'),('Telugu','D','mrabbu','Initial cluster.'),('Telugu','A','mabbu|mabbu-konu','Direct assimilation or r loss.'),('Gondi','B','mabbu','Explicit Telugu loan.'),('Badaga','O','mabbu','Internal reduction, transmission unresolved.')],eligibility='core-contact-caveat')
