"""Vowel-initial lateral/retroflex families, with formation and contact distinctions."""

def populate(add,tokens):
    add('d495','silk-cotton tree','regional *il-av-; *il-a-k tree formation?',
        'Ø','i','l','a','VC-a-v / VC-a-k','noun',
        'Tamil ila/ilavam/ilavu, Malayalam ilavu and Kannada elava establish initial vowel and medial lateral independently. Parji neluk has an additional initial nasal; the displayed optional *ń is a hypothesis rather than observed proto-evidence.',
        'The independent southern il/el forms favor an earlier vowel-first plant name. Eastern lēk is plausibly displaced, but its velar rather than labial ending needs a separate formation history.',
        'Conditional *il-a-k > *ela-k > *lēk gives Gondi/Konda/Kuvi lēk. Kuvi ḍākāngi would additionally require l > ḍ and a different formative or plant-name compound; its ā may preserve an earlier suffix vowel only under the cognacy analysis.',
        'K80 item 3 has no Kui attestation. Kuvi e versus ā is a real dialect/source contrast, not two independent roots. Parji n cannot simply be deleted from reconstruction to obtain a positive case; contact, nasal accretion and an older nasal input remain competing explanations. Badaga muccukikku means veil and is not a relevant tree-name witness.',
        {'Tamil':('R','ila|ilavam|ilavu','Vowel-first southern tree-name variants.'),'Malayalam':('R','ilavu|ilavam','Same order.'),
         'Kannada':('R','elava','Lowered initial vowel; same order.'),'Tulu':('R','āla','Initial vowel retained, quantity/quality history separate.'),
         'Gondi':('D','lēki|leke|lɛkee','Probable displacement in the velar formation; source quantity differs.'),
         'Konda':('D','lēka maran','First member displaced; maran is tree.'),
         'Kuwi':('A','lēko marnu|lēko|ḍākāngi','lēko probable displacement; correspondence and segmentation of ḍākāngi remain uncertain.'),
         'Parji':('A','neluk','Initial n has no established age; do not assume a vowel-initial input for this form.')},
        references='DEDR 495; K80 table 1 item 3, pp.496–499; parent vowel-lowering audit',
        boundary='Southern -av and eastern -ak formations distinguished; common plant-name origin does not prove identical suffix ancestry.')
    tokens('d495','Kuwi',D='lēko marnu|lēko',A='ḍākāngi')

    add('d499','backbiter, tell-tale','regional illāmalli; deeper segmentation unknown',
        'Ø','i','ll','ā','VCCVCCV opaque word','noun',
        'Kannada and Telugu both attest illāmalli. Neither supplies an independent ancient simplex or a soundly dated morphological analysis.',
        'The observed initial geminate and vowel-first order agree across the two languages; inheritance versus lexical diffusion is unresolved.',
        'No reversal is needed. The word could have circulated intact between neighboring languages; its date relative to Telugu metathesis is unknown.',
        'An opaque identical regional word is a boundary control, not a strong inherited counterexample. Do not reconstruct singleton *il merely by removing one l from its attested spelling.',
        {'Kannada':('R','illāmalli','Initial geminate, unchanged order.'),'Telugu':('R','illāmalli','Initial geminate, unchanged order.')},
        c2_structure='geminate',eligibility='regional-opaque-control',input_confidence='low',references='DEDR 499',
        boundary='No secure segmentation of the whole word.',mechanism='No initial displacement required.')

    add('d502','descend, lower, sink','*iẓ-i-; *iẓ-k-, *iẓi-(m)pp-, *iẓi-nt(t)-',
        'Ø','i','ẓ','i/zero','VC-i + tense/voice suffixes','verb',
        'Tamil iẓi with nonpast v/pp and past nt/tt, Kannada iẓi/iẓipu and the retained Parji iṛv and Gadaba iṛg independently establish vowel-first order. K03 pp.188–190 compares velar and labial nonpast stems and nasal past formations.',
        'Agreement between SD I and Central Dravidian supports older i–ẓ. The velar is independently present in Toda, Kannada, Parji and Gadaba formations, so Telugu digu does not require an invented velar inserted after metathesis.',
        'K03 p.189 derives *iẓ-g > *ẓi-gg > ḍiggu > ḍigu > digu: displacement, voiced-stop gemination and later degemination. Distinct *iẓ(i)-mpp > ḍimp and *iẓ(i)-ntt > *iẓ(i)-ncc > ḍinc retain old nonpast/past transitive formations. *iẓ-nd > dindu lexicalizes the intransitive past. ẓ > ḍ and later ḍ > d are separate positional developments.',
        'Short i in digu is compatible with a consonantal formative and later degemination; it must not be judged against an invented identical *iẓigV sequence with two vowels. The precise prehistoric suffix paradigm is K03’s reconstruction, not attested Proto-Dravidian. DEDR explicitly labels Gondi forms Telugu loans; K03 p.162 and PSS83 p.234 diagnose Kolami/Naikri borrowing. Naiki extensions remain recipient morphology. Kui d/ḍ transcription differs between Winfield works, noted by DEDR; do not convert that source discrepancy into a dated sound change.',
        {'Tamil':('R','iṛ̆i|iṛ̆ivu|iṛ̆ipu|iṛ̆ippu|iṛ̆ittu|iṛ̆iccu','Multiple tense/voice formations retain initial order.'),
         'Malayalam':('R','iṛ̆ika|iḷiyuka|iṛ̆ikka|iṛ̆ivu|iṛ̆uka','Retained initial order despite suffix-vowel variants.'),
         'Kannada':('R','iṛ̆i|iṛ̆ipu|iṛ̆aku|iṛ̆uku|iṛ̆iku','Retained root and distinct expansions.'),
         'Kodagu':('O','ɨḷi- (ɨḷiv-, ɨḷiñj-)|ɨlɨp- (ɨḷɨpi-)|ɨ·p- (ɨ·pi-)|aḷa- (-p-, -t-)','Retention plus medial lateral loss/compensatory length in Mercara; no initial displacement.'),
         'Toda':('O','i·x- (i·xy-)|i·k- (i·ky-)','Medial cluster developments and lengthening, initial vowel survives.'),
         'Tulu':('R','iliyuni|iriyuni|iri','Lateral/rhotic variants retain order.'),
         'Telugu':('D','ḍiggu|ḍigu|digu|ḍimpu|dimpu|ḍincu|dincu|ḍindu|digucu|ḍiŋku','Distinct displaced tense/voice-derived stems; derivatives are one root family. Database ḍindu preserves initial retroflex spelling versus K03 dindu.'),
         'Gondi':('B','ḍigānā|ḍig','Source explicitly < Telugu.'),
         'Konda':('D','ḍig- (-it-)|ḍip','Velar intransitive versus labial transitive stems.'),
         'Kui':('D','dīva (dīt-)|dippa (dipt-)|dīpka (dīpki-)','Different voice/number formations and quantity; d/ḍ source discrepancy kept explicit.'),
         'Kuwi':('D','dī- (-t-)','Displaced stem with long vowel.'),
         'Kolami':('B','ḍig|ḍigg|dig|dig- (dikt-)|dip- (dipt-)|digip- (digipt-)','Published early Telugu loan diagnosis.'),
         'Naikri':('B','ḍigg|ḍipp','Published early Telugu loan diagnosis.'),
         'Naiki':('B','ḍik|ḍig|ḍigul|ḍigl|ḍigup|ḍigap|ḍigp','Telugu-type stem with recipient derivational variants.'),
         'Parji':('R','iṛ|iṛi|iṛv|iṛkip- (iṛkit-)','Retained vowel-first inherited series.'),
         'Gadaba':('R','iṛg|iḍg|iṛigp- (iṛigt-)','Ollari and Salur retain vowel before apical.'),
         'Badaga':('O','īgu','Possible medial consonant loss/assimilation with lengthening, not initial displacement.')},
        confidence='high',input_confidence='high',references='K03 pp.162,188–190; K61 pp.52–53 §1.124 as cited by K03; PSS83 p.234; DEDR 502',
        boundary='Independent comparative tense/voice alternations motivate -k/-p, -nt/-ntt formations; not classes invented from outcomes.')
    tokens('d502','Kodagu',R='ɨḷi- (ɨḷiv-, ɨḷiñj-)|ɨlɨp- (ɨḷɨpi-)|aḷa- (-p-, -t-)',O='ɨ·p- (ɨ·pi-)')

    add('d504','pull, drag, pant','*i/īẓ-u-; long and short formations',
        'Ø','i/ī','ẓ','u','VC-u / VVC-C','verb',
        'Tamil/Malayalam iẓu, Kannada iẓ/īẓ/eẓe and Konda īṛis independently support a vowel before the apical, but not one invariant original quantity. Telugu īḍucu belongs to the long series; Tamil short iẓu cannot alone fix its exact input.',
        'Several branches agree on vowel-first order. Kui/Kuvi ḍr- may be innovative under cognacy, but the two-consonant onset cannot be derived by a bare swap with a single reconstructed ẓ without an independent consonant history.',
        'Long *īẓ- > Telugu īḍ- with suffix -cu retains order. An independently short *iẓ-k- > *iḍk > igg is a possible medial-assimilation route to iggu; exact cluster details remain conditional. Kui *iẓ-u-p > *ẓip plus ẓ > ḍr, or an earlier local consonant complex, could yield ḍripa; neither is established here. Brahui rūsing may reflect initial-vowel loss from a related u-vowel stem plus its own s extension.',
        'PSS83 p.244 places Brahui rūs among cases compatible with aphaeresis, not among its two stronger reversal cases. Long vowel controls cannot be defined using only modern Telugu length. Toda īṣf is explicitly alternatively compared with d542 īr; its imported Tamil iẓu cross-reference is not a Toda lexeme. Differences among pull, pant and suck formations may also involve distinct morphology.',
        {'Tamil':('R','iṛ̆u|iṛ̆uppu|ici','Vowel remains first; ici requires a separate consonant history.'),
         'Malayalam':('R','iṛ̆ukka|īṛ̆kkuka|iṛ̆ayuka|iṛ̆ukkuka','Short/long and formative variants preserve initial order.'),
         'Kannada':('R','īṛ̆|iṛ̆|eṛ̆e|īḍu','Quantity and apical variants retain order.'),
         'Kodagu':('R','ɨ·ḷ- (ɨ·p-, ɨ·t-)','Long initial vowel retained; paradigm has medial consonant alternation.'),
         'Kota':('R','iḷv- (iḷt-)|eḷv- (eḷt-)|iv- (ivt-)','Retained initial vowel; lateral loss in one pull formation.'),
         'Toda':('A','eł̣f- (eł̣t-)|ɨxy- (ɨxc-)|i·ṣf- (i·ṣt-)','First two retain order; long pull form has an explicit competing etymology.'),
         'Tulu':('O','igguni','Medial assimilation/loss, not initial displacement.'),
         'Telugu':('O','īḍucu|īḍcu|īḍupu|īḍpu|īḍu|iggu','Long īḍ retains order, short igg has a distinct medial development.'),
         'Gondi':('R','īsānā|iṛk','Initial vowel retained.'),
         'Konda':('R','īṛis- (-t-)|īṛispis|īṛay ā','Long initial vowel retained.'),
         'Kui':('A','ḍripa (ḍrit-)','Cluster origin and quantity history unresolved.'),
         'Kuwi':('A',"drī'nai|ḍriˀ",'Long/short source variants; cluster origin unresolved.'),
         'Kurux':('R','īsnā (īsyas)|īcnā (īcyas/iccyas)|īcnā (īcyas)','Long initial vowel retained, consonant changes separate.'),
         'Malto':('R','ice|íce|icgre|ic-qoṭe','Initial vowel retained; derivatives differ.'),
         'Brahui':('A','rūsing','Aphaeresis versus displacement and suffix history unresolved.'),
         'Badaga':('R','eḷe','Vowel-first pull root.')},
        quantity='mixed/uncertain',references='DEDR 504, including alternative Toda comparison; PSS83 p.244 example 821',
        boundary='Short *iẓ-u and long *īẓ-C formations distinguished; exact inherited quantity conditioning not assumed.')
    tokens('d504','Telugu',R='īḍucu|īḍcu|īḍupu|īḍpu|īḍu',O='iggu')
    tokens('d504','Toda',R='eł̣f- (eł̣t-)|ɨxy- (ɨxc-)',A='i·ṣf- (i·ṣt-)')

    add('d507','copulate, desire','regional *iẓ-ay- / *iẓ-aŋ-?',
        'Ø','i','ẓ','a','VC-ay / VC-a-NC','verb',
        'Tamil iẓai, Kota iṛ- and Kannada eḷasu favor an initial vowel and apical. Telugu/Kannada/Kolami deŋg has a velar nasal expansion; the imported *deŋ does not establish earlier order.',
        'The non-Telugu vowel-first comparison supports a potential displacement history, but the differing expansions and the source’s queried link to d457 iṇai leave exact cognacy less secure.',
        'Conditional *iẓ-aŋk > *eẓaŋk > *ẓēŋk > *ḍēŋg > dẽg requires contraction, ẓ > ḍ > d and shortening/nasal changes. That full suffix input is not independently attested. Kannada deŋgu and Kolami deŋg may reflect Telugu-area diffusion.',
        'Sexual-union vocabulary may spread or undergo expressive restructuring; this is a hypothesis requiring historical distribution, not a reason to exclude a inconvenient form automatically. Do not count Kannada and Kolami as independent innovations or reconstruct their suffix entirely from Telugu.',
        {'Tamil':('R','iṛ̆ai','Vowel-first intimate association root.'),'Kota':('R','iṛ- (iṭy-)','Vowel-first root with tense alternation.'),
         'Kannada':('A','eḷasu|deŋgu','Retained desire root, potentially diffused deŋg noun.'),'Telugu':('A','dẽgu','Displacement plausible but suffix and cognacy unresolved.'),
         'Kolami':('A','deŋg- (deŋkt-)','Potential Telugu-area loan.')},
        eligibility='cognacy-or-input-uncertain',input_confidence='low',references='DEDR 507, queried comparison with 457',
        boundary='Nasal-velar expansion is not independently matched to Tamil -ay or Kannada -as.')
    tokens('d507','Kannada',R='eḷasu',A='deŋgu')

    add('d508','creep, slide along ground','regional *iẓ-ay-; *iẓ-aŋk-?',
        'Ø','i','ẓ','a','VC-ay / VC-a-NC','verb',
        'Malayalam iẓayuka supplies the sole unshifted comparator; Telugu ḍē̃ku/dē̃ku has an additional nasal and velar. The source-level PSTDr label does not prove a wider reconstructed clade.',
        'The matching meaning and known vowel-first ẓ roots make earlier *iẓ plausible, but an independently shared nasal-velar derivative is missing.',
        'Conditional *iẓ-aŋk > *eẓaŋk > *ẓēŋk > ḍē̃ku > dē̃ku; dē̃kuru adds further morphology. Malayalam ēyuka can instead reflect medial ẓ loss and vowel contraction while remaining vowel-initial.',
        'Do not use Telugu ē alone as independent evidence for low *a. A second unshifted velar formation or early textual cognate would strengthen this etymology; otherwise separate inheritance from diffusion or accidental semantic resemblance.',
        {'Malayalam':('O','iṛ̆ayuka|iṛ̆accal|ēyuka','Retained forms plus medial consonant loss/contraction.'),
         'Telugu':('A','ḍē̃ku|dē̃ku|dē̃kuru','Probable displacement with unconfirmed formative ancestry.')},
        eligibility='cognacy-or-input-uncertain',input_confidence='low',references='DEDR 508',
        boundary='-ay and -aŋk must remain separate proposed formations.')
    tokens('d508','Malayalam',R='iṛ̆ayuka|iṛ̆accal',O='ēyuka')

    add('d512','grow weary, become emaciated','*iḷ-ay-; Telugu *iḷ-a-n-?',
        'Ø','i','ḷ','a','VC-ay / VC-a-n','verb/noun',
        'Tamil iḷai/iḷaippu, Malayalam iḷaykkuka and Kannada iḷidu support an initial vowel before lateral. Telugu ēlanna has a different nominal ending.',
        'All secure comparisons begin with a vowel; Telugu ēl retains V–l and provides no evidence for l-initial displacement.',
        'Possible *iḷa-n > *ela-n > ēlanna involves vowel/quantity and nominal strengthening, with original segment order retained. Tamil ciḷai has an additional initial consonant; it may be a related extended form or imply a deeper lost initial, unresolved.',
        'The low-vowel weary formation is an observed retention, but exact Telugu nn and long ē history needs lexical/historical support. Badaga heḷa explicitly competes with d4419; do not use it to reconstruct original h/c.',
        {'Tamil':('R','iḷai|iḷaippu|iḷaku|eḷi','Vowel-first base and extensions.'),
         'Malayalam':('R','iḷaykkuka|iḷappu|iḷaccal|īḷikkuka','Quantity/formation variants retain order.'),
         'Kannada':('R','iḷidu','Retained order.'),'Telugu':('R','ēlanna','Long-vowel noun retains order.'),
         'Badaga':('A','heḷa','Explicit competing etymology; initial h not secure inherited evidence.')},
        references='DEDR 512; Hockings–Pilot-Raichoor 1992 p.610',boundary='Low -ay independently observed, Telugu nominal extension differs.')

    add('d513','young, tender; young person; calf','*i/eḷ-a-; *iḷ-aŋk- and human formations',
        'Ø','i/e','ḷ','a','VC-a + nominal/human suffixes','adjective/noun',
        'Tamil iḷa/iḷam/iḷai, Kannada eḷa/eḷatu and Parji/Gadaba ile/iled independently support vowel-first short root. Exact proto *i versus *e must be separated from the secure relative vowel/lateral order.',
        'Agreement of SD I and Central Dravidian makes original V–ḷ more likely than independent vowel insertion into a common l-initial root. Telugu ela provides internal retained evidence without being the sole basis.',
        'Low-vowel derivatives *iḷ-aŋk > *eḷaŋk > *lēŋk > Telugu lē̃ga and *iḷ-ant > *lēnt > lē̃ta illustrate lowering plus displacement and subsequent nasal/stop changes. Telugu ela retains the root in other formations. Human and calf suffixes have distinct histories; Kui lāvenju/Kuvi lāa may preserve a differently ordered lowering/displacement history if correctly cognate.',
        'K80’s reassignment of Kui/Kuvi young-person forms to this family partly relies on the proposed rule, so those forms cannot independently prove that same rule. Konda lēta is explicitly a Telugu loan, whereas lēŋa requires a separate inheritance/contact assessment. PSS83 p.234 labels Kolami/Naikri lēŋga borrowed; Naikri lēta has the Telugu form too. Kurux lidum may be a regional loan or another formation. Telugu nelãta adds n while keeping medial l; it is not simple metathesis. Historical ḷēnṟu titles are being separately checked in DHARMA, not treated as modern independent roots.',
        {'Tamil':('R','iḷa|iḷam|iḷai|iḷaiyaṉ','Retained root and human derivatives.'),
         'Malayalam':('R','iḷa|iḷama|iḷayavan','Retained order.'),'Kannada':('R','eḷa|eḷatu|eḷe|eḷadu','Retained lowered root.'),
         'Kota':('R','eḷ','Retained order.'),'Toda':('R','eḷ|eḷk','Retained order; tipcat gloss is not independent young-root evidence.'),
         'Kodagu':('R','əḷeə','Retained order.'),
         'Tulu':('A','eḷe|eḷatɯ|lattɯ|lambu|lambɛ','Retained roots with dialectal initial-loss/strengthening forms; no unique shared displacement chronology.'),
         'Telugu':('M','ela|eḍanīru|lē̃|lē̃ta|lē̃ga|lē̃ka|lēma|nelãta|nelãtuka','Retained and displaced formations plus n-accreted human nouns.'),
         'Gondi':('D','leyor|layor|leyōṇḍu|raiyōl ( raiyōṛ)|ḍiyyōr|ḍiyyā','Displaced young-person series; dialectal liquid/stop and vowel variation needs recipient-specific history.'),
         'Konda':('A','lēŋa|lēta','Probable displaced calf word plus explicit Telugu loan.'),
         'Kui':('A','leti|lāvenju|lāa','Soft leti and reassigned young-person nouns require separate confidence.'),
         'Kuwi':('A',"liddi|lāa|rā'a|ṛa'a ( -sika)|ṛaˀ a",'Reassigned person forms and soft liddi; exact common formation uncertain.'),
         'Kolami':('B','le·ŋga','Published Telugu loan diagnosis.'),'Naikri':('B','lēŋga|lēta','Telugu-type calf/tender words.'),
         'Parji':('R','ile ( ilecil)|iled ( ilenkul)','Retained human series.'),'Gadaba':('R','ile|iled|ilenḍ ( iler)','Retained human series.'),
         'Kurux':('A','lidum','Origin of soft word unresolved.'),'Brahui':('R','īlum|īṛ','Kinship formations retain initial vowel; quantity and apical development separate.')},
        input_confidence='high',references='DEDR 513; K80 table 1 item 2 and discussion; PSS83 p.234; DHARMA Telugu 00038/00040 (historical appendix)',
        boundary='Young-person, calf and tender adjective formations are independently distinguishable; no semantic exceptionless law inferred.')
    tokens('d513','Telugu',R='ela|eḍanīru',D='lē̃|lē̃ta|lē̃ga|lē̃ka|lēma',A='nelãta|nelãtuka')
    tokens('d513','Tulu',R='eḷe|eḷatɯ',A='lattɯ|lambu|lambɛ')
    tokens('d513','Konda',D='lēŋa',B='lēta')
