"""O-initial comparisons reviewed individually; input differences remain explicit."""

def populate(add,tokens):
    add('d944','join, undertake; arise','regional *oṭ-ar / *oṭ-am',
        'Ø','o','ṭ','a','VC-a-C','verb',
        'Kannada oḍar and Telugu oḍamu agree short o before retroflex and a after it, but their final r/m differ.',
        'The two regional witnesses both have o-ḍ-a; Telugu is not the sole order witness.',
        '*oṭ-ar > Kannada oḍar and expanded causatives; proposed related *oṭ-am > Telugu oḍamu. Neither requires relocation.',
        'The r/m formation comparison and broad join/arise semantics are plausible rather than certain. Kannada -ar does not establish Telugu -am as an inherited identical suffix. Sparse regional cognacy/contact needs independent lexical history.',
        {'Kannada':('R','oḍar|oḍarcu|oḍaricu|oḍarisu|oḍarcisu','Retained regional base and derivatives.'),'Telugu':('R','oḍamu','Retained initial order, different final consonant.')},references='DEDR944 p.90 directly read',eligibility='regional-formation-control',input_confidence='medium')
    add('d946','break, burst; crack; defeat','*oṭ-i / *oṭ-ay; long *ōṭ variants',
        'Ø','o/u','ṭ','i/ay','VC-V; long and strong nominal formations','verb/noun',
        'Tamil oṭi/uṭai, Malayalam oṭiyuka/uṭayuka and Kannada oḍi establish short retroflex roots with distinct i/ay formations; long hole/burst forms recur independently in SD I, CD and eastern languages.',
        'Numerous vowel-first roots across branches support original V-ṭ. Long Telugu ōḍu is not evidence that a short metathesized stage occurred because the apical remains after the vowel.',
        'Short *oṭ-i/ay yields oḍi/oḍe and related strong derivatives; separately long ōṭ/ōḍ produces ōr/ōh/ōj in eastern languages. Toda vaṛ and Gondi vōṛ have initial glide development, while r/ṛ remains postvocalic. Tamil noṭi has secondary n, not root-apical promotion.',
        'Telugu defeat forms are explicitly questioned against run-away1041; retain them as uncertain cognacy, not extra exceptions. Gondi urung/oruŋ may instead belong with snap662, and the database ruŋ is only that cross-reference, not an attested Gondi displacement in946. Original source separates Kodagu oḍe/oḍa paradigms that the database misassigns Kannada. Kui ohpa length is queried in DEDR; keep short source and proposed ōhpa distinct. No deterministic reconstruction of every long form from the short root has been established.',
        {'Tamil':('R','oṭi|uṭai|oṭivu|oṭipu|uṭaivu|uṭaippu|ōṭṭai|noṭi','Short/strong/long forms and secondary-n variant.'),'Malayalam':('R','oṭiyuka|oṭikka|uṭayuka|uṭekka|oṭappu|ōṭṭa','Retained roots and nominal quantity contrast.'),'Kota':('R','oṛv- (oṛd-)|oṛc- (oṛc-)|oṛ|o·ṭ|ōṭ','Short verbs and long hole noun.'),'Toda':('R','vaṛ- (vaṛQ-)|vaṛf- (vaṛt-)|vɨṛy- (vɨṛs-)|vaṛ aḍy','Glide before vowel; root apical remains after it.'),'Kannada':('R','oḍi|uḍi|oḍisu|uḍisu|oḍaka|oḍaku|oḍe|oṭṭe|ōṭe','Several formations, no displacement.'),'Kodagu':('R','oḍe- (oḍev-, oḍand-)|oḍa- (oḍap- oḍat-)|oḍe|oḍeve','Source-corrected language.'),'Tulu':('R','oḍiyuni|oḍeyuni|oḍipuni|oḍepuni|uḍevuni|uḍepuni|oḍka|oḍpuni|oṭṭe','Syncope/strengthening preserve order.'),'Telugu':('A','oḍapi|oḍiyu|oḍucu|ōḍu|ōḍincu|ōṭu|ōṭi|ōṭami|ōṭamu|ōṭaṟu|ōṭāṟu','Secure break/crack formations; defeat may belong to1041.'),'Gondi':('A','vōṛānā|vōhtānā|ōr|ōh|ohtānā|orsahtānā|orih|urung|oruŋ|urŋg|uruht|ureht|urut|uris|urih','Retained primary break roots; urung family has explicit alternative662.'),'Kui':('R','ōja (ōji-)','Long retained root; queried causative retained in full appendix.'),'Kuwi':('R','ōy- (-it-)|ōh- (ōst-)','Long vowel first, apical lenition/loss.'),'Pengo':('R','ōh- (ōst-)','Long root first.'),'Kolami':('R','o·ḍ- (o·ḍt-)|o·ṭ- (o·ṭt-)','Long root with voice/strength contrast.'),'Naikri':('R','ōṛ|ōṭ','Long vowel first.'),'Naiki':('R','uṭup|oṭp|ōṛ- (ōṭṭ-)','Short transitive versus long intransitive.'),'Parji':('R','ōḍ|ōṭip- (ōṭit-)','Long retained forms.'),'Gadaba':('R','or','Vowel first.'),'Badaga':('R','ode|hode|iluode|odeda ilu','Retained base, prothesis and compounds.'),'Koraga':('R','oḍi|uḍe|oḍpu','Retained dialectal forms.')},quantity='short and independently long formations',references='DEDR946 p.91 directly read; alternative1041/662',eligibility='mixed-quantity-formation-control',input_confidence='high for comparative short and long forms')
    tokens('d946','Telugu',R='oḍapi|oḍiyu|oḍucu|ōṭi',A='ōḍu|ōḍincu|ōṭu|ōṭami|ōṭamu|ōṭaṟu|ōṭāṟu')
    tokens('d946','Gondi',R='vōṛānā|vōhtānā|ōr|ōh|ohtānā|orsahtānā|orih',A='urung|oruŋ|urŋg|uruht|ureht|urut|uris|urih')
    add('d947','lap, groin, waist','*oṭ/uṭ-V; varied extensions',
        'Ø','o/u','ṭ','i/u/a/e','VC-V / VC-VC','noun',
        'Malayalam oṭi/oṭuku, Kannada uḍi/uḍu/uḍa and Kota oṛ establish short vowel-before-retroflex; exact suffix quality varies independently.',
        'The SD I comparison establishes vowel-first order before considering Telugu oḍi.',
        '*oṭ-i > oḍi; Kannada uḍulu/uḍlu displays medial syncope with initial vowel retained. Naikri oḍḍi has strengthening, not displacement.',
        'Malayalam uṭampu anus is queried, and uyge belongs to Kuruba, not Malayalam, in the original. The lap/garment/testicle semantic range needs formation-level caution, but no selected form shows root-apical relocation.',
        {'Malayalam':('A','oṭi|oṭuku|uṭa|uṭampu','Queried anus derivative separated.'),'Kota':('R','oṛ|oṛ kaṭ|oṛkaṭ','Root and compound.'),'Kannada':('R','uḍi|uḍa|uḍu|uḍe|uḍalu|uḍil|uḍulu|uḍlu','Independent full and syncopated variants.'),'Kodagu':('R','oḍi katti','Waist-sword compound.'),'Telugu':('R','oḍi|oḍi-kaṭṭu','Retained root and girdle compound.'),'Naikri':('R','oḍḍi','Strengthened retained root.'),'Badaga':('R','ode|ode hūvadu|ode hūva sāstira','Testicle base and castration expressions.')},references='DEDR947 p.91 directly read',input_confidence='high for order; medium for root-vowel quality')
    tokens('d947','Malayalam',R='oṭi|oṭuku|uṭa',A='uṭampu')
    add('d949','sling; brickbat','regional *oṭ-icil',
        'Ø','o','ṭ','i','VC-i-CVC','noun',
        'Tamil and Malayalam oṭicil independently establish the full o-ṭ-i sequence matching Telugu oḍisela.',
        'Three-language full-form agreement supports retained order; no modern language is privileged.',
        '*oṭicil > oḍisela requires voicing and final-vowel/lateral formation history, not initial metathesis.',
        'A connection to break946 is semantically plausible through brickbat but not demonstrated as productive derivation; mark as a possible family merge only. Contact among southern sling names remains possible; no donor evidence here. Do not claim a proven -icil suffix boundary.',
        {'Tamil':('R','oṭicil','Full retained sequence.'),'Malayalam':('R','oṭicil|oṭiśil','Sibilant variation without reordering.'),'Telugu':('R','oḍisela','Retained high second-vowel formation.')},references='DEDR949 p.91 directly read',boundary='Full-form comparison secure; segmentation after oṭ is tentative.',input_confidence='high for full form')
    add('d950','sore, bubo','*oṭ-u/i; regional *oṭ-is/uc-',
        'Ø','o/u','ṭ','u/i/a','VC-V(C)','noun',
        'Tamil oṭu, Malayalam oṭuvu and Kannada oḍise/oḍucu supply full short vowel-first forms with independently variable high suffixes.',
        'Vowel-first forms across several southern branches establish input order; Telugu vaḍise cannot override them.',
        '*oṭ-is > oḍise; Telugu oḍise-gaḍḍa : vaḍise-gaḍḍa shows initial glide/vowel development (o > va or related prothetic history), with the retroflex still after the first vowel. It is not *oḍ > ḍo.',
        'Exact origin of va is unresolved without dialect/historical evidence; it may parallel rounded-vowel breaking elsewhere but that is not asserted as a dated Telugu rule. Both forms are one compound family, and the lump element gaḍḍa is not an extra root reflex.',
        {'Tamil':('R','oṭu|oṭu-kkaṭṭi','Root and boil compound.'),'Malayalam':('R','oṭuvu|oṭikkuru','High-vowel extensions.'),'Kannada':('R','oḍise|oḍucu|uḍacu|uḍucu|uḍi','Vowel variants, same initial order.'),'Tulu':('R','oḍi','Retained order.'),'Telugu':('R','oḍise-gaḍḍa|vaḍise-gaḍḍa','Glide/vowel variant retains V-apical relation.')},references='DEDR950 p.91 directly read',input_confidence='high for order')
    add('d954','shrink, subdue, cease, leave','*oṭ-uŋ / *oṭ-ukk; regional *uṭ-uŋ/uk',
        'Ø','o/u','ṭ','u','VC-u-NC / VC-u-CC','verb/noun',
        'Tamil oṭuŋku/oṭukku, Malayalam oṭuŋŋuka/oṭukkuka, Kannada uḍugu/uḍagu and Kurux oṛᵒgnā establish vowel-first retroflex and nasal/strong formations. High u is independently present, though Kannada also has a.',
        'SD I and North Dravidian full forms establish V-ṭ before Telugu/ Kui initial ḍ. This does not establish a unique o versus u at every regional stage.',
        'Possible *uṭ-uŋ > *ḍuuŋ > ḍūŋ with subsequent shortening before ŋk yields Telugu ḍuŋku; *oṭ-uŋ may instead yield short ḍoŋku directly under the different-vowel account. Long dō̃ku preserves another quantity/nasal variant. Kui ḍūmba/ḍūppa requires a labial formative distinct from Telugu velar; high u can support long u+u contraction if the prior regional root was u. No single intermediate is proven across all formations.',
        'Telugu uḍugu/uḍuvu retain the original order in quit/cease meanings; semantic/formative differentiation is real but not yet a deterministic phonological rule. uḍupu may belong to1009, and Kolami ūḍp/ūrp is explicitly queried. Badaga okku may reflect medial assimilation rather than concealed metathesis. A connection to compressed aṭ roots63/80 or oṭṭ960 requires independent vowel and semantic history, not an automatic merge.',
        {'Tamil':('R','oṭuŋku|oṭukku|oṭukkam|oṭuŋkal|oṭuŋki','Independent full high-vowel formations.'),'Malayalam':('R','oṭuŋŋuka|oṭukkuka|oṭukkam|oṭuka|oṭuvu','Retained order.'),'Kota':('R','oṛk- (oṛky-)|oṛg- (oṛgy-)','Medial syncope.'),'Toda':('R','vɨḍg- (vɨḍgy-)|vɨṛk- (vɨṛky-)|vɨḍg-|vɨṛk-','Initial glide plus retained postvocalic apical.'),'Kannada':('R','uḍugu|uḍagu|uḍugisu|uḍagisu|uḍukisu','Full u/a variants.'),'Tulu':('R','oḍuŋgeluni|oḍuŋgelɯ|oḍuŋkelɯ|oḍkelɯ|oḍka','Full and syncopated retained stems.'),'Telugu':('M','uḍugu|uḍuvu|uḍupu|ḍuŋku|ḍoŋku|dō̃ku','Retained quit versus displaced diminish, with vowel/quantity variation.'),'Kui':('D','ḍūmba (ḍūmbi-)|ḍūppa (ḍūpt-)','Displaced long labial formations.'),'Kolami':('A','ūḍp|ūrp','Queried cognacy.'),'Kurux':('R','oṛᵒgnā (oṛg-/oṛgc-)|oṛga\'ānā|oṛᵒknā (uṛᵘkʰyas)','Vowel-first full/syncopated paradigms.'),'Malto':('R','oṛge|oṛgre','Medial apical and derivative.'),'Badaga':('O','okku','Possible medial assimilation; no proof of earlier displacement.')},
        references='DEDR954 p.91 directly read; contrast1009/960',input_confidence='high for order and u-formative; medium for immediate root-vowel quality',eligibility='core-vowel-history-variable')
    tokens('d954','Telugu',R='uḍugu|uḍuvu',D='ḍuŋku|ḍoŋku|dō̃ku',A='uḍupu')
