"""Manual formation-level inputs for explicit conditioning tests.

These rows refine, and never add votes to, the root-family analysis. An input
marked conditional cannot confirm the rule which supplied its reconstruction.
Quantity prediction is conditional on displacement having occurred.
"""
FORMATIONS=[]
def f(entry,key,lang,input,v1,v2,structure,tier,forms,quantity,explanation,*,root_quantity='short',target='apical'):
    FORMATIONS.append(dict(Entry_ID=entry,Formation_ID=entry+':'+key,Language_ID=lang,
        Reconstructed_Input=input,V1=v1,V2=v2,Prechange_Structure=structure,
        Input_Tier=tier,Evidence_Forms=forms,Observed_Quantity=quantity,
        Root_Quantity=root_quantity,Target=target,Formation_Explanation=explanation))

# Input tiers: full = independently matched vowel-bearing formation;
# cluster = independently supported medial cluster, chronology still inferred;
# conditional = exact suffix/input unresolved; mixed = independent competing grades.
f('d63','hide','Telugu','*aṭ-aŋk','a','a','VC-a-NC','full','ḍā̃gu|dā̃gu','long','Tamil/Kannada full aṭaŋk independently supplies low a; retained submit forms are a separate observation below.')
f('d77','pound','Telugu','*aṭ-Vŋk / *aṭ-Vmp','a','unknown','VC-V-NC','conditional','ḍaŋgu|dampu','short','No uniquely matched shared vowel/formative; short output cannot itself select a zero-vowel input.')
f('d79','approach','Telugu','*aṭ-ay','a','a','VC-ay','full','ḍāyu|dāyu','long','Independent Tamil aṭai/Kannada aḍe; -k nearness derivative is separate.')
f('d79','near','Telugu','*aṭ-Vk-ar','a','unknown','VC-V-k-ar','conditional','ḍaggaṟa|daggaṟa','short','Strong velar derivative does not independently supply V2 or date strengthening.')
f('d86','anvil','Telugu','*aṭ-ay#kal','a','a','VC-ay#stone','full','ḍā-kallu|dākali','long','Independent support-stone compound demonstrates that this boundary need not block displacement.')
f('d202','pipal','Telugu','*ar-a-...','a','a','VC-a-X','conditional','rāvi|rāgi','long','Root low a supported; exact -v/-g formation is not recovered and is excluded from strict test.')
f('d228','rub','Telugu','*ar-ay','a','a','VC-ay','full','rāyu','long','Tamil arai, Malayalam arayuka and Kannada are independently establish formation.')
f('d233','fall','Telugu','*ar-al','a','a','VC-al','conditional','rālu','long','K61 cross-family Tamil aṟal comparison from d315; not an independently certain input in d233.')
f('d277','destroy-labial','Telugu','*aẓ-i-mpp','a','i','VC-i-NPP','full','ḍappi','short','Tamil/Malayalam high-i transitive stem supports high-i branch; exact mpp versus pp is comparative morphology.')
f('d277','destroy-past','Telugu','*aẓ-i-ntt > *aẓ-i-cc','a','i','VC-i-CC','full','ṛ̆assi','short','Dated initial-ḻ forms support displacement before later stop reflex; palatalization precedes loss of conditioning i under K03.')
f('d295','size','Telugu','*aḷ-av','a','a','VC-av','full','lāvu','long','Tamil aḷavu and Kannada aḷavu match low-vowel labial noun.')
f('d296','join','Telugu','*aḷ-ay','a','a','VC-ay','full','lāyu','long','Tamil aḷai and Malayalam aḷayuka support this formation independently.')
f('d301','desire','Telugu','*aḷ-i-NC?','a','i','VC-i-NC','conditional','lā̃cu','long','Independent base is high-i; exact nasal-palatal suffix absent. Long output challenges an unqualified high-i short prediction; nasal loss/lengthening is possible.')
f('d321','stone','Telugu','*aṟ-ay','a','a','VC-ay','full','ṟāyi|rāyi','long','Tamil aṟai and Kannada aṟe independently support ay formation.')
f('d321','small-stone','Telugu','*aṟ-pp?','a','zero','VC-PP','conditional','ṟappa','short','Strong labial expansion plausible, but the absence of an earlier vowel is not independently established.')
f('d307','cover','Telugu','*aḷ-V-NC','a','unknown','VC-V-NC','conditional','lā̃ncu|lā̃pu','long','Kannada aḷur has a different high-vowel extension; do not supply low a from long ā alone.')
f('d308','hole','Telugu','*aḷ-Vŋk','a','unknown','VC-V-NC','conditional','lā̃ga','long','Southern aḷay supports root order, not exact velar-nasal extension.')
f('d315','scratch','Telugu','*aṟ-uk(k) / *aṟ-kk','a','u/zero','VC-(u)-KK','conditional','ṟakku|rakku','short','High-u sever root independent; exact velar formation and pre-metathesis syncope remain alternatives.')
f('d319','shout','Telugu','*aṟ-j / *aṟ-Vŋk','a','unknown','VC-C / VC-V-NC','conditional','rajju|ṟaŋke','short','Several suffixes; consonantal rajju analysis does not determine the nasal-velar word input.')
f('d437','stumble','Telugu','*iṭ-a-k(k)?','i','a','VC-a-KK','conditional','ḍekku','short','Low-vowel iṭaṟ and eḍaŋk are independent, but exact kk stem is not. Shortening after contraction is a hypothesis.')
f('d443','strike','Telugu','*iṭ-i','i','i','VC-i','full','ḍī','long','Tamil/Malayalam/Kannada iṭi gives matching high vowels; impact-noun diffusion remains possible.')
f('d474','nonhuman-two','Telugu','*ir-aṇṭ','i','a','VC-a-NP','full','reṇḍu','short','Independent Tamil iraṇṭu. Low-vowel prediction gives earlier rēṇḍ, with later shortening needed for modern reṇḍu; historical long rēṇḍ forms are checked separately.')
f('d475','jujube','Telugu','*ir-a-ŋk?','i','a','VC-a-NC','conditional','rē̃gu','long','Low-vowel tree name independent, but nasal-velar suffix differs from southern dental names.')
f('d502','descend-velar','Telugu','*iẓ-g','i','zero','VC-G','cluster','ḍiggu|digu','short','K03 comparative velar stem; Parji/Gadaba consonantal counterparts support cluster branch. Do not invent *iẓigV.')
f('d502','descend-labial','Telugu','*iẓ(i)-mpp','i','i/zero','VC-(i)-NPP','mixed','ḍimpu|dimpu','short','Independent high-i root and consonantal allomorphs; syncope chronology remains unresolved.')
f('d513','young-calf','Telugu','*iḷ-aŋk','i','a','VC-a-NC','full','lē̃ga','long','Tamil iḷaŋ and southern low-a adjectives support the calf formation; human derivatives remain one root.')
f('d513','young-human','Telugu','*iḷ-ant','i','a','VC-a-NT','full','lē̃ta','long','Independent low-a root and human/age morphology; later nasal and dental history separate.')
f('d516','landing','Telugu','*iṟ-av','i','a','VC-av','conditional','rēvu','long','Low-a descent family independent, but precise -av landing noun is less securely matched than root.')
f('d517','prawn','Telugu','*iṟ-ay / *iṟ-av','i','a','VC-ay/av','conditional','reyya|royya','short','Southern av and eastern y are not identical; short e needs strengthening/shortening, o additionally needs rounding or different input.')
f('d527','lord','Telugu','*iṟ-ay-anṟu','i','a','VC-ay+human','full','ṟē̃ḍu','long','Tamil iṟai/iṟaivaṉ and Kannada eṟeya independently support low-ay title; human ending changes separately.')
f('d648','pant','Telugu','*ur-añc?','u','a','VC-a-NC','conditional','rō̃ju','long','Speech root has independent low a, but exact ñc formation not supplied.')
f('d651','mortar','Telugu','*ur-al','u','a','VC-al','full','rōlu','long','Tamil/Malayalam ural and Kannada oral independently establish the exact low-a instrument stem.')
f('d665','rub-dental','Telugu','*ur-d','u','zero','VC-D','cluster','ruddu','short','Kannada urdu supplies an independent cluster; gemination chronology unresolved.')
f('d665','rub-labial','Telugu','*ur-upp / *ur-pp','u','u/zero','VC-(u)-PP','mixed','rubbu','short','Full and syncopated analyses compete; same-u contraction plus shortening cannot be distinguished from earlier syncope.')
f('d689','comb','Telugu','*uẓ-v','u','zero','VC-Vconsonant','cluster','duvvu','short','Parji uṛv and Gadaba uṛv independently support consonantal labial formation; full uḍuv is another branch.')
f('d688','plough-nasal','Telugu','*uẓ-n','u','zero','VC-N','cluster','dunnu','short','K03 independently analyzes nasal versus velar formation; eastern bare *uẓ-u is a different formation.')
f('d688','plough-velar','Telugu','*uẓ-kk','u','zero','VC-KK','cluster','dukki','short','Tillage noun distinguished from nasal verb; same family, not two roots.')
f('d692','tiger','Telugu','*uẓ-uv-ay / *uẓ-v','u','u/zero','VC-(u)-Vconsonant','mixed','duvvu','short','Tamil uẓuvai gives full formation; pre-Telugu loss of u versus later shortening remains unresolved.')
f('d694','deer','Telugu','*uẓ-up(p)','u','u','VC-u-P(P)','full','duppi','short','Parji uṛup independently provides same-u labial formation. A real surface quantity exception: syncope or later pp-conditioned shortening needed.')
f('d698','inside-locative','Telugu','*uḷ-an','u','a','VC-an','full','lōna|lōnu','long','Kannada oḷa supports singleton low-a locative; the claimed Old Telugu oḷana witness is a disputed reading, now ēḷan ruling in DHARMA00099.')
f('d718','lament','Telugu','*uṟ-al > *oṟ-al','u','a','VC-al','full','ṟōlu|rōlu','long','Kannada oṟalu and Telugu retained oṟalu match the lateral extension.')
f('d719','throw','Telugu','*uṟ-uv / *uṟ-v','u','u/zero','VC-(u)-Vconsonant','mixed','ṟuvvu|ṟūvu','mixed','Both long and short outcomes preserved; exact relation of Kannada ub and Telugu vv unresolved.')
f('d2149','new','Telugu','*koẓ-utt-V','o','u','CVC-u-TT','conditional','krotta|kotta','short','Tamil koẓuntu supports high-u formation, not exact tt without comparative reconstruction; post-r-loss kotta belongs to same history.')
f('d4711','tree','Telugu','*mar-an','a','a','CVC-an','full','mrānu|mānu','long','Konda maran supplies final n independently; cannot derive n directly from Tamil m.')
f('d5409','finger','Telugu','*wer-al / *wir-al','i/e','a','CVC-al','full','vrēlu|vēlu','long','Tamil viral and Kannada beral support full low-a formation; earlier i/e distinction remains open.')
f('d1787','blind-full','Telugu','*kur-uṭ-V','u','u','CVC-u-Ṭ','full','gruḍḍi|gruḍḍu','short','Same-u full input predicts long surface ū only if no intervening syncope/shortening. Independently retained kurḍ cluster supports alternative chronology below.')
f('d1787','blind-cluster','Telugu','*kur-ḍ-V','u','zero','CVC-Ḍ','cluster','gruḍḍi|gruḍḍu','short','Tulu kurḍu/Kota kurḍ support the cluster stage independently, but not its exact date in Telugu.')
f('d4866','swallow','Telugu','*miẓ-uŋk','i','u','CVC-u-NC','full','mriŋgu|miŋgu','short','Tamil/Malayalam high-u formation independently matched; Konda i variant not erased.')
f('d4993','sink-full','Telugu','*muẓ-uŋk','u','u','CVC-u-NC','full','bruŋgu','short','Independent same-u full stem; short modern outcome requires syncope or contraction followed by shortening.')
f('d4993','sink-cluster','Telugu','*muẓ-ŋk','u','zero','CVC-NC','cluster','bruŋgu','short','Tulu/Konda cluster branch supports medial-vowel loss independently; m>b remains a separate change.')
f('d1619','below','Telugu','*kiẓ-nd','i','zero','CVC-ND','cluster','krinda|kinda','short','Independent short allomorph alongside long kīẓ; velar palatalization interaction is chronological evidence, not automatic proof of this suffix date.')
f('d3976','cotton','Telugu','*par-utti','a','u','CVC-u-TT','full','pratti|patti','short','Tamil/Malayalam parutti and Kannada parti support full plus cluster branch; crop diffusion considered separately.')
f('d4005','rib','Telugu','*paẓ-k','a','zero','CVC-K','cluster','prakka','short','Kannada paẓke/Konda paṛka support cluster; Indo-Aryan pakkha convergence remains a contact complication.')
f('d5263','write','Telugu','*war-ay','a','a','CVC-ay','full','vrāyu|rāyu','long','Tamil varai/Malayalam varayuka independently match; later w-loss differs from usual Telugu r-loss.')
f('d5295','erase','Telugu','*waẓ-i-cc / *waẓ-cc','a','i/zero','CVC-(i)-CC','conditional','vṛ̆accu|vraccu','short','High-i base and low-a causatives both occur independently; exact immediate causative vowel unresolved.')
f('d4555','town','Telugu','*poẓ-al','o','a','CVC-al','full','pṛ̆ōl|prōlu','long','Kannada poẓal independently matches, even if the settlement term was borrowed before local displacement.')
f('d910','seventy','Telugu','*eẓ-u#pat','e','u','VC-u#CVC','full','ḍebbadi','short','Independent short compound allomorph; long ēẓ seven is not its immediate input.')
f('d1818','tube','Telugu','*koẓ-al','o','a','CVC-al','full','krōlu','long','Independent Tamil kuẓal/Malayalam kuẓal/Kannada koẓal tube formation.')
f('d1818','dig','Telugu','*koẓ-cc?','o','zero','CVC-CC','conditional','kroccu|groccu','short','Consonantal derivative plausible, but cannot reconstruct deleted V2 solely from short o.')
f('d2146','fat','Telugu','*koẓ-uw / *koẓ-w','o','u/zero','CVC-(u)-Vconsonant','mixed','krovvu|kovvu','short','Full high-u and medial-cluster comparanda independently exist; their pre-Telugu ordering remains inferred.')
f('d3246','turn-labial','Telugu','*tir-upp','i','u','CVC-u-PP','full','trippu','short','Tamil tiruppu independently matches strong labial formation.')
f('d3246','turn-strong-velar','Telugu','*tir-ukk','i','u','CVC-u-KK','full','trikku','short','Tamil tirukku independently matches strong velar formation, contrasting with retained weak tirugu.')
f('d2359','snake','Telugu','*car-a-nc','a','a','CVC-a-NC','conditional','trā̃cu','long','Southern sara/sarai and regional nasal-palatal formation support low-a root; initial c/t history separate.')
f('d3949','crawl','Telugu','*par-a-k(k)','a','a','CVC-a-K(K)','full','prāku|pākul-āḍu','long','Tamil/Malayalam parakku/parakka support low-a velar formation; geminate simplification still needs chronology.')
f('d3982','rice','Telugu','*per/par-V + plural lu','a/e','unknown','CVC-V+plural','conditional','prālu','long','Eastern full roots establish order, not a unique low-a input or plural history.')
f('d4750','blunt','Telugu','*maẓ-ukk','a','u','CVC-u-KK','full','mrakku|mraggu','short','Tamil maẓukku independently supports high-u strong formation; voiced variant has additional history.')
f('d4761','fall-turn','Telugu','*maṟ-aŋk / *maṟ-NK','a','a/zero','CVC-(a)-NC','mixed','mraŋgu|mrandu','short','Independent Tamil low-a nasal stem versus possible consonantal variant; choosing zero just from short output would be circular.')
f('d5082','smear','Telugu','*meẓ-Vŋk / *meẓ-Vw','e','unknown','CVC-V-NC/V','conditional','mrē̃gu|mrēvu','long','Independent full comparison has u, not demonstrated a; exact long derivatives unresolved.')
f('d5411','open','Telugu','*wir-il?','i','i','CVC-il','conditional','vrīlu','long','K61 explicitly says proposed -il/-ul is unattested elsewhere; cannot confirm the same-vowel prediction using it.')
f('d817','wild-dog','Telugu','*er/ir-Vc','e/i','unknown','VC-VC','conditional','rēcu','long','Parji iric supports full high-i word, but exact e/i correspondence and suffix history remain unresolved.')
f('d820','soil','Telugu','*er-e#kaṭṭ','e','e','VC-e#clod','conditional','rē-gaḍa','long','Kannada ere is regional comparison; mid V2 cannot simply be labeled inherited a or high i.')
f('d859','throw','Telugu','*ir-Vm / *ir-m','i','unknown','VC-(V)-M','conditional','ṟimmu','short','Independent full root ir; exact nasal expansion and earlier V2 unresolved.')
f('d916','rise','Telugu','*ēṟ / *ēl','e','unknown','VVC','mixed','rēgu|lēcu','long','Independent long full root is a real challenge to short-input scope; an unrecorded short allomorph cannot be assumed.',root_quantity='long')
f('d954','shrink','Telugu','*o/uṭ-uŋk','o/u','u','VC-u-NC','mixed','ḍuŋku|ḍoŋku|dō̃ku','mixed','Independent o/u root variation; nasal and quantity variants cannot be collapsed to one immediate input.')

# Independently motivated retained controls, deliberately including eligible ones.
f('d63','submit','Telugu','*aṭ-aŋk','a','a','VC-a-NC','full','aḍagu|aḍãgu','short','Same broad phonological input as hide; semantic/formation differentiation is observed, not a proven conditioning law.')
f('d64','betel-pouch','Telugu','*aṭ-a-ppay','a','a','VC-a-PPay','full','aḍapamu','short','Independent Tamil/Malayalam low-a pouch formation; compound status alone cannot explain retention versus anvil.')
f('d76','cook','Telugu','*aṭ-u','a','u','VC-u#compound','full','aḍugaṇṭu','short','Independent singleton cooking stem, distinct from geminate pancake.')
f('d76','pancake','Telugu','*aṭṭ-u','a','u','VCC-u','full','aṭṭu','short','Independent geminate nominal input; outside singleton rule.',target='geminate-apical')
f('d79','arise','Telugu','*aṭ-ar','a','a','VC-ar','full','aḍaru','short','Retained low-a rhotic derivative in same approach family.')
f('d229','half','Telugu','*ar-ay','a','a','VC-ay','full','ara','short','Independent low-ay nominal form remains vowel-initial.')
f('d227','grace','Telugu','*ar-uḷ','a','u','VC-u-L','full','arulu','short','Independent high-u formation, no displacement.')
f('d295','measure','Telugu','*aḷ-av','a','a','VC-av','full','alavi','short','Retained related measure formation beside lāvu; final i/u history is separate.')
f('d296','seize','Telugu','*aḷ-am','a','a','VC-am','conditional','alamu','short','Independent root low a, but matching labial suffix less secure than -ay.')
f('d472','borrow','Telugu','*ir-av','i','a','VC-av','full','eravu','short','Tamil iravu/Malayalam iravu/Kannada eravu independently support exactly the low-vowel branch.')
f('d490','prey','Telugu','*ir-ay','i','a','VC-ay','full','era','short','Independent low-ay form shows lowering without displacement.')
f('d474','human-two','Telugu','*ir-u-var','i','u','VC-u-human','full','iruvuru','short','Human suffix is independently contrasted with nonhuman aṇṭ; one numeral family.')
f('d587','clothing','Telugu','*uṭ-upp','u','u','VC-u-PP','full','uḍupu','short','Independent matching-u clothing formation is a retained eligible control.')
f('d593','owner','Telugu','*uṭ-ay-an','u','a','VC-ay-human','full','oḍayãḍu|oḍayũḍu','short','Low-vowel human formation remains unchanged in order, limiting a general human-suffix explanation.')
f('d593','property','Telugu','*uṭ-am','u','a','VC-am','full','oḍami|oḍame','short','Independent low-a property noun.')
f('d665','rub-ay','Telugu','*ur-ay','u','a','VC-ay','full','orayu','short','Tamil urai/Malayalam urayuka/Kannada ore support low-ay retained form beside ruddu/rubbu.')
f('d661','steel','Telugu','*ur-ukk','u','u','VC-u-KK','full','ukku','short','Medial syncope and assimilation explain absent r; O rather than secure retained-apical evidence.')
f('d698','mind','Telugu','*uḷḷ-am','u','a','VCC-am','full','ullamu','short','Tamil/Malayalam independently support geminate; morphology genuinely distinguishes this from singleton locative.',target='geminate-apical')
f('d690','black-gram','Telugu','*uẓ-unt','u','u','VC-u-NT','full','uddulu','short','Full bean formation; medial apical assimilation yields uddulu, an O outcome rather than secure apical retention.')
f('d718','thunder','Telugu','*uṟ-um','u','u','VC-um','full','uṟumu','short','Independent high-u thunder formation retains order.')
f('d910','seven','Telugu','*ēẓ-u','e','u','VVC-u','full','ēḍu','long','Long numeral contrasts with independently short tens compound.',root_quantity='long')
f('d1619','long-below','Telugu','*kīẓ','i','zero','CVVC#verb','full','kīḍupaḍu','long','Independent long southern grade; not a hidden reconstruction from retention.',root_quantity='long')
f('d3246','turn-weak-velar','Telugu','*tir-uk','i','u','CVC-u-K','full','tirugu','short','Tamil tiruku/Kannada tirugu match weak velar; contrast with trikku is independently morphological.')
f('d3949','spread-labial','Telugu','*par-app','a','a','CVC-a-PP','full','parapu','short','Independent low-a labial derivative remains full while velar crawl prāku changes.')
f('d5263','scratch-high','Telugu','*war-i','a','i','CVC-i','full','variyu','short','Tamil vari supplies high-i formation, distinct from low-ay writing.')
f('d5411','open-root','Telugu','*wir-i','i','i','CVC-i','full','viri|viriyu','short','Independent same-i stem retains order; vrīlu has another uncertain suffix.')
f('d913','song','Telugu','*ēḷ','e','zero','VVC','full','ēla','long','Independent long song root, retained control.',root_quantity='long')
f('d945','with-compound','Telugu','*oṭam#paṭ','o','a','VC-am#verb','full','oḍam-baḍu','short','Independent comitative compound; Tulu aphaeresis has a separate history.')

# Cross-language tests with independently explicit inputs and hard challenges.
f('d688','plough-vowel','Kui','*uẓ-u','u','u','VC-u','full','ṛūva (ṛūt-)','long','Vowel-bearing eastern formation, unlike Telugu nasal/velar derivatives.')
f('d661','melt','Kui','*ur-uk','u','u','VC-u-K','full','rūga (rūgi-)','long','Tamil/Malayalam uruku supports same-u velar stem.')
f('d718','thunder','Kui','*ur-um','u','u','VC-um','full','rūma (rūmi-)|rūmba (rūmbi-)','long','Independent full high-u labial stem; Telugu retains corresponding order.')
f('d837','white-ant','Kuwi','*el-um/b','e','u','VC-u-M/P','full','līmpu|līmbu|lēmpu|limbu','mixed','Parji elub/Gondi elum support different e-u, yet long ī/ē and short i coexist. Vocalism unresolved, not repaired by invented a.')
f('d4418','bone','Kui','*peṛ-en','e','e','CVC-en','full','pṛēnu ( pṛēka)','long','Konda peṛen gives independent e-e; deeper second e origin not established. This is not an independently low-a lowering test.')
f('d4183','squeeze','Kui','*piẓ-i-C','i','i','CVC-i-C','conditional','pṛihpa (pṛiht-)|vṛīsa (vṛīsi-)','mixed','Same-i root independent, exact s/h/labial formation differs; high-vowel contraction does not fix every derivative quantity.')
f('d4177','twist','Kui','*pir-i-p','i','i','CVC-i-P','full','prīpa (prīt-)','long','Independent full twist root with high i; labial transitive is locally explicit.')
f('d3244','wither','Brahui','*tir-a-kk','i','a','CVC-a-KK','full','trikking','short','Southern tirakku independently low-a. Brahui preserves i with short output, unlike unqualified Telugu-style long rule; geographical conditioning differs.')
f('d4177','twist-retained','Brahui','*pir-k','i','zero','CVC-K','cluster','pirɣẖing','short','Explicit PSS83 counterexample to closed-stem Brahui application, despite following consonant.')

# Grammatical domains are explicitly covered but excluded from the lexical rule.
f('d868','say-infinitive','Telugu','*an-an','a','a','VC-AN','full','anan|nān','mixed','Literary infinitive alternation is independently paired; grammatical nasal domain is not the classical apical rule.',target='grammatical-nasal')
f('d868','say-negative','Telugu','*an-aka','a','a','VC-AKA','full','anaka|nāka','mixed','Negative suffix supplies low a; analogy/contraction may generalize an allomorph.',target='grammatical-nasal')
f('d868','say-negative-person','Telugu','*an-aru','a','a','VC-ARU','full','anaru|naru','short','Short output despite two source a vowels is an explicit paradigm challenge.',target='grammatical-nasal')
f('d1','distal-oblique','Telugu','*ad-an-i','a','a','VC-AN-I','full','adi|dāni-','mixed','Comparative oblique augment; mixed direct/oblique paradigm, not a lexical quantity test.',target='grammatical-deictic')
f('d410','proximal-oblique','Telugu','*id-an-i','i','a','VC-AN-I','conditional','idi|dīni-','mixed','Exact proximal prehistory depends on comparison with distal augment; high output may be analogical.',target='grammatical-deictic')

# Final cluster sweep: inputs are independently assessed, not restored from quantity.
f('d1278','scorch','Telugu','*kar-Vŋ','a','unknown','CVC-V-NC','conditional','krā̃gu','long','Independent karu/kār grades do not supply exact nasal derivative V2.',root_quantity='mixed')
f('d1287','abound','Telugu','*kar-nd / *kar-a-nd','a','unknown','CVC-(V)-ND','conditional','krandu-konu','short','Exact nd formation lacks an independent full comparator.')
f('d1291','ring-velar','Telugu','*kar-ŋg','a','zero','CVC-NG','cluster','kraŋgu','short','Gondi karŋg independently supplies consonantal nasal-velar formation.')
f('d1291','ring-dental','Telugu','*kar-Vnd','a','unknown','CVC-V-ND','conditional','krandu','short','Dental variant differs from independent Gondi velar formation.')
f('d1292','melt','Telugu','*kar-aŋg','a','a','CVC-a-NG','full','krā̃gu','long','Kannada karaŋgu and Telugu karãgu independently match low-a formation.')
f('d1292','melt-retained','Telugu','*kar-aŋg','a','a','CVC-a-NG','full','karãgu','short','Same eligible full formation is retained beside krā̃gu; genuine application counterexample.')
f('d1347','bonduc','Telugu','*kaẓ-a-cc / *kaẓ-cc','a','a/zero','CVC-(a)-CC','mixed','gracca','short','Full kaẓacci exists but botanical suffix correspondence and earlier syncope are uncertain; do not silently select cluster input.')
f('d1349','loosen','Telugu','*kaẓ-al','a','a','CVC-al','full','krālu','long','Independent southern kaẓal exactly supplies the later lateral as well as initial apical.')
f('d1359','canal','Telugu','*kaẓ-i-y / *kaẓ-y','a','i/zero','CVC-(i)-Y','mixed','krayya','short','High-i base known; formative y strengthening and its vowel chronology unresolved.')
f('d1368','overflow-labial','Telugu','*kaẓ-um','a','u','CVC-u-M','full','krammu','short','Tamil kaẓumu independently supplies labial high-u formation; doubling of m is additional.')
f('d1368','overflow-palatal','Telugu','*kaẓ-V-cc','a','unknown','CVC-V-CC','conditional','kraccu','short','Labial full comparator cannot determine distinct palatal formation.')
f('d1477','vomit','Telugu','*kar-āy / *kār-y','a','ā/zero','CVC-āY / CVVC-Y','mixed','krāyu|grāyu','long','Tulu short-root long-suffix and southern long-root alternatives both independent.',root_quantity='mixed')
f('d1507','pongamia','Telugu','*kar-aŋ-Vg','a','a','CVC-a-NG-VG','conditional','krānugu','long','Konda kaṛaŋ supports low-a tree base but Telugu extra vowel/velar ending needs its own history.')
f('d1580','curd','Telugu','*kaẓ-an','a','a','CVC-an','conditional','krānu','long','Kannada final l and Tamil i/ā vocalism leave exact Telugu n formation conditional.')
f('d1594','grow-lean','Telugu','*kiṟ-y / *kiṟ-i-y','i','zero/i','CVC-(i)-Y','mixed','kriyyu','short','Full high-i root exists; exact strengthened glide formation and syncope chronology do not.')
f('d1767','bend-full','Telugu','*kur-aŋg','u','a','CVC-a-NG','full','kruŋgu','short','Tamil kuraŋku independently supplies low-a nasal-velar input: surface long prediction fails; alternate cluster branch can precede exchange.')
f('d1767','bend-cluster','Telugu','*kur-ŋg','u','zero','CVC-NG','cluster','kruŋgu','short','Kota koṛng and Kannada consonantal bend series support medial syncope independently, without dating it in Telugu.')
f('d1769','monkey','Telugu','*kor-ant','o','a','CVC-a-NT','conditional','krō̃ti','long','Independent southern nasal-velar noun does not by itself establish Telugu dental suffix.')
f('d1774','recite','Telugu','*kor-al-c','o','a','CVC-al-C','full','krōlcu','long','Kannada koralcu independently matches rhotic, low vowel, lateral and palatal extension.')
f('d1822','rot','Telugu','*kuẓ-l / *kuẓ-V-l','u','unknown','CVC-(V)-L','conditional','kruḷḷu','short','Southern low-ay stem does not supply exact doubled lateral suffix.')
f('d1850','pound','Telugu','*gur-d','u','zero','CVC-D','cluster','gruddu','short','Kannada gurdu independently supplies medial r+d; strengthening and inherited-versus-contact relation separate.')
f('d1923','cram','Telugu','*kur-kk / *kūr-k','u','unknown','CVC-KK / CVVC-K','mixed','krukku','short','Long r and short lateral/rhotic alternatives differ in morphology.',root_quantity='mixed')
f('d2008','side','Telugu','*kēr-V / *ker-V-v','e','unknown','CVVC / CVC-V-C','mixed','krē|krēva','long','Independent long and short full forms; exact low-a-v suffix unsupported.',root_quantity='mixed')
f('d2010','mock','Telugu','*kēr-ḍ/n','e','unknown','CVVC-C','conditional','krēḍincu|krēṇincu','long','Independent full long kēru/Gondi kīr; no short *ker-a derivative is established.',root_quantity='long')
f('d2356','rope','Telugu','*car-aṭ','a','a','CVC-a-Ṭ','full','trāḍu','long','Tamil/Malayalam caraṭu independently matches both apicals and low a; initial c>t separate.')
f('d2360','slip','Telugu','*sar-g','a','zero','CVC-G','cluster','sraggu','short','Tulu sarki independently supplies consonantal r-velar branch; voicing and strengthening separate.')
f('d2687','shrink-full','Telugu','*cur-ukk','u','u','CVC-u-KK','full','srukku','short','Tamil curukku independently gives same-u input, surface long prediction fails; independent surku branch below permits earlier syncope.')
f('d2687','shrink-cluster','Telugu','*cur-k','u','zero','CVC-K','cluster','srukku','short','Kannada surku independently supplies consonantal branch.')
f('d3095','churn','Telugu','*tar-c','a','zero','CVC-C','cluster','traccu','short','Telugu tarcu with independent Parji full-r evidence supports cluster direction; additional c strengthening inferred.')
f('d3095','churn-retained','Telugu','*tar-c','a','zero','CVC-C','cluster','tarcu','short','Same internal cluster retained: consonantal input does not make application obligatory.')
f('d3115','embers','Telugu','*taẓ-m-p','a','zero','CVC-M-P','conditional','trampi','short','Gondi taṛm supports labial m, not exact p extension or its vowel chronology.')
f('d3122','dig','Telugu','*taẓ-v','a','unknown','CVC-(V)-Vconsonant','conditional','travvu','short','Independent apical order and Kuvi j contrast; exact Telugu labial V2 unknown.')
f('d3174','drink','Telugu','*tār-g','a','zero','CVVC-G','cluster','trāgu','long','Parji tār/Gadaba tārg independently long; contact direction remains unresolved. Outside short-input rule.',root_quantity='long')
f('d3192','wither','Telugu','*tāṟ-ḍ / *taṟ-aḍ','a','zero/a','CVVC-C / CVC-a-C','mixed','trāḍuvaḍu','long','Full long root and short differently suffixed derivatives compete.',root_quantity='mixed')
f('d3340','push-long','Telugu','*tor-a-y/c/l','o','a','CVC-a-C','conditional','trōyu|trōcu|trōlu','long','Low-a root independent but each exact y/c/l suffix requires its own comparative support.')
f('d3340','push-labial','Telugu','*tor-b','o','zero','CVC-B','conditional','drobbu','short','No independently full identical voiced-geminate labial formation; contact plausible.')
f('d3343','rust','Telugu','*tur-pp/kk / *tur-upp/ukk','u','zero/u','CVC-(u)-CC','mixed','truppu|trukku','short','Malayalam turuvu/turumpu supports labial root, not exact doubled pp/kk before metathesis.')
f('d3437','snap','Telugu','*teṟ-i-C / *teṟ-C','e','i/zero','CVC-(i)-C','mixed','tregu|trevvu|trempu|trencu','short','High-i base known, distinct velar/labial/nasal formative chronology unresolved.')
f('d3522','tread','Telugu','*toẓ-ik / *toẓ-k','o','i/zero','CVC-(i)-K','mixed','trokku','short','Independent full high-i and labial consonantal forms, exact velar branch and vowel lowering unresolved.')
f('d3962','split','Telugu','*par-d/t','a','zero','CVC-D/T','cluster','bradda','short','Tulu partɛ and Kolami part independently support dental cluster; initial/suffix voicing separate.')
f('d3972','grow','Telugu','*par-b / *par-u-b','a','zero/u','CVC-(u)-B','mixed','prabbu','short','Full paru/paruppu and differently suffixed labial/dental comparanda leave exact b history unresolved.')
f('d3999','old','Telugu','*paẓ-ant','a','a','CVC-a-NT','conditional','prā̃ta','long','Low-a root and Gondi paṛana independent; exact n+t formation not independently matched in this audit.')
f('d4002','blame','Telugu','*paẓ-i-y/b / *paẓ-y/b','a','i/zero','CVC-(i)-C','mixed','prayi|prabbu','short','High-i base independent; exact consonantal suffix prehistory unresolved.')
f('d4175','rattan-long','Telugu','*pir-amp','i','a','CVC-a-MP','full','prēmu','long','Tamil pirampu/Malayalam perampu independently match low-a labial plant name; final cluster simplification separate.')
f('d4175','rattan-short','Telugu','*par-bb / *pir-a-mp','a','unknown','CVC-CC / CVC-a-MP','conditional','prabba|prabbili','short','Short a and strengthened bb differ from prēmu; do not equate their inputs solely by shared plant meaning.')
f('d4176','separate','Telugu','*pir-i-d-ul / *pir-d-ul','i','i/zero','CVC-(i)-D-UL','mixed','pridulu','short','Exact d-ul formation not independently matched; same-i root alone cannot force a full-input quantity test.')
f('d4193','intestine','Telugu','*piẓ-V-g','i','unknown','CVC-V-G','conditional','prēgu','long','Parji high-u l noun and Gondi long root do not establish Telugu velar V2.',root_quantity='mixed')
f('d4283','protect','Telugu','*por-a-c/d/p','o','a','CVC-a-C','conditional','prōcu|prōdi|prōpu','long','Low-a root independent; exact individual suffixes need comparison.')
f('d4283','support-a','Telugu','*por-V-p / *par-V-p','o/a','unknown','CVC-V-P','conditional','prāpu','long','ā variant unresolved; avoid silently selecting root a.')
f('d4312','worm-full','Telugu','*puẓ-uv','u','u','CVC-u-Vconsonant','full','pruvvu','short','Full Telugu puruvu independently agrees with southern puẓu root and has matching labial suffix. Same-u surface long prediction fails unless earlier syncope or later shortening intervenes.')
f('d4312','worm-cluster','Telugu','*puẓ-v','u','zero','CVC-Vconsonant','cluster','pruvvu','short','Te purvu and Konda piṛvu independently support labial cluster, chronology of vowel loss still inferred.')
f('d4312','worm-retained','Telugu','*puẓ-uv','u','u','CVC-u-Vconsonant','full','puruvu','short','Same full labial formation retains order; direct application counterexample.')
f('d4537','hearth','Telugu','*por-i-y / *por-y','o','i/zero','CVC-(i)-Y','mixed','proyyi','short','High-i parching base independent; exact strengthened hearth glide formation conditional.')
f('d4545','earring','Telugu','*por-Vŋg','o','unknown','CVC-V-NG','conditional','prō̃gu','long','Independent full r names end in c/sk, not exact Telugu ŋg; unknown V2.')
f('d4559','day-full','Telugu','*poẓ-ut','o','u','CVC-u-T','full','proddu','short','Tamil poẓutu independently matches high-u dental formation.')
f('d4559','day-cluster','Telugu','*poẓ-t','o','zero','CVC-T','cluster','proddu','short','Kannada poẓtu/portu independently support consonantal dental formation.')
f('d4591','heap','Telugu','*pōr-k / *por-a-k','o','zero/a','CVVC-K / CVC-a-K','mixed','prōgu|prōka','long','Long root and short low-a lateral derivative exist; exact velar grade unresolved.',root_quantity='mixed')
f('d4599','strand','Telugu','*pōẓ-ŋg/j','o','unknown','CVVC-NC','conditional','prō̃gu|prō̃ju','long','All secure full root comparanda long; unrecorded short grade cannot rescue a short-only rule.',root_quantity='long')
f('d4728','cloud','Telugu','*mar-b','a','zero','CVC-B','cluster','mrabbu','short','Kannada/Tulu marbu independently provide full medial labial cluster.')
f('d4971','stump','Telugu','*mor-aḍ','o','a','CVC-a-Ḍ','full','mrōḍu','long','Tamil/Malayalam muraṭu, Kannada/Te moraḍu independently match full low-a dental noun.')
f('d4971','stump-retained','Telugu','*mor-aḍ','o','a','CVC-a-Ḍ','full','moraḍu','short','Same stem and stump meaning retain full order; morphology alone does not separate these variants.')
f('d4975','perish','Telugu','*mur-uŋk','u','u','CVC-u-NK','full','bruŋgu','short','Tamil muruŋku independently supplies same-u nasal-velar perish formation. Long surface prediction fails; m>b and suffix voicing are separate.')
f('d4975','kill-glide','Telugu','*mur-i-y / *mur-y','u','i/zero','CVC-(i)-Y','mixed','bruyyu|bruncu','short','High-i root independent, exact glide/nasal-palatal formation unresolved.')
f('d5007','mould','Telugu','*muṟ-k','u','zero','CVC-K','cluster','mrukku','short','Gondi murk/Tulu murguni independently support medial cluster.')
f('d5123','bow','Telugu','*moẓ-k/g','o','zero','CVC-K/G','cluster','mrokku|mroggu','short','Kannada moẓgu and Parji/Gondi moṛk independently supply apical-velar cluster.')
f('d5372','live','Telugu','*bar-d-uk','a','zero','CVC-D-UK','cluster','braduku|bratuku','short','Kannada barduku independently short in this derivative despite long bare vāẓ. Contact history separate.')
