"""Editorial selections. Each section contains ten distinct primary root families.
Forms are matched against the frozen cited evidence by build.py, never invented IDs.
An asterisk marks a reconstruction, not a database headword endorsement.
"""
EXAMPLES = {
 'inputs': [
  (229, '*ar-ay', [('Tamil','arai'),('Kannada','are'),('Telugu','ara')], 'Retains V–r. Compare “rub” below; the historical status of -ay is not settled, so a noun/verb rule would be premature.'),
  (472, '*ir-av', [('Tamil','iravu'),('Kannada','eravu'),('Telugu','eravu')], 'Retains V–r despite an independently matched low-vowel formation. Borrowing is possible but undocumented.'),
  (490, '*ir-ay', [('Tamil','irai'),('Kannada','ere'),('Telugu','era')], 'Retains V–r. Lowering and final contraction do not relocate r; no source-marked loan explains retention.'),
  (240, '*al-ay / *al-aŋ', [('Tamil','alai'),('Telugu','ala'),('Kui','lānga')], 'Telugu retains the order; Kui changes it in the nasal formation. Derivatives are one family, not repeated votes.'),
  (84, '*aṭ-ar', [('Tamil','aṭar'),('Kannada','aḍar'),('Telugu','aḍaru')], 'Low-vowel retention with independently matching morphology. Strengthened pile nouns are separate formations.'),
  (247, '*al-ar', [('Tamil','alar'),('Telugu','alaru'),('Kannada','aral')], 'Telugu retains initial V–l. Kannada exchanges l…r, a different process that the initial-order count must not erase.'),
  (63, '*aṭ-aŋk', [('Tamil','aṭaŋku'),('Telugu','aḍagu'),('Telugu','ḍā̃gu')], 'Submit retains the order; hide has displacement and lengthening. The semantic split is observed, not a demonstrated phonological condition.'),
  (79, '*aṭ-ay / *aṭ-ar', [('Tamil','aṭai'),('Telugu','dāyu'),('Telugu','aḍaru')], 'Approach has displacement; the related arise formation retains order. Different suffixes must remain visible.'),
  (228, '*ar-ay', [('Tamil','arai'),('Telugu','rāyu')], 'Rub has displacement and lengthening, unlike half. Related retained fragment nouns are in the same family.'),
  (277, '*aẓ-i-ntt / *aẓ-i-mpp', [('Telugu','ṛ̆assi'),('Telugu','ḍappi'),('Telugu','aṛ̆isina')], 'Destroy has changed and retained formations. Early inscriptional ḻ supports an intermediate before initial ḍ; forms are not free variants.'),
 ],
 'quantity': [
  (63, 'd63:hide', [('Telugu','ḍā̃gu')], 'Low a: long ā. Compare Tamil aṭaŋku. Retained submit forms do not test the quantity of a displaced output.'),
  (79, 'd79:approach', [('Telugu','dāyu')], 'Low a: long ā. Tamil aṭai and Kannada aḍe support the formation; daggaṟa has a different extension.'),
  (228, 'd228:rub', [('Telugu','rāyu')], 'Low a: long ā; *ar-ay → *rāy. Compare Tamil arai and Kannada are.'),
  (295, 'd295:size', [('Telugu','lāvu')], 'Low a: long ā; *aḷ-av → *lāv. Tamil aḷavu matches the noun; retained alavi remains in the same family.'),
  (651, 'd651:mortar', [('Telugu','rōlu')], 'Low a: long ō; *ur-al → *rōl. Tamil ural and Kannada oral support the exact instrument formation.'),
  (277, 'd277:destroy-labial', [('Telugu','ḍappi')], 'Different high i: short a; *aẓ-i-mpp → *ẓapp → ḍappi. The high vowel and the labial formation require independent support.'),
  (4866, 'd4866:swallow', [('Telugu','mriŋgu')], 'Different high u: short i; *miẓ-uŋk → *miẓ-ŋk → *mẓiŋk → mriŋgu. Konda also preserves a real i-formative variant.'),
  (4728, 'd4728:cloud', [('Telugu','mrabbu')], 'Consonantal input: short a; *mar-b → mrabb. Kannada/Tulu marbu independently establish the medial cluster.'),
  (5372, 'd5372:live', [('Telugu','braduku')], 'Consonantal input: short a; *bar-d-uk → bra-d-uk. Kannada barduku supports this short derivative despite the long bare root vāẓ.'),
  (4005, 'd4005:rib', [('Telugu','prakka')], 'Consonantal input: short a; *paẓ-k → *pẓakk → prakka. Kannada paẓke and Konda paṛka support it; Indo-Aryan pakkha convergence complicates the family.'),
 ],
 'reduction': [
  (2149, None, [('Telugu','krotta'),('Telugu','kotta')], 'New: full-order southern comparanda support kr as innovative; subsequent r-loss yields the reduced variant.'),
  (2146, None, [('Telugu','krovvu'),('Telugu','kovvu')], 'Fat: the attested kr variant supplies the intermediate missing from kovvu alone.'),
  (4711, None, [('Telugu','mrānu'),('Telugu','mānu')], 'Tree: mrānu bridges the earlier mar- order and mānu. Nasal and velar derivatives are not independent roots.'),
  (3976, None, [('Telugu','pratti'),('Telugu','patti')], 'Cotton: pratti preserves evidence that the r-less form cannot provide on its own; the wider word history still needs contact scrutiny.'),
  (5409, None, [('Telugu','vrēlu'),('Telugu','vēlu')], 'Finger: the vr variant supports reduction after displacement. Lengthening belongs to the earlier formation history.'),
  (3122, None, [('Telugu','travvu'),('Telugu','tavvu')], 'Dig: the full-order comparative base plus attested tr supports a reduction path; r-less spellings alone would not establish it.'),
  (4559, None, [('Telugu','proddu'),('Telugu','poddu')], 'Time/day: proddu supports a local r-loss path. Southern portu → pottu shows why direct assimilation remains an alternative for an isolated reduced form.'),
  (4866, None, [('Telugu','mriŋgu'),('Telugu','miŋgu')], 'Swallow: Tamil miẓuŋku → reconstructed mẓiŋk → mriŋgu → miŋgu. Similar r-less forms elsewhere could instead involve direct medial loss.'),
  (1619, None, [('Telugu','krinda'),('Telugu','kinda')], 'Below: *kiẓ-nd → krinda precedes productive k-palatalization; r-loss restores k next to i afterwards. Other palatalization blockers must also be considered.'),
  (5263, None, [('Telugu','vrāyu'),('Telugu','rāyu')], 'Write: reduction removes the first consonant v, not r. This rāyu must not be merged with the unrelated rub family merely because it is homophonous.'),
 ],
 'languages': [
  (63, '*aṭ-aŋk', [('Telugu','ḍā̃gu'),('Kui','ḍāpa')], 'Both have displacement; both also retain other formations. Shared output does not date a single shared event.'),
  (474, None, [('Telugu','reṇḍu'),('Kui','rī')], 'Two: both have displacement, but numeral allomorphs and human/nonhuman suffixes differ. Telugu short e is a quantity exception.'),
  (228, '*ar-ay / *ar-a-C', [('Telugu','rāyu'),('Kui','rāpka')], 'Rub: both have initial r, but the Telugu y formation and the Kui causative are not identical morphological observations.'),
  (4711, None, [('Telugu','mrānu'),('Kui','mrānu')], 'Tree: both have mr, but distinct suffixes, nasal history and possible lexical transmission prevent counting this as a dated shared innovation.'),
  (240, '*al-ay / *al-aŋ', [('Telugu','ala'),('Kui','lānga')], 'Telugu retains; Kui displaces in a nasal derivative. Compare exact formations before inferring different phonological rules.'),
  (282, '*aẓ-u / *aẓ-ay', [('Telugu','ēḍucu'),('Kui','ṛīva')], 'Telugu ēḍucu retains vowel-before-apical order despite its long vowel. Kui initial ṛ is innovative; the source of ī remains unresolved.'),
  (305, '*al/ḷ-Vk / *al/ḷ-Vñc', [('Telugu','aluku'),('Kui','lānja')], 'Telugu retains; Kui displaces. The velar versus nasal-palatal suffix difference is real; an unknown formative vowel must stay unknown.'),
  (480, '*ir-u / *ir-V-v', [('Telugu','iravu'),('Kui','rīnda')], 'Telugu noun retains; Kui steady/stand formation displaces. The precise source of Kui long ī is not established.'),
  (3259, '*ti/eṯ-a', [('Telugu','teṟacu'),('Kui','dāpa')], 'Open: Telugu retains a low-vowel input; Kui has displacement plus other changes. Konda ṟe and eastern j/d reflexes suggest intermediate cluster loss.'),
  (4760, '*maṯ-aŋk', [('Telugu','maṟũgu'),('Kui','mrānga')], 'Forget/be lost: Telugu retains; Kui mrānga preserves a cluster linking the full form to eastern j/d outcomes. Matching nasal morphology strengthens the comparison.'),
 ],
 'kui': [
  (228,'rāpka','rub','rāk-p-','rākt-','Initial ar → rā and suffix kp → pk are separate changes in the same word.'),
  (1080,'kapka','laugh','kak-p-','kakt-','Kui reverses the cluster; Kuvi kakpinai is a possible retained comparator, not a Kui exception.'),
  (1628,'kopka','sit','kok-p-','kokt-','The stem-final velar is independently visible before the past dental; a compound duplicate is excluded.'),
  (2654,'subga','roast','sug-b-','sugd-','The voiced gb/bɡ alternation parallels kp/pk. The dental stem is printed in the source gloss.'),
  (5200,'lepka','break, snap','lek-p-','lekt-','Compare Winfield’s perfect participle leksa: the labial belongs to this particular derived formation.'),
  (4760,'mrāpka','lose, obliterate','mrāk-p-','mrākt-','mr is already present before the local stem–suffix reversal; two processes must not be pooled.'),
  (520,'repka','break into pieces','rek-p-','rekt-','The local velar-plus-labial input is explicit even though the deeper apical formation has its own history.'),
  (1851,'kōpka','reduce','kōk-p-','kōkt-','The related kṛōpka is part of this same root family, not a second independent example.'),
  (3439,'tepka','overtake','tek-p-','tekt-','A further source-supported velar stem; the dental alternant corroborates the stem boundary.'),
  (3514,'tropka','cause to roll','trok-p-','trokt-','The initial tr cluster and the medial kp reversal have different inputs and different conditioning.'),
 ],
 'clusters': [
  (3364,'*tuḷ- / *tuḷḷ-', [('Telugu','tuḷḷu'),('Telugu','truḷḷu')], 'Added r is the stronger account: the original lateral remains in place. Krishnamurti (1961:131 n.80) connects the cluster with literary hyperstandardization.'),
  (1898,'Earlier order unresolved', [('Telugu','krūru')], 'Two rhotics and a long vowel complicate a simple exchange. Sanskrit krūra is a plausible donor, not a demonstrated borrowing here.'),
  (3411,'Regional *teḍḍ-', [('Telugu','teḍḍu'),('Telugu','treḍḍu')], 'The medial ḍḍ is still present. An additional r, analogy or a more complex history is required; literal promotion alone does not suffice.'),
  (5368,'*wāl-', [('Telugu','vālu'),('Telugu','vrālu')], 'Both r and the original l survive. This is not a simple swap of that l with the vowel; the related inclination entry is not counted again.'),
  (5250,'Regional *vant-; deeper input uncertain', [('Telugu','vanta'),('Telugu','vranti')], 'The nt sequence survives beside an extra r. No independent earlier rhotic position is established.'),
  (5555,'*wē / *wey; apical input unestablished', [('Telugu','vēyu'),('Telugu','vrēyu')], 'A cluster variant exists, but an independently supported apical to move is missing.'),
  (2090,'Regional *kottaḷam', [('Telugu','kottaḍamu'),('Telugu','krottaḷamu')], 'The medial dental and retroflex material remains, alongside ḷ/ḍ variation. Cultural vocabulary and transmission history weaken a simple metathesis diagnosis.'),
  (4194,'Competing liquid-bearing analyses', [('Telugu','prēlu')], 'Both liquids survive in the cluster form; competing etymologies and formations prevent a unique reconstruction.'),
  (5087,'*mē-k?; Old Telugu comparison uncertain', [('Telugu','mēka'),('Telugu','mṛ̆ēka')], 'The Old Telugu form’s meaning is not established. It cannot be labelled goat merely because the source places it near this entry.'),
  (4608,'Earlier full-order input unestablished', [('Telugu','prāmu'),('Telugu','pāmu')], 'The cluster/reduced pair may illustrate r-loss, but without an independent full-order antecedent it does not establish an earlier metathesis.'),
 ]
}
