// Render the final, frozen-analysis narrative as a self-contained HTML report.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {marked} from '/Users/aryamanarora/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/marked/lib/marked.esm.js';
const here=path.dirname(fileURLToPath(import.meta.url));
const md=fs.readFileSync(path.join(here,'REPORT.md'),'utf8');
const headings=[];
const slug=s=>s.replace(/<[^>]*>/g,'').normalize('NFD').replace(/\p{M}/gu,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
let body=marked.parse(md,{gfm:true});
body=body.replace(/<h([1-3])>([\s\S]*?)<\/h\1>/g,(_,level,text)=>{let id=slug(text);if(level==='2')headings.push({id,text});return `<h${level} id="${id}">${text}</h${level}>`});
body=body.replace(/<table>/g,'<div class="table-wrap"><table>').replace(/<\/table>/g,'</table></div>');
const css=`
:root{--ink:#1c2c35;--muted:#536369;--line:#d7dedb;--accent:#1a6257;--paper:#fdfdf9}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.68 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:var(--accent);text-underline-offset:3px}a:hover{color:#082f2a}.top{border-bottom:1px solid var(--line);padding:16px 36px;display:flex;justify-content:space-between;gap:18px;flex-wrap:wrap;font-size:13px}.top strong{letter-spacing:.12em;text-transform:uppercase;font-size:11px}main{max-width:1130px;padding:40px 50px 80px;margin:auto}h1{font:46px/1.12 Georgia,"Times New Roman",serif;letter-spacing:-.02em;max-width:950px;margin:12px 0 25px}h2{font:30px/1.22 Georgia,serif;margin:58px 0 18px;padding-top:18px;border-top:1px solid var(--line);scroll-margin-top:18px}h3{font:22px/1.3 Georgia,serif;margin:30px 0 12px}p{margin:16px 0}strong{font-weight:650}em{font-family:"Charis SIL","Noto Serif",Georgia,serif}ul,ol{padding-left:25px}li{margin:8px 0}.table-wrap{overflow:auto;margin:25px 0}table{width:100%;border-collapse:collapse;font-size:14px;line-height:1.5}thead{background:#eaf0ed}th{text-align:left;font-size:12px;letter-spacing:.015em}td,th{padding:11px 13px;border-bottom:1px solid var(--line);vertical-align:top}blockquote{background:#f1f4ed;border-left:3px solid var(--accent);padding:4px 20px;margin:28px 0;color:#30433f}code{font:13px ui-monospace,SFMono-Regular,monospace;background:#edf1ec;padding:2px 4px;border-radius:3px}pre{overflow:auto;padding:16px;background:#edf1ec}pre code{padding:0}hr{border:0;border-top:1px solid var(--line);margin:35px 0}.contents{max-width:1130px;margin:0 auto;padding:22px 50px 0;font-size:14px}.contents summary{cursor:pointer;color:var(--accent)}.contents ol{columns:2;column-gap:35px;line-height:1.4}.contents li{break-inside:avoid;margin:9px 0}footer{padding:25px 36px;border-top:1px solid var(--line);font-size:13px;color:var(--muted)}
@media(max-width:760px){body{font-size:16px}main{padding:24px 20px 50px}.top{padding:14px 20px}h1{font-size:35px}h2{font-size:27px;margin-top:38px}.contents{padding:18px 20px 0}.contents ol{columns:1}td,th{padding:9px}}
@media print{@page{size:A4;margin:19mm 17mm}body{background:white;font-size:10.5pt;line-height:1.45}.top,.contents,footer{display:none}main{padding:0;max-width:none}h1{font-size:26pt}h2{font-size:18pt;margin-top:25pt;break-after:avoid}h3{font-size:13pt;break-after:avoid}table{font-size:8pt}td,th{padding:5pt}.table-wrap{overflow:visible}tr{break-inside:avoid}a{color:inherit;text-decoration:none}blockquote{break-inside:avoid}p{orphans:3;widows:3}}
`;
const toc=headings.map(h=>`<li><a href="#${h.id}">${h.text}</a></li>`).join('');
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Shinaic accent — quantitative research report</title><style>${css}</style><header class="top"><strong>Jambu · Research / 9 September 2026</strong><nav><a href="appendices/index.html">Complete annotated appendices</a> · <a href="appendices/tables.html">Quantitative tables</a> · <a href="REPORT.md">Markdown</a></nav></header><details class="contents"><summary>Contents</summary><ol>${toc}</ol></details><main>${body}</main><footer>Research-only analysis of a frozen Jambu snapshot. Source readings, competing etymologies, excluded comparisons and unresolved cases remain available in the linked appendices.</footer></html>`;
fs.writeFileSync(path.join(here,'REPORT.html'),html);
console.log(JSON.stringify({markdownWords:md.split(/\s+/).length,htmlBytes:Buffer.byteLength(html),sections:headings.length}));
